enum FieldType {
    ObjectID = 'ObjectID',
    Name = 'Name',
    File = 'File',
    ImageFile = 'ImageFile',
    Hostname = 'Hostname',
    URL = 'URL',
    Route = 'Route',
    Number = 'Number',
    Password = 'Password',
    Text = 'Text',
    Email = 'Email',
    Date = 'Date',
    DateTime = 'DateTime',
    LongText = 'LongText',
    Color = 'Color',
    Port = 'Port',
    HiddenText = 'HiddenText',
    Actions = 'Actions',
    Boolean = 'Boolean',
    Entity = 'Entity',
    EntityArray = 'EntityArray',
    Markdown = 'Markdown',
    HTML = 'HTML',
    CSS = 'CSS', 
    JavaScript = 'JavaScript'
}

export default FieldType;
