import { MigrationInterface, QueryRunner } from "typeorm";

/*
 * Adds an index on `IncidentMember.isMemberNotified`. The
 * `IncidentMembers/SendMemberAddedNotification` cron polls
 * `WHERE isMemberNotified = false` every minute; without the
 * index that's a full table scan that scales with every
 * incident-member assignment ever made.
 *
 * The autogenerated diff also picked up unrelated drift between
 * the local dev database and the current entity models (drops
 * of `User.themePreference`, `StatusPage.showGridView`,
 * `StatusPageResource.statusPageGridColumnId`, and ALTER COLUMN
 * default changes on `OnCallDutyPolicyScheduleLayer`). Those
 * changes belong to other branches and must not run here — they
 * were stripped to keep this migration tightly scoped.
 */
export class AddIsMemberNotifiedIndex1779540427366
  implements MigrationInterface
{
  public name: string = "AddIsMemberNotifiedIndex1779540427366";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE INDEX "IDX_0c2358ce5ea46732d76c4cbb26" ON "IncidentMember" ("isMemberNotified") `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX "public"."IDX_0c2358ce5ea46732d76c4cbb26"`,
    );
  }
}
