enum EmailTemplateType {
  BlankTemplate = "BlankTemplate.hbs",
  ForgotPassword = "ForgotPassword.hbs",
  ProbeOffline = "ProbeOffline.hbs",
  SignupWelcomeEmail = "SignupWelcomeEmail.hbs",
  ProbeConnectionStatusChange = "ProbeConnectionStatusChange.hbs",
  AIAgentConnectionStatusChange = "AIAgentConnectionStatusChange.hbs",
  AIAgentOwnerAdded = "AIAgentOwnerAdded.hbs",
  ConfirmStatusPageSubscription = "ConfirmStatusPageSubscription.hbs",
  EmailVerified = "EmailVerified.hbs",
  PasswordChanged = "PasswordChanged.hbs",
  ProbeOwnerAdded = "ProbeOwnerAdded.hbs",
  InviteMember = "InviteMember.hbs",
  EmailChanged = "EmailChanged.hbs",
  SubscribedToStatusPage = "SubscribedToStatusPage.hbs",
  SubscriberAnnouncementCreated = "SubscriberAnnouncementCreated.hbs",
  SubscriberIncidentCreated = "SubscriberIncidentCreated.hbs",
  SubscriberIncidentPostmortemCreated = "SubscriberIncidentPostmortemCreated.hbs",
  StatusPageSubscriberReport = "StatusPageSubscriberReport.hbs",
  SubscriberIncidentNoteCreated = "SubscriberIncidentNoteCreated.hbs",
  SubscriberIncidentStateChanged = "SubscriberIncidentStateChanged.hbs",
  SubscriberScheduledMaintenanceEventCreated = "SubscriberScheduledMaintenanceEventCreated.hbs",
  ManageExistingStatusPageSubscriberSubscription = "ManageExistingStatusPageSubscriberSubscription.hbs",
  SubscriberScheduledMaintenanceEventStateChanged = "SubscriberScheduledMaintenanceEventStateChanged.hbs",
  StatusPageForgotPassword = "StatusPageForgotPassword.hbs",
  StatusPagePasswordChanged = "StatusPagePasswordChanged.hbs",
  StatusPageWelcomeEmail = "StatusPageWelcomeEmail.hbs",
  SubscriberScheduledMaintenanceEventNoteCreated = "SubscriberScheduledMaintenanceEventNoteCreated.hbs",
  SMTPTest = "SMTPTest.hbs",
  MonitorOwnerAdded = "MonitorOwnerAdded.hbs",
  MonitorOwnerResourceCreated = "MonitorOwnerResourceCreated.hbs",
  MonitorProbesStatus = "MonitorProbesStatus.hbs",
  MonitorOwnerStatusChanged = "MonitorOwnerStatusChanged.hbs",

  IncidentOwnerAdded = "IncidentOwnerAdded.hbs",
  IncidentOwnerStateChanged = "IncidentOwnerStateChanged.hbs",
  IncidentOwnerNotePosted = "IncidentOwnerNotePosted.hbs",
  IncidentOwnerResourceCreated = "IncidentOwnerResourceCreated.hbs",

  AlertOwnerAdded = "AlertOwnerAdded.hbs",
  AlertOwnerStateChanged = "AlertOwnerStateChanged.hbs",
  AlertOwnerNotePosted = "AlertOwnerNotePosted.hbs",
  AlertOwnerResourceCreated = "AlertOwnerResourceCreated.hbs",

  AlertEpisodeOwnerAdded = "AlertEpisodeOwnerAdded.hbs",
  AlertEpisodeOwnerStateChanged = "AlertEpisodeOwnerStateChanged.hbs",
  AlertEpisodeOwnerNotePosted = "AlertEpisodeOwnerNotePosted.hbs",
  AlertEpisodeOwnerResourceCreated = "AlertEpisodeOwnerResourceCreated.hbs",

  ScheduledMaintenanceOwnerNotePosted = "ScheduledMaintenanceOwnerNotePosted.hbs",
  ScheduledMaintenanceOwnerAdded = "ScheduledMaintenanceOwnerAdded.hbs",
  ScheduledMaintenanceOwnerStateChanged = "ScheduledMaintenanceOwnerStateChanged.hbs",
  ScheduledMaintenanceOwnerResourceCreated = "ScheduledMaintenanceOwnerResourceCreated.hbs",
  StatusPageOwnerResourceCreated = "StatusPageOwnerResourceCreated.hbs",
  StatusPageOwnerAdded = "StatusPageOwnerAdded.hbs",
  StatusPageOwnerAnnouncementPosted = "StatusPageOwnerAnnouncementPosted.hbs",
  SimpleMessage = "SimpleMessage.hbs",
  VerificationCode = "VerificationCode.hbs",
  AcknowledgeIncident = "AcknowledgeIncident.hbs",
  AcknowledgeAlert = "AcknowledgeAlert.hbs",
  AcknowledgeAlertEpisode = "AcknowledgeAlertEpisode.hbs",

  UserAddedToOnCallPolicy = "UserAddedToOnCallPolicy.hbs",
  UserRemovedFromOnCallPolicy = "UserRemovedFromOnCallPolicy.hbs",
  UserCurrentlyOnOnCallRoster = "UserCurrentlyOnOnCallRoster.hbs",
  UserNextOnOnCallRoster = "UserNextOnOnCallRoster.hbs",
  UserNoLongerActiveOnOnCallRoster = "UserNoLongerActiveOnOnCallRoster.hbs",

  ProjectSubscriptionOverdue = "ProjectSubscriptionOverdue.hbs",
  Invoice = "Invoice.hbs",
}

export default EmailTemplateType;
