
export const timezones = [
    { name: 'ACDT/ACST - Adelaide', code: '0' },
    { name: 'ACDT/ACST - Broken Hill', code: '1' },
    { name: 'ACDT/ACST - South', code: '2' },
    { name: 'ACDT/ACST - Yancowinna', code: '3' },
    { name: 'ACST - Darwin', code: '4' },
    { name: 'ACST - North', code: '5' },
    { name: 'ACWST - Eucla', code: '6' },
    { name: 'AEDT/AEST - ACT', code: '7' },
    { name: 'AEDT/AEST - Canberra', code: '8' },
    { name: 'AEDT/AEST - Currie', code: '9' },
    { name: 'AEDT/AEST - Hobart', code: '10' },
    { name: 'AEDT/AEST - Melbourne', code: '11' },
    { name: 'AEDT/AEST - NSW', code: '12' },
    { name: 'AEDT/AEST - Sydney', code: '13' },
    { name: 'AEDT/AEST - Tasmania', code: '14' },
    { name: 'AEDT/AEST - Victoria', code: '15' },
    { name: 'AEST - Brisbane', code: '16' },
    { name: 'AEST - Lindeman', code: '17' },
    { name: 'AEST - Queensland', code: '18' },
    { name: 'AFT - Kabul', code: '19' },
    { name: 'AKST/AKDT - Alaska', code: '20' },
    { name: 'AKST/AKDT - Anchorage', code: '21' },
    { name: 'AKST/AKDT - Juneau', code: '22' },
    { name: 'AKST/AKDT - Nome', code: '23' },
    { name: 'AKST/AKDT - Sitka', code: '24' },
    { name: 'AKST/AKDT - Yakutat', code: '25' },
    { name: 'ALMT - Almaty', code: '26' },
    { name: 'AMST/AMT - Campo Grande', code: '27' },
    { name: 'AMST/AMT - Cuiaba', code: '28' },
    { name: 'AMT - Acre', code: '29' },
    { name: 'AMT - Boa Vista', code: '30' },
    { name: 'AMT - Eirunepe', code: '31' },
    { name: 'AMT - Manaus', code: '32' },
    { name: 'AMT - Porto Acre', code: '33' },
    { name: 'AMT - Porto Velho', code: '34' },
    { name: 'AMT - Rio Branco', code: '35' },
    { name: 'AMT - West', code: '36' },
    { name: 'AMT - Yerevan', code: '37' },
    { name: 'ANAT - Anadyr', code: '38' },
    { name: 'AQTT - Aqtau', code: '39' },
    { name: 'AQTT - Aqtobe', code: '40' },
    { name: 'ART - Buenos Aires', code: '41' },
    { name: 'ART - Catamarca', code: '42' },
    { name: 'ART - Comod Rivadavia, Argentina', code: '43' },
    { name: 'ART - Cordoba', code: '44' },
    { name: 'ART - Jujuy', code: '45' },
    { name: 'ART - La Rioja, Argentina', code: '46' },
    { name: 'ART - Mendoza', code: '47' },
    { name: 'ART - Rio Gallegos, Argentina', code: '48' },
    { name: 'ART - Rosario', code: '49' },
    { name: 'ART - Salta, Argentina', code: '50' },
    { name: 'ART - San Juan, Argentina', code: '51' },
    { name: 'ART - San Luis, Argentina', code: '52' },
    { name: 'ART - Tucuman, Argentina', code: '53' },
    { name: 'ART - Ushuaia, Argentina', code: '54' },
    { name: 'AST - Aden', code: '55' },
    { name: 'AST - Anguilla', code: '56' },
    { name: 'AST - Aruba', code: '57' },
    { name: 'AST - Baghdad', code: '58' },
    { name: 'AST - Barbados', code: '59' },
    { name: 'AST - Blanc-Sablon', code: '60' },
    { name: 'AST - Curacao', code: '61' },
    { name: 'AST - Dominica', code: '62' },
    { name: 'AST - Grenada', code: '63' },
    { name: 'AST - Guadeloupe', code: '64' },
    { name: 'AST - Kralendijk', code: '65' },
    { name: 'AST - Kuwait', code: '66' },
    { name: 'AST - Lower Princes', code: '67' },
    { name: 'AST - Martinique', code: '68' },
    { name: 'AST - Montserrat', code: '69' },
    { name: 'AST - Port of Spain', code: '70' },
    { name: 'AST - Puerto Rico', code: '71' },
    { name: 'AST - Qatar', code: '72' },
    { name: 'AST - Riyadh', code: '73' },
    { name: 'AST - Santo Domingo', code: '74' },
    { name: 'AST - St Barthelemy', code: '75' },
    { name: 'AST - St Kitts', code: '76' },
    { name: 'AST - St Lucia', code: '77' },
    { name: 'AST - St Thomas', code: '78' },
    { name: 'AST - St Vincent', code: '79' },
    { name: 'AST - Tortola', code: '80' },
    { name: 'AST - Virgin', code: '81' },
    { name: 'AST/ADT - Bermuda', code: '82' },
    { name: 'AST/ADT - Glace Bay', code: '83' },
    { name: 'AST/ADT - Goose Bay', code: '84' },
    { name: 'AST/ADT - Halifax', code: '85' },
    { name: 'AST/ADT - Moncton', code: '86' },
    { name: 'AST/ADT - Thule', code: '87' },
    { name: 'AWST - Casey', code: '88' },
    { name: 'AWST - Perth', code: '89' },
    { name: 'AWST - West', code: '90' },
    { name: 'AZOT/AZOST - Azores', code: '91' },
    { name: 'AZT/AZST - Baku', code: '92' },
    { name: 'BDT - Dacca', code: '93' },
    { name: 'BDT - Dhaka', code: '94' },
    { name: 'BNT - Brunei', code: '95' },
    { name: 'BOT - La Paz', code: '96' },
    { name: 'BRST/BRT - Araguaina', code: '97' },
    { name: 'BRST/BRT - East', code: '98' },
    { name: 'BRST/BRT - Sao Paulo', code: '99' },
    { name: 'BRT - Bahia', code: '100' },
    { name: 'BRT - Belem', code: '101' },
    { name: 'BRT - Fortaleza', code: '102' },
    { name: 'BRT - Maceio', code: '103' },
    { name: 'BRT - Recife', code: '104' },
    { name: 'BRT - Santarem', code: '105' },
    { name: 'BTT - Thimbu', code: '106' },
    { name: 'BTT - Thimphu', code: '107' },
    { name: 'CAT - Blantyre', code: '108' },
    { name: 'CAT - Bujumbura', code: '109' },
    { name: 'CAT - Gaborone', code: '110' },
    { name: 'CAT - Harare', code: '111' },
    { name: 'CAT - Kigali', code: '112' },
    { name: 'CAT - Lubumbashi', code: '113' },
    { name: 'CAT - Lusaka', code: '114' },
    { name: 'CAT - Maputo', code: '115' },
    { name: 'CCT - Cocos', code: '116' },
    { name: 'CET - Algiers', code: '117' },
    { name: 'CET - Tunis', code: '118' },
    { name: 'CET/CEST - Amsterdam', code: '119' },
    { name: 'CET/CEST - Andorra', code: '120' },
    { name: 'CET/CEST - Belgrade', code: '121' },
    { name: 'CET/CEST - Berlin', code: '123' },
    { name: 'CET/CEST - Bratislava', code: '124' },
    { name: 'CET/CEST - Brussels', code: '125' },
    { name: 'CET/CEST - Budapest', code: '126' },
    { name: 'CET/CEST - Busingen', code: '127' },
    { name: 'CET/CEST - Ceuta', code: '128' },
    { name: 'CET/CEST - Copenhagen', code: '129' },
    { name: 'CET/CEST - Gibraltar', code: '130' },
    { name: 'CET/CEST - Jan Mayen', code: '131' },
    { name: 'CET/CEST - Ljubljana', code: '132' },
    { name: 'CET/CEST - Longyearbyen', code: '133' },
    { name: 'CET/CEST - Luxembourg', code: '134' },
    { name: 'CET/CEST - Madrid', code: '135' },
    { name: 'CET/CEST - Malta', code: '136' },
    { name: 'CET/CEST - Monaco', code: '137' },
    { name: 'CET/CEST - Oslo', code: '138' },
    { name: 'CET/CEST - Paris', code: '139' },
    { name: 'CET/CEST - Podgorica', code: '140' },
    { name: 'CET/CEST - Prague', code: '141' },
    { name: 'CET/CEST - Rome', code: '142' },
    { name: 'CET/CEST - San Marino', code: '143' },
    { name: 'CET/CEST - Sarajevo', code: '144' },
    { name: 'CET/CEST - Skopje', code: '145' },
    { name: 'CET/CEST - Stockholm', code: '146' },
    { name: 'CET/CEST - Tirane', code: '147' },
    { name: 'CET/CEST - Tripoli', code: '148' },
    { name: 'CET/CEST - Vaduz', code: '149' },
    { name: 'CET/CEST - Vatican', code: '150' },
    { name: 'CET/CEST - Vienna', code: '151' },
    { name: 'CET/CEST - Warsaw', code: '152' },
    { name: 'CET/CEST - Zagreb', code: '153' },
    { name: 'CET/CEST - Zurich', code: '154' },
    { name: 'CHADT/CHAST - Chatham', code: '155' },
    { name: 'CHOT - Choibalsan', code: '156' },
    { name: 'CHUT - Chuuk', code: '157' },
    { name: 'CHUT - Truk', code: '158' },
    { name: 'CHUT - Yap', code: '159' },
    { name: 'CKT - Rarotonga', code: '160' },
    { name: 'CLST/CLT - Continental', code: '161' },
    { name: 'CLST/CLT - Palmer', code: '162' },
    { name: 'CLST/CLT - Santiago', code: '163' },
    { name: 'COT - Bogota', code: '164' },
    { name: 'CST - Belize', code: '165' },
    { name: 'CST - Chongqing', code: '166' },
    { name: 'CST - Chungking', code: '167' },
    { name: 'CST - Costa Rica', code: '168' },
    { name: 'CST - East-Saskatchewan', code: '169' },
    { name: 'CST - El Salvador', code: '170' },
    { name: 'CST - Guatemala', code: '171' },
    { name: 'CST - Harbin', code: '172' },
    { name: 'CST - Macao', code: '173' },
    { name: 'CST - Macau', code: '174' },
    { name: 'CST - Managua', code: '175' },
    { name: 'CST - Regina', code: '176' },
    { name: 'CST - Saskatchewan', code: '177' },
    { name: 'CST - Shanghai', code: '178' },
    { name: 'CST - Swift Current', code: '179' },
    { name: 'CST - Taipei', code: '180' },
    { name: 'CST - Tegucigalpa', code: '181' },
    { name: 'CST/CDT - Bahia Banderas', code: '182' },
    { name: 'CST/CDT - Beulah, North Dakota', code: '183' },
    { name: 'CST/CDT - Cancun', code: '184' },
    { name: 'CST/CDT - Center, North Dakota', code: '185' },
    { name: 'CST/CDT - Central', code: '186' },
    { name: 'CST/CDT - Chicago', code: '187' },
    { name: 'CST/CDT - General', code: '188' },
    { name: 'CST/CDT - Havana', code: '189' },
    { name: 'CST/CDT - Indiana-Starke', code: '190' },
    { name: 'CST/CDT - Knox I\'N', code: '191' },
    { name: 'CST/CDT - Knox, Indiana', code: '192' },
    { name: 'CST/CDT - Matamoros', code: '193' },
    { name: 'CST/CDT - Menominee', code: '194' },
    { name: 'CST/CDT - Merida', code: '195' },
    { name: 'CST/CDT - Mexico City', code: '196' },
    { name: 'CST/CDT - Monterrey', code: '197' },
    { name: 'CST/CDT - New Salem, North Dakota', code: '198' },
    { name: 'CST/CDT - Rainy River', code: '199' },
    { name: 'CST/CDT - Rankin Inlet', code: '200' },
    { name: 'CST/CDT - Resolute', code: '201' },
    { name: 'CST/CDT - Tell City, Indiana', code: '202' },
    { name: 'CST/CDT - Winnipeg', code: '203' },
    { name: 'CVT - Cape Verde', code: '204' },
    { name: 'CXT - Christmas', code: '205' },
];
