enum EventName {
    ACTIVE_INCIDENTS_COUNT_REFRESH = 'ACTIVE_INCIDENTS_COUNT_REFRESH',
    PROJECT_INVITATIONS_REFRESH = 'PROJECT_INVITATIONS_REFRESH',
    SET_NEW_PROFILE_PICTURE = 'SET_NEW_PROFILE_PICTURE',
}

export default EventName;
