enum PageMap {
  INIT = "INIT",
  INIT_PROJECT = "INIT_PROJECT",

  // ONBOARDING
  WELCOME = "WELCOME",

  //SSO
  PROJECT_SSO = "PROJECT_SSO",

  // Logs (standalone product)
  LOGS_ROOT = "LOGS_ROOT",
  LOGS = "LOGS",

  // Metrics (standalone product)
  METRICS_ROOT = "METRICS_ROOT",
  METRICS = "METRICS",
  METRIC_VIEW = "METRIC_VIEW",

  // Traces (standalone product)
  TRACES_ROOT = "TRACES_ROOT",
  TRACES = "TRACES",
  TRACE_VIEW = "TRACE_VIEW",

  HOME = "HOME",
  HOME_NOT_OPERATIONAL_MONITORS = "HOME_NOT_OPERATIONAL_MONITORS",
  HOME_ONGOING_SCHEDULED_MAINTENANCE_EVENTS = "HOME_ONGOING_SCHEDULED_MAINTENANCE_EVENTS",
  HOME_ACTIVE_ALERTS = "HOME_ACTIVE_ALERTS",
  HOME_ACTIVE_EPISODES = "HOME_ACTIVE_EPISODES",
  HOME_ACTIVE_INCIDENT_EPISODES = "HOME_ACTIVE_INCIDENT_EPISODES",

  INCIDENTS_ROOT = "INCIDENTS_ROOT",
  INCIDENTS = "INCIDENTS",
  UNRESOLVED_INCIDENTS = "UNRESOLVED_INCIDENTS",
  INCIDENTS_WORKSPACE_CONNECTION_SLACK = "INCIDENTS_WORKSPACE_CONNECTION_SLACK",
  INCIDENTS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS = "INCIDENTS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS",
  INCIDENT_CREATE = "INCIDENT_CREATE",
  INCIDENT_VIEW = "INCIDENT_VIEW",
  INCIDENT_VIEW_DELETE = "INCIDENT_VIEW_DELETE",
  INCIDENT_VIEW_SETTINGS = "INCIDENT_VIEW_SETTINGS",
  INCIDENT_VIEW_STATE_TIMELINE = "INCIDENT_VIEW_STATE_TIMELINE",
  INCIDENT_VIEW_ROOT_CAUSE = "INCIDENT_VIEW_ROOT_CAUSE",
  INCIDENT_VIEW_REMEDIATION = "INCIDENT_VIEW_REMEDIATION",
  INCIDENT_VIEW_POSTMORTEM = "INCIDENT_VIEW_POSTMORTEM",
  INCIDENT_VIEW_DESCRIPTION = "INCIDENT_VIEW_DESCRIPTION",
  INCIDENT_VIEW_INTERNAL_NOTE = "INCIDENT_VIEW_INTERNAL_NOTE",
  INCIDENT_VIEW_PUBLIC_NOTE = "INCIDENT_VIEW_PUBLIC_NOTE",
  INCIDENT_VIEW_CUSTOM_FIELDS = "INCIDENT_VIEW_CUSTOM_FIELDS",
  INCIDENT_VIEW_OWNERS = "INCIDENT_VIEW_OWNERS",
  INCIDENT_VIEW_ROLES = "INCIDENT_VIEW_ROLES",
  INCIDENT_VIEW_ON_CALL_POLICY_EXECUTION_LOGS = "INCIDENT_VIEW_ON_CALL_POLICY_EXECUTION_LOGS",

  INCIDENT_VIEW_NOTIFICATION_LOGS = "INCIDENT_VIEW_NOTIFICATION_LOGS",
  INCIDENT_VIEW_AI_LOGS = "INCIDENT_VIEW_AI_LOGS",
  INCIDENT_VIEW_SLA = "INCIDENT_VIEW_SLA",

  // Incident Episodes
  INCIDENT_EPISODES = "INCIDENT_EPISODES",
  UNRESOLVED_INCIDENT_EPISODES = "UNRESOLVED_INCIDENT_EPISODES",
  INCIDENT_EPISODE_CREATE = "INCIDENT_EPISODE_CREATE",
  INCIDENT_EPISODE_VIEW = "INCIDENT_EPISODE_VIEW",
  INCIDENT_EPISODE_VIEW_DELETE = "INCIDENT_EPISODE_VIEW_DELETE",
  INCIDENT_EPISODE_VIEW_DESCRIPTION = "INCIDENT_EPISODE_VIEW_DESCRIPTION",
  INCIDENT_EPISODE_VIEW_ROOT_CAUSE = "INCIDENT_EPISODE_VIEW_ROOT_CAUSE",
  INCIDENT_EPISODE_VIEW_POSTMORTEM = "INCIDENT_EPISODE_VIEW_POSTMORTEM",
  INCIDENT_EPISODE_VIEW_REMEDIATION = "INCIDENT_EPISODE_VIEW_REMEDIATION",
  INCIDENT_EPISODE_VIEW_OWNERS = "INCIDENT_EPISODE_VIEW_OWNERS",
  INCIDENT_EPISODE_VIEW_STATE_TIMELINE = "INCIDENT_EPISODE_VIEW_STATE_TIMELINE",
  INCIDENT_EPISODE_VIEW_INCIDENTS = "INCIDENT_EPISODE_VIEW_INCIDENTS",
  INCIDENT_EPISODE_VIEW_INTERNAL_NOTE = "INCIDENT_EPISODE_VIEW_INTERNAL_NOTE",
  INCIDENT_EPISODE_VIEW_MEMBERS = "INCIDENT_EPISODE_VIEW_MEMBERS",
  INCIDENT_EPISODE_DOCS = "INCIDENT_EPISODE_DOCS",

  // Incident Settings (Product-level)
  INCIDENTS_SETTINGS_STATE = "INCIDENTS_SETTINGS_STATE",
  INCIDENTS_SETTINGS_SEVERITY = "INCIDENTS_SETTINGS_SEVERITY",
  INCIDENTS_SETTINGS_TEMPLATES = "INCIDENTS_SETTINGS_TEMPLATES",
  INCIDENTS_SETTINGS_TEMPLATES_VIEW = "INCIDENTS_SETTINGS_TEMPLATES_VIEW",
  INCIDENTS_SETTINGS_NOTE_TEMPLATES = "INCIDENTS_SETTINGS_NOTE_TEMPLATES",
  INCIDENTS_SETTINGS_NOTE_TEMPLATES_VIEW = "INCIDENTS_SETTINGS_NOTE_TEMPLATES_VIEW",
  INCIDENTS_SETTINGS_POSTMORTEM_TEMPLATES = "INCIDENTS_SETTINGS_POSTMORTEM_TEMPLATES",
  INCIDENTS_SETTINGS_POSTMORTEM_TEMPLATES_VIEW = "INCIDENTS_SETTINGS_POSTMORTEM_TEMPLATES_VIEW",
  INCIDENTS_SETTINGS_CUSTOM_FIELDS = "INCIDENTS_SETTINGS_CUSTOM_FIELDS",
  INCIDENTS_SETTINGS_GROUPING_RULES = "INCIDENTS_SETTINGS_GROUPING_RULES",
  INCIDENTS_SETTINGS_SLA_RULES = "INCIDENTS_SETTINGS_SLA_RULES",
  INCIDENTS_SETTINGS_ROLES = "INCIDENTS_SETTINGS_ROLES",

  ALERTS_ROOT = "ALERTS_ROOT",
  ALERTS = "ALERTS",
  UNRESOLVED_ALERTS = "UNRESOLVED_ALERTS",
  ALERTS_WORKSPACE_CONNECTION_SLACK = "ALERTS_WORKSPACE_CONNECTION_SLACK",
  ALERTS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS = "ALERTS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS",
  ALERT_VIEW = "ALERT_VIEW",
  ALERT_VIEW_DELETE = "ALERT_VIEW_DELETE",
  ALERT_VIEW_STATE_TIMELINE = "ALERT_VIEW_STATE_TIMELINE",
  ALERT_VIEW_INTERNAL_NOTE = "ALERT_VIEW_INTERNAL_NOTE",
  ALERT_VIEW_CUSTOM_FIELDS = "ALERT_VIEW_CUSTOM_FIELDS",
  ALERT_VIEW_OWNERS = "ALERT_VIEW_OWNERS",
  ALERT_VIEW_DESCRIPTION = "ALERT_VIEW_DESCRIPTION",
  ALERT_VIEW_ROOT_CAUSE = "ALERT_VIEW_ROOT_CAUSE",
  ALERT_VIEW_REMEDIATION = "ALERT_VIEW_REMEDIATION",
  ALERT_VIEW_ON_CALL_POLICY_EXECUTION_LOGS = "ALERT_VIEW_ON_CALL_POLICY_EXECUTION_LOGS",

  ALERT_VIEW_NOTIFICATION_LOGS = "ALERT_VIEW_NOTIFICATION_LOGS",
  ALERT_VIEW_AI_LOGS = "ALERT_VIEW_AI_LOGS",

  // Alert Episodes
  ALERT_EPISODES = "ALERT_EPISODES",
  UNRESOLVED_ALERT_EPISODES = "UNRESOLVED_ALERT_EPISODES",
  ALERT_EPISODE_CREATE = "ALERT_EPISODE_CREATE",
  ALERT_EPISODE_VIEW = "ALERT_EPISODE_VIEW",
  ALERT_EPISODE_VIEW_DELETE = "ALERT_EPISODE_VIEW_DELETE",
  ALERT_EPISODE_VIEW_DESCRIPTION = "ALERT_EPISODE_VIEW_DESCRIPTION",
  ALERT_EPISODE_VIEW_ROOT_CAUSE = "ALERT_EPISODE_VIEW_ROOT_CAUSE",
  ALERT_EPISODE_VIEW_OWNERS = "ALERT_EPISODE_VIEW_OWNERS",
  ALERT_EPISODE_VIEW_STATE_TIMELINE = "ALERT_EPISODE_VIEW_STATE_TIMELINE",
  ALERT_EPISODE_VIEW_ALERTS = "ALERT_EPISODE_VIEW_ALERTS",
  ALERT_EPISODE_VIEW_INTERNAL_NOTE = "ALERT_EPISODE_VIEW_INTERNAL_NOTE",
  ALERT_EPISODE_VIEW_REMEDIATION = "ALERT_EPISODE_VIEW_REMEDIATION",
  ALERT_EPISODE_DOCS = "ALERT_EPISODE_DOCS",

  // Alert Settings (Product-level)
  ALERTS_SETTINGS_STATE = "ALERTS_SETTINGS_STATE",
  ALERTS_SETTINGS_SEVERITY = "ALERTS_SETTINGS_SEVERITY",
  ALERTS_SETTINGS_NOTE_TEMPLATES = "ALERTS_SETTINGS_NOTE_TEMPLATES",
  ALERTS_SETTINGS_NOTE_TEMPLATES_VIEW = "ALERTS_SETTINGS_NOTE_TEMPLATES_VIEW",
  ALERTS_SETTINGS_CUSTOM_FIELDS = "ALERTS_SETTINGS_CUSTOM_FIELDS",
  ALERTS_SETTINGS_GROUPING_RULES = "ALERTS_SETTINGS_GROUPING_RULES",

  SCHEDULED_MAINTENANCE_EVENTS_ROOT = "SCHEDULED_MAINTENANCE_EVENTS_ROOT",
  SCHEDULED_MAINTENANCE_EVENTS = "SCHEDULED_MAINTENANCE_EVENTS",
  SCHEDULED_MAINTENANCE_EVENTS_WORKSPACE_CONNECTION_SLACK = "SCHEDULED_MAINTENANCE_EVENTS_WORKSPACE_CONNECTION_SLACK",
  SCHEDULED_MAINTENANCE_EVENTS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS = "SCHEDULED_MAINTENANCE_EVENTS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS",
  SCHEDULED_MAINTENANCE_EVENT_CREATE = "SCHEDULED_MAINTENANCE_EVENT_CREATE",
  ONGOING_SCHEDULED_MAINTENANCE_EVENTS = "ONGOING_SCHEDULED_MAINTENANCE_EVENTS",
  SCHEDULED_MAINTENANCE_VIEW = "SCHEDULED_MAINTENANCE_VIEW",
  SCHEDULED_MAINTENANCE_VIEW_DELETE = "SCHEDULED_MAINTENANCE_VIEW_DELETE",
  SCHEDULED_MAINTENANCE_VIEW_DESCRIPTION = "SCHEDULED_MAINTENANCE_VIEW_DESCRIPTION",
  SCHEDULED_MAINTENANCE_VIEW_STATE_TIMELINE = "SCHEDULED_MAINTENANCE_VIEW_STATE_TIMELINE",
  SCHEDULED_MAINTENANCE_INTERNAL_NOTE = "SCHEDULED_MAINTENANCE_INTERNAL_NOTE",
  SCHEDULED_MAINTENANCE_PUBLIC_NOTE = "SCHEDULED_MAINTENANCE_PUBLIC_NOTE",
  SCHEDULED_MAINTENANCE_VIEW_CUSTOM_FIELDS = "SCHEDULED_MAINTENANCE_VIEW_CUSTOM_FIELDS",
  SCHEDULED_MAINTENANCE_VIEW_OWNERS = "SCHEDULED_MAINTENANCE_VIEW_OWNERS",
  SCHEDULED_MAINTENANCE_VIEW_SETTINGS = "SCHEDULED_MAINTENANCE_VIEW_SETTINGS",
  SCHEDULED_MAINTENANCE_VIEW_NOTIFICATION_LOGS = "SCHEDULED_MAINTENANCE_VIEW_NOTIFICATION_LOGS",
  SCHEDULED_MAINTENANCE_VIEW_AI_LOGS = "SCHEDULED_MAINTENANCE_VIEW_AI_LOGS",

  // Scheduled Maintenance Settings (Product-level)
  SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_STATE = "SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_STATE",
  SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_TEMPLATES = "SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_TEMPLATES",
  SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_TEMPLATES_VIEW = "SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_TEMPLATES_VIEW",
  SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_NOTE_TEMPLATES = "SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_NOTE_TEMPLATES",
  SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_NOTE_TEMPLATES_VIEW = "SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_NOTE_TEMPLATES_VIEW",
  SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_CUSTOM_FIELDS = "SCHEDULED_MAINTENANCE_EVENTS_SETTINGS_CUSTOM_FIELDS",

  MONITORS = "MONITORS",
  MONITORS_ROOT = "MONITORS_ROOT",
  MONITOR_CREATE = "MONITOR_CREATE",
  MONITORS_INOPERATIONAL = "MONITORS_INOPERATIONAL",
  MONITORS_DISABLED = "MONITORS_DISABLED",
  MONITORS_WORKSPACE_CONNECTION_SLACK = "MONITORS_WORKSPACE_CONNECTION_SLACK",
  MONITORS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS = "MONITORS_WORKSPACE_CONNECTION_MICROSOFT_TEAMS",
  MONITORS_PROBE_DISCONNECTED = "MONITORS_PROBE_DISCONNECTED",
  MONITORS_PROBE_DISABLED = "MONITORS_PROBE_DISABLED",
  MONITOR_VIEW = "MONITOR_VIEW",
  MONITOR_VIEW_METRICS = "MONITOR_VIEW_METRICS",
  MONITOR_VIEW_CRITERIA = "MONITOR_VIEW_CRITERIA",
  MONITOR_VIEW_DELETE = "MONITOR_VIEW_DELETE",
  MONITOR_VIEW_STATUS_TIMELINE = "MONITOR_VIEW_STATUS_TIMELINE",
  MONITOR_VIEW_INCIDENTS = "MONITOR_VIEW_INCIDENTS",
  MONITOR_VIEW_ALERTS = "MONITOR_VIEW_ALERTS",
  MONITOR_VIEW_CUSTOM_FIELDS = "MONITOR_VIEW_CUSTOM_FIELDS",
  MONITOR_VIEW_INTERVAL = "MONITOR_VIEW_INTERVAL",
  MONITOR_VIEW_PROBES = "MONITOR_VIEW_PROBES",
  MONITOR_VIEW_LOGS = "MONITOR_VIEW_LOGS",
  MONITOR_VIEW_DOCUMENTATION = "MONITOR_VIEW_DOCUMENTATION",
  MONITOR_VIEW_OWNERS = "MONITOR_VIEW_OWNERS",
  MONITOR_VIEW_SETTINGS = "MONITOR_VIEW_SETTINGS",

  // Monitor Settings (Product-level)
  MONITORS_SETTINGS = "MONITORS_SETTINGS",
  MONITORS_SETTINGS_CUSTOM_FIELDS = "MONITORS_SETTINGS_CUSTOM_FIELDS",
  MONITORS_SETTINGS_SECRETS = "MONITORS_SETTINGS_SECRETS",

  MONITOR_GROUPS_ROOT = "MONITOR_GROUPS_ROOT",
  MONITOR_GROUPS = "MONITOR_GROUPS",
  MONITOR_GROUP_VIEW = "MONITOR_GROUP_VIEW",
  MONITOR_GROUP_VIEW_DELETE = "MONITOR_GROUP_VIEW_DELETE",
  MONITOR_GROUP_VIEW_MONITORS = "MONITOR_GROUP_VIEW_MONITORS",
  MONITOR_GROUP_VIEW_OWNERS = "MONITOR_GROUP_VIEW_OWNERS",
  MONITOR_GROUP_VIEW_INCIDENTS = "MONITOR_GROUP_VIEW_INCIDENTS",
  MONITOR_GROUP_VIEW_ALERTS = "MONITOR_GROUP_VIEW_ALERTS",

  SERVICE_ROOT = "SERVICE_ROOT",
  SERVICES = "SERVICES",
  SERVICE_VIEW = "SERVICE_VIEW",
  SERVICE_VIEW_DELETE = "SERVICE_VIEW_DELETE",
  SERVICE_VIEW_SETTINGS = "SERVICE_VIEW_SETTINGS",
  SERVICE_VIEW_MONITORS = "SERVICE_VIEW_MONITORS",
  SERVICE_VIEW_INCIDENTS = "SERVICE_VIEW_INCIDENTS",
  SERVICE_VIEW_ALERTS = "SERVICE_VIEW_ALERTS",
  SERVICE_VIEW_LOGS = "SERVICE_VIEW_LOGS",
  SERVICE_VIEW_TRACES = "SERVICE_VIEW_TRACES",
  SERVICE_VIEW_METRICS = "SERVICE_VIEW_METRICS",
  SERVICE_VIEW_OWNERS = "SERVICE_VIEW_OWNERS",
  SERVICE_VIEW_DEPENDENCIES = "SERVICE_VIEW_DEPENDENCIES",
  SERVICE_VIEW_CODE_REPOSITORIES = "SERVICE_VIEW_CODE_REPOSITORIES",
  SERVICE_DEPENDENCY_GRAPH = "SERVICE_DEPENDENCY_GRAPH",

  // Code Repository
  CODE_REPOSITORY_ROOT = "CODE_REPOSITORY_ROOT",
  CODE_REPOSITORY = "CODE_REPOSITORY",
  CODE_REPOSITORY_VIEW = "CODE_REPOSITORY_VIEW",
  CODE_REPOSITORY_VIEW_DELETE = "CODE_REPOSITORY_VIEW_DELETE",
  CODE_REPOSITORY_VIEW_SETTINGS = "CODE_REPOSITORY_VIEW_SETTINGS",
  CODE_REPOSITORY_VIEW_SERVICES = "CODE_REPOSITORY_VIEW_SERVICES",

  DASHBOARDS_ROOT = "DASHBOARDS_ROOT",
  DASHBOARDS = "DASHBOARDS",
  DASHBOARD_VIEW = "DASHBOARD_VIEW",
  DASHBOARD_VIEW_OVERVIEW = "DASHBOARD_VIEW_OVERVIEW",
  DASHBOARD_VIEW_DELETE = "DASHBOARD_VIEW_DELETE",
  DASHBOARD_VIEW_SETTINGS = "DASHBOARD_VIEW_SETTINGS",

  STATUS_PAGES_ROOT = "STATUS_PAGES_ROOT",
  STATUS_PAGES = "STATUS_PAGES",
  STATUS_PAGE_ANNOUNCEMENTS = "STATUS_PAGE_ANNOUNCEMENTS",
  ANNOUNCEMENT_CREATE = "ANNOUNCEMENT_CREATE",
  ANNOUNCEMENT_VIEW = "ANNOUNCEMENT_VIEW",

  ANNOUNCEMENT_VIEW_NOTIFICATION_LOGS = "ANNOUNCEMENT_VIEW_NOTIFICATION_LOGS",
  ANNOUNCEMENT_VIEW_DELETE = "ANNOUNCEMENT_VIEW_DELETE",
  STATUS_PAGE_VIEW = "STATUS_PAGE_VIEW",
  STATUS_PAGE_VIEW_BRANDING = "STATUS_PAGE_VIEW_BRADNING",
  STATUS_PAGE_VIEW_HEADER_STYLE = "STATUS_PAGE_VIEW_HEADER_STYLE",
  STATUS_PAGE_VIEW_FOOTER_STYLE = "STATUS_PAGE_VIEW_FOOTER_STYLE",
  STATUS_PAGE_VIEW_OVERVIEW_PAGE_BRANDING = "STATUS_PAGE_VIEW_OVERVIEW_PAGE_BRANDING",
  STATUS_PAGE_VIEW_NAVBAR_STYLE = "STATUS_PAGE_VIEW_NAVBAR_STYLE",
  STATUS_PAGE_VIEW_DELETE = "STATUS_PAGE_VIEW_DELETE",
  STATUS_PAGE_VIEW_DOMAINS = "STATUS_PAGE_VIEW_DOMAINS",
  STATUS_PAGE_VIEW_EMBEDDED = "STATUS_PAGE_VIEW_EMBEDDED",
  STATUS_PAGE_VIEW_ANNOUNCEMENTS = "STATUS_PAGE_VIEW_ANNOUNCEMENTS",
  STATUS_PAGE_VIEW_EMAIL_SUBSCRIBERS = "STATUS_PAGE_VIEW_EMAIL_SUBSCRIBERS",
  STATUS_PAGE_VIEW_SMS_SUBSCRIBERS = "STATUS_PAGE_VIEW_SMS_SUBSCRIBERS",
  STATUS_PAGE_VIEW_SLACK_SUBSCRIBERS = "STATUS_PAGE_VIEW_SLACK_SUBSCRIBERS",
  STATUS_PAGE_VIEW_MICROSOFT_TEAMS_SUBSCRIBERS = "STATUS_PAGE_VIEW_MICROSOFT_TEAMS_SUBSCRIBERS",
  STATUS_PAGE_VIEW_WEBHOOK_SUBSCRIBERS = "STATUS_PAGE_VIEW_WEBHOOK_SUBSCRIBERS",
  STATUS_PAGE_VIEW_RESOURCES = "STATUS_PAGE_VIEW_RESOURCES",
  STATUS_PAGE_VIEW_ADVANCED_OPTIONS = "STATUS_PAGE_VIEW_ADVANCED_OPTIONS",
  STATUS_PAGE_VIEW_AUTHENTICATION_SETTINGS = "STATUS_PAGE_VIEW_AUTHENTICATION_SETTINGS",
  STATUS_PAGE_VIEW_CUSTOM_HTML_CSS = "STATUS_PAGE_VIEW_CUSTOM_HTML_CSS",
  STATUS_PAGE_VIEW_GROUPS = "STATUS_PAGE_VIEW_GROUPS",
  STATUS_PAGE_VIEW_SUBSCRIBER_SETTINGS = "STATUS_PAGE_VIEW_SUBSCRIBER_SETTINGS",
  STATUS_PAGE_VIEW_PRIVATE_USERS = "STATUS_PAGE_VIEW_PRIVATE_USERS",
  STATUS_PAGE_VIEW_CUSTOM_FIELDS = "STATUS_PAGE_VIEW_CUSTOM_FIELDS",
  STATUS_PAGE_VIEW_REPORTS = "STATUS_PAGE_VIEW_REPORTS",
  STATUS_PAGE_VIEW_SSO = "STATUS_PAGE_VIEW_SSO",
  STATUS_PAGE_VIEW_SCIM = "STATUS_PAGE_VIEW_SCIM",
  STATUS_PAGE_VIEW_OWNERS = "STATUS_PAGE_VIEW_OWNERS",
  STATUS_PAGE_VIEW_SETTINGS = "STATUS_PAGE_VIEW_SETTINGS",
  STATUS_PAGE_VIEW_NOTIFICATION_LOGS = "STATUS_PAGE_VIEW_NOTIFICATION_LOGS",

  // Status Pages Settings (Product-level)
  STATUS_PAGES_SETTINGS_ANNOUNCEMENT_TEMPLATES = "STATUS_PAGES_SETTINGS_ANNOUNCEMENT_TEMPLATES",
  STATUS_PAGES_SETTINGS_ANNOUNCEMENT_TEMPLATES_VIEW = "STATUS_PAGES_SETTINGS_ANNOUNCEMENT_TEMPLATES_VIEW",
  STATUS_PAGES_SETTINGS_SUBSCRIBER_NOTIFICATION_TEMPLATES = "STATUS_PAGES_SETTINGS_SUBSCRIBER_NOTIFICATION_TEMPLATES",
  STATUS_PAGES_SETTINGS_SUBSCRIBER_NOTIFICATION_TEMPLATES_VIEW = "STATUS_PAGES_SETTINGS_SUBSCRIBER_NOTIFICATION_TEMPLATES_VIEW",
  STATUS_PAGES_SETTINGS_CUSTOM_FIELDS = "STATUS_PAGES_SETTINGS_CUSTOM_FIELDS",

  ON_CALL_DUTY_ROOT = "ON_CALL_DUTY_ROOT",
  ON_CALL_DUTY = "ON_CALL_DUTY",
  ON_CALL_DUTY_POLICIES = "ON_CALL_DUTY_POLICIES",
  ON_CALL_DUTY_POLICY_USER_OVERRIDES = "ON_CALL_DUTY_POLICY_USER_OVERRIDES",
  ON_CALL_DUTY_EXECUTION_LOGS = "ON_CALL_DUTY_EXECUTION_LOGS",
  ON_CALLDUTY_USER_TIME_LOGS = "ON_CALLDUTY_USER_TIME_LOGS",
  ON_CALL_DUTY_EXECUTION_LOGS_TIMELINE = "ON_CALL_DUTY_EXECUTION_LOGS_TIMELINE",
  ON_CALL_DUTY_POLICY_VIEW = "ON_CALL_DUTY_POLICY_VIEW",
  ON_CALL_DUTY_POLICY_VIEW_CUSTOM_FIELDS = "ON_CALL_DUTY_POLICY_VIEW_CUSTOM_FIELDS",
  ON_CALL_DUTY_POLICY_VIEW_OWNERS = "ON_CALL_DUTY_POLICY_VIEW_OWNERS",
  ON_CALL_DUTY_POLICY_VIEW_DELETE = "ON_CALL_DUTY_POLICY_VIEW_DELETE",
  ON_CALL_DUTY_POLICY_VIEW_EXECUTION_LOGS = "ON_CALL_DUTY_POLICY_VIEW_EXECUTION_LOGS",
  ON_CALL_DUTY_POLICY_VIEW_USER_OVERRIDES = "ON_CALL_DUTY_POLICY_VIEW_USER_OVERRIDES",
  ON_CALL_DUTY_POLICY_VIEW_ESCALATION = "ON_CALL_DUTY_POLICY_VIEW_ESCALATION",
  ON_CALL_DUTY_POLICY_VIEW_EXECUTION_LOG_VIEW = "ON_CALL_DUTY_POLICY_VIEW_EXECUTION_LOG_VIEW",
  ON_CALL_DUTY_POLICY_VIEW_NOTIFICATION_LOGS = "ON_CALL_DUTY_POLICY_VIEW_NOTIFICATION_LOGS",

  ON_CALL_DUTY_WORKSPACE_CONNECTION_SLACK = "ON_CALL_DUTY_WORKSPACE_CONNECTION_SLACK",
  ON_CALL_DUTY_WORKSPACE_CONNECTION_MICROSOFT_TEAMS = "ON_CALL_DUTY_WORKSPACE_CONNECTION_MICROSOFT_TEAMS",

  ON_CALL_DUTY_SCHEDULES = "ON_CALL_DUTY_SCHEDULES",
  ON_CALL_DUTY_SCHEDULE_VIEW = "ON_CALL_DUTY_SCHEDULE_VIEW",
  ON_CALL_DUTY_SCHEDULE_VIEW_DELETE = "ON_CALL_DUTY_SCHEDULE_VIEW_DELETE",
  ON_CALL_DUTY_SCHEDULE_VIEW_LAYERS = "ON_CALL_DUTY_SCHEDULE_VIEW_LAYERS",
  ON_CALL_DUTY_SCHEDULE_VIEW_NOTIFICATION_LOGS = "ON_CALL_DUTY_SCHEDULE_VIEW_NOTIFICATION_LOGS",
  ON_CALL_DUTY_SCHEDULE_VIEW_SETTINGS = "ON_CALL_DUTY_SCHEDULE_VIEW_SETTINGS",

  // On-Call Duty Settings (Product-level)
  ON_CALL_DUTY_SETTINGS_CUSTOM_FIELDS = "ON_CALL_DUTY_SETTINGS_CUSTOM_FIELDS",

  // Incoming Call Policy
  ON_CALL_DUTY_INCOMING_CALL_POLICIES = "ON_CALL_DUTY_INCOMING_CALL_POLICIES",
  ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW = "ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW",
  ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_ESCALATION = "ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_ESCALATION",
  ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_LOGS = "ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_LOGS",
  ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_LOG_VIEW = "ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_LOG_VIEW",
  ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_SETTINGS = "ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_SETTINGS",
  ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_DELETE = "ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_DELETE",
  ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_DOCS = "ON_CALL_DUTY_INCOMING_CALL_POLICY_VIEW_DOCS",

  AUTOMATION_SCRIPTS = "AUTOMATION_SCRIPTS",
  REPORTS = "REPORTS",
  ERROR_TRACKER = "ERROR_TRACKER",

  // User Settings.
  USER_SETTINGS_ROOT = "USER_SETTINGS_ROOT",
  USER_SETTINGS = "USER_SETTINGS",
  USER_SETTINGS_CUSTOM_FIELDS = "USER_SETTINGS_CUSTOM_FIELDS",
  USER_SETTINGS_NOTIFICATION_METHODS = "USER_SETTINGS_NOTIFICATION_METHODS",
  USER_SETTINGS_SLACK_INTEGRATION = "USER_SETTINGS_SLACK_INTEGRATION",
  USER_SETTINGS_MICROSOFT_TEAMS_INTEGRATION = "USER_SETTINGS_MICROSOFT_TEAMS_INTEGRATION",
  USER_SETTINGS_INCIDENT_ON_CALL_RULES = "USER_SETTINGS_INCIDENT_ON_CALL_RULES",
  USER_SETTINGS_ALERT_ON_CALL_RULES = "USER_SETTINGS_ALERT_ON_CALL_RULES",
  USER_SETTINGS_EPISODE_ON_CALL_RULES = "USER_SETTINGS_EPISODE_ON_CALL_RULES",
  USER_SETTINGS_ON_CALL_LOGS = "USER_SETTINGS_ON_CALL_LOGS",
  USER_SETTINGS_ON_CALL_LOGS_TIMELINE = "USER_SETTINGS_ON_CALL_LOGS_TIMELINE",
  USER_SETTINGS_NOTIFICATION_SETTINGS = "USER_SETTINGS_NOTIFICATION_SETTINGS",
  USER_SETTINGS_INCOMING_CALL_PHONE_NUMBERS = "USER_SETTINGS_INCOMING_CALL_PHONE_NUMBERS",

  // Settings Routes
  SETTINGS_ROOT = "SETTINGS_ROOT",
  SETTINGS = "SETTINGS",
  SETTINGS_DANGERZONE = "SETTINGS_DANGERZONE",

  SETTINGS_TELEMETRY_INGESTION_KEYS = "SETTINGS_TELEMETRY_INGESTION_KEYS",
  SETTINGS_TELEMETRY_INGESTION_KEY_VIEW = "SETTINGS_TELEMETRY_INGESTION_KEY_VIEW",

  // API Keys.
  SETTINGS_APIKEYS = "SETTINGS_APIKEYS",
  SETTINGS_APIKEY_VIEW = "SETTINGS_APIKEY_VIEW",

  // Team
  SETTINGS_TEAMS = "SETTINGS_TEAMS",
  SETTINGS_USERS = "SETTINGS_USERS",
  SETTINGS_USER_VIEW = "SETTINGS_USER_VIEW",
  SETTINGS_TEAM_VIEW = "SETTINGS_TEAM_VIEW",

  // Probe
  SETTINGS_PROBE_VIEW = "SETTINGS_PROBE_VIEW",

  // Workspace integrations
  SETTINGS_SLACK_INTEGRATION = "SETTINGS_SLACK_INTEGRATION",
  SETTINGS_MICROSOFT_TEAMS_INTEGRATION = "SETTINGS_MICROSOFT_TEAMS_INTEGRATION",

  // Labels.
  SETTINGS_LABELS = "SETTINGS_LABELS",

  // Probes.
  SETTINGS_PROBES = "SETTINGS_PROBES",

  // AI Agents.
  SETTINGS_AI_AGENTS = "SETTINGS_AI_AGENTS",
  SETTINGS_AI_AGENT_VIEW = "SETTINGS_AI_AGENT_VIEW",

  // LLM Providers.
  SETTINGS_LLM_PROVIDERS = "SETTINGS_LLM_PROVIDERS",
  SETTINGS_LLM_PROVIDER_VIEW = "SETTINGS_LLM_PROVIDER_VIEW",

  // AI Billing
  SETTINGS_AI_BILLING = "SETTINGS_AI_BILLING",

  // SSO.
  SETTINGS_SSO = "SETTINGS_SSO",

  // SCIM.
  SETTINGS_SCIM = "SETTINGS_SCIM",

  // Domains

  SETTINGS_DOMAINS = "SETTINGS_DOMAINS",

  // BILLING

  SETTINGS_BILLING = "SETTINGS_BILLING",
  SETTINGS_BILLING_INVOICES = "SETTINGS_BILLING_INVOICES",
  SETTINGS_USAGE_HISTORY = "SETTINGS_USAGE_HISTORY",

  // Featur Flags
  SETTINGS_FEATURE_FLAGS = "SETTINGS_FEATURE_FLAGS",

  // Misc
  LOGOUT = "LOGOUT",
  USER_PROFILE_OVERVIEW = "USER_PROFILE_OVERVIEW",
  USER_PROFILE_PASSWORD = "USER_PROFILE_PASSWORD",
  USER_PROFILE_PICTURE = "USER_PROFILE_PICTURE",
  USER_TWO_FACTOR_AUTH = "USER_TWO_FACTOR_AUTH",
  USER_PROFILE_DELETE = "USER_PROFILE_DELETE",
  ACTIVE_INCIDENTS = "ACTIVE_INCIDENTS",
  ACTIVE_ALERTS = "ACTIVE_ALERTS",
  PROJECT_INVITATIONS = "PROJECT_INVITATIONS",

  // WORKFLOW
  WORKFLOWS_ROOT = "WORKFLOWS_ROOT",
  WORKFLOWS = "WORKFLOWS",
  WORKFLOWS_LOGS = "WORKFLOWS_LOGS",
  WORKFLOWS_VARIABLES = "WORKFLOWS_VARIABLES",
  WORKFLOW_VIEW = "WORKFLOW_VIEW",
  WORKFLOW_DELETE = "WORKFLOW_DELETE",
  WORKFLOW_BUILDER = "WORKFLOW_BUILDER",
  WORKFLOW_LOGS = "WORKFLOW_LOGS",
  WORKFLOW_VARIABLES = "WORKFLOW_VARIABLES",
  WORKFLOW_VIEW_SETTINGS = "WORKFLOW_VIEW_SETTINGS",

  // SMS and Call
  SETTINGS_NOTIFICATION_SETTINGS = "SETTINGS_NOTIFICATION_SETTINGS",

  SETTINGS_NOTIFICATION_LOGS = "SETTINGS_NOTIFICATION_LOGS",

  // AI Logs
  SETTINGS_AI_LOGS = "SETTINGS_AI_LOGS",

  // AI Agent Tasks
  AI_AGENT_TASKS_ROOT = "AI_AGENT_TASKS_ROOT",
  AI_AGENT_TASKS = "AI_AGENT_TASKS",
  AI_AGENT_TASK_VIEW = "AI_AGENT_TASK_VIEW",
  AI_AGENT_TASK_VIEW_LOGS = "AI_AGENT_TASK_VIEW_LOGS",
  AI_AGENT_TASK_VIEW_PULL_REQUESTS = "AI_AGENT_TASK_VIEW_PULL_REQUESTS",
  AI_AGENT_TASK_VIEW_DELETE = "AI_AGENT_TASK_VIEW_DELETE",

  // Exceptions (standalone, not under Telemetry)
  EXCEPTIONS_ROOT = "EXCEPTIONS_ROOT",
  EXCEPTIONS = "EXCEPTIONS",
  EXCEPTIONS_UNRESOLVED = "EXCEPTIONS_UNRESOLVED",
  EXCEPTIONS_RESOLVED = "EXCEPTIONS_RESOLVED",
  EXCEPTIONS_ARCHIVED = "EXCEPTIONS_ARCHIVED",
  EXCEPTIONS_VIEW_ROOT = "EXCEPTIONS_VIEW_ROOT",
  EXCEPTIONS_VIEW = "EXCEPTIONS_VIEW",

  // Push Logs in resource views
}

export default PageMap;
