enum PageMap {
    INIT = 'INIT',
    HOME = 'HOME',
    INCIDENTS = 'INCIDENTS',

    MONITORS = 'MONITORS',
    STATUS_PAGE = 'STATUSPAGE',
    LOGS = 'LOGS',
    ON_CALL = 'ON_CALL',
    AUTOMATION_SCRIPTS = 'AUTOMATION_SCRIPTS',
    REPORTS = 'REPORTS',
    ERROR_TRACKER = 'ERROR_TRACKER',

    // Settings Routes
    SETTINGS = 'SETTINGS',
    SETTINGS_DANGERZONE = 'SETTINGS_DANGERZONE',

    // API Keys.
    SETTINGS_APIKEYS = 'SETTINGS_APIKEYS',
    SETTINGS_APIKEY_VIEW = 'SETTINGS_APIKEY_VIEW',
    SETTINGS_CUSTOM_SMTP = 'SETTINGS_CUSTOM_SMTP',

    // Team
    SETTINGS_TEAMS = 'SETTINGS_TEAMS',
    SETTINGS_TEAM_VIEW = 'SETTINGS_TEAM_VIEW',

    // Labels.
    SETTINGS_LABELS = 'SETTINGS_LABELS',

    // Misc
    LOGOUT = 'LOGOUT',
}

export default PageMap;
