#
# HTTP Test Server Dockerfile
#

# Pull base image nodejs image.
FROM node:17-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

# Install common-server
RUN mkdir /usr/src/
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm ci
COPY ./common-server /usr/src/common-server

#SET ENV Variables

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true




RUN mkdir /usr/src/app

WORKDIR /usr/src/app

# Copy package.json files
COPY ./licensing/package.json /usr/src/app/package.json
COPY ./licensing/package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm ci

# Expose ports.
#   - 3004: OneUptime-licensing
EXPOSE 3004

# Expose Debugger port
EXPOSE 9229 

#Run the app
CMD [ "npm", "run", "dev" ]
