#
# HTTP Test Server Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]
RUN npm install typescript -g

# Install CommonServer
RUN mkdir /usr/src/
RUN mkdir /usr/src/CommonServer
WORKDIR /usr/src/CommonServer
COPY ./CommonServer/package*.json /usr/src/CommonServer/
RUN npm install
COPY ./CommonServer /usr/src/CommonServer
RUN npm run compile

#SET ENV Variables

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true




RUN mkdir /usr/src/app

WORKDIR /usr/src/app

# Copy package.json files
COPY ./licensing/package.json /usr/src/app/package.json
COPY ./licensing/package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm install

# Expose ports.
#   - 3004: OneUptime-licensing
EXPOSE 3004

# Expose Debugger port
EXPOSE 9229 

#Run the app
CMD [ "npm", "run", "dev" ]
