#
# HTTP Test Server Dockerfile
#

# Pull base image nodejs image.
FROM node:16

#SET ENV Variables

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

WORKDIR /usr/src/app

# Copy package.json files
COPY ./package.json /usr/src/app/package.json
COPY ./package-lock.json /usr/src/app/package-lock.json

# Install app dependencies
RUN npm install

# Expose ports.
#   - 3004: Fyipe-licensing
EXPOSE 3004

# Expose Debugger port
EXPOSE 9229 

#Run the app
CMD [ "npm", "run", "dev" ]
