#
# OneUptime Docs Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]
RUN npm install typescript -g
RUN npm install ts-node -g
RUN npm install nodemon -g

RUN mkdir /usr/src

# Install common
RUN mkdir /usr/src/Common
WORKDIR /usr/src/Common
COPY ./Common/package*.json /usr/src/Common/
RUN npm install
COPY ./Common /usr/src/Common
RUN npm run compile

# Install Model
RUN mkdir /usr/src/Model
WORKDIR /usr/src/Model
COPY ./Model/package*.json /usr/src/Model/
RUN npm install
COPY ./Model /usr/src/Model
RUN npm run compile

# Install CommonServer
RUN mkdir /usr/src/CommonServer
WORKDIR /usr/src/CommonServer
COPY ./CommonServer/package*.json /usr/src/CommonServer/
RUN npm install
COPY ./CommonServer /usr/src/CommonServer
RUN npm run compile


#SET ENV Variables


WORKDIR /usr/src/app

# Copy package.json files
COPY ./HelmChart/package.json /usr/src/app/package.json
COPY ./HelmChart/package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm install

# Expose ports.
#   - 3423: OneUptime Helm Chart Server
EXPOSE 3423

# Expose Debugger port
EXPOSE 9229 

#Run the app
CMD [ "npm", "run", "dev" ]
