{{- if and (index .Values "cert-manager" "enabled") (index .Values "certManagerLetsEncrypt" "enabled") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ index .Values "certManagerLetsEncrypt" "server" | quote }}
    email: {{ index .Values "certManagerLetsEncrypt" "email" | quote }}
    # The ACME certificate profile
    profile: tlsserver
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt
    solvers:
      - http01:
          ingress:
            class: {{ .Values.oneuptimeIngress.className }}
            ingressTemplate:
              metadata:
                annotations:
                  nginx.ingress.kubernetes.io/ssl-redirect: "false"
                  nginx.ingress.kubernetes.io/priority: "1000"
              spec:
                ingressClassName: {{ .Values.oneuptimeIngress.className }}
{{- end }}
