enum PageMap {
  INIT = "INIT",
  HOME = "HOME",
  LOGOUT = "LOGOUT",
  SETTINGS = "SETTINGS",

  USERS = "USERS",
  USER_VIEW = "USER_VIEW",
  USER_SETTINGS = "USER_SETTINGS",
  USER_DELETE = "USER_DELETE",

  PROJECTS = "PROJECTS",
  PROJECT_VIEW = "PROJECT_VIEW",
  PROJECT_DELETE = "PROJECT_DELETE",

  SETTINGS_HOST = "SETTINGS_HOST",
  SETTINGS_SMTP = "SETTINGS_SMTP",
  SETTINGS_CALL_AND_SMS = "SETTINGS_CALL_AND_SMS",
  SETTINGS_WHATSAPP = "SETTINGS_WHATSAPP",
  SETTINGS_PROBES = "SETTINGS_PROBES",
  SETTINGS_LLMS = "SETTINGS_LLMS",
  SETTINGS_AUTHENTICATION = "SETTINGS_AUTHENTICATION",
  SETTINGS_API_KEY = "SETTINGS_API_KEY",
}

export default PageMap;
