export default {
    'Subscriber Incident Created': [
        '{{incidentTime}} : Time at which this incident occured.',
        '{{monitorName}} : Name of the monitor on which incident has occured.',
        '{{projectName}} : Name of the project on which the incident has occured.',
        '{{incidentType}} : Type of incident.',
        '{{componentName}} : Name of the component the monitor belongs to',
        '{{statusPageUrl}} : URL of the Status Page your subscriber can go to. ',
        '{{incident.customFields.*}} : The value of any incident custom field',
        '{{monitor.customFields.*}} : The value of any monitor custom field',
    ],
    'Subscriber Incident Acknowledged': [
        '{{incidentTime}} : Time at which this incident occured.',
        '{{monitorName}} : Name of the monitor on which incident has occured.',
        '{{projectName}} : Name of the project on which the incident has occured.',
        '{{incidentType}} : Type of incident.',
        '{{componentName}} : Name of the component the monitor belongs to',
        '{{statusPageUrl}} : URL of the Status Page your subscriber can go to. ',
        '{{incident.customFields.*}} : The value of any incident custom field',
        '{{monitor.customFields.*}} : The value of any monitor custom field',
    ],
    'Subscriber Incident Resolved': [
        '{{incidentTime}} : Time at which this incident occured.',
        '{{monitorName}} : Name of the monitor on which incident has occured.',
        '{{projectName}} : Name of the project on which the incident has occured.',
        '{{incidentType}} : Type of incident.',
        '{{componentName}} : Name of the component the monitor belongs to',
        '{{statusPageUrl}} : URL of the Status Page your subscriber can go to. ',
        '{{incident.customFields.*}} : The value of any incident custom field',
        '{{monitor.customFields.*}} : The value of any monitor custom field',
    ],
};
