services:

  # Redis for caching and cluster state
  redis:
    extends:
        file: ./docker-compose.base.yml
        service: redis

  llm: 
    extends:
        file: ./docker-compose.base.yml
        service: llm
    ports:
        - '8547:8547'
    build:
        network: host
        context: ./LLM
        dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  oneuptime:
    driver: bridge