#
# OneUptime Docs Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

# Install common-server
RUN mkdir /usr/src
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm ci
COPY ./common-server /usr/src/common-server

#SET ENV Variables

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true




WORKDIR /usr/src/app

# Copy package.json files
COPY ./api-docs/package.json /usr/src/app/package.json
COPY ./api-docs/package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm ci

# Expose ports.
#   - 3000:  OneUptime
EXPOSE 3000

#Run the app
CMD [ "npm", "run", "dev" ]
