#
# OneUptime Docs Dockerfile
#

# Pull base image nodejs image.
FROM node:17-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

#SET ENV Variables

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Install nodemon 
RUN npm install nodemon -g

WORKDIR /usr/src/app

# Copy package.json files
COPY ./api-docs/package.json /usr/src/app/package.json
COPY ./api-docs/package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm ci

# Expose ports.
#   - 3000:  OneUptime
EXPOSE 3000

#Run the app
CMD [ "npm", "run", "dev" ]
