import Route from "../../API/Route";
import IconProp from "../../Icon/IconProp";
import ComponentID from "../ComponentID";
import ComponentMetadata, {
  ComponentInputType,
  ComponentType,
} from "./../Component";

const components: Array<ComponentMetadata> = [
  {
    id: ComponentID.AIGenerateText,
    title: "Generate Text with AI",
    category: "AI",
    description:
      "Generate text from an instruction and explicit workflow context using the project's configured LLM provider.",
    iconProp: IconProp.Sparkles,
    componentType: ComponentType.Component,
    documentationLink: Route.fromString("/workflow/docs/AI.md"),
    arguments: [
      {
        type: ComponentInputType.LongText,
        name: "System Instructions",
        description:
          "Optional high-level instructions that define the model's role, tone, or constraints.",
        required: false,
        id: "system-prompt",
        placeholder:
          "Example: Write concise, customer-safe operational updates.",
        isSensitive: true,
      },
      {
        type: ComponentInputType.Markdown,
        name: "Prompt",
        description:
          "The task for the model. You can insert values from variables or earlier workflow components.",
        required: true,
        id: "prompt",
        placeholder: "Summarize the following incident for our support team.",
        isSensitive: true,
      },
      {
        type: ComponentInputType.JSON,
        name: "Context",
        description:
          "Optional JSON data appended after an explicit marker as untrusted workflow context.",
        required: false,
        id: "context",
        placeholder: '{ "incident": "{{...}}" }',
        isSensitive: true,
      },
      {
        type: ComponentInputType.Decimal,
        name: "Temperature",
        description:
          "Controls variation from 0 to 1. Defaults to 0.2 for predictable workflow output.",
        required: false,
        id: "temperature",
        placeholder: "0.2",
        isAdvanced: true,
      },
      {
        type: ComponentInputType.Number,
        name: "Maximum Output Tokens",
        description:
          "Maximum tokens the model may generate, from 1 to 4096. Defaults to 1024.",
        required: false,
        id: "max-output-tokens",
        placeholder: "1024",
        isAdvanced: true,
      },
    ],
    returnValues: [
      {
        type: ComponentInputType.LongText,
        name: "Response",
        description: "Text generated by the configured AI model.",
        required: false,
        id: "response",
        isSensitive: true,
      },
      {
        type: ComponentInputType.Text,
        name: "Provider",
        description: "Name of the LLM provider used for the request.",
        required: false,
        id: "provider",
      },
      {
        type: ComponentInputType.Text,
        name: "Model",
        description: "Configured model name used for the request.",
        required: false,
        id: "model",
      },
      {
        type: ComponentInputType.Number,
        name: "Total Tokens",
        description: "Total input and output tokens reported by the provider.",
        required: false,
        id: "total-tokens",
      },
      {
        type: ComponentInputType.Number,
        name: "Completion Tokens",
        description: "Output tokens reported by the provider.",
        required: false,
        id: "completion-tokens",
      },
      {
        type: ComponentInputType.Text,
        name: "LLM Log ID",
        description: "ID of the metered LLM log for this request.",
        required: false,
        id: "llm-log-id",
      },
      {
        type: ComponentInputType.Text,
        name: "Error",
        description: "Error message when the request follows the Error port.",
        required: false,
        id: "error",
      },
    ],
    inPorts: [
      {
        title: "In",
        description:
          "Connect the component that should run before AI generation.",
        id: "in",
      },
    ],
    outPorts: [
      {
        title: "Success",
        description: "Runs when the model returns a response successfully.",
        id: "success",
      },
      {
        title: "Error",
        description:
          "Runs when validation, access, provider, budget, billing, or timeout checks fail.",
        id: "error",
      },
    ],
  },
];

export default components;
