import PageComponentProps from "../../PageComponentProps";
import React, {
  Fragment,
  FunctionComponent,
  ReactElement,
  useState,
} from "react";
import { useParams } from "react-router-dom";
import ObjectID from "Common/Types/ObjectID";
import ModelTable from "Common/UI/Components/ModelTable/ModelTable";
import AIAgentTaskLog from "Common/Models/DatabaseModels/AIAgentTaskLog";
import FieldType from "Common/UI/Components/Types/FieldType";
import Navigation from "Common/UI/Utils/Navigation";
import { ButtonStyleType } from "Common/UI/Components/Button/Button";
import IconProp from "Common/Types/Icon/IconProp";
import Modal, { ModalWidth } from "Common/UI/Components/Modal/Modal";
import SimpleLogViewer from "Common/UI/Components/SimpleLogViewer/SimpleLogViewer";
import {
  AIAgentTaskLogEntries,
  AIAgentTaskLogEntry,
} from "Common/Types/AI/AIAgentTaskLog";
import LogSeverity from "Common/Types/Log/LogSeverity";
import Pill from "Common/UI/Components/Pill/Pill";
import { Green, Red, Yellow, Blue, Gray500 } from "Common/Types/BrandColors";
import OneUptimeDate from "Common/Types/Date";

const AIAgentTaskLogsPage: FunctionComponent<
  PageComponentProps
> = (): ReactElement => {
  const { id } = useParams();
  const modelId: ObjectID = new ObjectID(id || "");

  const [showViewLogsModal, setShowViewLogsModal] = useState<boolean>(false);
  const [logEntries, setLogEntries] = useState<AIAgentTaskLogEntries>([]);

  const getSeverityPill = (severity: LogSeverity): ReactElement => {
    switch (severity) {
      case LogSeverity.Error:
      case LogSeverity.Fatal:
        return <Pill text={severity} color={Red} />;
      case LogSeverity.Warning:
        return <Pill text={severity} color={Yellow} />;
      case LogSeverity.Information:
        return <Pill text={severity} color={Green} />;
      case LogSeverity.Debug:
      case LogSeverity.Trace:
        return <Pill text={severity} color={Blue} />;
      default:
        return <Pill text={severity} color={Gray500} />;
    }
  };

  return (
    <Fragment>
      <>
        <ModelTable<AIAgentTaskLog>
          modelType={AIAgentTaskLog}
          id="ai-agent-task-logs-table"
          isDeleteable={false}
          isEditable={false}
          isCreateable={false}
          userPreferencesKey="ai-agent-task-logs-table"
          name="AI Agent Task Logs"
          query={{
            aiAgentTaskId: modelId,
          }}
          selectMoreFields={{
            logs: true,
          }}
          actionButtons={[
            {
              title: "View Logs",
              buttonStyleType: ButtonStyleType.NORMAL,
              icon: IconProp.List,
              onClick: async (
                item: AIAgentTaskLog,
                onCompleteAction: VoidFunction,
              ) => {
                setLogEntries((item.logs as AIAgentTaskLogEntries) || []);
                setShowViewLogsModal(true);
                onCompleteAction();
              },
            },
          ]}
          isViewable={false}
          cardProps={{
            title: "Task Logs",
            description:
              "Log entries generated by the AI agent during task execution.",
          }}
          noItemsMessage={"No logs have been generated for this task yet."}
          showRefreshButton={true}
          viewPageRoute={Navigation.getCurrentRoute()}
          filters={[
            {
              field: {
                createdAt: true,
              },
              title: "Created At",
              type: FieldType.Date,
            },
            {
              field: {
                aiAgent: {
                  name: true,
                },
              },
              title: "AI Agent",
              type: FieldType.Entity,
            },
          ]}
          columns={[
            {
              field: {
                _id: true,
              },
              title: "Log ID",
              type: FieldType.ObjectID,
            },
            {
              field: {
                aiAgent: {
                  name: true,
                },
              },
              title: "AI Agent",
              type: FieldType.Entity,
              getElement: (item: AIAgentTaskLog): ReactElement => {
                return <>{item.aiAgent?.name || "Unknown"}</>;
              },
            },
            {
              field: {
                createdAt: true,
              },
              title: "Created At",
              type: FieldType.DateTime,
            },
          ]}
        />

        {showViewLogsModal && (
          <Modal
            title={"Task Logs"}
            description="Log entries from this task execution"
            isLoading={false}
            modalWidth={ModalWidth.Large}
            onSubmit={() => {
              setShowViewLogsModal(false);
            }}
            submitButtonText={"Close"}
            submitButtonStyleType={ButtonStyleType.NORMAL}
          >
            <SimpleLogViewer>
              {logEntries.length === 0 ? (
                <div>No log entries found.</div>
              ) : (
                logEntries.map((entry: AIAgentTaskLogEntry, i: number) => {
                  return (
                    <div
                      key={i}
                      className="flex items-start space-x-2 py-1 border-b border-gray-700"
                    >
                      <span className="text-gray-400 text-xs whitespace-nowrap">
                        {OneUptimeDate.getDateAsLocalFormattedString(
                          entry.logAt,
                          true,
                        )}
                      </span>
                      <span>{getSeverityPill(entry.severity)}</span>
                      <span className="flex-1">{entry.message}</span>
                    </div>
                  );
                })
              )}
            </SimpleLogViewer>
          </Modal>
        )}
      </>
    </Fragment>
  );
};

export default AIAgentTaskLogsPage;
