import ProjectType from '../types/project';

class Project {
    static getProjects(): Array<ProjectType> {
        return [
            {
                name: 'licensing',
                path: 'licensing',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'dashboard',
                path: 'dashboard',
                isReact: true,
                isApiServer: false,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'admin-dashboard',
                path: 'admin-dashboard',
                isReact: true,
                isApiServer: false,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'accounts',
                path: 'accounts',
                isReact: true,
                isApiServer: false,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'status-page',
                path: 'status-page',
                isReact: true,
                isApiServer: false,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'http-test-server',
                path: 'http-test-server',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'api-docs',
                path: 'api-docs',
                isReact: false,
                isApiServer: false,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'backend',
                path: 'backend',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'application-scanner',
                path: 'aplication-scanner',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'common',
                path: 'common',
                isReact: false,
                isApiServer: true,
                isTypeScript: true,
                isDependency: true,
            },
            {
                name: 'common-ui',
                path: 'common-ui',
                isReact: true,
                isApiServer: false,
                isTypeScript: true,
                isDependency: true,
            },
            {
                name: 'common-server',
                path: 'common-server',
                isReact: false,
                isApiServer: true,
                isTypeScript: true,
                isDependency: true,
            },
            {
                name: 'data-ingestor',
                path: 'data-ingestor',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'helm-chart',
                path: 'helm-chart',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'home',
                path: 'home',
                isReact: false,
                isApiServer: true,
                isTypeScript: true,
                isDependency: false,
            },
            {
                name: 'init-script',
                path: 'init-script',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },

            {
                name: 'js-sdk',
                path: 'js-sdk',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'licesning',
                path: 'licesning',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'lighthouse-runner',
                path: 'lighthouse-runner',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'oneuptime-acme-http-01',
                path: 'oneuptime-acme-http-01',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'oneuptime-gl-manager',
                path: 'oneuptime-gl-manager',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'oneuptime-le-store',
                path: 'oneuptime-le-store',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'probe',
                path: 'probe',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'probe-api',
                path: 'probe-api',
                isReact: false,
                isApiServer: true,
                isTypeScript: true,
                isDependency: false,
            },
            {
                name: 'script-runner',
                path: 'script-runner',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'realtime',
                path: 'realtime',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
            {
                name: 'zapier',
                path: 'zapier',
                isReact: false,
                isApiServer: true,
                isTypeScript: false,
                isDependency: false,
            },
        ];
    }
}

export default Project;
