#
# OneUptime-backend Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl


# Install python
RUN apk update && apk add --no-cache --virtual .gyp python3 make g++

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

# Install common-server
RUN mkdir /usr/src
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm install
COPY ./common-server /usr/src/common-server

#SET ENV Variables

WORKDIR /usr/src/app

# Install trivy for container scanning
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin

# Install app dependencies
RUN cd /usr/src/app

RUN mkdir -p greenlock.d || echo "Directory already exists"

# Copy package.json files
COPY ./backend/package.json /usr/src/app/package.json
COPY ./backend/package-lock.json /usr/src/app/package-lock.json


RUN npm install

# Expose ports.
#   - 3002: OneUptime-backend
EXPOSE 3002
EXPOSE 9229

#Run the app
CMD [ "npm", "run", "dev"]
