#
# Fyipe-backend Dockerfile
#

# Pull base image nodejs image.
FROM node:16

#SET ENV Variables


WORKDIR /usr/src/app

# Install trivy for container scanning
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin

# Install app dependencies
RUN cd /usr/src/app

RUN mkdir -p greenlock.d
# Copy package.json files
COPY ./package.json /usr/src/app/package.json


RUN npm install

# Expose ports.
#   - 3002: Fyipe-backend
EXPOSE 3002
EXPOSE 9229

#Run the app
CMD [ "npm", "run", "dev"]
