#
# Accounts Dockerfile
#

# Pull base image nodejs image.
FROM node:16

#SET ENV Variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

WORKDIR /usr/src/app

# Copy package.json files
COPY ./package.json /usr/src/app/package.json


# Install app dependencies
RUN npm install

# Expose ports.
#   - 3009: Fyipe:script-runner
EXPOSE 3009

# Expose Debugging port.
EXPOSE 9229

#Run the app
CMD [ "npm", "run", "dev" ]
