#
# Accounts Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

RUN mkdir /usr/src

# Install common
RUN mkdir /usr/src/common
WORKDIR /usr/src/common
COPY ./common/package*.json /usr/src/common/
RUN npm install
COPY ./common /usr/src/common

# Install common-server
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm install
COPY ./common-server /usr/src/common-server

#SET ENV Variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true




WORKDIR /usr/src/app

# Copy package.json files
COPY ./script-runner/package.json /usr/src/app/package.json
COPY ./script-runner/package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm install

# Expose ports.
#   - 3009: OneUptime:script-runner
EXPOSE 3009

# Expose Debugging port.
EXPOSE 9229

#Run the app
CMD [ "npm", "run", "dev" ]
