#
# Accounts Dockerfile
#

# Pull base image nodejs image.
FROM node:16

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

#SET ENV Variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Install nodemon 
RUN npm install nodemon -g

WORKDIR /usr/src/app

# Copy package.json files
COPY ./package.json /usr/src/app/package.json
COPY ./package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm ci

# Expose ports.
#   - 3009: Fyipe:script-runner
EXPOSE 3009

# Expose Debugging port.
EXPOSE 9229

#Run the app
CMD [ "npm", "run", "dev" ]
