apiVersion: v2
name: oneuptime
description: The Complete Open-Source Observability Platform
icon: https://raw.githubusercontent.com/OneUptime/oneuptime/master/Home/Static/img/OneUptimePNG/1.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: monitoring-logging
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: 83F2C1DDF58A052464C4A1729D87E494AC016697
    url: https://keybase.io/oneuptime/pgp_keys.asc


dependencies:
- name: keda
  version: "2.17.2"
  repository: "https://kedacore.github.io/charts"
  condition: keda.enabled
- name: cert-manager
  version: "v1.18.2"
  repository: "https://charts.jetstack.io"
  condition: cert-manager.enabled

