#
# Home Dev Dockerfile
#

# Pull base image nodejs image.
FROM node:17-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

#SET ENV Variables

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Install nodemon 
RUN npm install nodemon -g

WORKDIR /usr/src/app

# Copy package.json files
COPY ./home/package.json /usr/src/app/package.json
COPY ./home/package-lock.json /usr/src/app/package-lock.json


# Install app dependencies
RUN npm ci

# Expose ports.
#   - 1444: OneUptime Home
EXPOSE 1444

# Expose Debugger port
EXPOSE 9229 

#Run the app
CMD [ "npm", "run", "dev" ]
