apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.oneuptime.apiKey | b64enc | quote }}
