import ExceptionPullRequestTaskHandler from "./ExceptionPullRequestTaskHandler";
import { ExceptionDetails } from "../Utils/BackendAPI";
import PullRequestCreator from "../Utils/PullRequestCreator";
import CodeFixTaskType from "Common/Types/AI/CodeFixTaskType";

/*
 * Fixes an exception: the code agent analyzes the stack trace, patches the
 * root cause, and the shared pipeline opens a pull request with the fix.
 */
export default class FixExceptionTaskHandler extends ExceptionPullRequestTaskHandler {
  public readonly taskType: string = CodeFixTaskType.FixException;
  public readonly name: string = "Fix Exception Handler";

  protected readonly branchPrefix: string = "oneuptime-fix-exception-";
  protected readonly noActionMessage: string =
    "No fixes could be applied to any repository";

  // Build the prompt for the code agent
  protected buildPrompt(
    exceptionDetails: ExceptionDetails,
    servicePathInRepository: string | null,
  ): string {
    let prompt: string = `You are a software engineer fixing a bug in a codebase.

## Exception Information

**Exception Type:** ${exceptionDetails.exception.exceptionType}

**Error Message:**
${exceptionDetails.exception.message}

**Stack Trace:**
\`\`\`
${exceptionDetails.exception.stackTrace}
\`\`\`

## Task

Please analyze the stack trace and fix the exception. Here are the steps to follow:

1. Identify the root cause of the exception from the stack trace
2. Find the relevant source files in the codebase
3. Implement a fix for the issue
4. Make sure your fix handles edge cases appropriately
5. The fix should be minimal and focused - only change what's necessary

## Guidelines

- Do NOT add excessive error handling or logging unless necessary
- Do NOT refactor unrelated code
- Keep the fix simple and targeted
- Preserve existing code style and patterns
- If you cannot determine how to fix the issue, explain why

## Hard Rules — never break these

- NEVER delete or weaken input validation, authentication, authorization,
  payment/plan checks, rate limits, or state-machine invariants to make an
  error stop occurring. If the exception is thrown by an intentional check
  rejecting bad or unauthorized input, that check is working: the correct
  fix is to validate earlier, return a clearer error to the caller, or make
  no change — never to remove the check.
- If the exception reflects invalid END-USER input or an expected denial
  (a 4xx-style condition) rather than a code defect, prefer improving the
  validation and the error message over changing behavior. If no safe code
  change exists, make no changes and explain why.
- NEVER change shared utilities or cross-cutting contracts to suppress a
  single call site's error; fix the call site.
- If the throw site interpolates dynamic values (IDs, emails, domains,
  file paths, request payloads) directly into the exception message,
  rewrite that message to be parameterized: keep the message static and
  move the dynamic values into structured attributes/fields. This keeps
  user data out of error messages and stops the same root cause from
  splintering into many separate exception groups.

Please proceed with analyzing and fixing this exception.`;

    if (servicePathInRepository) {
      prompt = `The service code is located in the \`${servicePathInRepository}\` directory.\n\n${prompt}`;
    }

    return prompt;
  }

  /*
   * Commit subject and PR title are built from the exception TYPE and
   * service — never the message, which can interpolate user data.
   */
  protected buildCommitMessage(exceptionDetails: ExceptionDetails): string {
    const subject: string = PullRequestCreator.generatePRTitle({
      exceptionType: exceptionDetails.exception.exceptionType,
      serviceName: exceptionDetails.service?.name || "",
    });

    return `${subject}

This commit fixes an exception detected by OneUptime.

Exception Type: ${exceptionDetails.exception.exceptionType}
Exception ID: ${exceptionDetails.exception.id}

Automatically generated by OneUptime AI Agent.`;
  }

  // Build the pull request title
  protected buildPullRequestTitle(exceptionDetails: ExceptionDetails): string {
    return PullRequestCreator.generatePRTitle({
      exceptionType: exceptionDetails.exception.exceptionType,
      serviceName: exceptionDetails.service?.name || "",
    });
  }

  // Build the pull request body
  protected buildPullRequestBody(
    exceptionDetails: ExceptionDetails,
    agentSummary: string,
  ): string {
    return PullRequestCreator.generatePRBody({
      exceptionMessage: exceptionDetails.exception.message,
      exceptionType: exceptionDetails.exception.exceptionType,
      stackTrace: exceptionDetails.exception.stackTrace,
      serviceName: exceptionDetails.service?.name || "Unknown Service",
      summary: agentSummary,
    });
  }

  // Get handler description
  public getDescription(): string {
    return "Analyzes exceptions detected by OneUptime and attempts to fix them by modifying the source code and creating a pull request.";
  }
}
