#
# application-scanner Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

RUN mkdir /usr/src

# Install common
RUN mkdir /usr/src/common
WORKDIR /usr/src/common
COPY ./common/package*.json /usr/src/common/
RUN npm install
COPY ./common /usr/src/common
RUN npm compile

# Install common-server
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm install
COPY ./common-server /usr/src/common-server
RUN npm compile

WORKDIR /usr/src/app

# Install app dependencies
RUN cd /usr/src/app

# Copy package.json files
COPY ./application-scanner/package.json /usr/src/app/package.json
COPY ./application-scanner/package-lock.json /usr/src/app/package-lock.json


RUN npm install

# Expose ports.
#   - 3005: Application Scanner
EXPOSE 3005

#Run the app
RUN npm compile
CMD [ "npm", "run", "dev"]

