#
# lighthouse-runner Dockerfile
#

# Pull base image nodejs image.
FROM node:17-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

#SET ENV Variables
ENV CHROME_PATH=/usr/bin/google-chrome

WORKDIR /usr/src/app

RUN apk add chromium


# Install app dependencies
RUN cd /usr/src/app

# Copy package.json files
COPY ./package.json /usr/src/app/package.json
COPY ./package-lock.json /usr/src/app/package-lock.json


RUN npm ci

# Expose ports.
#   - 3015: Lighthouse Runner
EXPOSE 3015

#Run the app
CMD [ "npm", "run", "dev"]

