#
# lighthouse-runner Dockerfile
#

# Pull base image nodejs image.
FROM node:17-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

# Install common-server
RUN mkdir /usr/src
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm ci
COPY ./common-server /usr/src/common-server

#SET ENV Variables
ENV CHROME_PATH=/usr/bin/google-chrome

WORKDIR /usr/src/app

RUN apk add chromium


# Install app dependencies
RUN cd /usr/src/app

# Copy package.json files
COPY ./lighthouse-runner/package.json /usr/src/app/package.json
COPY ./lighthouse-runner/package-lock.json /usr/src/app/package-lock.json


RUN npm ci

# Expose ports.
#   - 3015: Lighthouse Runner
EXPOSE 3015

#Run the app
CMD [ "npm", "run", "dev"]

