import SubjectPullRequestTaskHandler from "./SubjectPullRequestTaskHandler";
import { SubjectTaskDetails } from "../Utils/BackendAPI";
import CodeFixTaskType from "Common/Types/AI/CodeFixTaskType";

/*
 * FixFromIncident: a completed Sentinel investigation's root-cause analysis
 * becomes the pull request that fixes the identified cause — the roadmap's
 * headline `code_fix` recipe in human-triggered form (the user clicks
 * "Open Fix PR from this analysis" on the investigation panel).
 *
 * Like its ImproveInstrumentation sibling, this task has no telemetry
 * exception: its subject is the investigated incident/alert, and its context
 * (the posted analysis + the repository resolved without a stack trace)
 * comes from /ai-agent-data/get-instrumentation-task-details keyed by the
 * run id — the shared SubjectPullRequestTaskHandler pipeline.
 */
export default class FixFromIncidentTaskHandler extends SubjectPullRequestTaskHandler {
  public readonly taskType: string = CodeFixTaskType.FixFromIncident;
  public readonly name: string = "Fix From Incident Handler";

  protected readonly branchPrefix: string = "oneuptime-incident-fix-";
  protected readonly noActionMessage: string =
    "No fix could be applied to any repository";
  protected readonly noRepositoryMessage: string =
    "Could not resolve a repository for this fix task. Connect the right repository through the GitHub App.";

  // Build the prompt for the code agent
  protected buildPrompt(
    details: SubjectTaskDetails,
    servicePathInRepository: string | null,
  ): string {
    let prompt: string = `You are a senior software engineer fixing the root cause of a production ${details.subjectType}.

OneUptime's autonomous AI SRE investigated a production ${details.subjectType} titled "${details.subjectTitle}"${
      details.serviceName
        ? ` affecting the service "${details.serviceName}"`
        : ""
    } and identified a root cause. Its full analysis is below: it cites the telemetry evidence it examined and names the cause it concluded.

## Root Cause Analysis

${details.analysisMarkdown}

## Task

Fix the root cause the analysis identifies. Steps:

1. Read the analysis carefully: identify the concluded root cause and which operations, services, or code paths it implicates
2. Find those code paths in this repository
3. Implement a fix for the identified cause
4. Make sure the fix handles edge cases appropriately
5. Include or adjust tests where this repository's conventions make it natural (existing test directories, naming patterns, frameworks already in use) — do NOT introduce a new test framework

## Requirements

- Keep the diff small and focused: fix the identified cause, nothing else
- Follow the repository's EXISTING conventions and code style exactly
- Do NOT add unrelated refactors, drive-by cleanups, or new dependencies
- If the analysis implicates configuration or infrastructure outside this repository, fix what IS in this repository and explain the rest
- If none of the implicated code paths are in this repository, or the analysis does not identify a fixable cause, explain why and make no changes

Please proceed with fixing the root cause.`;

    if (servicePathInRepository) {
      prompt = `The service code is located in the \`${servicePathInRepository}\` directory.\n\n${prompt}`;
    }

    return prompt;
  }

  // Build commit message for the fix
  protected buildCommitMessage(details: SubjectTaskDetails): string {
    const shortTitle: string = this.cleanSubjectTitle(
      details.subjectTitle,
      SubjectPullRequestTaskHandler.COMMIT_SUBJECT_TITLE_LENGTH,
    );

    return `fix: ${shortTitle}

Fixes the root cause identified by OneUptime AI's automated investigation
of this ${details.subjectType}.

Automatically generated by OneUptime AI Agent.`;
  }

  // Build the pull request title
  protected buildPullRequestTitle(details: SubjectTaskDetails): string {
    const shortTitle: string = this.cleanSubjectTitle(
      details.subjectTitle,
      SubjectPullRequestTaskHandler.PR_TITLE_SUBJECT_LENGTH,
    );

    return `fix: ${shortTitle}`;
  }

  // Build the pull request body — the analysis IS the rationale.
  protected buildPullRequestBody(
    details: SubjectTaskDetails,
    agentSummary: string,
  ): string {
    const analysis: string = details.analysisMarkdown;
    const analysisCap: number =
      SubjectPullRequestTaskHandler.PR_BODY_ANALYSIS_LENGTH;

    return `## Fix from Incident Analysis

This pull request was generated from an AI investigation — OneUptime's AI SRE investigated a production ${details.subjectType}, and this PR attempts to fix the root cause its analysis identified.

**${details.subjectType === "incident" ? "Incident" : "Alert"}:** ${details.subjectTitle}
**Service:** ${details.serviceName || "Unknown"}

### Root cause analysis (the investigation's findings)

${analysis.substring(0, analysisCap)}${analysis.length > analysisCap ? "\n...(truncated)" : ""}

### Summary of Changes

${agentSummary}

---

> **Generated from an AI investigation — opened as a draft, review before merging.** The analysis above is AI-authored: verify the diagnosis matches this diff before accepting the fix, then mark the pull request ready for review. Nothing is merged automatically.

*This PR was automatically generated by [OneUptime AI Agent](https://oneuptime.com)*`;
  }

  // Get handler description
  public getDescription(): string {
    return "Turns a completed AI investigation's root-cause analysis into a pull request that fixes the identified cause — a small focused diff following the repository's conventions, with tests where they are natural.";
  }
}
