import SubjectPullRequestTaskHandler from "./SubjectPullRequestTaskHandler";
import { SubjectTaskDetails } from "../Utils/BackendAPI";
import CodeFixTaskType from "Common/Types/AI/CodeFixTaskType";

/*
 * FixPerformance: a deterministically-detected performance pattern in a
 * trace (N+1 queries, one dominant slow span, sequential-that-could-be-
 * parallel siblings) becomes the pull request that fixes it — human-
 * triggered from the trace view ("Fix performance with AI").
 *
 * This task has no telemetry exception and no incident/alert subject: its
 * entire context is the SpanTreeAnalyzer evidence captured into
 * AIRun.taskContext at trigger time and served back (rendered + structured)
 * by /ai-agent-data/get-instrumentation-task-details keyed by the run id —
 * the shared SubjectPullRequestTaskHandler pipeline with subjectType
 * "trace". The evidence is the recipe's contract: the agent fixes ONLY the
 * evidenced pattern, never speculative optimizations.
 */
export default class FixPerformanceTaskHandler extends SubjectPullRequestTaskHandler {
  public readonly taskType: string = CodeFixTaskType.FixPerformance;
  public readonly name: string = "Fix Performance Handler";

  protected readonly branchPrefix: string = "oneuptime-perf-fix-";
  protected readonly noActionMessage: string =
    "No performance fix could be applied to any repository";
  protected readonly noRepositoryMessage: string =
    "Could not resolve a repository for this performance fix task. Connect the right repository through the GitHub App.";

  // Build the prompt for the code agent
  protected buildPrompt(
    details: SubjectTaskDetails,
    servicePathInRepository: string | null,
  ): string {
    let prompt: string = `You are a senior performance engineer fixing a measured performance problem in a production trace.

OneUptime analyzed the span tree of a production trace${
      details.serviceName ? ` from the service "${details.serviceName}"` : ""
    } DETERMINISTICALLY (no AI involved in the detection) and found the pattern(s) below. Every number is measured from the actual spans.

## Performance Evidence

${details.analysisMarkdown}

## Task

Fix ONLY the evidenced pattern(s) above. What the right fix looks like depends on the pattern:

- **N+1 pattern** (many near-identical sibling operations): batch the repeated operation — one query with an IN/JOIN instead of one query per item, a bulk fetch instead of a per-item HTTP call, or a dataloader/cache where that is this codebase's idiom
- **Sequential siblings that could be parallel**: run the independent operations concurrently (e.g. Promise.all / asyncio.gather / errgroup — whatever this repository already uses); do NOT parallelize operations that depend on each other's results
- **Dominant slow span**: make the single dominant operation cheaper — add the missing index, narrow the selected columns, add caching, or restructure the hot operation, following what the evidence (statement/URL) implicates

Steps:

1. Read the evidence carefully: the span names, normalized statements, and URLs identify the exact operations
2. Find the code that emits those operations in this repository
3. Implement the fix for the evidenced pattern
4. Include or adjust tests where this repository's conventions make it natural (existing test directories, naming patterns, frameworks already in use) — do NOT introduce a new test framework

## Requirements

- Keep the diff small and focused: fix the evidenced pattern, nothing else
- NO speculative optimizations: do not touch code paths the evidence does not implicate, even if they look slow
- Follow the repository's EXISTING conventions and code style exactly
- Do NOT add unrelated refactors, drive-by cleanups, or new dependencies
- If the fix belongs in configuration or infrastructure outside this repository (e.g. a database index migration lives elsewhere), fix what IS in this repository and explain the rest
- If none of the implicated operations are emitted from this repository, explain why and make no changes

Please proceed with fixing the evidenced performance pattern.`;

    if (servicePathInRepository) {
      prompt = `The service code is located in the \`${servicePathInRepository}\` directory.\n\n${prompt}`;
    }

    return prompt;
  }

  // Build commit message for the fix
  protected buildCommitMessage(details: SubjectTaskDetails): string {
    const shortTitle: string = this.cleanSubjectTitle(
      details.subjectTitle,
      SubjectPullRequestTaskHandler.COMMIT_SUBJECT_TITLE_LENGTH,
    );

    return `perf: ${shortTitle}

Fixes a performance pattern detected deterministically in a production
trace's span tree by OneUptime.

Automatically generated by OneUptime AI Agent.`;
  }

  // Build the pull request title — the top finding's headline.
  protected buildPullRequestTitle(details: SubjectTaskDetails): string {
    const shortTitle: string = this.cleanSubjectTitle(
      details.subjectTitle,
      SubjectPullRequestTaskHandler.PR_TITLE_SUBJECT_LENGTH,
    );

    return `perf: ${shortTitle}`;
  }

  // Build the pull request body — the evidence IS the rationale.
  protected buildPullRequestBody(
    details: SubjectTaskDetails,
    agentSummary: string,
  ): string {
    const evidence: string = details.analysisMarkdown;
    const evidenceCap: number =
      SubjectPullRequestTaskHandler.PR_BODY_ANALYSIS_LENGTH;

    return `## Performance Fix from Trace Evidence

This pull request was generated from deterministic span-tree analysis of a production trace — no AI was involved in DETECTING the problem below; the AI agent only wrote the fix for it.

**Trace:** \`${details.traceId || "unknown"}\`
**Service:** ${details.serviceName || "Unknown"}

### Performance evidence (measured from the trace's spans)

${evidence.substring(0, evidenceCap)}${evidence.length > evidenceCap ? "\n...(truncated)" : ""}

### Summary of Changes

${agentSummary}

---

> **Opened as a draft — review before merging.** The evidence above is measured; the fix is AI-authored — verify the change actually batches/parallelizes/optimizes the implicated operations and nothing else, then mark the pull request ready for review. Nothing is merged automatically.

*This PR was automatically generated by [OneUptime AI Agent](https://oneuptime.com)*`;
  }

  // Get handler description
  public getDescription(): string {
    return "Turns a deterministically-detected trace performance pattern (N+1, dominant span, sequential siblings) into a pull request that fixes exactly the evidenced pattern — a small focused diff following the repository's conventions.";
  }
}
