import SubjectPullRequestTaskHandler from "./SubjectPullRequestTaskHandler";
import { SubjectTaskDetails } from "../Utils/BackendAPI";
import CodeFixTaskType from "Common/Types/AI/CodeFixTaskType";

/*
 * ImproveInstrumentation: an inconclusive Sentinel investigation (root cause
 * undeterminable — insufficient telemetry) becomes a pull request that adds
 * the missing observability, so the NEXT investigation of a similar signal
 * can reach a conclusion.
 *
 * Unlike the exception-driven recipes, this task has no telemetry exception:
 * its subject is the investigated incident/alert, and its context (the
 * inconclusive analysis + the repository resolved without a stack trace)
 * comes from /ai-agent-data/get-instrumentation-task-details keyed by the
 * run id — the shared SubjectPullRequestTaskHandler pipeline.
 */
export default class ImproveInstrumentationTaskHandler extends SubjectPullRequestTaskHandler {
  public readonly taskType: string = CodeFixTaskType.ImproveInstrumentation;
  public readonly name: string = "Improve Instrumentation Handler";

  protected readonly branchPrefix: string = "oneuptime-instrumentation-";
  protected readonly noActionMessage: string =
    "No instrumentation could be added to any repository";
  protected readonly noRepositoryMessage: string =
    "Could not resolve a repository for this instrumentation task. Connect the right repository through the GitHub App.";

  // Build the prompt for the code agent
  protected buildPrompt(
    details: SubjectTaskDetails,
    servicePathInRepository: string | null,
  ): string {
    let prompt: string = `You are a software engineer improving the observability of a codebase.

OneUptime's autonomous AI SRE investigated a production ${details.subjectType} titled "${details.subjectTitle}"${
      details.serviceName
        ? ` affecting the service "${details.serviceName}"`
        : ""
    } and could NOT determine the root cause — the available telemetry was INSUFFICIENT. Its full inconclusive analysis is below: it lists what was checked, what the evidence showed, and what was missing.

## Inconclusive Investigation Analysis

${details.analysisMarkdown}

## Task

Add the missing observability to the code paths the analysis implicates, so the NEXT investigation of a similar signal can reach a conclusion. Steps:

1. Read the analysis carefully: identify which operations, services, or code paths it discusses and — most importantly — which questions it could NOT answer for lack of telemetry
2. Find those code paths in this repository
3. Add structured log statements at the decision points where the analysis lacked visibility, including the relevant identifiers/attributes a future investigation would query by
4. Wrap the operations the analysis discusses in OpenTelemetry spans (or the repository's existing tracing idiom) where they are missing, with span attributes covering the unknowns the analysis calls out
5. Add metric counters or histograms ONLY where the analysis explicitly mentions an unmeasured rate, count, or duration

## Requirements

- Follow the repository's EXISTING telemetry idioms exactly — use the logger, tracer, and metrics libraries already in use; do NOT introduce new dependencies or frameworks
- Do NOT change any business logic, control flow, error handling behavior, or return values — this change is instrumentation only
- Keep the diff small and focused: instrument the code paths the analysis implicates, not the whole codebase
- Never log secrets, credentials, tokens, or full request/response bodies
- If you cannot find the implicated code paths in this repository, explain why and make no changes

Please proceed with adding the missing instrumentation.`;

    if (servicePathInRepository) {
      prompt = `The service code is located in the \`${servicePathInRepository}\` directory.\n\n${prompt}`;
    }

    return prompt;
  }

  // Build commit message for the instrumentation change
  protected buildCommitMessage(details: SubjectTaskDetails): string {
    const shortTitle: string = this.cleanSubjectTitle(
      details.subjectTitle,
      SubjectPullRequestTaskHandler.COMMIT_SUBJECT_TITLE_LENGTH,
    );

    return `chore(observability): add instrumentation for ${shortTitle}

OneUptime AI's automated investigation of this ${details.subjectType} was
inconclusive because the telemetry was insufficient. This commit adds the
missing logs/spans/metrics to the implicated code paths — no business
logic is changed.

Automatically generated by OneUptime AI Agent.`;
  }

  // Build the pull request title
  protected buildPullRequestTitle(details: SubjectTaskDetails): string {
    const shortTitle: string = this.cleanSubjectTitle(
      details.subjectTitle,
      SubjectPullRequestTaskHandler.PR_TITLE_SUBJECT_LENGTH,
    );

    return `chore(observability): add instrumentation for ${shortTitle}`;
  }

  // Build the pull request body — the inconclusive analysis IS the rationale.
  protected buildPullRequestBody(
    details: SubjectTaskDetails,
    agentSummary: string,
  ): string {
    const analysis: string = details.analysisMarkdown;
    const analysisCap: number =
      SubjectPullRequestTaskHandler.PR_BODY_ANALYSIS_LENGTH;

    return `## Observability Improvement

This pull request was automatically generated by OneUptime AI Agent because OneUptime AI's automated investigation of a production ${details.subjectType} was **inconclusive** — the available telemetry was insufficient to determine a root cause. The changes add the missing instrumentation (structured logs, spans, metrics) to the implicated code paths so the next investigation of a similar signal can reach a conclusion.

**${details.subjectType === "incident" ? "Incident" : "Alert"}:** ${details.subjectTitle}
**Service:** ${details.serviceName || "Unknown"}

### Why: the inconclusive investigation

${analysis.substring(0, analysisCap)}${analysis.length > analysisCap ? "\n...(truncated)" : ""}

### Summary of Changes

${agentSummary}

---

> **Instrumentation only** — this PR must not change business logic. It is opened as a draft: review it and mark it ready for review before merging; nothing is merged automatically.

*This PR was automatically generated by [OneUptime AI Agent](https://oneuptime.com)*`;
  }

  // Get handler description
  public getDescription(): string {
    return "Turns an inconclusive AI investigation into a pull request that adds the missing observability (structured logs, OpenTelemetry spans, metrics) to the implicated code paths, without changing business logic.";
  }
}
