import SubjectPullRequestTaskHandler from "./SubjectPullRequestTaskHandler";
import { SubjectTaskDetails } from "../Utils/BackendAPI";
import CodeFixTaskType from "Common/Types/AI/CodeFixTaskType";

/*
 * ImproveLogging: a service-scoped logging-hygiene pass. A user clicks
 * "Improve logging with AI" on the service's Logs page; the agent audits
 * the service's logging and opens a draft PR that makes logs structured,
 * correctly leveled, correlated, and free of user data — WITHOUT changing
 * behavior. Context (service id + name, repository resolved by service
 * name) comes from /ai-agent-data/get-instrumentation-task-details.
 */
export default class ImproveLoggingTaskHandler extends SubjectPullRequestTaskHandler {
  public readonly taskType: string = CodeFixTaskType.ImproveLogging;
  public readonly name: string = "Improve Logging Handler";

  protected readonly branchPrefix: string = "oneuptime-logging-";
  protected readonly noActionMessage: string =
    "No logging improvements could be applied to any repository";
  protected readonly noRepositoryMessage: string =
    "Could not resolve a repository for this logging-improvement task. Connect the right repository through the GitHub App.";

  // Build the prompt for the code agent
  protected buildPrompt(
    details: SubjectTaskDetails,
    servicePathInRepository: string | null,
  ): string {
    let prompt: string = `You are a software engineer improving the LOGGING of a codebase${
      details.serviceName ? ` (the service "${details.serviceName}")` : ""
    }. This is an instrumentation-hygiene pass: you change how the code logs, never what the code does.

## Task

Audit the logging in this repository and improve it. Work through this checklist, applying whichever items you find violations of — and nothing else:

1. **Parameterize log messages.** Where dynamic values (user IDs, emails, order numbers, domains, request payloads) are interpolated directly into the message string, make the message static and move the values into structured fields/attributes using the repository's logging library. Static messages keep user data out of log text and make logs groupable and searchable.
2. **Never log secrets or personal data.** Remove or mask passwords, tokens, API keys, cookies, authorization headers, and full request/response bodies from log statements. Where the value is needed for debugging, log a stable identifier or a hash instead.
3. **Fix severity levels.** Expected/operational conditions (validation rejections, cache misses, retries that succeed) should not log at ERROR; genuine failures should not hide at DEBUG/INFO. Align levels with what an on-call engineer should be paged-adjacent about.
4. **Record exceptions properly.** Where code logs a raw stack trace into a log body (e.g. \`logger.error(err)\` string-dumps), switch to the logging/telemetry library's exception-recording mechanism so error trackers receive structured exception.type/message/stacktrace instead of scraping text.
5. **Correlate.** Where the repository already has tracing, ensure log statements flow through the instrumented logger so trace/span IDs attach to log records; do not hand-roll correlation IDs if the library provides them.
6. **Cut noise.** Collapse repetitive per-item logging inside loops into summaries; remove logs that state the obvious on every request. Be conservative — when in doubt, keep the log line.

## Requirements

- Use the logging library the repository ALREADY uses — do NOT introduce new dependencies or logging frameworks
- Do NOT change any business logic, control flow, error handling behavior, or return values — this change is logging only
- Do NOT delete error logging that surfaces genuine failures; an error that was visible must stay visible
- Keep the diff focused: fix the clearest violations rather than touching every file; prefer the service's hot paths and error paths
- Preserve existing code style and patterns
- If the logging is already in good shape, make no changes and explain why

Please proceed with auditing and improving the logging.`;

    if (servicePathInRepository) {
      prompt = `The service code is located in the \`${servicePathInRepository}\` directory — audit THAT directory's logging.\n\n${prompt}`;
    }

    return prompt;
  }

  // Build commit message for the logging change
  protected buildCommitMessage(details: SubjectTaskDetails): string {
    return `chore(logging): improve logging hygiene${
      details.serviceName ? ` for ${details.serviceName}` : ""
    }

Parameterized log messages, corrected severity levels, structured
exception recording, and reduced noise. Logging only — no business
logic is changed.

Automatically generated by OneUptime AI Agent.`;
  }

  // Build the pull request title
  protected buildPullRequestTitle(details: SubjectTaskDetails): string {
    const title: string = `chore(logging): improve logging hygiene${
      details.serviceName ? ` for ${details.serviceName}` : ""
    }`;

    return this.cleanSubjectTitle(
      title,
      SubjectPullRequestTaskHandler.PR_TITLE_SUBJECT_LENGTH,
    );
  }

  // Build the pull request body
  protected buildPullRequestBody(
    details: SubjectTaskDetails,
    agentSummary: string,
  ): string {
    return `## Logging Improvement

This pull request was automatically generated by OneUptime AI Agent at a user's request. It improves the logging hygiene of ${
      details.serviceName
        ? `the service **${details.serviceName}**`
        : "this repository"
    }: parameterized messages (user data out of log text), corrected severity levels, structured exception recording, trace correlation, and less noise. It does **not** change business behavior.

### Summary of Changes

${agentSummary}

---

> **Logging only** — this PR must not change business logic. It is opened as a draft: review it and mark it ready for review before merging; nothing is merged automatically.

*This PR was automatically generated by [OneUptime AI Agent](https://oneuptime.com)*`;
  }

  // Get handler description
  public getDescription(): string {
    return "Audits a service's logging and opens a pull request that parameterizes messages, fixes severity levels, records exceptions structurally, adds trace correlation, and cuts noise — without changing business behavior.";
  }
}
