import ExceptionPullRequestTaskHandler from "./ExceptionPullRequestTaskHandler";
import { ExceptionDetails } from "../Utils/BackendAPI";
import CodeFixTaskType from "Common/Types/AI/CodeFixTaskType";

// Single-line exception message length caps for commit subjects / PR titles.
const COMMIT_SUBJECT_MESSAGE_LENGTH: number = 50;
const PR_TITLE_MESSAGE_LENGTH: number = 70;

// Stack traces in PR bodies are truncated to keep the PR readable.
const PR_BODY_STACK_TRACE_LENGTH: number = 2000;

/*
 * Writes a failing regression test that reproduces an exception — it does
 * NOT fix the bug. The shared pipeline opens a pull request whose test
 * SHOULD FAIL on the current code until the underlying bug is fixed.
 */
export default class WriteRegressionTestTaskHandler extends ExceptionPullRequestTaskHandler {
  public readonly taskType: string = CodeFixTaskType.WriteRegressionTest;
  public readonly name: string = "Write Regression Test Handler";

  protected readonly branchPrefix: string = "oneuptime-regression-test-";
  protected readonly noActionMessage: string =
    "No regression test could be written for any repository";

  // Build the prompt for the code agent
  protected buildPrompt(
    exceptionDetails: ExceptionDetails,
    servicePathInRepository: string | null,
  ): string {
    let prompt: string = `You are a software engineer writing a regression test for a bug in a codebase.

## Exception Information

**Exception Type:** ${exceptionDetails.exception.exceptionType}

**Error Message:**
${exceptionDetails.exception.message}

**Stack Trace:**
\`\`\`
${exceptionDetails.exception.stackTrace}
\`\`\`

## Task

Write ONLY a failing regression test that reproduces this exception. Do NOT fix the bug. Here are the steps to follow:

1. Identify from the stack trace which code path raises the exception
2. Discover the repository's existing test framework and conventions (look at existing test files, test directories, package manifests, and CI configuration)
3. Write a single focused test (or a minimal set of tests) that exercises that code path with inputs that trigger this exception
4. Place the test where the repository's conventions say tests for that code belong, following its naming and style exactly

## Requirements

- The test MUST FAIL on the current code, and it must fail for this exception's reason (same exception type / message) — not because of setup mistakes, missing imports, or wrong assertions
- Do NOT modify any production/source code — only add test code
- Do NOT fix the bug, work around it, or weaken the test so it passes
- Do NOT introduce a new test framework or new dependencies — use what the repository already uses
- Name the test so a reader knows it reproduces this production exception
- Add a short comment in the test explaining that it was generated from a production exception observed by OneUptime and that it should start passing once the underlying bug is fixed
- If reproducing the exception requires stubbing external services, keep the stubs minimal and local to the test
- If you cannot write a test that reproduces this exception, explain why and make no changes

Please proceed with writing the failing regression test.`;

    if (servicePathInRepository) {
      prompt = `The service code is located in the \`${servicePathInRepository}\` directory.\n\n${prompt}`;
    }

    return prompt;
  }

  // Build commit message for the regression test
  protected buildCommitMessage(exceptionDetails: ExceptionDetails): string {
    const shortMessage: string = this.cleanExceptionMessage(
      exceptionDetails.exception.message,
      COMMIT_SUBJECT_MESSAGE_LENGTH,
    );

    return `test: reproduce ${shortMessage}

This commit adds a failing regression test that reproduces an exception
detected by OneUptime. It does not fix the underlying bug — the test
should fail until the bug is fixed.

Exception Type: ${exceptionDetails.exception.exceptionType}
Exception ID: ${exceptionDetails.exception.id}

Automatically generated by OneUptime AI Agent.`;
  }

  // Build the pull request title
  protected buildPullRequestTitle(exceptionDetails: ExceptionDetails): string {
    const shortMessage: string = this.cleanExceptionMessage(
      exceptionDetails.exception.message,
      PR_TITLE_MESSAGE_LENGTH,
    );

    return `test: reproduce ${shortMessage}`;
  }

  // Build the pull request body
  protected buildPullRequestBody(
    exceptionDetails: ExceptionDetails,
    agentSummary: string,
  ): string {
    const stackTrace: string = exceptionDetails.exception.stackTrace;

    return `## Regression Test

This pull request was automatically generated by OneUptime AI Agent from a production exception. It adds a **failing regression test** that reproduces the exception — it does **not** fix the underlying bug.

> **This test SHOULD FAIL** on the current code until the underlying bug is fixed. Once the bug is fixed, the test should pass and will guard against the exception regressing.

### Exception Details

**Service:** ${exceptionDetails.service?.name || "Unknown Service"}
**Type:** ${exceptionDetails.exception.exceptionType}
**Message:** ${exceptionDetails.exception.message}

### Stack Trace

\`\`\`
${stackTrace.substring(0, PR_BODY_STACK_TRACE_LENGTH)}${stackTrace.length > PR_BODY_STACK_TRACE_LENGTH ? "\n...(truncated)" : ""}
\`\`\`

### Summary of Changes

${agentSummary}

---

*This PR was automatically generated by [OneUptime AI Agent](https://oneuptime.com)*`;
  }

  // Get handler description
  public getDescription(): string {
    return "Writes a failing regression test that reproduces an exception detected by OneUptime and opens a pull request. The test should fail until the underlying bug is fixed — it does not fix the bug.";
  }
}
