enum PageMap {
    OVERVIEW = 'OVERVIEW',
    INCIDENT_LIST = 'INCIDENT_LIST',
    INCIDENT_DETAIL = 'INCIDENT_DETAIL',
    ANNOUNCEMENT_DETAIL = 'ANNOUNCEMENT_DETAIL',
    ANNOUNCEMENT_LIST = 'ANNOUNCEMENT_LIST',
    SCHEDULED_EVENT_LIST = 'SCHEDULED_EVENT_LIST',
    SCHEDULED_EVENT_DETAIL = 'SCHEDULED_EVENT_DETAIL',
    RSS = 'RSS',
    SUBSCRIBE = 'SUBSCRIBE',

    NOT_FOUND = 'NOT_FOUND',

    PREVIEW_OVERVIEW = 'PREVIEW_OVERVIEW',
    PREVIEW_INCIDENT_LIST = 'PREVIEW_INCIDENT_LIST',
    PREVIEW_INCIDENT_DETAIL = 'PREVIEW_INCIDENT_DETAIL',
    PREVIEW_ANNOUNCEMENT_DETAIL = 'PREVIEW_ANNOUNCEMENT_DETAIL',
    PREVIEW_ANNOUNCEMENT_LIST = 'PREVIEW_ANNOUNCEMENT_LIST',
    PREVIEW_SCHEDULED_EVENT_LIST = 'PREVIEW_SCHEDULED_EVENT_LIST',
    PREVIEW_SCHEDULED_EVENT_DETAIL = 'PREVIEW_SCHEDULED_EVENT_DETAIL',
    PREVIEW_RSS = 'RSS',
    PREVIEW_SUBSCRIBE = 'PREVIEW_SUBSCRIBE',

    // Accounts.
    LOGIN = 'LOGIN',
    RESET_PASSWORD = 'RESET_PASSWORD',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',

    // Accounts.
    PREVIEW_LOGIN = 'PREVIEW_LOGIN',
    PREVIEW_RESET_PASSWORD = 'PREVIEW_RESET_PASSWORD',
    PREVIEW_FORGOT_PASSWORD = 'PREVIEW_FORGOT_PASSWORD',
}

export default PageMap;
