enum PageMap {
  OVERVIEW = "OVERVIEW",
  INCIDENT_LIST = "INCIDENT_LIST",
  INCIDENT_DETAIL = "INCIDENT_DETAIL",
  ANNOUNCEMENT_DETAIL = "ANNOUNCEMENT_DETAIL",
  ANNOUNCEMENT_LIST = "ANNOUNCEMENT_LIST",
  SCHEDULED_EVENT_LIST = "SCHEDULED_EVENT_LIST",
  SCHEDULED_EVENT_DETAIL = "SCHEDULED_EVENT_DETAIL",
  RSS = "RSS",

  SUBSCRIBE_EMAIL = "SUBSCRIBE_EMAIL",
  CONFIRM_SUBSCRIPTION = "CONFIRM_SUBSCRIPTION",
  SUBSCRIBE_SMS = "SUBSCRIBE_SMS",
  SUBSCRIBE_SLACK = "SUBSCRIBE_SLACK",
  SUBSCRIBE_MICROSOFT_TEAMS = "SUBSCRIBE_MICROSOFT_TEAMS",
  SUBSCRIBE_WEBHOOKS = "SUBSCRIBE_WEBHOOKS",
  UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION",

  NOT_FOUND = "NOT_FOUND",
  FORBIDDEN = "FORBIDDEN",

  PREVIEW_OVERVIEW = "PREVIEW_OVERVIEW",
  PREVIEW_INCIDENT_LIST = "PREVIEW_INCIDENT_LIST",
  PREVIEW_INCIDENT_DETAIL = "PREVIEW_INCIDENT_DETAIL",
  PREVIEW_ANNOUNCEMENT_DETAIL = "PREVIEW_ANNOUNCEMENT_DETAIL",
  PREVIEW_ANNOUNCEMENT_LIST = "PREVIEW_ANNOUNCEMENT_LIST",
  PREVIEW_SCHEDULED_EVENT_LIST = "PREVIEW_SCHEDULED_EVENT_LIST",
  PREVIEW_SCHEDULED_EVENT_DETAIL = "PREVIEW_SCHEDULED_EVENT_DETAIL",
  PREVIEW_RSS = "PREVIEW_RSS",

  PREVIEW_SUBSCRIBE_EMAIL = "PREVIEW_SUBSCRIBE_EMAIL",
  PREVIEW_CONFIRM_SUBSCRIPTION = "PREVIEW_CONFIRM_SUBSCRIPTION",
  PREVIEW_SUBSCRIBE_SMS = "PREVIEW_SUBSCRIBE_SMS",
  PREVIEW_SUBSCRIBE_SLACK = "PREVIEW_SUBSCRIBE_SLACK",
  PREVIEW_SUBSCRIBE_MICROSOFT_TEAMS = "PREVIEW_SUBSCRIBE_MICROSOFT_TEAMS",
  PREVIEW_SUBSCRIBE_WEBHOOKS = "PREVIEW_SUBSCRIBE_WEBHOOKS",
  PREVIEW_UPDATE_SUBSCRIPTION = "PREVIEW_UPDATE_SUBSCRIPTION",

  // Accounts.
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  RESET_PASSWORD = "RESET_PASSWORD",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  SSO = "SSO",

  // Accounts.
  PREVIEW_LOGIN = "PREVIEW_LOGIN",
  PREVIEW_RESET_PASSWORD = "PREVIEW_RESET_PASSWORD",
  PREVIEW_FORGOT_PASSWORD = "PREVIEW_FORGOT_PASSWORD",
  PREVIEW_SSO = "PREVIEW_SSO",
  PREVIEW_LOGOUT = "PREVIEW_LOGOUT",

  PREVIEW_FORBIDDEN = "PREVIEW_FORBIDDEN",

  MASTER_PASSWORD = "MASTER_PASSWORD",
  PREVIEW_MASTER_PASSWORD = "PREVIEW_MASTER_PASSWORD",
}

export default PageMap;
