export const STATUSPAGE_REQUEST: string = 'STATUSPAGE_REQUEST';
export const STATUSPAGE_SUCCESS: string = 'STATUSPAGE_SUCCESS';
export const STATUSPAGE_FAILURE: string = 'STATUSPAGE_FAILURE';

export const STATUSPAGE_NOTES_REQUEST: string = 'STATUSPAGE_NOTES_REQUEST';
export const STATUSPAGE_NOTES_SUCCESS: string = 'STATUSPAGE_NOTES_SUCCESS';
export const STATUSPAGE_NOTES_FAILURE: string = 'STATUSPAGE_NOTES_FAILURE';
export const STATUSPAGE_NOTES_RESET: string = 'STATUSPAGE_NOTES_RESET';
export const INDIVIDUAL_NOTES_ENABLE: string = 'INDIVIDUAL_NOTES_ENABLE';
export const INDIVIDUAL_NOTES_DISABLE: string = 'INDIVIDUAL_NOTES_DISABLE';

export const NEW_THEME_NOTES_SUCCESS: string = 'NEW_THEME_NOTES_SUCCESS';

export const MORE_NOTES_REQUEST: string = 'MORE_NOTES_REQUEST';
export const MORE_NOTES_SUCCESS: string = 'MORE_NOTES_SUCCESS';
export const MORE_NOTES_FAILURE: string = 'MORE_NOTES_FAILURE';

export const SCHEDULED_EVENTS_REQUEST: string = 'SCHEDULED_EVENTS_REQUEST';
export const SCHEDULED_EVENTS_SUCCESS: string = 'SCHEDULED_EVENTS_SUCCESS';
export const SCHEDULED_EVENTS_FAILURE: string = 'SCHEDULED_EVENTS_FAILURE';
export const SCHEDULED_EVENTS_RESET: string = 'SCHEDULED_EVENTS_RESET';

export const ONGOING_SCHEDULED_EVENTS_REQUEST: $TSFixMe =
    'ONGOING_SCHEDULED_EVENTS_REQUEST';
export const ONGOING_SCHEDULED_EVENTS_SUCCESS: $TSFixMe =
    'ONGOING_SCHEDULED_EVENTS_SUCCESS';
export const ONGOING_SCHEDULED_EVENTS_FAILURE: $TSFixMe =
    'ONGOING_SCHEDULED_EVENTS_FAILURE';
export const ONGOING_SCHEDULED_EVENTS_RESET: string =
    'ONGOING_SCHEDULED_EVENTS_RESET';

export const MORE_EVENTS_REQUEST: string = 'MORE_EVENTS_REQUEST';
export const MORE_EVENTS_SUCCESS: string = 'MORE_EVENTS_SUCCESS';
export const MORE_EVENTS_FAILURE: string = 'MORE_EVENTS_FAILURE';

export const FUTURE_EVENTS_REQUEST: string = 'FUTURE_EVENTS_REQUEST';
export const FUTURE_EVENTS_SUCCESS: string = 'FUTURE_EVENTS_SUCCESS';
export const FUTURE_EVENTS_FAILURE: string = 'FUTURE_EVENTS_FAILURE';

export const MORE_FUTURE_EVENTS_REQUEST: string = 'MORE_FUTURE_EVENTS_REQUEST';
export const MORE_FUTURE_EVENTS_SUCCESS: string = 'MORE_FUTURE_EVENTS_SUCCESS';
export const MORE_FUTURE_EVENTS_FAILURE: string = 'MORE_FUTURE_EVENTS_FAILURE';

export const INDIVIDUAL_EVENTS_REQUEST: string = 'INDIVIDUAL_EVENTS_REQUEST';
export const INDIVIDUAL_EVENTS_SUCCESS: string = 'INDIVIDUAL_EVENTS_SUCCESS';
export const INDIVIDUAL_EVENTS_FAILURE: string = 'INDIVIDUAL_EVENTS_FAILURE';

export const SELECT_PROBE: string = 'SELECT_PROBE';

export const FETCH_INCIDENT_NOTES_REQUEST: string =
    'FETCH_INCIDENT_NOTES_REQUEST';
export const FETCH_INCIDENT_NOTES_SUCCESS: string =
    'FETCH_INCIDENT_NOTES_SUCCESS';
export const FETCH_INCIDENT_NOTES_FAILURE: string =
    'FETCH_INCIDENT_NOTES_FAILURE';

export const MORE_INCIDENT_NOTES_REQUEST: string =
    'MORE_INCIDENT_NOTES_REQUEST';
export const MORE_INCIDENT_NOTES_SUCCESS: string =
    'MORE_INCIDENT_NOTES_SUCCESS';
export const MORE_INCIDENT_NOTES_FAILURE: string =
    'MORE_INCIDENT_NOTES_FAILURE';

export const FETCH_INCIDENT_REQUEST: string = 'FETCH_INCIDENT_REQUEST';
export const FETCH_INCIDENT_SUCCESS: string = 'FETCH_INCIDENT_SUCCESS';
export const FETCH_INCIDENT_FAILURE: string = 'FETCH_INCIDENT_FAILURE';

// Fetch Monitor Statuses
export const FETCH_MONITOR_STATUSES_REQUEST: string =
    'FETCH_MONITOR_STATUSES_REQUEST';
export const FETCH_MONITOR_STATUSES_SUCCESS: string =
    'FETCH_MONITOR_STATUSES_SUCCESS';
export const FETCH_MONITOR_STATUSES_FAILURE: string =
    'FETCH_MONITOR_STATUSES_FAILURE';

export const FETCH_MONITOR_LOGS_REQUEST: string = 'FETCH_MONITOR_LOGS_REQUEST';
export const FETCH_MONITOR_LOGS_SUCCESS: string = 'FETCH_MONITOR_LOGS_SUCCESS';
export const FETCH_MONITOR_LOGS_FAILURE: string = 'FETCH_MONITOR_LOGS_FAILURE';

export const FETCH_EVENT_NOTES_REQUEST: string = 'FETCH_EVENT_NOTES_REQUEST';
export const FETCH_EVENT_NOTES_SUCCESS: string = 'FETCH_EVENT_NOTES_SUCCESS';
export const FETCH_EVENT_NOTES_FAILURE: string = 'FETCH_EVENT_NOTES_FAILURE';
export const MORE_EVENT_NOTE_REQUEST: string = 'MORE_EVENT_NOTE_REQUEST';
export const MORE_EVENT_NOTE_SUCCESS: string = 'MORE_EVENT_NOTE_SUCCESS';
export const MORE_EVENT_NOTE_FAILURE: string = 'MORE_EVENT_NOTE_FAILURE';
export const FETCH_EVENT_REQUEST: string = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS: string = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE: string = 'FETCH_EVENT_FAILURE';

export const FETCH_LAST_INCIDENT_TIMELINE_REQUEST: $TSFixMe =
    'FETCH_LAST_INCIDENT_TIMELINE_REQUEST';
export const FETCH_LAST_INCIDENT_TIMELINE_SUCCESS: $TSFixMe =
    'FETCH_LAST_INCIDENT_TIMELINE_SUCCESS';
export const FETCH_LAST_INCIDENT_TIMELINE_FAILURE: $TSFixMe =
    'FETCH_LAST_INCIDENT_TIMELINE_FAILURE';

export const FETCH_LAST_INCIDENT_TIMELINES_REQUEST: $TSFixMe =
    'FETCH_LAST_INCIDENT_TIMELINES_REQUEST';
export const FETCH_LAST_INCIDENT_TIMELINES_SUCCESS: $TSFixMe =
    'FETCH_LAST_INCIDENT_TIMELINES_SUCCESS';
export const FETCH_LAST_INCIDENT_TIMELINES_FAILURE: $TSFixMe =
    'FETCH_LAST_INCIDENT_TIMELINES_FAILURE';

export const SHOW_EVENT_CARD: string = 'SHOW_EVENT_CARD';
export const SHOW_INCIDENT_CARD: string = 'SHOW_INCIDENT_CARD';

// Announcements
export const FETCH_ANNOUNCEMENTS_REQUEST: string =
    'FETCH_ANNOUNCEMENTS_REQUEST';
export const FETCH_ANNOUNCEMENTS_SUCCESS: string =
    'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILURE: string =
    'FETCH_ANNOUNCEMENTS_FAILURE';

export const FETCH_SINGLE_ANNOUNCEMENTS_SUCCESS: $TSFixMe =
    'FETCH_SINGLE_ANNOUNCEMENTS_SUCCESS';
export const FETCH_SINGLE_ANNOUNCEMENTS_FAILURE: $TSFixMe =
    'FETCH_SINGLE_ANNOUNCEMENTS_FAILURE';
export const FETCH_SINGLE_ANNOUNCEMENTS_REQUEST: $TSFixMe =
    'FETCH_SINGLE_ANNOUNCEMENTS_REQUEST';

export const FETCH_ANNOUNCEMEMTLOGS_REQUEST: string =
    'FETCH_ANNOUNCEMEMTLOGS_REQUEST';
export const FETCH_ANNOUNCEMEMTLOGS_SUCCESS: string =
    'FETCH_ANNOUNCEMEMTLOGS_SUCCESS';
export const FETCH_ANNOUNCEMEMTLOGS_FAILURE: string =
    'FETCH_ANNOUNCEMEMTLOGS_FAILURE';

// Past events
export const PAST_EVENTS_REQUEST: string = 'PAST_EVENTS_REQUEST';
export const PAST_EVENTS_SUCCESS: string = 'PAST_EVENTS_SUCCESS';
export const PAST_EVENTS_FAILURE: string = 'PAST_EVENTS_FAILURE';
export const MORE_PAST_EVENTS_REQUEST: string = 'MORE_PAST_EVENTS_REQUEST';
export const MORE_PAST_EVENTS_SUCCESS: string = 'MORE_PAST_EVENTS_SUCCESS';
export const MORE_PAST_EVENTS_FAILURE: string = 'MORE_PAST_EVENTS_FAILURE';

// Calculate time
export const CALCULATE_TIME_REQUEST: string = 'CALCULATE_TIME_REQUEST';
export const CALCULATE_TIME_SUCCESS: string = 'CALCULATE_TIME_SUCCESS';
export const CALCULATE_TIME_FAILURE: string = 'CALCULATE_TIME_FAILURE';

// Fetch tweets
export const FETCH_TWEETS_REQUEST: string = 'FETCH_TWEETS_REQUEST';
export const FETCH_TWEETS_SUCCESS: string = 'FETCH_TWEETS_SUCCESS';
export const FETCH_TWEETS_FAILURE: string = 'FETCH_TWEETS_FAILURE';

// Fetch external statuspage
export const FETCH_EXTERNAL_STATUSPAGES_REQUEST: $TSFixMe =
    'FETCH_EXTERNAL_STATUS_PAGESREQUEST';
export const FETCH_EXTERNAL_STATUSPAGES_SUCCESS: $TSFixMe =
    'FETCH_EXTERNAL_STATUS_PAGESSUCCESS';
export const FETCH_EXTERNAL_STATUSPAGES_FAILURE: $TSFixMe =
    'FETCH_EXTERNAL_STATUS_PAGESFAILURE';

//Fetch all resources
export const FETCH_ALL_RESOURCES_SUCCESS: string =
    'FETCH_ALL_RESOURCES_SUCCESS';

//Handle language change
export const TRANSLATE_LANGUAGE: string = 'TRANSLATE_LANGUAGE';
