#
# Fyipe Docs Dockerfile
#

# Pull base image nodejs image.
FROM node:16

#SET ENV Variables

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

WORKDIR /usr/src/app

# Copy package.json files
COPY ./package.json /usr/src/app/package.json


# Install app dependencies
RUN npm install

# Expose ports.
#   - 1445: Fyipe Docs
EXPOSE 1445

#Run the app
CMD [ "npm", "run", "dev" ]
