import { Renderer, marked } from "marked";
import CaptureSpan from "../Utils/Telemetry/CaptureSpan";
import markdownSlugify from "./MarkdownSlugify";

export type MarkdownRenderer = Renderer;

export enum MarkdownContentType {
  Docs,
  Blog,
  Email,
  // Compact rendering tuned for small surfaces (e.g. the blog validation modal).
  BlogValidation,
}

export default class Markdown {
  @CaptureSpan()
  public static convertToPlainText(markdown: string): string {
    if (!markdown) {
      return "";
    }

    let text: string = markdown;

    // Remove HTML tags
    text = text.replace(/<[^>]*>/g, "");

    // Convert markdown links [text](url) to just text
    text = text.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");

    // Convert markdown images ![alt](url) to just alt text
    text = text.replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1");

    // Remove markdown bold/italic markers
    text = text.replace(/\*\*([^*]+)\*\*/g, "$1"); // **bold**
    text = text.replace(/\*([^*]+)\*/g, "$1"); // *italic*
    text = text.replace(/__([^_]+)__/g, "$1"); // __bold__
    text = text.replace(/_([^_]+)_/g, "$1"); // _italic_

    // Remove markdown strikethrough
    text = text.replace(/~~([^~]+)~~/g, "$1");

    // Remove markdown code blocks
    text = text.replace(/```[\s\S]*?```/g, "");
    text = text.replace(/`([^`]+)`/g, "$1");

    // Remove markdown headers
    text = text.replace(/^#{1,6}\s+/gm, "");

    // Remove markdown blockquotes
    text = text.replace(/^>\s+/gm, "");

    // Remove markdown horizontal rules
    text = text.replace(/^[-*_]{3,}$/gm, "");

    // Remove markdown list markers
    text = text.replace(/^[\s]*[-*+]\s+/gm, "");
    text = text.replace(/^[\s]*\d+\.\s+/gm, "");

    // Decode HTML entities
    text = text.replace(/&lt;/g, "<");
    text = text.replace(/&gt;/g, ">");
    text = text.replace(/&amp;/g, "&");
    text = text.replace(/&quot;/g, '"');
    text = text.replace(/&#39;/g, "'");
    text = text.replace(/&nbsp;/g, " ");

    // Normalize whitespace - collapse multiple spaces/newlines
    text = text.replace(/\n\s*\n/g, "\n");
    text = text.replace(/[ \t]+/g, " ");

    // Trim whitespace
    text = text.trim();

    return text;
  }
  private static blogRenderer: Renderer | null = null;
  private static docsRenderer: Renderer | null = null;
  private static emailRenderer: Renderer | null = null;
  private static blogValidationRenderer: Renderer | null = null;

  @CaptureSpan()
  public static async convertToHTML(
    markdown: string,
    contentType: MarkdownContentType,
  ): Promise<string> {
    let renderer: Renderer | null = null;

    if (contentType === MarkdownContentType.Blog) {
      renderer = this.getBlogRenderer();
    }

    if (contentType === MarkdownContentType.Docs) {
      renderer = this.getDocsRenderer();
    }

    if (contentType === MarkdownContentType.Email) {
      renderer = this.getEmailRenderer();
    }

    if (contentType === MarkdownContentType.BlogValidation) {
      renderer = this.getBlogValidationRenderer();
    }

    /*
     * Escape raw HTML tokens in the markdown source to prevent XSS.
     * This only affects raw HTML that users type directly (e.g. <img onerror=...>),
     * not HTML generated by the renderer methods (headings, paragraphs, etc.).
     */
    if (renderer) {
      renderer.html = (html: string): string => {
        return Markdown.escapeHtml(html);
      };
    }

    const htmlBody: string = await marked(markdown, {
      renderer: renderer,
    });

    return htmlBody;
  }

  private static escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  private static getEmailRenderer(): Renderer {
    if (this.emailRenderer !== null) {
      return this.emailRenderer;
    }

    const renderer: Renderer = new Renderer();

    this.emailRenderer = renderer;

    return renderer;
  }

  /*
   * Compact renderer for small surfaces like the blog validation modal. Smaller,
   * quieter headings (no oversized doc titles, no permalink anchors), tight
   * paragraph/list rhythm, and subtle code styling so a long report stays
   * readable in a constrained, scrollable panel.
   */
  private static getBlogValidationRenderer(): Renderer {
    if (this.blogValidationRenderer !== null) {
      return this.blogValidationRenderer;
    }

    const renderer: Renderer = new Renderer();

    renderer.heading = function (text, level) {
      if (level <= 2) {
        return `<h3 class="mt-7 mb-3 pt-6 border-t border-gray-100 first:mt-0 first:pt-0 first:border-t-0 text-[0.7rem] font-semibold uppercase tracking-wider text-emerald-700">${text}</h3>`;
      }
      if (level === 3) {
        return `<h4 class="mt-5 mb-1.5 text-sm font-semibold text-gray-900">${text}</h4>`;
      }
      return `<h5 class="mt-4 mb-1 text-sm font-semibold text-gray-700">${text}</h5>`;
    };

    renderer.paragraph = function (text) {
      return `<p class="my-2.5 text-sm leading-relaxed text-gray-600">${text}</p>`;
    };

    renderer.list = function (body, ordered, start) {
      const tag: string = ordered ? "ol" : "ul";
      const cls: string = ordered
        ? "list-decimal pl-5 my-2 space-y-1.5 text-sm text-gray-600 marker:text-gray-400"
        : "list-disc pl-5 my-2 space-y-1.5 text-sm text-gray-600 marker:text-gray-300";
      const startAttr: string =
        ordered && start !== 1 ? ` start="${start}"` : "";
      return `<${tag}${startAttr} class="${cls}">${body}</${tag}>`;
    };
    renderer.listitem = function (text) {
      return `<li class="leading-relaxed pl-1">${text}</li>`;
    };

    renderer.strong = function (text) {
      return `<strong class="font-semibold text-gray-800">${text}</strong>`;
    };
    renderer.em = function (text) {
      return `<em class="italic">${text}</em>`;
    };

    renderer.blockquote = function (quote) {
      return `<blockquote class="my-3 border-s-2 border-emerald-200 ps-3 text-sm text-gray-600">${quote}</blockquote>`;
    };

    renderer.hr = function () {
      return '<hr class="my-5 border-t border-gray-100" />';
    };

    renderer.codespan = function (code) {
      const escaped: string = Markdown.escapeHtml(code);
      return `<code class="rounded bg-gray-100 px-1.5 py-0.5 text-[0.8125rem] text-gray-700 font-mono break-words">${escaped}</code>`;
    };

    renderer.code = function (code, language) {
      const escaped: string = Markdown.escapeHtml(code);
      return `<pre class="my-3 overflow-x-auto rounded-lg bg-gray-50 border border-gray-100 p-3 text-xs leading-relaxed"><code class="language-${language} font-mono text-gray-700">${escaped}</code></pre>`;
    };

    renderer.table = function (header, body) {
      return `<div class="my-4 overflow-x-auto rounded-lg border border-gray-100"><table class="min-w-full text-sm text-left">${header}${body}</table></div>`;
    };
    renderer.tablerow = function (content) {
      return `<tr class="border-b border-gray-100 last:border-b-0">${content}</tr>`;
    };
    renderer.tablecell = function (content, flags) {
      const tag: string = flags.header ? "th" : "td";
      const align: string = flags.align ? ` text-${flags.align}` : "";
      const headerClass: string = flags.header
        ? " font-semibold text-gray-900 bg-gray-50"
        : " text-gray-600";
      return `<${tag} class="px-3 py-2${align}${headerClass}">${content}</${tag}>`;
    };

    renderer.link = function (href, _title, text) {
      if (!href) {
        return text as string;
      }
      const isExternal: boolean = href.startsWith("http");
      const rel: string = isExternal
        ? ' target="_blank" rel="noopener noreferrer"'
        : "";
      return `<a href="${href}"${rel} class="text-emerald-700 font-medium underline decoration-emerald-200 underline-offset-2 hover:decoration-emerald-400 break-words">${text}</a>`;
    };

    this.blogValidationRenderer = renderer;

    return renderer;
  }

  /*
   * Heading text -> the `id` used for in-page anchors. The rules live in
   * MarkdownSlugify.ts, a dependency-free module, so the docs anchor scripts
   * (Scripts/Docs/CheckAnchors.ts, FixAnchors.ts) can share them without
   * pulling in marked or the telemetry stack — see the comment there.
   */
  public static slugify(text: string): string {
    return markdownSlugify(text);
  }

  /*
   * Human-readable names for the languages a docs code fence can declare.
   * Rendered into the code block's header bar. A fence with no language, or
   * one that is not listed here, gets no label rather than a guess — the
   * label used to come from highlight.js auto-detection, which cheerfully
   * announced shell snippets as "PHP".
   */
  private static readonly codeLanguageNames: Record<string, string> = {
    apache: "Apache",
    bash: "Bash",
    c: "C",
    cpp: "C++",
    csharp: "C#",
    css: "CSS",
    diff: "Diff",
    dns: "DNS Zone",
    docker: "Dockerfile",
    dockerfile: "Dockerfile",
    go: "Go",
    graphql: "GraphQL",
    groovy: "Groovy",
    hcl: "HCL",
    html: "HTML",
    http: "HTTP",
    ini: "INI",
    java: "Java",
    javascript: "JavaScript",
    js: "JavaScript",
    json: "JSON",
    jsx: "JSX",
    kotlin: "Kotlin",
    lua: "Lua",
    makefile: "Makefile",
    markdown: "Markdown",
    md: "Markdown",
    nginx: "Nginx",
    perl: "Perl",
    php: "PHP",
    powershell: "PowerShell",
    proto: "Protobuf",
    py: "Python",
    python: "Python",
    r: "R",
    rb: "Ruby",
    ruby: "Ruby",
    rust: "Rust",
    scala: "Scala",
    sh: "Shell",
    shell: "Shell",
    sql: "SQL",
    swift: "Swift",
    terraform: "Terraform",
    toml: "TOML",
    ts: "TypeScript",
    tsx: "TSX",
    typescript: "TypeScript",
    xml: "XML",
    yaml: "YAML",
    yml: "YAML",
    zsh: "Shell",
  };

  private static getDocsRenderer(): Renderer {
    if (this.docsRenderer !== null) {
      return this.docsRenderer;
    }

    const renderer: Renderer = new Renderer();

    /*
     * The docs renderer emits semantic markup with a small set of stable class
     * names and leaves every colour, size and spacing decision to
     * Docs/Static/css/style.css. Utility classes used to be baked in here,
     * which meant the same element was styled from two places at once and made
     * a dark theme impossible without editing this file.
     */

    renderer.paragraph = function (text) {
      return `<p>${text}</p>`;
    };

    renderer.blockquote = function (quote) {
      const calloutMatch: RegExpMatchArray | null = quote.match(
        /<p[^>]*>\s*<strong>(Note|Warning|Tip|Danger|Info|Caution):?<\/strong>/i,
      );

      if (calloutMatch) {
        const type: string = calloutMatch[1]!.toLowerCase();
        const configMap: Record<string, { icon: string; label: string }> = {
          note: {
            icon: `<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>`,
            label: "Note",
          },
          info: {
            icon: `<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>`,
            label: "Info",
          },
          tip: {
            icon: `<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/>`,
            label: "Tip",
          },
          warning: {
            icon: `<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z"/>`,
            label: "Warning",
          },
          caution: {
            icon: `<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z"/>`,
            label: "Caution",
          },
          danger: {
            icon: `<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>`,
            label: "Danger",
          },
        };

        const config: { icon: string; label: string } =
          configMap[type] || configMap["note"]!;

        const content: string = quote.replace(
          /<p[^>]*>\s*<strong>(Note|Warning|Tip|Danger|Info|Caution):?<\/strong>\s*/i,
          "<p>",
        );

        return `<div class="docs-callout docs-callout--${type}">
          <div class="docs-callout__head">
            <svg class="docs-callout__icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">${config.icon}</svg>
            <span class="docs-callout__label">${config.label}</span>
          </div>
          <div class="docs-callout__body">${content}</div>
        </div>`;
      }

      return `<blockquote class="docs-quote">${quote}</blockquote>`;
    };

    renderer.image = function (href, title, text) {
      const titleAttr: string = title
        ? ` title="${Markdown.escapeHtml(title)}"`
        : "";
      return `<img src="${href}" alt="${text || ""}"${titleAttr} class="docs-image" loading="lazy" decoding="async" />`;
    };

    renderer.link = function (href, title, text) {
      if (!href) {
        return text as string;
      }

      const target: string = href.toLowerCase();
      const isExternal: boolean =
        (target.startsWith("http://") || target.startsWith("https://")) &&
        !target.includes("oneuptime.com");
      const titleAttr: string = title
        ? ` title="${Markdown.escapeHtml(title)}"`
        : "";
      const externalAttrs: string = isExternal
        ? ' target="_blank" rel="noopener noreferrer"'
        : "";
      const marker: string = isExternal
        ? '<svg class="docs-link__external" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/></svg>'
        : "";

      return `<a class="docs-link" href="${href}"${titleAttr}${externalAttrs}>${text}${marker}</a>`;
    };

    renderer.code = function (code, language) {
      const lang: string = (language || "").trim().toLowerCase();

      if (lang === "mermaid") {
        /*
         * Mermaid reads the diagram from textContent, so escaping here keeps
         * the diagram identical while making sure a `<` in a node label can
         * never be parsed as markup.
         */
        return `<div class="docs-diagram"><div class="mermaid">${Markdown.escapeHtml(code)}</div></div>`;
      }

      const escaped: string = Markdown.escapeHtml(code);
      const label: string | undefined = Markdown.codeLanguageNames[lang];
      /*
       * `nohighlight` stops highlight.js auto-detecting a language for fences
       * that never declared one — plain text is honest, a wrong grammar is not.
       */
      const codeClass: string = lang ? `language-${lang}` : "nohighlight";
      /*
       * The copy button ships hidden and the page's script unhides it once it
       * has wired up the click handler and filled in the translated label —
       * without scripting it would be a dead control with an English name.
       * The bar reserves its height either way, so nothing shifts.
       */
      const bar: string = `<div class="docs-code__bar">
          <span class="docs-code__lang">${label || ""}</span>
          <button type="button" class="docs-code__copy" data-copy-code hidden>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>
            <span class="docs-code__copy-text"></span>
          </button>
        </div>`;

      return `<div class="docs-code"${lang ? ` data-language="${lang}"` : ""}>${bar}<pre><code class="${codeClass}">${escaped}</code></pre></div>`;
    };

    renderer.heading = function (text, level) {
      const slug: string = Markdown.slugify(text);
      const anchor: string =
        level >= 2 && level <= 4
          ? `<a class="docs-anchor" href="#${slug}" aria-hidden="true" tabindex="-1">#</a>`
          : "";

      const safeLevel: number = Math.min(Math.max(level, 1), 6);

      return `<h${safeLevel} id="${slug}" class="docs-heading docs-h${safeLevel}"><span class="docs-heading__text">${text}</span>${anchor}</h${safeLevel}>`;
    };

    renderer.hr = function () {
      return '<hr class="docs-hr" />';
    };

    renderer.table = function (header, body) {
      return `<div class="docs-table-wrapper" tabindex="0"><table class="docs-table">${header}${body}</table></div>`;
    };

    renderer.tablerow = function (content) {
      return `<tr>${content}</tr>`;
    };

    renderer.tablecell = function (content, flags) {
      const tag: string = flags.header ? "th" : "td";
      const align: string = flags.align
        ? ` style="text-align:${flags.align}"`
        : "";
      return `<${tag}${align}>${content}</${tag}>`;
    };

    // Inline code
    renderer.codespan = function (code) {
      const escaped: string = Markdown.escapeHtml(code);
      return `<code class="docs-code-inline">${escaped}</code>`;
    };

    this.docsRenderer = renderer;

    return renderer;
  }

  private static getBlogRenderer(): Renderer {
    if (this.blogRenderer !== null) {
      return this.blogRenderer;
    }

    const renderer: Renderer = new Renderer();

    renderer.paragraph = function (text) {
      return `<p class="mt-5 mb-2 leading-8 text-gray-600 text-lg">${text}</p>`;
    };

    renderer.blockquote = function (quote) {
      return `<blockquote class="p-4 pt-1 pb-1 my-4 border-s-4 border-indigo-500">
            <div class="leading-8 text-gray-600">${quote}</div>
        </blockquote>`;
    };

    renderer.code = function (code, language) {
      const escaped: string = Markdown.escapeHtml(code);
      return `<pre class="language-${language} rounded-md"><code class="language-${language} rounded-md">${escaped}</code></pre>`;
    };

    renderer.heading = function (text, level) {
      if (level === 1) {
        return `<h1 class="my-5 mt-8 text-4xl font-bold tracking-tight text-gray-800">${text}</h1>`;
      } else if (level === 2) {
        return `<h2 class="my-5  mt-8 text-3xl font-bold tracking-tight text-gray-800">${text}</h2>`;
      } else if (level === 3) {
        return `<h3 class="my-5  mt-8 text-2xl font-bold tracking-tight text-gray-800">${text}</h3>`;
      } else if (level === 4) {
        return `<h4 class="my-5  mt-8 text-xl font-bold tracking-tight text-gray-800">${text}</h4>`;
      } else if (level === 5) {
        return `<h5 class="my-5  mt-8 text-lg font-bold tracking-tight text-gray-800">${text}</h5>`;
      }
      return `<h6 class="my-5 tracking-tight font-bold text-gray-800">${text}</h6>`;
    };

    // Lists
    renderer.list = function (body, ordered, start) {
      const tag: string = ordered ? "ol" : "ul";
      const cls: string = ordered
        ? "list-decimal pl-6 my-6 space-y-2 text-gray-700"
        : "list-disc pl-6 my-6 space-y-2 text-gray-700";
      const startAttr: string =
        ordered && start !== 1 ? ` start="${start}"` : "";
      return `<${tag}${startAttr} class="${cls}">${body}</${tag}>`;
    };
    renderer.listitem = function (text) {
      return `<li class="leading-7">${text}</li>`;
    };

    // Tables
    renderer.table = function (header, body) {
      return `<div class="overflow-x-auto my-8"><table class="min-w-full border border-gray-200 text-sm text-left">
        ${header}${body}
      </table></div>`;
    };
    renderer.tablerow = function (content) {
      return `<tr class="border-b last:border-b-0">${content}</tr>`;
    };
    renderer.tablecell = function (content, flags) {
      const type: string = flags.header ? "th" : "td";
      const base: string = "px-4 py-2 border-r last:border-r-0 border-gray-200";
      const align: string = flags.align ? ` text-${flags.align}` : "";
      const weight: string = flags.header ? " font-semibold bg-gray-50" : "";
      return `<${type} class="${base}${align}${weight}">${content}</${type}>`;
    };

    // Inline code
    renderer.codespan = function (code) {
      const escaped: string = Markdown.escapeHtml(code);
      return `<code class="rounded-md bg-gray-100 px-1.5 py-0.5 text-sm text-pink-600">${escaped}</code>`;
    };

    // Horizontal rule
    renderer.hr = function () {
      return '<hr class="my-12 border-t border-gray-200" />';
    };

    // Emphasis / Strong / Strikethrough
    renderer.strong = function (text) {
      return `<strong class="font-semibold text-gray-800">${text}</strong>`;
    };
    renderer.em = function (text) {
      return `<em class="italic text-gray-700">${text}</em>`;
    };
    renderer.del = function (text) {
      return `<del class="line-through text-gray-400">${text}</del>`;
    };

    // Images
    renderer.image = function (href, _title, text) {
      return `<figure class="my-8"><img src="${href}" alt="${text}" class="rounded-xl shadow-sm border border-gray-200" loading="lazy"/><figcaption class="mt-2 text-center text-sm text-gray-500">${text || ""}</figcaption></figure>`;
    };

    /*
     * Links
     * We explicitly add underline + color classes because Tailwind Typography (prose-*)
     * styles may get overridden by surrounding utility classes or global resets.
     * External links open in a new tab with proper rel attributes; internal links stay in-page.
     */
    renderer.link = function (href, title, text) {
      // Guard: if no href, just return the text.
      if (!href) {
        return text as string;
      }

      const isHash: boolean = href.startsWith("#");
      const isMailTo: boolean = href.startsWith("mailto:");
      const isTel: boolean = href.startsWith("tel:");
      const isInternal: boolean =
        href.startsWith("/") ||
        href.includes("oneuptime.com") ||
        isHash ||
        isMailTo ||
        isTel;

      const baseClasses: string = [
        "font-semibold",
        "text-indigo-600",
        "underline",
        "underline-offset-2",
        "decoration-indigo-300",
        "hover:decoration-indigo-500",
        "hover:text-indigo-500",
        "transition-colors",
      ].join(" ");

      const titleAttr: string = title ? ` title="${title}"` : "";
      const externalAttrs: string = isInternal
        ? ""
        : ' target="_blank" rel="noopener noreferrer"';

      return `<a href="${href}"${titleAttr} class="${baseClasses}"${externalAttrs}>${text}</a>`;
    };

    this.blogRenderer = renderer;

    return renderer;
  }
}
