export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'auth/LOGIN_FAILED';
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const RESET_LOGIN = 'auth/RESET_LOGIN';
export const SAVE_STATUS_PAGE = 'auth/SAVE_STATUS_PAGE';

// Use token for logging in a user
export const AUTH_VERIFICATION_SUCCESS = 'auth/AUTH_VERIFICATION_SUCCESS';
export const AUTH_VERIFICATION_FAILED = 'auth/AUTH_VERIFICATION_FAILED';
export const AUTH_VERIFICATION_REQUEST = 'auth/AUTH_VERIFICATION_REQUEST';
export const RESET_AUTH_VERIFICATION = 'auth/RESET_AUTH_VERIFICATION';

// Use backup code for logging in a user
export const BACKUP_CODE_VERIFICATION_SUCCESS =
    'auth/BACKUP_CODE_VERIFICATION_SUCCESS';
export const BACKUP_CODE_VERIFICATION_FAILED =
    'auth/BACKUP_CODE_VERIFICATION_FAILED';
export const BACKUP_CODE_VERIFICATION_REQUEST =
    'auth/BACKUP_CODE_VERIFICATION_REQUEST';
export const RESET_BACKUP_CODE_VERIFICATION =
    'auth/RESET_BACKUP_CODE_VERIFICATION';
