export const PASSWORDRESET_SUCCESS = 'auth/PASSWORDRESET_SUCCESS';
export const PASSWORDRESET_FAILED = 'auth/PASSWORDRESET_FAILED';
export const PASSWORDRESET_REQUEST = 'auth/PASSWORDRESET_REQUEST';
export const RESET_PASSWORDRESET = 'auth/RESET_PASSWORDRESET';