export const RESENDTOKEN_SUCCESS = 'auth/RESENDTOKEN_SUCCESS';
export const RESENDTOKEN_FAILED = 'auth/RESENDTOKEN_FAILED';
export const RESENDTOKEN_REQUEST = 'auth/RESENDTOKEN_REQUEST';
export const RESENDTOKEN_RESET = 'auth/RESENDTOKEN_RESET';
