export const  PASSWORDRESET_SUCCESS: string = 'auth/PASSWORDRESET_SUCCESS';
export const  PASSWORDRESET_FAILED: string = 'auth/PASSWORDRESET_FAILED';
export const  PASSWORDRESET_REQUEST: string = 'auth/PASSWORDRESET_REQUEST';
export const  RESET_PASSWORDRESET: string = 'auth/RESET_PASSWORDRESET';
