import { describe, expect, test } from "@jest/globals";
import fs from "fs";
import path from "path";
import {
  ProjectedPoint,
  ROBINSON_VIEW_BOX,
  ROBINSON_VIEW_BOX_HEIGHT,
  ROBINSON_VIEW_BOX_WIDTH,
  projectRobinson,
} from "../../FeatureSet/Dashboard/src/Components/NetworkSite/Geo/GeoProjection";
import {
  MAX_ZOOM,
  WORLD_VIEWPORT,
} from "../../FeatureSet/Dashboard/src/Components/NetworkSite/Geo/GeoViewport";

/*
 * Validates the checked-in map geometry assets generated by
 * Scripts/Geo/GenerateMapGeometry.js: shape, feature counts, path sanity and
 * — most importantly — that the outlines are viewBox-consistent with the
 * runtime pin projection in GeoProjection.ts, so a site pin projected at
 * runtime lands on its country outline.
 *
 * The map is one zoomable world view, so the geometry ships in two tiers:
 * a small overview drawn when the frame is wide, and a ~6x larger detail
 * tier fetched once somebody zooms in. Both must be interchangeable — same
 * viewBox, same coordinate space — because the map swaps them under a live
 * frame and a mismatch would visibly shift every coastline.
 */

interface GeometryFeature {
  id: string;
  name: string;
  path: string;
}

interface GeometryFile {
  viewBox: string;
  features: Array<GeometryFeature>;
}

const GEO_DIR: string = path.join(
  __dirname,
  "..",
  "..",
  "FeatureSet",
  "Dashboard",
  "src",
  "Components",
  "NetworkSite",
  "Geo",
);

function loadGeometry(fileName: string): GeometryFile {
  return JSON.parse(
    fs.readFileSync(path.join(GEO_DIR, fileName), "utf8"),
  ) as GeometryFile;
}

interface Point {
  x: number;
  y: number;
}

/*
 * Paths are "M<x>,<y>l<dx>,<dy> <dx>,<dy>...Z" per ring — one absolute
 * anchor then a single relative polyline (the encoding that makes the detail
 * tier affordable; see Scripts/Geo/README.md). Anything reading these
 * coordinates has to accumulate the deltas, so this parser IS the contract:
 * if the generator ever goes back to absolute coordinates, every assertion
 * below reads garbage rather than failing honestly — hence the format test
 * that runs first.
 */
function subpathsOf(pathD: string): Array<Array<Point>> {
  const subpaths: Array<Array<Point>> = [];

  for (const chunk of pathD.split("M")) {
    if (!chunk.trim()) {
      continue;
    }
    const [anchorText, stepsText]: Array<string | undefined> = chunk
      .replace(/Z\s*$/, "")
      .split("l");
    const anchor: Array<number> = (anchorText ?? "")
      .trim()
      .split(",")
      .map(Number);

    let x: number = anchor[0]!;
    let y: number = anchor[1]!;
    const points: Array<Point> = [{ x, y }];

    if (stepsText && stepsText.trim()) {
      for (const pair of stepsText.trim().split(/\s+/)) {
        const [dx, dy]: Array<number> = pair.split(",").map(Number);
        x += dx!;
        y += dy!;
        points.push({ x, y });
      }
    }

    subpaths.push(points);
  }

  return subpaths;
}

function pointsOf(pathD: string): Array<Point> {
  return subpathsOf(pathD).flat();
}

interface Bounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

function pathBounds(pathD: string): Bounds {
  return boundsOfPoints(pointsOf(pathD));
}

function boundsOfPoints(points: Array<Point>): Bounds {
  const bounds: Bounds = {
    minX: Infinity,
    minY: Infinity,
    maxX: -Infinity,
    maxY: -Infinity,
  };
  for (const point of points) {
    bounds.minX = Math.min(bounds.minX, point.x);
    bounds.maxX = Math.max(bounds.maxX, point.x);
    bounds.minY = Math.min(bounds.minY, point.y);
    bounds.maxY = Math.max(bounds.maxY, point.y);
  }
  return bounds;
}

/*
 * Bounds of a feature's largest ring — its mainland. Outlying islands are
 * exactly what the two resolution tiers legitimately disagree about, so
 * comparing whole-feature bounds across tiers compares the disagreement.
 */
function mainlandBounds(pathD: string): Bounds {
  let best: Bounds | null = null;
  let bestArea: number = -1;
  for (const subpath of subpathsOf(pathD)) {
    const bounds: Bounds = boundsOfPoints(subpath);
    const area: number =
      (bounds.maxX - bounds.minX) * (bounds.maxY - bounds.minY);
    if (area > bestArea) {
      bestArea = area;
      best = bounds;
    }
  }
  return best!;
}

/*
 * Largest horizontal step between two consecutive points of any subpath.
 * A ring that crosses the ±180° antimeridian without being cut there (Fiji,
 * Russia's Chukotka tip and Wrangel Island) shows up as a step spanning most
 * of the map — and renders as a straight streak clear across the finished
 * map. Scripts/Geo/GenerateMapGeometry.js cuts those rings at the meridian;
 * this measures that the cut actually happened.
 */
function widestHorizontalStep(pathD: string): number {
  let widest: number = 0;
  for (const subpath of subpathsOf(pathD)) {
    for (let i: number = 1; i < subpath.length; i++) {
      widest = Math.max(widest, Math.abs(subpath[i]!.x - subpath[i - 1]!.x));
    }
  }
  return widest;
}

function featureById(file: GeometryFile, id: string): GeometryFeature {
  const feature: GeometryFeature | undefined = file.features.find(
    (candidate: GeometryFeature) => {
      return candidate.id === id;
    },
  );
  expect(feature).toBeDefined();
  return feature!;
}

const OVERVIEW: GeometryFile = loadGeometry("WorldCountriesGeometry.json");
const DETAIL: GeometryFile = loadGeometry("WorldCountriesDetailGeometry.json");

const TIERS: Array<[string, GeometryFile]> = [
  ["overview", OVERVIEW],
  ["detail", DETAIL],
];

describe.each(TIERS)("%s geometry", (_name: string, file: GeometryFile) => {
  test("viewBox matches the Robinson projection constants", () => {
    expect(file.viewBox).toBe(ROBINSON_VIEW_BOX);
  });

  /*
   * Runs before everything that parses a path: the parser above assumes the
   * relative encoding, so if the generator changes format this fails loudly
   * instead of every other assertion silently reading nonsense.
   */
  test("every path uses the absolute-anchor + relative-polyline encoding", () => {
    for (const feature of file.features) {
      // An absolute "L" would mean the encoding changed under the parser.
      expect(feature.path).not.toMatch(/L/);
      expect(feature.path.startsWith("M")).toBe(true);
      expect(feature.path.endsWith("Z")).toBe(true);
      for (const chunk of feature.path.split("M").filter((part: string) => {
        return part.trim().length > 0;
      })) {
        expect(chunk).toContain("l");
      }
    }
  });

  test("every feature has a well-formed id, name and path", () => {
    const seenIds: Set<string> = new Set();
    for (const feature of file.features) {
      expect(feature.id.length).toBeGreaterThan(0);
      expect(feature.name.length).toBeGreaterThan(0);
      expect(feature.path.length).toBeGreaterThan(0);
      expect(seenIds.has(feature.id)).toBe(false);
      seenIds.add(feature.id);

      const points: Array<Point> = pointsOf(feature.path);
      // A drawable ring needs at least three corners.
      expect(points.length).toBeGreaterThanOrEqual(3);
      for (const point of points) {
        expect(Number.isFinite(point.x)).toBe(true);
        expect(Number.isFinite(point.y)).toBe(true);
      }
    }
  });

  test("no outline streaks across the map at the antimeridian", () => {
    const streaking: Array<string> = file.features
      .filter((feature: GeometryFeature) => {
        return (
          widestHorizontalStep(feature.path) >= ROBINSON_VIEW_BOX_WIDTH / 2
        );
      })
      .map((feature: GeometryFeature) => {
        return feature.name;
      });
    expect(streaking).toEqual([]);
  });

  test("all paths stay inside the viewBox", () => {
    for (const feature of file.features) {
      const bounds: Bounds = pathBounds(feature.path);
      expect(bounds.minX).toBeGreaterThanOrEqual(0);
      expect(bounds.maxX).toBeLessThanOrEqual(ROBINSON_VIEW_BOX_WIDTH);
      expect(bounds.minY).toBeGreaterThanOrEqual(0);
      expect(bounds.maxY).toBeLessThanOrEqual(ROBINSON_VIEW_BOX_HEIGHT);
    }
  });

  test("contains the expected countries", () => {
    expect(file.features.length).toBeGreaterThanOrEqual(170);
    expect(featureById(file, "840").name).toBe("United States of America");
    expect(featureById(file, "156").name).toBe("China");
    expect(featureById(file, "076").name).toBe("Brazil");
    expect(featureById(file, "036").name).toBe("Australia");
    expect(featureById(file, "356").name).toBe("India");
    expect(featureById(file, "710").name).toBe("South Africa");
  });

  /*
   * The reason this repo generates its own geometry instead of shipping a
   * pre-projected atlas: the runtime projects pins with the same math, so a
   * pin must land on its own country.
   */
  test("runtime pin projections land inside their country outlines", () => {
    const pins: Array<{ id: string; latitude: number; longitude: number }> = [
      // Kansas City, roughly the middle of the contiguous US.
      { id: "840", latitude: 39.0997, longitude: -94.5786 },
      // Brasília in Brazil.
      { id: "076", latitude: -15.8267, longitude: -47.9218 },
      // Canberra in Australia.
      { id: "036", latitude: -35.2809, longitude: 149.13 },
      // Beijing in China.
      { id: "156", latitude: 39.9042, longitude: 116.4074 },
      // New Delhi in India.
      { id: "356", latitude: 28.6139, longitude: 77.209 },
      // Pretoria in South Africa.
      { id: "710", latitude: -25.7479, longitude: 28.2293 },
    ];
    for (const pin of pins) {
      const point: ProjectedPoint = projectRobinson(
        pin.latitude,
        pin.longitude,
      );
      const bounds: Bounds = pathBounds(featureById(file, pin.id).path);
      expect(point[0]).toBeGreaterThanOrEqual(bounds.minX);
      expect(point[0]).toBeLessThanOrEqual(bounds.maxX);
      expect(point[1]).toBeGreaterThanOrEqual(bounds.minY);
      expect(point[1]).toBeLessThanOrEqual(bounds.maxY);
    }
  });
});

/*
 * The two tiers are swapped under a live frame, so they have to be the same
 * map at two resolutions — not two maps.
 */
describe("the two tiers are interchangeable", () => {
  test("they share a viewBox", () => {
    expect(DETAIL.viewBox).toBe(OVERVIEW.viewBox);
  });

  test("the detail tier is strictly finer, not merely different", () => {
    const overviewPoints: number = OVERVIEW.features.reduce(
      (total: number, feature: GeometryFeature): number => {
        return total + pointsOf(feature.path).length;
      },
      0,
    );
    const detailPoints: number = DETAIL.features.reduce(
      (total: number, feature: GeometryFeature): number => {
        return total + pointsOf(feature.path).length;
      },
      0,
    );
    expect(detailPoints).toBeGreaterThan(overviewPoints * 3);
  });

  test("every overview country is also in the detail tier", () => {
    const detailIds: Set<string> = new Set(
      DETAIL.features.map((feature: GeometryFeature) => {
        return feature.id;
      }),
    );
    const missing: Array<string> = OVERVIEW.features
      .filter((feature: GeometryFeature) => {
        return !detailIds.has(feature.id);
      })
      .map((feature: GeometryFeature) => {
        return feature.name;
      });
    expect(missing).toEqual([]);
  });

  /*
   * The finer source ADDS land — peninsulas, islands and specks the coarse
   * one drops — so the detail outline covers the overview one rather than
   * matching it. The epsilon absorbs the simplification pass shaving a hair
   * off an extremity.
   *
   * Containment, not equality, is the invariant that holds everywhere: the
   * United States is the case that proves it, because the 50m data keeps the
   * Aleutian islands on the far side of the antimeridian and the 110m data
   * does not — its bounds jump from x≈320 to x≈891.
   */
  test("the detail tier covers the overview tier, country by country", () => {
    const epsilon: number = 2;
    for (const id of ["840", "156", "076", "036", "356", "710"]) {
      const overviewBounds: Bounds = pathBounds(featureById(OVERVIEW, id).path);
      const detailBounds: Bounds = pathBounds(featureById(DETAIL, id).path);
      expect(detailBounds.minX).toBeLessThanOrEqual(
        overviewBounds.minX + epsilon,
      );
      expect(detailBounds.maxX).toBeGreaterThanOrEqual(
        overviewBounds.maxX - epsilon,
      );
      expect(detailBounds.minY).toBeLessThanOrEqual(
        overviewBounds.minY + epsilon,
      );
      expect(detailBounds.maxY).toBeGreaterThanOrEqual(
        overviewBounds.maxY - epsilon,
      );
    }
  });

  /*
   * Containment alone would still pass if the detail tier were drawn in a
   * different projection and merely happened to be bigger. Comparing each
   * country's MAINLAND — its largest ring, ignoring the outlying islands the
   * tiers legitimately disagree about — is what actually pins the two to the
   * same coordinate space.
   */
  test("each country's mainland sits in the same place in both tiers", () => {
    for (const id of ["840", "156", "076", "036", "356", "710"]) {
      const overviewBounds: Bounds = mainlandBounds(
        featureById(OVERVIEW, id).path,
      );
      const detailBounds: Bounds = mainlandBounds(featureById(DETAIL, id).path);
      expect(detailBounds.minX).toBeCloseTo(overviewBounds.minX, -1);
      expect(detailBounds.maxX).toBeCloseTo(overviewBounds.maxX, -1);
      expect(detailBounds.minY).toBeCloseTo(overviewBounds.minY, -1);
      expect(detailBounds.maxY).toBeCloseTo(overviewBounds.maxY, -1);
    }
  });
});

/*
 * Size is a product decision, not an accident: the overview is downloaded by
 * anyone who opens the map, and the detail tier by anyone who zooms. A
 * regeneration that quietly multiplied either would be a performance
 * regression nobody would notice until it shipped.
 */
describe("asset budget", () => {
  function kilobytes(fileName: string): number {
    return fs.statSync(path.join(GEO_DIR, fileName)).size / 1024;
  }

  test("the overview tier stays small enough for a first paint", () => {
    expect(kilobytes("WorldCountriesGeometry.json")).toBeLessThan(140);
  });

  test("the detail tier stays within its on-demand budget", () => {
    expect(kilobytes("WorldCountriesDetailGeometry.json")).toBeLessThan(700);
  });

  /*
   * The US-only geometry that backed the deleted "United States" map mode.
   * It must not come back: a per-country outline file is the exact thing
   * this change removed, and re-adding one restores the question of which
   * countries get one.
   */
  test("no per-country geometry is checked in", () => {
    const perCountryFiles: Array<string> = fs
      .readdirSync(GEO_DIR)
      .filter((name: string) => {
        return name.endsWith(".json") && !name.startsWith("WorldCountries");
      });
    expect(perCountryFiles).toEqual([]);
  });
});

/*
 * The detail tier's simplification tolerance and the map's MAX_ZOOM are
 * chosen against each other (see Scripts/Geo/README.md). If somebody raises
 * MAX_ZOOM without regenerating finer geometry, the simplification starts
 * showing as visible corners on coastlines — so pin the relationship.
 */
describe("detail resolution supports the deepest zoom", () => {
  const DETAIL_TOLERANCE_VIEWBOX_UNITS: number = 0.04;

  test("one tolerance is about one screen pixel at MAX_ZOOM", () => {
    // A map rendered at a typical dashboard width.
    const renderedWidthPx: number = 1000;
    const pixelsPerUnit: number =
      renderedWidthPx / (WORLD_VIEWPORT.width / MAX_ZOOM);
    expect(DETAIL_TOLERANCE_VIEWBOX_UNITS * pixelsPerUnit).toBeLessThanOrEqual(
      1.5,
    );
  });

  test("detail coordinates are quantized finer than the tolerance", () => {
    // Two decimals: quantization must not dominate the simplification.
    const steps: Array<string> = DETAIL.features[0]!.path.split("l")[1]!
      .trim()
      .split(/\s+/)
      .slice(0, 50);
    for (const step of steps) {
      for (const value of step.split(",")) {
        const decimals: number = (value.split(".")[1] || "").length;
        expect(decimals).toBeLessThanOrEqual(2);
      }
    }
  });
});
