import { describe, expect, test } from "@jest/globals";
import fs from "fs";
import path from "path";
import {
  ALBERS_USA_VIEW_BOX,
  ALBERS_USA_VIEW_BOX_WIDTH,
  ProjectedPoint,
  ROBINSON_VIEW_BOX,
  ROBINSON_VIEW_BOX_WIDTH,
  projectAlbersUsa,
  projectRobinson,
} from "../../FeatureSet/Dashboard/src/Components/NetworkSite/Geo/GeoProjection";

/*
 * Validates the checked-in map geometry assets generated by
 * Scripts/Geo/GenerateMapGeometry.js: shape, feature counts, path sanity and
 * — most importantly — that the outlines are viewBox-consistent with the
 * runtime pin projections in GeoProjection.ts, so a site pin projected at
 * runtime lands on its state/country outline.
 */

interface GeometryFeature {
  id: string;
  name: string;
  path: string;
}

interface GeometryFile {
  viewBox: string;
  features: Array<GeometryFeature>;
}

const GEO_DIR: string = path.join(
  __dirname,
  "..",
  "..",
  "FeatureSet",
  "Dashboard",
  "src",
  "Components",
  "NetworkSite",
  "Geo",
);

function loadGeometry(fileName: string): GeometryFile {
  return JSON.parse(
    fs.readFileSync(path.join(GEO_DIR, fileName), "utf8"),
  ) as GeometryFile;
}

// Extracts every numeric coordinate from an SVG path 'd' string.
function pathNumbers(pathD: string): Array<number> {
  const matches: Array<string> | null = pathD.match(/-?\d+(?:\.\d+)?/g);
  return (matches ?? []).map((value: string) => {
    return Number(value);
  });
}

interface Bounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

function pathBounds(pathD: string): Bounds {
  const numbers: Array<number> = pathNumbers(pathD);
  const bounds: Bounds = {
    minX: Infinity,
    minY: Infinity,
    maxX: -Infinity,
    maxY: -Infinity,
  };
  for (let i: number = 0; i < numbers.length; i += 2) {
    bounds.minX = Math.min(bounds.minX, numbers[i]!);
    bounds.maxX = Math.max(bounds.maxX, numbers[i]!);
    bounds.minY = Math.min(bounds.minY, numbers[i + 1]!);
    bounds.maxY = Math.max(bounds.maxY, numbers[i + 1]!);
  }
  return bounds;
}

/*
 * Largest horizontal step between two consecutive points of any subpath.
 * A ring that crosses the ±180° antimeridian without being cut there (Fiji,
 * Russia's Chukotka tip and Wrangel Island) shows up as a step spanning most
 * of the map — and renders as a straight streak clear across the finished
 * map. Scripts/Geo/GenerateMapGeometry.js cuts those rings at the meridian;
 * this measures that the cut actually happened.
 */
function widestHorizontalStep(pathD: string): number {
  let widest: number = 0;
  for (const subpath of pathD.split("M")) {
    if (!subpath.trim()) {
      continue;
    }
    const numbers: Array<number> = pathNumbers(subpath);
    for (let i: number = 2; i + 1 < numbers.length; i += 2) {
      widest = Math.max(widest, Math.abs(numbers[i]! - numbers[i - 2]!));
    }
  }
  return widest;
}

function expectNoAntimeridianStreaks(file: GeometryFile, width: number): void {
  const streaking: Array<string> = file.features
    .filter((feature: GeometryFeature) => {
      return widestHorizontalStep(feature.path) >= width / 2;
    })
    .map((feature: GeometryFeature) => {
      return feature.name;
    });
  expect(streaking).toEqual([]);
}

function featureById(file: GeometryFile, id: string): GeometryFeature {
  const feature: GeometryFeature | undefined = file.features.find(
    (candidate: GeometryFeature) => {
      return candidate.id === id;
    },
  );
  expect(feature).toBeDefined();
  return feature!;
}

function expectWellFormedFeatures(file: GeometryFile): void {
  const seenIds: Set<string> = new Set();
  for (const feature of file.features) {
    expect(feature.id.length).toBeGreaterThan(0);
    expect(feature.name.length).toBeGreaterThan(0);
    expect(feature.path.length).toBeGreaterThan(0);
    expect(feature.path.startsWith("M")).toBe(true);
    expect(feature.path.endsWith("Z")).toBe(true);
    expect(seenIds.has(feature.id)).toBe(false);
    seenIds.add(feature.id);

    const numbers: Array<number> = pathNumbers(feature.path);
    expect(numbers.length).toBeGreaterThanOrEqual(6);
    // Coordinates come in x,y pairs and every one must be finite.
    expect(numbers.length % 2).toBe(0);
    for (const value of numbers) {
      expect(Number.isFinite(value)).toBe(true);
    }
  }
}

describe("UsStatesGeometry.json", () => {
  const usStates: GeometryFile = loadGeometry("UsStatesGeometry.json");

  test("viewBox matches the AlbersUSA projection constants", () => {
    expect(usStates.viewBox).toBe(ALBERS_USA_VIEW_BOX);
  });

  test("no outline streaks across the map at the antimeridian", () => {
    expectNoAntimeridianStreaks(usStates, ALBERS_USA_VIEW_BOX_WIDTH);
  });

  test("contains the 50 states plus DC", () => {
    /*
     * us-atlas states-10m ships 56 entries; the 5 island territories (AS,
     * GU, MP, PR, VI) fall outside the AlbersUSA composite and are dropped
     * by the generator, leaving 50 states + DC.
     */
    expect(usStates.features.length).toBeGreaterThanOrEqual(51);
    expect(featureById(usStates, "06").name).toBe("California");
    expect(featureById(usStates, "48").name).toBe("Texas");
    expect(featureById(usStates, "11").name).toBe("District of Columbia");
    expect(featureById(usStates, "02").name).toBe("Alaska");
    expect(featureById(usStates, "15").name).toBe("Hawaii");
  });

  test("every feature has a well-formed id, name and path", () => {
    expectWellFormedFeatures(usStates);
  });

  test("paths stay near the viewBox (Aleutian tail may spill slightly)", () => {
    for (const feature of usStates.features) {
      const bounds: Bounds = pathBounds(feature.path);
      expect(bounds.minX).toBeGreaterThanOrEqual(-80);
      expect(bounds.maxX).toBeLessThanOrEqual(1060);
      expect(bounds.minY).toBeGreaterThanOrEqual(-20);
      expect(bounds.maxY).toBeLessThanOrEqual(630);
    }
  });

  test("runtime pin projections land inside their state outlines", () => {
    const pins: Array<{ id: string; latitude: number; longitude: number }> = [
      // Washington DC in the District of Columbia.
      { id: "11", latitude: 38.9072, longitude: -77.0369 },
      // Los Angeles in California.
      { id: "06", latitude: 34.0522, longitude: -118.2437 },
      // Anchorage in the Alaska inset.
      { id: "02", latitude: 61.2181, longitude: -149.9003 },
      // Honolulu in the Hawaii inset.
      { id: "15", latitude: 21.3069, longitude: -157.8583 },
    ];
    for (const pin of pins) {
      const point: ProjectedPoint | null = projectAlbersUsa(
        pin.latitude,
        pin.longitude,
      );
      expect(point).not.toBeNull();
      const bounds: Bounds = pathBounds(featureById(usStates, pin.id).path);
      expect(point![0]).toBeGreaterThanOrEqual(bounds.minX);
      expect(point![0]).toBeLessThanOrEqual(bounds.maxX);
      expect(point![1]).toBeGreaterThanOrEqual(bounds.minY);
      expect(point![1]).toBeLessThanOrEqual(bounds.maxY);
    }
  });
});

describe("WorldCountriesGeometry.json", () => {
  const worldCountries: GeometryFile = loadGeometry(
    "WorldCountriesGeometry.json",
  );

  test("viewBox matches the Robinson projection constants", () => {
    expect(worldCountries.viewBox).toBe(ROBINSON_VIEW_BOX);
  });

  /*
   * Regression: Fiji and two Russian polygons cross the antimeridian, and
   * before the generator cut them there they drew straight lines across the
   * entire finished map.
   */
  test("no outline streaks across the map at the antimeridian", () => {
    expectNoAntimeridianStreaks(worldCountries, ROBINSON_VIEW_BOX_WIDTH);
  });

  test("contains the expected countries", () => {
    // world-atlas countries-110m ships 177 countries.
    expect(worldCountries.features.length).toBeGreaterThanOrEqual(170);
    expect(featureById(worldCountries, "840").name).toBe(
      "United States of America",
    );
    expect(featureById(worldCountries, "156").name).toBe("China");
    expect(featureById(worldCountries, "076").name).toBe("Brazil");
    expect(featureById(worldCountries, "036").name).toBe("Australia");
  });

  test("every feature has a well-formed id, name and path", () => {
    expectWellFormedFeatures(worldCountries);
  });

  test("all paths stay inside the viewBox", () => {
    for (const feature of worldCountries.features) {
      const bounds: Bounds = pathBounds(feature.path);
      expect(bounds.minX).toBeGreaterThanOrEqual(0);
      expect(bounds.maxX).toBeLessThanOrEqual(960);
      expect(bounds.minY).toBeGreaterThanOrEqual(0);
      expect(bounds.maxY).toBeLessThanOrEqual(500);
    }
  });

  test("runtime pin projections land inside their country outlines", () => {
    const pins: Array<{ id: string; latitude: number; longitude: number }> = [
      // Kansas City, roughly the middle of the contiguous US.
      { id: "840", latitude: 39.0997, longitude: -94.5786 },
      // Brasília in Brazil.
      { id: "076", latitude: -15.8267, longitude: -47.9218 },
      // Canberra in Australia.
      { id: "036", latitude: -35.2809, longitude: 149.13 },
    ];
    for (const pin of pins) {
      const point: ProjectedPoint = projectRobinson(
        pin.latitude,
        pin.longitude,
      );
      const bounds: Bounds = pathBounds(
        featureById(worldCountries, pin.id).path,
      );
      expect(point[0]).toBeGreaterThanOrEqual(bounds.minX);
      expect(point[0]).toBeLessThanOrEqual(bounds.maxX);
      expect(point[1]).toBeGreaterThanOrEqual(bounds.minY);
      expect(point[1]).toBeLessThanOrEqual(bounds.maxY);
    }
  });
});
