/*
 * The metrics the VMware agent sends, as its vcenter receiver declares them
 * (opentelemetry-collector-contrib 0.161.0, receiver/vcenterreceiver/
 * metadata.yaml): every metric the receiver turns on by default, plus
 * vcenter.host.memory.capacity, which the agent's otel-collector-config.yaml
 * turns on. Name, description, unit, kind and value type are the receiver's
 * own, so the metric catalog and every chart read the probe's data exactly as
 * they read the agent's. Generated from metadata.yaml; do not edit by hand.
 */

export interface VCenterMetricDefinition {
  description: string;
  unit: string;
  kind: "sum" | "gauge";
  valueType: "int" | "double";
}

export const VCENTER_METRICS: Record<string, VCenterMetricDefinition> = {
  "vcenter.cluster.cpu.effective": {
    description: "The effective CPU available to the cluster. This value excludes CPU from hosts in maintenance mode or are unresponsive.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.cluster.cpu.limit": {
    description: "The amount of CPU available to the cluster.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.cluster.host.count": {
    description: "The number of hosts in the cluster.",
    unit: "{hosts}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.cluster.memory.effective": {
    description: "The effective available memory of the cluster.",
    unit: "By",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.cluster.memory.limit": {
    description: "The available memory of the cluster.",
    unit: "By",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.cluster.vm.count": {
    description: "The number of virtual machines in the cluster.",
    unit: "{virtual_machines}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.cluster.vm_template.count": {
    description: "The number of virtual machine templates in the cluster.",
    unit: "{virtual_machine_templates}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.cluster.vsan.congestions": {
    description: "The congestions of IOs generated by all vSAN clients in the cluster.",
    unit: "{congestions/s}",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.cluster.vsan.latency.avg": {
    description: "The overall cluster latency while accessing vSAN storage.",
    unit: "us",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.cluster.vsan.operations": {
    description: "The vSAN IOPs of a cluster.",
    unit: "{operations/s}",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.cluster.vsan.throughput": {
    description: "The vSAN throughput of a cluster.",
    unit: "By/s",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.datacenter.cluster.count": {
    description: "The number of clusters in the datacenter.",
    unit: "{clusters}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datacenter.cpu.limit": {
    description: "The total amount of CPU available to the datacenter.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datacenter.datastore.count": {
    description: "The number of datastores in the datacenter.",
    unit: "{datastores}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datacenter.disk.space": {
    description: "The amount of available and used disk space in the datacenter.",
    unit: "By",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datacenter.host.count": {
    description: "The number of hosts in the datacenter.",
    unit: "{hosts}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datacenter.memory.limit": {
    description: "The total amount of memory available to the datacenter.",
    unit: "By",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datacenter.vm.count": {
    description: "The number of VM's in the datacenter.",
    unit: "{virtual_machines}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datastore.disk.usage": {
    description: "The amount of space in the datastore.",
    unit: "By",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.datastore.disk.utilization": {
    description: "The utilization of the datastore.",
    unit: "%",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.host.cpu.capacity": {
    description: "Total CPU capacity of the host system.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.host.cpu.reserved": {
    description: "The CPU of the host reserved for use by virtual machines.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.host.cpu.usage": {
    description: "The amount of CPU used by the host.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.host.cpu.utilization": {
    description: "The CPU utilization of the host system.",
    unit: "%",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.host.disk.latency.avg": {
    description: "The latency of operations to the host system's disk.",
    unit: "ms",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.host.disk.latency.max": {
    description: "Highest latency value across all disks used by the host.",
    unit: "ms",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.host.disk.throughput": {
    description: "Average number of kilobytes read from or written to the disk each second.",
    unit: "{KiBy/s}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.host.memory.capacity": {
    description: "Total memory  capacity of the host system.",
    unit: "MiBy",
    kind: "sum",
    valueType: "double",
  },
  "vcenter.host.memory.usage": {
    description: "The amount of memory the host system is using.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.host.memory.utilization": {
    description: "The percentage of the host system's memory capacity that is being utilized.",
    unit: "%",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.host.network.packet.drop.rate": {
    description: "The rate of packets dropped across each physical NIC (network interface controller) instance on the host.",
    unit: "{packets/s}",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.host.network.packet.error.rate": {
    description: "The rate of packet errors transmitted or received on the host network.",
    unit: "{errors/s}",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.host.network.packet.rate": {
    description: "The rate of packets transmitted or received across each physical NIC (network interface controller) instance on the host.",
    unit: "{packets/s}",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.host.network.throughput": {
    description: "The amount of data that was transmitted or received over the network by the host.",
    unit: "{KiBy/s}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.host.network.usage": {
    description: "The sum of the data transmitted and received for all the NIC instances of the host.",
    unit: "{KiBy/s}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.host.vsan.cache.hit_rate": {
    description: "The host's read IOs which could be satisfied by the local client cache.",
    unit: "%",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.host.vsan.congestions": {
    description: "The congestions of IOs generated by all vSAN clients in the host.",
    unit: "{congestions/s}",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.host.vsan.latency.avg": {
    description: "The host latency while accessing vSAN storage.",
    unit: "us",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.host.vsan.operations": {
    description: "The vSAN IOPs of a host.",
    unit: "{operations/s}",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.host.vsan.throughput": {
    description: "The vSAN throughput of a host.",
    unit: "By/s",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.resource_pool.cpu.shares": {
    description: "The amount of shares of CPU in the resource pool.",
    unit: "{shares}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.resource_pool.cpu.usage": {
    description: "The usage of the CPU used by the resource pool.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.resource_pool.memory.ballooned": {
    description: "The amount of memory in a resource pool that is ballooned due to virtualization.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.resource_pool.memory.granted": {
    description: "The amount of memory that is granted to VMs in the resource pool from shared and non-shared host memory.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.resource_pool.memory.shares": {
    description: "The amount of shares of memory in the resource pool.",
    unit: "{shares}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.resource_pool.memory.swapped": {
    description: "The amount of memory that is granted to VMs in the resource pool from the host's swap space.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.resource_pool.memory.usage": {
    description: "The usage of the memory by the resource pool.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.cpu.readiness": {
    description: "Percentage of time that the virtual machine was ready, but could not get scheduled to run on the physical CPU.",
    unit: "%",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.vm.cpu.usage": {
    description: "The amount of CPU used by the VM.",
    unit: "MHz",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.cpu.utilization": {
    description: "The CPU utilization of the VM.",
    unit: "%",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.vm.disk.latency.avg": {
    description: "The latency of operations to the virtual machine's disk.",
    unit: "ms",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.vm.disk.latency.max": {
    description: "The highest reported total latency (device and kernel times) over an interval of 20 seconds.",
    unit: "ms",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.vm.disk.throughput": {
    description: "Average number of kilobytes read from or written to the virtual disk each second.",
    unit: "{KiBy/s}",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.vm.disk.usage": {
    description: "The amount of storage space used by the virtual machine.",
    unit: "By",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.disk.utilization": {
    description: "The utilization of storage on the virtual machine.",
    unit: "%",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.vm.memory.ballooned": {
    description: "The amount of memory that is ballooned due to virtualization.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.memory.swapped": {
    description: "The portion of memory that is granted to this VM from the host's swap space.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.memory.swapped_ssd": {
    description: "The amount of memory swapped to fast disk device such as SSD.",
    unit: "KiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.memory.usage": {
    description: "The amount of memory that is used by the virtual machine.",
    unit: "MiBy",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.memory.utilization": {
    description: "The memory utilization of the VM.",
    unit: "%",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.vm.network.packet.drop.rate": {
    description: "The rate of transmitted or received packets dropped by each vNIC (virtual network interface controller) on the virtual machine.",
    unit: "{packets/s}",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.vm.network.packet.rate": {
    description: "The rate of packets transmitted or received by each vNIC (virtual network interface controller) on the virtual machine.",
    unit: "{packets/s}",
    kind: "gauge",
    valueType: "double",
  },
  "vcenter.vm.network.throughput": {
    description: "The amount of data that was transmitted or received over the network of the virtual machine.",
    unit: "By/s",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.network.usage": {
    description: "The network utilization combined transmit and receive rates during an interval.",
    unit: "{KiBy/s}",
    kind: "sum",
    valueType: "int",
  },
  "vcenter.vm.vsan.latency.avg": {
    description: "The virtual machine latency while accessing vSAN storage.",
    unit: "us",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.vm.vsan.operations": {
    description: "The vSAN IOPs of a virtual machine.",
    unit: "{operations/s}",
    kind: "gauge",
    valueType: "int",
  },
  "vcenter.vm.vsan.throughput": {
    description: "The vSAN throughput of a virtual machine.",
    unit: "By/s",
    kind: "gauge",
    valueType: "double",
  },
};
