
####################################
#IMPORTANT: Kube Reosurces below are ONLY for SaaS service
####################################

{{- if .Values.saas.isSaasService }}
###########-----HOME------#################
# Fyipe Home
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" .Release.Name "home"  }}
    labels:
        app: {{ printf "%s-%s" .Release.Name "home"  }}
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" .Release.Name "home"  }}
    replicas: {{ .Values.replicaCount }}
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" .Release.Name "home"  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "home" .Values.image.tag }}
                  name: {{ printf "%s-%s" .Release.Name "home"  }}
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  env:
                      - name: IS_SAAS_SERVICE
                        value: 'true'
                      - name: NODE_ENV
                        value: 'production'
                  ports:
                      - containerPort: {{ .Values.host.homePort }}
                        hostPort: {{ .Values.host.homePort }}
                        name: {{ printf "%s-%s" .Release.Name "home"  }}
            restartPolicy: {{ .Values.image.restartPolicy }}

---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" .Release.Name "home"  }}
    name: {{ printf "%s-%s" .Release.Name "home"  }}
spec:
    ports:
        - port: {{ .Values.host.homeServicePort }}
          protocol: TCP
          targetPort: {{ .Values.host.homePort }}
    selector:
        app: {{ printf "%s-%s" .Release.Name "home"  }}
    type: {{ .Values.service.type }}
---
###########################################
{{- end }}