import CreateBy from "../Types/Database/CreateBy";
import UpdateBy from "../Types/Database/UpdateBy";
import { OnCreate, OnUpdate } from "../Types/Database/Hooks";
import DatabaseService from "./DatabaseService";
import CalendarFeedToken, {
  CalendarFeedRotation,
  MintedCalendarFeedToken,
} from "../Utils/OnCall/CalendarFeedToken";
import CaptureSpan from "../Utils/Telemetry/CaptureSpan";
import Model from "../../Models/DatabaseModels/UserOnCallCalendarFeed";
import BadDataException from "../../Types/Exception/BadDataException";
import NotAuthorizedException from "../../Types/Exception/NotAuthorizedException";
import NotFoundException from "../../Types/Exception/NotFoundException";
import CalendarFeedWindow from "../../Types/OnCallDutyPolicy/CalendarFeedWindow";
import ObjectID from "../../Types/ObjectID";
import OneUptimeDate from "../../Types/Date";

/*
 * The personal calendar feed row: one per (project, user).
 *
 * WHAT THE HOOKS GUARANTEE
 *
 *   - Only root creates one. The table create list is already empty, but the
 *     hook says it out loud: the plaintext token is minted here or by the
 *     calendar API, never by a request body.
 *   - A created row always carries a consistent token set (see
 *     CalendarFeedToken.applyTokenColumnsOnCreate): there is no path to a row
 *     whose hash does not match its token.
 *   - pastDays / futureDays are clamped to the CalendarFeedWindow bounds on
 *     every write, so a feed can never be asked to render a year.
 *
 * Rotation lives here too (rotateTokenById) so the grace-hash bookkeeping is
 * written once and the API, the member-leave cleanup and the tests share it.
 * Cache purging is the caller's job - this service knows nothing about the
 * feed cache.
 */
export class Service extends DatabaseService<Model> {
  public constructor() {
    super(Model);
  }

  @CaptureSpan()
  protected override async onBeforeCreate(
    createBy: CreateBy<Model>,
  ): Promise<OnCreate<Model>> {
    if (!createBy.props.isRoot) {
      throw new NotAuthorizedException(
        "Calendar feeds are generated by the calendar API, not created directly.",
      );
    }

    const projectId: ObjectID | undefined =
      createBy.data.projectId || createBy.props.tenantId;

    if (!projectId) {
      throw new BadDataException("projectId is required");
    }

    if (!createBy.data.userId) {
      throw new BadDataException("userId is required");
    }

    createBy.data.projectId = projectId;

    // Root only reaches this line, so a pre-minted token may be trusted.
    CalendarFeedToken.applyTokenColumnsOnCreate(createBy.data, {
      trustSuppliedToken: true,
    });

    createBy.data.pastDays = CalendarFeedWindow.clampPastDays(
      createBy.data.pastDays,
    );
    createBy.data.futureDays = CalendarFeedWindow.clampFutureDays(
      createBy.data.futureDays,
    );

    return { createBy, carryForward: null };
  }

  @CaptureSpan()
  protected override async onBeforeUpdate(
    updateBy: UpdateBy<Model>,
  ): Promise<OnUpdate<Model>> {
    if (updateBy.data.pastDays !== undefined) {
      updateBy.data.pastDays = CalendarFeedWindow.clampPastDays(
        updateBy.data.pastDays,
      );
    }

    if (updateBy.data.futureDays !== undefined) {
      updateBy.data.futureDays = CalendarFeedWindow.clampFutureDays(
        updateBy.data.futureDays,
      );
    }

    return { updateBy, carryForward: null };
  }

  /**
   * Create the feed row for a user in a project and hand the plaintext token
   * back ONCE, so the caller can build the subscription URL without a
   * decrypt round-trip. Root only; the caller is responsible for holding the
   * per-(project, user) lock the API uses around mint-or-rotate.
   */
  @CaptureSpan()
  public async createForUser(data: {
    projectId: ObjectID;
    userId: ObjectID;
  }): Promise<{ feed: Model; minted: MintedCalendarFeedToken }> {
    const minted: MintedCalendarFeedToken = CalendarFeedToken.mintSet();

    const feed: Model = new Model();
    feed.projectId = data.projectId;
    feed.userId = data.userId;
    feed.token = minted.token;
    feed.rotatedAt = OneUptimeDate.getCurrentDate();

    const created: Model = await this.create({
      data: feed,
      props: { isRoot: true },
    });

    return { feed: created, minted };
  }

  /**
   * Rotate the token of an existing feed: mint a new one, move the current
   * hash into the 30-day grace slot, stamp rotatedAt. Returns the new
   * plaintext token ONCE. Root write; the caller purges caches.
   */
  @CaptureSpan()
  public async rotateTokenById(data: {
    id: ObjectID;
  }): Promise<CalendarFeedRotation> {
    const existing: Model | null = await this.findOneBy({
      query: { _id: data.id },
      select: { _id: true, tokenHash: true },
      props: { isRoot: true, ignoreHooks: true },
    });

    if (!existing) {
      throw new NotFoundException("Calendar feed not found.");
    }

    const rotation: CalendarFeedRotation = CalendarFeedToken.buildRotation({
      currentTokenHash: existing.tokenHash,
    });

    await this.updateOneById({
      id: data.id,
      data: CalendarFeedToken.toRotationUpdateData(rotation),
      props: { isRoot: true },
    });

    return rotation;
  }
}

export default new Service();
