enum ColumnType {
    Version = "Version",
    Phone = "Phone",
    HashedString = "Hashed String",
    Password = "Password",
    Email = "Email",
    Color = "Color",
    Slug = "Slug",
    Name = "Name",
    Description = "Description",
    ObjectID = "Object ID",
    File = "File",
    Buffer = "Buffer",
    ShortURL = "Short URL",
    Markdown = "Markdown",
    Domain = "Domain",
    LongURL = "URL",
    ShortText = "Text",
    OTP = "One Time Password",
    LongText = "Long Text",
    HTML = "HTML",
    JavaScript = "JavaSCript",
    CSS = "CSS",
    Date = "Date",
    Boolean ="Boolean",
    Array = "Array",
    SmallPositiveNumber = "Small Positive Number",
    PositiveNumber = "Positive Number",
    BigPositiveNumber = "Big Positive Number",
    SmallNumber = "Small Number",
    Number = "Number",
    BigNumber ="Big Number",
    Entity = "Entity",
    EntityArray ="Entity Array",
    JSON = "JSON",
    Permission = "Permission",
    CustomFieldType = "Custom Field Type"
}

export default ColumnType;
