import Service from "../../../Models/DatabaseModels/Service";
import { RestoreServiceLowerNameIndex1786100000000 } from "../../../Server/Infrastructure/Postgres/SchemaMigrations/1786100000000-RestoreServiceLowerNameIndex";
import SchemaMigrations from "../../../Server/Infrastructure/Postgres/SchemaMigrations/Index";
import { QueryRunner, getMetadataArgsStorage } from "typeorm";
import type { IndexMetadataArgs } from "typeorm/metadata-args/IndexMetadataArgs";
import { describe, expect, test } from "@jest/globals";

const INDEX_NAME: string = "IDX_SERVICE_PROJECT_LOWER_NAME";

/*
 * The telemetry ingest path resolves `service.name` case-insensitively, so the
 * predicate is `LOWER("Service"."name") = $2`. Only an EXPRESSION index can
 * serve that; an index over the raw `name` column cannot, and the lookup
 * degrades to O(services in project) heap fetches on the hottest read in the
 * product. Production ran at 100% CPU on it.
 *
 * The index this migration creates has been deleted from production once
 * already. It was created as IDX_SERVICE_PROJECT_NAME_UNIQUE by migration
 * 1774559064921 and dropped by autogenerated migration 1775735059360, whose
 * down() "restores" it WITHOUT the LOWER() — so even the round-trip loses it.
 * The cause is structural: TypeORM's schema builder matches database indexes to
 * entity metadata by NAME and drops every one it cannot find, and an expression
 * index that exists only in a migration is invisible to entity metadata.
 *
 * Three things must therefore all hold, and a regression in ANY one silently
 * reintroduces the incident:
 *
 *   1. The entity declares the index BY NAME with `synchronize: false`. This is
 *      what stops the next `migration:generate` emitting a DROP for it. Without
 *      it the migration below gets undone and nobody notices until CPU spikes.
 *   2. The migration's SQL contract: up() creates an expression index on
 *      LOWER("name"), partial on "deletedAt" IS NULL, and down() drops it.
 *   3. The migration is registered in SchemaMigrations/Index.ts. An
 *      unregistered migration is dead code that never runs on boot.
 *
 * Pure metadata/mocks — no Postgres connection anywhere.
 */
describe("Service LOWER(name) expression index", () => {
  describe("1. the entity declaration that keeps it alive", () => {
    type FindIndexFunction = () => IndexMetadataArgs | undefined;

    const findIndex: FindIndexFunction = (): IndexMetadataArgs | undefined => {
      return getMetadataArgsStorage().indices.find(
        (index: IndexMetadataArgs): boolean => {
          return index.target === Service && index.name === INDEX_NAME;
        },
      );
    };

    test("Service declares the index by name", () => {
      /*
       * Name matching is the whole mechanism — RdbmsSchemaBuilder looks up
       * `metadata.indices.find((i) => i.name === tableIndex.name)` and drops
       * anything unmatched. The name here must equal the one in the migration.
       */
      expect(findIndex()).toBeDefined();
    });

    test("the declaration opts OUT of schema synchronization", () => {
      /*
       * THE assertion. `synchronize: false` makes the builder skip the index in
       * dropOldIndices AND in createNewIndices. Flip this to true (or drop the
       * option) and TypeORM owns the index again — at which point it cannot
       * express LOWER() and will replace it with a raw-column index, which is
       * exactly the regression that caused the incident.
       */
      expect(findIndex()?.synchronize).toBe(false);
    });

    test("the pre-existing raw-name unique index is left untouched", () => {
      /*
       * The expression index is additive. The raw (projectId, name) unique
       * index still enforces the create-race guard that the service layer's
       * catch-and-refetch path depends on.
       */
      const rawUnique: IndexMetadataArgs | undefined = getMetadataArgsStorage()
        .indices.filter((index: IndexMetadataArgs): boolean => {
          return index.target === Service;
        })
        .find((index: IndexMetadataArgs): boolean => {
          return index.unique === true && index.name === undefined;
        });

      expect(rawUnique).toBeDefined();
    });
  });

  describe("2. the migration's SQL contract", () => {
    type CapturedQueriesFunction = (
      run: (queryRunner: QueryRunner) => Promise<void>,
    ) => Promise<Array<string>>;

    const capturedQueries: CapturedQueriesFunction = async (
      run: (queryRunner: QueryRunner) => Promise<void>,
    ): Promise<Array<string>> => {
      const queries: Array<string> = [];
      const queryRunner: QueryRunner = {
        query: async (sql: string): Promise<void> => {
          queries.push(sql);
        },
      } as unknown as QueryRunner;

      await run(queryRunner);
      return queries;
    };

    test("up() indexes the LOWER() EXPRESSION, not the raw column", () => {
      /*
       * An index on ("projectId", "name") is not a substitute and would leave
       * the predicate non-sargable. This is the difference between O(log n) and
       * O(services in project) per ingest resolution.
       */
      return capturedQueries(async (qr: QueryRunner): Promise<void> => {
        await new RestoreServiceLowerNameIndex1786100000000().up(qr);
      }).then((queries: Array<string>): void => {
        expect(queries).toHaveLength(1);
        expect(queries[0]).toContain('LOWER("name")');
        expect(queries[0]).toContain('ON "Service"');
        expect(queries[0]).toContain(INDEX_NAME);
      });
    });

    test("up() matches the query's soft-delete predicate", async () => {
      /*
       * The lookup always carries `deletedAt IS NULL` (DatabaseService adds it
       * for every non-withDeleted read). A partial index on the same predicate
       * stays usable and stays small.
       */
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreServiceLowerNameIndex1786100000000().up(qr);
        },
      );

      expect(queries[0]).toContain('WHERE "deletedAt" IS NULL');
    });

    test("up() carries createdAt so the ORDER BY needs no Sort node", async () => {
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreServiceLowerNameIndex1786100000000().up(qr);
        },
      );

      expect(queries[0]).toContain('"createdAt"');
    });

    test("up() is idempotent so a hand-built index does not break the deploy", async () => {
      /*
       * The incident mitigation is to build this CONCURRENTLY on the live
       * database under the same name before deploying. IF NOT EXISTS makes the
       * migration a no-op in that case instead of a failed deploy.
       */
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreServiceLowerNameIndex1786100000000().up(qr);
        },
      );

      expect(queries[0]).toContain("IF NOT EXISTS");
    });

    test("up() is NOT concurrent — migrations run inside one transaction", async () => {
      /*
       * TypeORM defaults migrationsTransactionMode to "all", and CREATE INDEX
       * CONCURRENTLY cannot run inside a transaction block. Adding CONCURRENTLY
       * here would abort the entire migration run on boot.
       */
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreServiceLowerNameIndex1786100000000().up(qr);
        },
      );

      expect(queries[0]).not.toContain("CONCURRENTLY");
    });

    test("up() does NOT recreate the index as UNIQUE", async () => {
      /*
       * The dropped original was unique. Recreating it that way fails on any
       * project already holding two services whose names differ only by case —
       * which the surviving raw-name unique index permits. Restoring
       * case-insensitive uniqueness needs a dedupe pass and its own migration.
       */
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreServiceLowerNameIndex1786100000000().up(qr);
        },
      );

      expect(queries[0]).not.toContain("UNIQUE");
    });

    test("down() drops exactly what up() created", async () => {
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreServiceLowerNameIndex1786100000000().down(qr);
        },
      );

      expect(queries).toHaveLength(1);
      expect(queries[0]).toContain("DROP INDEX");
      expect(queries[0]).toContain(INDEX_NAME);
    });
  });

  describe("3. registration", () => {
    test("the migration is registered so it actually runs on boot", () => {
      /*
       * CI enforces this separately, but an unregistered migration is dead
       * code — the index would never be created in any environment.
       */
      expect(SchemaMigrations).toContain(
        RestoreServiceLowerNameIndex1786100000000,
      );
    });

    test("it is registered AFTER the migration that dropped the original", () => {
      /*
       * Ordering is the correctness condition: 1775735059360 drops
       * IDX_SERVICE_PROJECT_NAME_UNIQUE. Running this restore before that drop
       * would leave a database with no usable index again.
       */
      const names: Array<string> = SchemaMigrations.map(
        (migration: unknown): string => {
          return (migration as { name: string }).name;
        },
      );

      const restoreAt: number = names.indexOf(
        "RestoreServiceLowerNameIndex1786100000000",
      );
      const dropperAt: number = names.indexOf("MigrationName1775735059360");

      expect(restoreAt).toBeGreaterThan(-1);
      expect(dropperAt).toBeGreaterThan(-1);
      expect(restoreAt).toBeGreaterThan(dropperAt);
    });
  });
});
