import CephCluster from "../../../Models/DatabaseModels/CephCluster";
import DockerHost from "../../../Models/DatabaseModels/DockerHost";
import GlobalOIDCProject from "../../../Models/DatabaseModels/GlobalOidcProject";
import GlobalSSOProject from "../../../Models/DatabaseModels/GlobalSsoProject";
import IoTFleet from "../../../Models/DatabaseModels/IoTFleet";
import KubernetesCluster from "../../../Models/DatabaseModels/KubernetesCluster";
import NetworkDevice from "../../../Models/DatabaseModels/NetworkDevice";
import NetworkInterface from "../../../Models/DatabaseModels/NetworkInterface";
import ProxmoxCluster from "../../../Models/DatabaseModels/ProxmoxCluster";
import { RestoreDroppedUniqueIndexes1786200000000 } from "../../../Server/Infrastructure/Postgres/SchemaMigrations/1786200000000-RestoreDroppedUniqueIndexes";
import SchemaMigrations from "../../../Server/Infrastructure/Postgres/SchemaMigrations/Index";
import { QueryRunner, getMetadataArgsStorage } from "typeorm";
import type { IndexMetadataArgs } from "typeorm/metadata-args/IndexMetadataArgs";
import { describe, expect, test } from "@jest/globals";

/*
 * Nine UNIQUE indexes were deleted from production by autogenerated migrations
 * and never restored. They were found by auditing every hand-named index ever
 * created in a migration up() against a database with all registered
 * migrations applied: 308 exist, 302 are absent, and ten of the absent ones
 * carried a UNIQUE/partial/expression definition TypeORM cannot express and so
 * never re-created. (The tenth, the Service LOWER(name) index, is covered by
 * RestoreServiceLowerNameIndexMigration.test.ts.)
 *
 * The cause is structural, so the fix has to be structural too:
 * RdbmsSchemaBuilder.dropOldIndices matches database indexes to entity metadata
 * BY NAME and drops every one it cannot find. An index that lives only in a
 * migration is invisible to entity metadata and gets dropped again on the next
 * `migration:generate`.
 *
 * Three things must therefore all hold, and a regression in ANY one puts the
 * index back on death row:
 *
 *   1. Each entity declares its index BY NAME with `synchronize: false`.
 *   2. The migration creates all nine, partial on "deletedAt" IS NULL, and
 *      repairs duplicates first so it cannot fail on real data.
 *   3. The migration is registered — an unregistered migration never runs.
 *
 * Pure metadata/mocks — no Postgres connection anywhere.
 */

type ModelClass = { new (): unknown };

// [entity, index name, table name]
const PINNED_INDEXES: Array<[ModelClass, string, string]> = [
  [CephCluster, "IDX_ceph_cluster_slug", "CephCluster"],
  [DockerHost, "IDX_docker_host_slug", "DockerHost"],
  [IoTFleet, "IDX_iot_fleet_slug", "IoTFleet"],
  [KubernetesCluster, "IDX_kubernetes_cluster_slug", "KubernetesCluster"],
  [NetworkDevice, "IDX_network_device_slug", "NetworkDevice"],
  [ProxmoxCluster, "IDX_proxmox_cluster_slug", "ProxmoxCluster"],
  [
    GlobalOIDCProject,
    "IDX_GlobalOIDCProject_globalOidcId_projectId",
    "GlobalOIDCProject",
  ],
  [
    GlobalSSOProject,
    "IDX_GlobalSSOProject_globalSsoId_projectId",
    "GlobalSSOProject",
  ],
  [
    NetworkInterface,
    "IDX_network_interface_device_ifindex",
    "NetworkInterface",
  ],
];

type CapturedQueriesFunction = (
  run: (queryRunner: QueryRunner) => Promise<void>,
) => Promise<Array<string>>;

const capturedQueries: CapturedQueriesFunction = async (
  run: (queryRunner: QueryRunner) => Promise<void>,
): Promise<Array<string>> => {
  const queries: Array<string> = [];
  const queryRunner: QueryRunner = {
    query: async (sql: string): Promise<void> => {
      queries.push(sql);
    },
  } as unknown as QueryRunner;

  await run(queryRunner);
  return queries;
};

type UpQueriesFunction = () => Promise<Array<string>>;

const upQueries: UpQueriesFunction = (): Promise<Array<string>> => {
  return capturedQueries(async (qr: QueryRunner): Promise<void> => {
    await new RestoreDroppedUniqueIndexes1786200000000().up(qr);
  });
};

describe("restored UNIQUE indexes", () => {
  describe("1. the entity declarations that keep them alive", () => {
    test.each(PINNED_INDEXES)(
      "%p declares %s by name",
      (model: ModelClass, indexName: string): void => {
        const found: IndexMetadataArgs | undefined =
          getMetadataArgsStorage().indices.find(
            (index: IndexMetadataArgs): boolean => {
              return index.target === model && index.name === indexName;
            },
          );

        expect(found).toBeDefined();
      },
    );

    test.each(PINNED_INDEXES)(
      "%p declares %s as UNIQUE and partial",
      (model: ModelClass, indexName: string): void => {
        /*
         * THE assertion. These are declared NATIVELY, not pinned with
         * synchronize:false, so the schema builder owns them and the drift
         * check actively polices them. For that to work the declaration has to
         * match the database: same name, same uniqueness, same columns.
         * dropOldIndices compares exactly those, and drops on any mismatch.
         */
        const found: IndexMetadataArgs | undefined =
          getMetadataArgsStorage().indices.find(
            (index: IndexMetadataArgs): boolean => {
              return index.target === model && index.name === indexName;
            },
          );

        expect(found?.unique).toBe(true);
        expect(found?.where).toBe('"deletedAt" IS NULL');
      },
    );

    test.each(PINNED_INDEXES)(
      "%p leaves %s under TypeORM's ownership",
      (model: ModelClass, indexName: string): void => {
        /*
         * The opposite of the Service LOWER(name) index, which MUST opt out
         * because @Index() cannot express an expression index. These nine can
         * all be expressed, so opting them out would only hide them from the
         * drift check for no benefit.
         */
        const found: IndexMetadataArgs | undefined =
          getMetadataArgsStorage().indices.find(
            (index: IndexMetadataArgs): boolean => {
              return index.target === model && index.name === indexName;
            },
          );

        expect(found?.synchronize).not.toBe(false);
      },
    );
  });

  describe("2. the migration's SQL contract", () => {
    test("creates all nine indexes and no others", async () => {
      const creates: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes("CREATE UNIQUE INDEX");
        },
      );

      expect(creates).toHaveLength(PINNED_INDEXES.length);

      for (const [, indexName] of PINNED_INDEXES) {
        expect(
          creates.some((sql: string): boolean => {
            return sql.includes(`"${indexName}"`);
          }),
        ).toBe(true);
      }
    });

    test("every index is UNIQUE — the lost guarantee is the point", async () => {
      const creates: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes("CREATE UNIQUE INDEX");
        },
      );

      for (const sql of creates) {
        expect(sql).toContain("CREATE UNIQUE INDEX");
      }
    });

    test("every index is partial on deletedAt IS NULL", async () => {
      /*
       * Matches how the app reads (DatabaseService adds deletedAt IS NULL to
       * every non-withDeleted query) and stops a soft-deleted row holding a
       * slug hostage forever.
       */
      const creates: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes("CREATE UNIQUE INDEX");
        },
      );

      for (const sql of creates) {
        expect(sql).toContain('WHERE "deletedAt" IS NULL');
      }
    });

    test("every index is idempotent", async () => {
      /*
       * An operator may build these by hand ahead of the deploy. IF NOT EXISTS
       * makes that a no-op rather than a failed migration.
       */
      const creates: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes("CREATE UNIQUE INDEX");
        },
      );

      for (const sql of creates) {
        expect(sql).toContain("IF NOT EXISTS");
      }
    });

    test("no index is created CONCURRENTLY", async () => {
      /*
       * migrationsTransactionMode defaults to "all", and CREATE INDEX
       * CONCURRENTLY cannot run inside a transaction block — it would abort
       * the entire migration run on boot.
       */
      for (const sql of await upQueries()) {
        expect(sql).not.toContain("CONCURRENTLY");
      }
    });

    test("every index is repaired BEFORE it is created", async () => {
      /*
       * A UNIQUE index cannot be built over existing duplicates. If a CREATE
       * ever preceded its repair, the migration would fail on real data and
       * block the deploy — which is the failure mode this ordering prevents.
       */
      const queries: Array<string> = await upQueries();

      for (const [, indexName, table] of PINNED_INDEXES) {
        const createAt: number = queries.findIndex((sql: string): boolean => {
          return sql.includes(`"${indexName}"`);
        });
        const repairAt: number = queries.findIndex((sql: string): boolean => {
          return sql.includes(`UPDATE "${table}"`);
        });

        expect(repairAt).toBeGreaterThan(-1);
        expect(createAt).toBeGreaterThan(repairAt);
      }
    });

    test("repairs are deterministic — oldest row always wins", async () => {
      const repairs: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes("ROW_NUMBER()");
        },
      );

      expect(repairs).toHaveLength(PINNED_INDEXES.length);

      for (const sql of repairs) {
        expect(sql).toContain('ORDER BY "createdAt" ASC, _id ASC');
        // Only the losers are touched.
        expect(sql).toContain("r.rn > 1");
      }
    });

    test("slug repair RENAMES and never deletes", async () => {
      /*
       * A slug collision must not cost the user a row. The losing row keeps
       * all its data and gets a discriminator appended.
       */
      const slugRepairs: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes('SET "slug"');
        },
      );

      expect(slugRepairs).toHaveLength(6);

      for (const sql of slugRepairs) {
        expect(sql).toContain("LEFT(t._id::text, 8)");
        expect(sql).not.toContain("DELETE");
      }
    });

    test("duplicate mapping rows are SOFT-deleted, never hard-deleted", async () => {
      /*
       * Soft-deleting takes the row out of a partial index without destroying
       * it and without touching any foreign key, so no cascade can fire.
       */
      const softDeletes: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes('SET "deletedAt" = CURRENT_TIMESTAMP');
        },
      );

      expect(softDeletes).toHaveLength(3);
    });

    test("the migration never hard-deletes anything", async () => {
      for (const sql of await upQueries()) {
        expect(sql).not.toContain("DELETE FROM");
      }
    });

    test("repairs only consider live rows", async () => {
      /*
       * The index is partial, so a soft-deleted duplicate is already outside
       * it and must not be "repaired".
       */
      const repairs: Array<string> = (await upQueries()).filter(
        (sql: string): boolean => {
          return sql.includes("ROW_NUMBER()");
        },
      );

      for (const sql of repairs) {
        expect(sql).toContain('WHERE "deletedAt" IS NULL');
      }
    });

    test("down() drops exactly the nine indexes up() created", async () => {
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreDroppedUniqueIndexes1786200000000().down(qr);
        },
      );

      expect(queries).toHaveLength(PINNED_INDEXES.length);

      for (const [, indexName] of PINNED_INDEXES) {
        expect(
          queries.some((sql: string): boolean => {
            return sql.includes("DROP INDEX") && sql.includes(indexName);
          }),
        ).toBe(true);
      }
    });

    test("down() does not attempt to un-repair data", async () => {
      /*
       * A renamed slug and a soft-deleted duplicate are indistinguishable
       * afterwards from ones the application produced. Guessing would corrupt
       * live data, so down() only reverses the schema.
       */
      const queries: Array<string> = await capturedQueries(
        async (qr: QueryRunner): Promise<void> => {
          await new RestoreDroppedUniqueIndexes1786200000000().down(qr);
        },
      );

      for (const sql of queries) {
        expect(sql).not.toContain("UPDATE");
      }
    });
  });

  describe("3. registration", () => {
    test("the migration is registered so it actually runs on boot", () => {
      expect(SchemaMigrations).toContain(
        RestoreDroppedUniqueIndexes1786200000000,
      );
    });

    test("it runs after every migration that dropped one of these indexes", () => {
      /*
       * Restoring before the drop would leave the database with no index
       * again. 1783937343400 is the migration that removed the NetworkDevice
       * and NetworkInterface indexes.
       */
      const names: Array<string> = SchemaMigrations.map(
        (migration: unknown): string => {
          return (migration as { name: string }).name;
        },
      );

      const restoreAt: number = names.indexOf(
        "RestoreDroppedUniqueIndexes1786200000000",
      );
      const dropperAt: number = names.indexOf("MigrationName1783937343400");

      expect(restoreAt).toBeGreaterThan(-1);
      expect(dropperAt).toBeGreaterThan(-1);
      expect(restoreAt).toBeGreaterThan(dropperAt);
    });
  });
});
