enum CopilotEventType {
  IMPROVE_COMMENTS = "IMPROVE_COMMENTS",
  FIX_GRAMMAR_AND_SPELLING = "FIX_GRAMMAR_AND_SPELLING",
  IMPROVE_VARIABLE_NAMES = "IMPROVE_VARIABLE_NAMES",
}

export default CopilotEventType;
