module.exports = {
    'Subscriber Incident Created': [
        '{{userName}} : User display name.',
        '{{monitorName}} : Name of the monitor on which incident has occured.',
        '{{projectName}} : Name of the project on which the incident has occured.',
        '{{incidentTime}} : Time at which this incident occured.',
        '{{incidentType}} : Type of incident.',
        '{{userId}} : Unique identifier for user account.',
        '{{projectId}} : Unique identifier for the current project.',
        "{{trackEmailAsViewedUrl}} : Include this in your email to track emails and know when they're opened.",
        '{{statusPageUrl}} : URL of the Status Page your subscriber can go to. ',
        '{{incident.customFields.*}} : The value of any incident custom field',
        '{{monitor.customFields.*}} : The value of any monitor custom field',
    ],
    'Subscriber Incident Acknowldeged': [
        '{{userName}} : User display name.',
        '{{monitorName}} : Name of the monitor on which incident has occured.',
        '{{projectName}} : Name of the project on which the incident has occured.',
        '{{incidentTime}} : Time at which this incident occured.',
        '{{incidentType}} : Type of incident.',
        '{{userId}} : Unique identifier for user account.',
        '{{projectId}} : Unique identifier for the current project.',
        "{{trackEmailAsViewedUrl}} : Include this in your email to track emails and know when they're opened.",
        '{{statusPageUrl}} : URL of the Status Page your subscriber can go to. ',
        '{{incident.customFields.*}} : The value of any incident custom field',
        '{{monitor.customFields.*}} : The value of any monitor custom field',
        '{{length}} : Length of the incident',
    ],
    'Subscriber Incident Resolved': [
        '{{userName}} : User display name.',
        '{{monitorName}} : Name of the monitor on which incident has occured.',
        '{{projectName}} : Name of the project on which the incident has occured.',
        '{{incidentTime}} : Time at which this incident occured.',
        '{{incidentType}} : Type of incident.',
        '{{userId}} : Unique identifier for user account.',
        '{{projectId}} : Unique identifier for the current project.',
        "{{trackEmailAsViewedUrl}} : Include this in your email to track emails and know when they're opened.",
        '{{statusPageUrl}} : URL of the Status Page your subscriber can go to. ',
        '{{incident.customFields.*}} : The value of any incident custom field',
        '{{monitor.customFields.*}} : The value of any monitor custom field',
        '{{length}} : Length of the incident',
    ],
    'Team Member Incident': [
        '{{ incidentTime }} : Time at which this incident occured.',
        '{{ monitorName }} : Name of the monitor on which incident has occured.',
        '{{ accessToken }} : unique key for authentication and authorization to fyipe API.',
        '{{ userName }} : User display name.',
        '{{ userId }} : Unique identifier for your account.',
        '{{ projectId }}: Unique identifier for the current project.',
        '{{ ack_url }} : Url to acknowledge monitor incidents.',
        '{{ resolve_url }} : Url to resolve monitor incidents.',
    ],
};
