#
# OneUptime-backend Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl


# Install python
RUN apk update && apk add --no-cache --virtual .gyp python3 make g++

#Use bash shell by default
SHELL ["/bin/bash", "-c"]
RUN npm install typescript -g
RUN npm install nodemon -g

RUN mkdir /usr/src

# Install common
RUN mkdir /usr/src/Common
WORKDIR /usr/src/Common
COPY ./Common/package*.json /usr/src/Common/
RUN npm install
COPY ./Common /usr/src/Common
RUN npm run compile

# Install CommonServer
RUN mkdir /usr/src/CommonServer
WORKDIR /usr/src/CommonServer
COPY ./CommonServer/package*.json /usr/src/CommonServer/
RUN npm install
COPY ./CommonServer /usr/src/CommonServer
RUN npm run compile

#SET ENV Variables

WORKDIR /usr/src/app

# Install trivy for container scanning
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin

# Install app dependencies
RUN cd /usr/src/app

RUN mkdir -p greenlock.d || echo "Directory already exists"

# Copy package.json files
COPY ./DashboardAPI/package.json /usr/src/app/package.json
COPY ./DashboardAPI/package-lock.json /usr/src/app/package-lock.json


RUN npm install

# Expose ports.
#   - 3002: OneUptime-backend
EXPOSE 3002
EXPOSE 9229

#Run the app
RUN npm run compile
CMD [ "npm", "run", "dev"]
