import { TerraformProviderConfig, OpenAPISpec } from "./Types";
import { FileGenerator } from "./FileGenerator";
import { StringUtils } from "./StringUtils";
import { OpenAPIParser } from "./OpenAPIParser";

export class DocumentationGenerator {
  private config: TerraformProviderConfig;
  private spec: OpenAPISpec;
  private fileGenerator: FileGenerator;

  constructor(config: TerraformProviderConfig, spec: OpenAPISpec) {
    this.config = config;
    this.spec = spec;
    this.fileGenerator = new FileGenerator(config.outputDir);
  }

  async generateDocumentation(): Promise<void> {
    await this.generateProviderDoc();
    await this.generateResourceDocs();
    await this.generateDataSourceDocs();
    await this.generateExamples();
    await this.generateReadme();
  }

  private async generateProviderDoc(): Promise<void> {
    const providerDoc = `---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "${this.config.providerName} Provider"
subcategory: ""
description: |-
  Terraform provider for ${StringUtils.capitalize(this.config.providerName)}.
---

# ${StringUtils.capitalize(this.config.providerName)} Provider

${this.spec.info.description || `Terraform provider for ${StringUtils.capitalize(this.config.providerName)}.`}

## Example Usage

\`\`\`terraform
terraform {
  required_providers {
    ${this.config.providerName} = {
      source = "oneuptime/${this.config.providerName}"
      version = "${this.config.providerVersion}"
    }
  }
}

provider "${this.config.providerName}" {
  host     = "oneuptime.com"  # Optional, defaults to oneuptime.com (internally becomes oneuptime.com/api)
  api_key  = var.${this.config.providerName}_api_key
}
\`\`\`

## Schema

### Optional

- \`host\` (String) The ${this.config.providerName} host (without /api path). Defaults to 'oneuptime.com' if not specified. The provider automatically appends '/api' to the host. Can also be set via the \`${StringUtils.toConstantCase(this.config.providerName)}_HOST\` environment variable.
- \`api_key\` (String, Sensitive) API key for authentication. Can also be set via the \`${StringUtils.toConstantCase(this.config.providerName)}_API_KEY\` environment variable.
`;

    await this.fileGenerator.writeFileInDir("docs", "index.md", providerDoc);
  }

  private async generateResourceDocs(): Promise<void> {
    // Create parser and get resources
    const parser = new OpenAPIParser();
    parser.setSpec(this.spec);
    const resources = parser.getResources();

    this.fileGenerator.ensureDirectory("docs/resources");

    for (const resource of resources) {
      const resourceDoc = this.generateResourceDoc(resource);
      await this.fileGenerator.writeFileInDir(
        "docs/resources",
        `${resource.name}.md`,
        resourceDoc,
      );
    }
  }

  private async generateDataSourceDocs(): Promise<void> {
    // Create parser and get data sources
    const parser = new OpenAPIParser();
    parser.setSpec(this.spec);
    const dataSources = parser.getDataSources();

    this.fileGenerator.ensureDirectory("docs/data-sources");

    for (const dataSource of dataSources) {
      const dataSourceDoc = this.generateDataSourceDoc(dataSource);
      await this.fileGenerator.writeFileInDir(
        "docs/data-sources",
        `${dataSource.name}.md`,
        dataSourceDoc,
      );
    }
  }

  private generateResourceDoc(resource: any): string {
    const resourceName = StringUtils.capitalize(
      resource.name.replace(/_/g, " "),
    );

    // Generate schema documentation
    const schemaItems: string[] = [];
    for (const [name, attr] of Object.entries(resource.schema)) {
      const attrInfo = attr as any;
      const required = attrInfo.required
        ? "Required"
        : attrInfo.computed
          ? "Computed"
          : "Optional";
      const sensitive = attrInfo.sensitive ? ", Sensitive" : "";
      schemaItems.push(
        `- \`${name}\` (${StringUtils.capitalize(attrInfo.type)}${sensitive}) ${attrInfo.description || `${resourceName} ${name}`}. ${required}.`,
      );
    }

    return `---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "${this.config.providerName}_${resource.name} Resource - ${this.config.providerName}"
subcategory: ""
description: |-
  ${resourceName} resource
---

# ${this.config.providerName}_${resource.name} (Resource)

${resourceName} resource

## Example Usage

\`\`\`terraform
resource "${this.config.providerName}_${resource.name}" "example" {
  name        = "example-${resource.name}"
  description = "Example ${resource.name}"
}
\`\`\`

## Schema

${schemaItems.join("\n")}

## Import

Import is supported using the following syntax:

\`\`\`shell
terraform import ${this.config.providerName}_${resource.name}.example <id>
\`\`\`
`;
  }

  private generateDataSourceDoc(dataSource: any): string {
    const dataSourceName = StringUtils.capitalize(
      dataSource.name.replace(/_/g, " "),
    );

    // Generate schema documentation
    const schemaItems: string[] = [];
    for (const [name, attr] of Object.entries(dataSource.schema)) {
      const attrInfo = attr as any;
      const required = attrInfo.required
        ? "Required"
        : attrInfo.computed
          ? "Computed"
          : "Optional";
      const sensitive = attrInfo.sensitive ? ", Sensitive" : "";
      schemaItems.push(
        `- \`${name}\` (${StringUtils.capitalize(attrInfo.type)}${sensitive}) ${attrInfo.description || `${dataSourceName} ${name}`}. ${required}.`,
      );
    }

    return `---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "${this.config.providerName}_${dataSource.name} Data Source - ${this.config.providerName}"
subcategory: ""
description: |-
  ${dataSourceName} data source
---

# ${this.config.providerName}_${dataSource.name} (Data Source)

${dataSourceName} data source

## Example Usage

\`\`\`terraform
data "${this.config.providerName}_${dataSource.name}" "example" {
  name = "example-${dataSource.name}"
}
\`\`\`

## Schema

${schemaItems.join("\n")}
`;
  }

  private async generateExamples(): Promise<void> {
    this.fileGenerator.ensureDirectory("examples");

    // Generate provider example
    const providerExample = `terraform {
  required_providers {
    ${this.config.providerName} = {
      source = "oneuptime/${this.config.providerName}"
      version = "${this.config.providerVersion}"
    }
  }
}

provider "${this.config.providerName}" {
  host    = "oneuptime.com"  # Optional, defaults to oneuptime.com (provider appends /api automatically)
  api_key = var.${this.config.providerName}_api_key
}

# Configure variables
variable "${this.config.providerName}_api_key" {
  description = "API key for ${this.config.providerName}"
  type        = string
  sensitive   = true
}
`;

    await this.fileGenerator.writeFileInDir(
      "examples",
      "provider.tf",
      providerExample,
    );

    // Generate resources example
    const parser = new OpenAPIParser();
    parser.setSpec(this.spec);
    const resources = parser.getResources();

    if (resources.length > 0) {
      const firstResource = resources[0];
      if (firstResource) {
        const resourceExample = `# Example usage of ${this.config.providerName}_${firstResource.name} resource
resource "${this.config.providerName}_${firstResource.name}" "example" {
  name        = "example-${firstResource.name}"
  description = "Example ${firstResource.name} created by Terraform"
}

# Output the resource ID
output "${firstResource.name}_id" {
  description = "ID of the created ${firstResource.name}"
  value       = ${this.config.providerName}_${firstResource.name}.example.id
}
`;

        await this.fileGenerator.writeFileInDir(
          "examples",
          "resources.tf",
          resourceExample,
        );
      }
    }

    // Generate data sources example
    const dataSources = parser.getDataSources();

    if (dataSources.length > 0) {
      const firstDataSource = dataSources[0];
      if (firstDataSource) {
        const dataSourceExample = `# Example usage of ${this.config.providerName}_${firstDataSource.name} data source
data "${this.config.providerName}_${firstDataSource.name}" "example" {
  name = "example-${firstDataSource.name}"
}

# Output the data source result
output "${firstDataSource.name}_result" {
  description = "Result of the ${firstDataSource.name} data source"
  value       = data.${this.config.providerName}_${firstDataSource.name}.example
}
`;

        await this.fileGenerator.writeFileInDir(
          "examples",
          "data-sources.tf",
          dataSourceExample,
        );
      }
    }
  }

  private async generateReadme(): Promise<void> {
    const readmeContent = `# Terraform Provider for ${StringUtils.capitalize(this.config.providerName)}

${this.spec.info.description || `Terraform provider for ${StringUtils.capitalize(this.config.providerName)}.`}

## Requirements

- [Terraform](https://www.terraform.io/downloads.html) >= 1.0
- [Go](https://golang.org/doc/install) >= 1.21

## Building The Provider

1. Clone the repository
\`\`\`sh
git clone https://github.com/oneuptime/terraform-provider-${this.config.providerName}
cd terraform-provider-${this.config.providerName}
\`\`\`

2. Build the provider using the Go \`install\` command:
\`\`\`sh
go build
\`\`\`

## Using the Provider

\`\`\`terraform
terraform {
  required_providers {
    ${this.config.providerName} = {
      source = "oneuptime/${this.config.providerName}"
      version = "${this.config.providerVersion}"
    }
  }
}

provider "${this.config.providerName}" {
  host    = "https://api.${this.config.providerName}.com"
  api_key = var.${this.config.providerName}_api_key
}
\`\`\`

## Developing the Provider

If you wish to work on the provider, you'll first need [Go](http://www.golang.org) installed on your machine (see [Requirements](#requirements) above).

To compile the provider, run \`go build\`. This will build the provider and put the provider binary in the current directory.

To generate or update documentation, run \`go generate\`.

In order to run the full suite of Acceptance tests, run \`make testacc\`.

*Note:* Acceptance tests create real resources, and often cost money to run.

\`\`\`sh
make testacc
\`\`\`

## Local Installation

To install the provider locally for testing:

\`\`\`sh
make install
\`\`\`

This will build and install the provider to your local Terraform plugins directory.

## Testing

To run unit tests:

\`\`\`sh
go test ./...
\`\`\`

To run acceptance tests:

\`\`\`sh
TF_ACC=1 go test ./... -v -timeout 120m
\`\`\`

## Documentation

Documentation is generated using [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs). Run the following command to generate documentation:

\`\`\`sh
go generate
\`\`\`

## Contributing

1. Fork the repository
2. Create your feature branch (\`git checkout -b feature/amazing-feature\`)
3. Commit your changes (\`git commit -am 'Add some amazing feature'\`)
4. Push to the branch (\`git push origin feature/amazing-feature\`)
5. Open a Pull Request

## License

This project is licensed under the Apache 2.0 License - see the [LICENSE](LICENSE) file for details.
`;

    await this.fileGenerator.writeFile("README.md", readmeContent);
  }
}
