/*
 * Per-resource-type "how to send telemetry" markdown for the in-app
 * Documentation tab. Each builder receives the project's OneUptime URL and
 * the selected ingestion key so the snippets are copy-paste ready.
 */
export interface DocVars {
  oneuptimeUrl: string;
  apiKey: string;
}

export const getServerlessDocMarkdown: (vars: DocVars) => string = (
  vars: DocVars,
): string => {
  return [
    "## Send telemetry from your serverless functions",
    "",
    "OneUptime auto-discovers a **Serverless Function** as soon as it receives",
    "telemetry tagged with the `faas.name` resource attribute. Instrument your",
    "function with the OpenTelemetry SDK for your runtime and export OTLP to",
    "OneUptime.",
    "",
    "### 1. Set resource attributes",
    "",
    "| Attribute | Required | Example |",
    "| --- | --- | --- |",
    "| `faas.name` | yes | `checkout-handler` |",
    "| `faas.version` | no | `1.4.2` |",
    "| `faas.instance` | no | per-instance id (shows under Instances) |",
    "| `cloud.platform` | no | `aws_lambda`, `gcp_cloud_functions`, `azure_functions` |",
    "| `cloud.region` | no | `us-east-1` |",
    "",
    "### 2. Point the OTLP exporter at OneUptime",
    "",
    "Most language auto-instrumentations read these environment variables:",
    "",
    "> **This token is a secret.** Use a **Server** ingestion key here and set it",
    "> as a function environment variable. A key that reaches a browser can be",
    "> read by anyone who views the page source; for anything running in a",
    "> browser, create a **Browser** ingestion key instead.",
    "",
    "```bash",
    `OTEL_EXPORTER_OTLP_ENDPOINT="${vars.oneuptimeUrl}/otlp"`,
    `OTEL_EXPORTER_OTLP_HEADERS="x-oneuptime-token=${vars.apiKey}"`,
    `OTEL_RESOURCE_ATTRIBUTES="faas.name=checkout-handler,faas.version=1.4.2"`,
    "```",
    "",
    "### 3. Deploy",
    "",
    "Once the function emits a span, log or metric it appears under **Serverless",
    "Functions**. The overview shows invocations, error rate and p95 duration",
    "derived from your traces.",
  ].join("\n");
};

export const getCloudDocMarkdown: (vars: DocVars) => string = (
  vars: DocVars,
): string => {
  return [
    "## Connect a managed cloud environment",
    "",
    "OneUptime groups managed compute (AWS ECS / Fargate, Google Cloud Run,",
    "Azure Container Apps, Elastic Beanstalk, App Runner, ...) into a **Cloud",
    "Environment** — one per `cloud.platform` + `cloud.account.id` +",
    "`cloud.region`.",
    "",
    "### 1. Enable the cloud resource detector",
    "",
    "OpenTelemetry SDKs and the Collector ship resource detectors that fill in",
    "`cloud.platform`, `cloud.account.id` and `cloud.region` automatically:",
    "",
    "- AWS ECS / Fargate: `OTEL_RESOURCE_DETECTORS=env,ecs` (or the Collector",
    "  `resourcedetection` processor with `detectors: [ecs]`)",
    "- Google Cloud Run: `detectors: [gcp]`",
    "- Azure Container Apps: `detectors: [azure]`",
    "",
    "### 2. Export OTLP to OneUptime",
    "",
    "> **This token is a secret.** A collector runs on your own infrastructure, so",
    "> use a **Server** ingestion key here. Never put one in browser JavaScript —",
    "> a **Browser** ingestion key exists for that, and is restricted to the",
    "> origins you list on it.",
    "",
    "```yaml",
    "exporters:",
    "  otlphttp/oneuptime:",
    `    endpoint: ${vars.oneuptimeUrl}/otlp`,
    "    headers:",
    `      x-oneuptime-token: ${vars.apiKey}`,
    "```",
    "",
    "### 3. View",
    "",
    "Workloads running on this environment show up grouped here. The overview",
    "shows CPU and memory per task (from container metrics) and request volume",
    "from your traces.",
  ].join("\n");
};

export const getRumDocMarkdown: (vars: DocVars) => string = (
  vars: DocVars,
): string => {
  return [
    "## Instrument a browser or mobile app",
    "",
    "OneUptime classifies telemetry as **RUM** when its resource carries client",
    "attributes — `browser.platform` / `browser.language` / `browser.brands` for",
    "web, or `device.id` / `device.model.identifier` / `device.manufacturer` for",
    "mobile. The application is identified by `service.name`, and its telemetry is",
    "owned by this RUM application (it is never duplicated as a backend Service).",
    "",
    "> **Setting `service.name` alone is not enough.** The OpenTelemetry browser",
    "> SDKs do not add `browser.*` attributes unless you enable the browser",
    "> resource detector or set them yourself — without them this becomes a",
    "> backend Service, not a RUM application.",
    "",
    "### Use a Browser ingestion key",
    "",
    "Everything in the browser section below ships to your users. The token in it",
    "is public — anyone who views source, opens devtools or reads your bundle can",
    "copy it. Create the key as a **Browser** key in **Settings > Telemetry",
    "Ingestion Keys** and list the origins your site is served from:",
    "",
    "- it is accepted only from those origins, so a copied key does not work from",
    "  anyone else's page;",
    "- it can only write traces, logs, metrics and session replays — not profiles,",
    "  source maps, syslog, Fluent, Pyroscope or security events;",
    "- it is rate limited per key, can be switched off in one edit, and can be",
    "  given an expiry.",
    "",
    "> **Never ship a Server ingestion key to a browser.** A Server key has full",
    "> ingest access from anywhere, with no origin check. Once it is in page",
    "> source, anyone who finds it can write forged spans, logs and metrics into",
    "> this project — poisoning dashboards, firing false alerts and running up your",
    "> metered usage — until you notice and rotate it.",
    "",
    "### Browser (OpenTelemetry Web)",
    "",
    "```bash",
    "npm install @opentelemetry/sdk-trace-web @opentelemetry/resources \\",
    "  @opentelemetry/semantic-conventions @opentelemetry/context-zone \\",
    "  @opentelemetry/opentelemetry-browser-detector \\",
    "  @opentelemetry/exporter-trace-otlp-http @opentelemetry/instrumentation \\",
    "  @opentelemetry/instrumentation-document-load \\",
    "  @opentelemetry/instrumentation-fetch",
    "```",
    "",
    "Create `src/telemetry.ts` and import it as the **first** import of your app:",
    "",
    "```ts",
    'import { WebTracerProvider, BatchSpanProcessor } from "@opentelemetry/sdk-trace-web";',
    'import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";',
    'import { ZoneContextManager } from "@opentelemetry/context-zone";',
    'import { registerInstrumentations } from "@opentelemetry/instrumentation";',
    'import { DocumentLoadInstrumentation } from "@opentelemetry/instrumentation-document-load";',
    'import { FetchInstrumentation } from "@opentelemetry/instrumentation-fetch";',
    'import { defaultResource, detectResources, resourceFromAttributes } from "@opentelemetry/resources";',
    'import { browserDetector } from "@opentelemetry/opentelemetry-browser-detector";',
    'import { ATTR_SERVICE_NAME } from "@opentelemetry/semantic-conventions";',
    "",
    "// browserDetector supplies the browser.* attributes that make this RUM.",
    "const resource = defaultResource()",
    "  .merge(detectResources({ detectors: [browserDetector] }))",
    "  .merge(",
    "    resourceFromAttributes({",
    '      [ATTR_SERVICE_NAME]: "storefront-web",',
    "    }),",
    "  );",
    "",
    "const provider = new WebTracerProvider({",
    "  resource: resource,",
    "  spanProcessors: [",
    "    new BatchSpanProcessor(",
    "      new OTLPTraceExporter({",
    `        url: "${vars.oneuptimeUrl}/otlp/v1/traces",`,
    "        // This value is public. It must be a Browser ingestion key,",
    "        // never a Server one.",
    `        headers: { "x-oneuptime-token": "${vars.apiKey}" },`,
    "      }),",
    "    ),",
    "  ],",
    "});",
    "",
    "provider.register({ contextManager: new ZoneContextManager() });",
    "",
    "registerInstrumentations({",
    "  instrumentations: [",
    "    new DocumentLoadInstrumentation(),",
    "    // List only origins whose API allows the traceparent header.",
    "    new FetchInstrumentation({",
    "      propagateTraceHeaderCorsUrls: [/^https:\\/\\/api\\.example\\.com/],",
    "    }),",
    "  ],",
    "});",
    "```",
    "",
    "If your site sends a Content Security Policy, allow the exporter or it will",
    "fail silently:",
    "",
    "```",
    `connect-src 'self' ${vars.oneuptimeUrl};`,
    "```",
    "",
    "### Mobile (Swift / Android)",
    "",
    "Use the OpenTelemetry Swift or Android SDK, set `service.name`, and export",
    "OTLP to OneUptime:",
    "",
    "> **Mobile needs a Server key, and a mobile bundle can be unpacked.** A",
    "> Browser key is enforced against the `Origin` header, which a mobile SDK",
    "> does not send, so it cannot be used here. Assume the token shipped in your",
    "> app will be extracted, and use the controls that do apply: pin a service",
    "> name on the key so extracted copies cannot forge backend telemetry, set a",
    "> requests-per-minute limit and an expiry, and rotate the key with each",
    "> release train.",
    "",
    "```bash",
    `OTEL_EXPORTER_OTLP_ENDPOINT="${vars.oneuptimeUrl}/otlp"`,
    `OTEL_EXPORTER_OTLP_HEADERS="x-oneuptime-token=${vars.apiKey}"`,
    'OTEL_RESOURCE_ATTRIBUTES="service.name=storefront-mobile,device.manufacturer=Acme,device.model.identifier=AC-100"',
    "```",
    "",
    "Most mobile SDKs set the `device.*` attributes for you — verify it, and set",
    "them explicitly as above if the application is filed under Services instead.",
    "",
    "### Verify the token",
    "",
    "```bash",
    `curl -i ${vars.oneuptimeUrl}/otlp/v1/validate \\`,
    `  -H "x-oneuptime-token: ${vars.apiKey}"`,
    "```",
    "",
    "Once events arrive, the app appears under **RUM** with page views, error rate",
    "and p95 duration. Full guides: [Browser Setup](/docs/rum/browser-setup),",
    "[Mobile Setup](/docs/rum/mobile-setup), [Core Web Vitals](/docs/rum/web-vitals)",
    "and [Troubleshooting](/docs/rum/troubleshooting).",
  ].join("\n");
};
