# Use a Node.js LTS (Long Term Support) version as the base image
FROM node:18.13.0-alpine

# Set the working directory inside the container to /app
WORKDIR /app

# Copy your server's package.json and package-lock.json files into the container
COPY ./Playwright/package*.json /usr/src/app/

# Install the server's dependencies inside the container
RUN npm install

# Copy the rest of your server's files into the container
COPY . .

EXPOSE 1444

# Start the server inside the container
CMD [ "npm", "run", "dev" ]
