#
# container-scanner Dockerfile
#

# Pull base image nodejs image.
FROM node:lts-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

# Install common-server
RUN mkdir /usr/src
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm ci --only=production
COPY ./common-server /usr/src/common-server

WORKDIR /usr/src/app

# Install app dependencies
RUN cd /usr/src/app

# Copy package.json files
COPY ./container-scanner/package.json /usr/src/app/package.json
COPY ./container-scanner/package-lock.json /usr/src/app/package-lock.json

RUN npm ci

# Expose ports.
#   - 3055: Container Scanner
EXPOSE 3055

#Run the app
CMD [ "npm", "run", "dev"]

