import { JSONObject } from "../../../Types/JSON";

/*
 * Huntress webhook bodies in the shapes Huntress documents
 * (https://api.huntress.io/v1/webhooks_doc.json, read 2026-10-09):
 *
 *   - IncidentReportPayload, for incident_report.created, .closed and
 *     .comment_added (which adds "comment"): account {id, name}, api_url,
 *     body, closed_at, created_at, event_type, id, indicator_counts,
 *     organization {id, name}, platform, sent_at, severity, status,
 *     status_updated_at, subject, summary, updated_at - plus the deprecated
 *     account_id and organization_id, and agent_id;
 *   - EscalationPayload, for escalation.* and platform_action.*;
 *   - OneTimeNotificationPayload, for account_notice.notification and
 *     platform_action.notification.
 *
 * Values follow the examples in Huntress's REST API reference (subject
 * "LOW - Incident on laptop01 (Test)") and the subject format in its
 * support article on parsing incident alerts ("CRITICAL - Incident on
 * DESKTOP-ARL0EQ1 (My Organization)", "CRITICAL - ISOLATED - Incident on
 * ..."). Shared by every Huntress suite, so they all read the same reports.
 */

export const HUNTRESS_ACCOUNT_ID: number = 5;
export const HUNTRESS_ORGANIZATION_ID: number = 4;
export const HUNTRESS_REPORT_ID: number = 1234;

export function getHuntressIncidentReportBody(
  overrides: JSONObject = {},
): JSONObject {
  return {
    event_type: "incident_report.created",
    id: HUNTRESS_REPORT_ID,
    account: { id: HUNTRESS_ACCOUNT_ID, name: "Example MSP" },
    account_id: HUNTRESS_ACCOUNT_ID,
    organization: { id: HUNTRESS_ORGANIZATION_ID, name: "Acme Corp" },
    organization_id: HUNTRESS_ORGANIZATION_ID,
    agent_id: 12,
    api_url: `https://api.huntress.io/v1/incident_reports/${HUNTRESS_REPORT_ID}`,
    body: "<p>Autogenerated report content.</p>",
    closed_at: null,
    created_at: "2026-10-09T03:00:00Z",
    sent_at: "2026-10-09T03:05:00Z",
    status_updated_at: "2026-10-09T03:05:00Z",
    updated_at: "2026-10-09T03:05:00Z",
    indicator_counts: {
      footholds: 1,
      monitored_files: 0,
      process_detections: 2,
      ransomware_canaries: 0,
      antivirus_detections: 0,
    },
    platform: "windows",
    severity: "critical",
    status: "sent",
    subject: "CRITICAL - Incident on DESKTOP-ARL0EQ1 (Acme Corp)",
    summary:
      "Huntress detected a malicious scheduled task on this host. We recommend removing the file and scheduled task listed in the remediation steps below.",
    ...overrides,
  };
}

export function getHuntressClosedBody(overrides: JSONObject = {}): JSONObject {
  return getHuntressIncidentReportBody({
    event_type: "incident_report.closed",
    status: "closed",
    closed_at: "2026-10-09T05:00:00Z",
    status_updated_at: "2026-10-09T05:00:00Z",
    ...overrides,
  });
}

export function getHuntressCommentBody(
  comment: string,
  overrides: JSONObject = {},
): JSONObject {
  return getHuntressIncidentReportBody({
    event_type: "incident_report.comment_added",
    comment,
    ...overrides,
  });
}

// An identity (ITDR) report: the subject names a user, not a host.
export function getHuntressIdentityReportBody(
  overrides: JSONObject = {},
): JSONObject {
  return getHuntressIncidentReportBody({
    id: 5678,
    platform: "microsoft_365",
    severity: "high",
    subject: "HIGH - Incident on jane.doe@acme.example (Acme Corp)",
    summary: "A sign-in from a known bad IP was followed by a new inbox rule.",
    indicator_counts: { managed_identity: 1 },
    ...overrides,
  });
}

export function getHuntressEscalationBody(
  eventType: string = "escalation.created",
): JSONObject {
  return {
    event_type: eventType,
    id: 84938,
    account: { id: HUNTRESS_ACCOUNT_ID, name: "Example MSP" },
    api_url: "https://api.huntress.io/v1/escalations/84938",
    created_at: "2026-10-09T03:00:00Z",
    updated_at: "2026-10-09T03:00:00Z",
    resolved_at: null,
    organizations: [{ id: HUNTRESS_ORGANIZATION_ID, name: "Acme Corp" }],
    total_organizations_impacted: 1,
    severity: "high",
    status: "open",
    subject: "Defender Disabled",
    type: "Environmental Issue",
  };
}

export function getHuntressAccountNoticeBody(): JSONObject {
  return {
    event_type: "account_notice.notification",
    id: 99,
    account: { id: HUNTRESS_ACCOUNT_ID, name: "Example MSP" },
    body: "Scheduled maintenance this weekend.",
    created_at: "2026-10-09T03:00:00Z",
    subject: "Account notice",
  };
}
