// Admin Project Note
export const ADD_PROJECT_NOTE_REQUEST = 'ADD_PROJECT_NOTE_REQUEST';
export const ADD_PROJECT_NOTE_RESET = 'ADD_PROJECT_NOTE_RESET';
export const ADD_PROJECT_NOTE_SUCCESS = 'ADD_PROJECT_NOTE_SUCCESS';
export const ADD_PROJECT_NOTE_FAILURE = 'ADD_PROJECT_NOTE_FAILURE';