// Fetch All Audit Log List
export const FETCH_AUDITLOGS_REQUEST = 'FETCH_AUDITLOGS_REQUEST';
export const FETCH_AUDITLOGS_SUCCESS = 'FETCH_AUDITLOGS_SUCCESS';
export const FETCH_AUDITLOGS_FAILURE = 'FETCH_AUDITLOGS_FAILURE';

// Search Audit Logs
export const SEARCH_AUDITLOGS_REQUEST = 'SEARCH_AUDITLOGS_REQUEST';
export const SEARCH_AUDITLOGS_SUCCESS = 'SEARCH_AUDITLOGS_SUCCESS';
export const SEARCH_AUDITLOGS_FAILURE = 'SEARCH_AUDITLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_AUDITLOGS_REQUEST = 'DELETE_ALL_AUDITLOGS_REQUEST';
export const DELETE_ALL_AUDITLOGS_SUCCESS = 'DELETE_ALL_AUDITLOGS_SUCCESS';
export const DELETE_ALL_AUDITLOGS_FAILURE = 'DELETE_ALL_AUDITLOGS_FAILURE';

// Fetch audit log status
export const FETCH_AUDITLOG_STATUS_SUCCESS = 'FETCH_AUDITLOG_STATUS_SUCCESS';
export const FETCH_AUDITLOG_STATUS_FAILED = 'FETCH_AUDITLOG_STATUS_FAILED';
export const FETCH_AUDITLOG_STATUS_REQUEST = 'FETCH_AUDITLOG_STATUS_REQUEST';
export const FETCH_AUDITLOG_STATUS_RESET = 'FETCH_AUDITLOG_STATUS_RESET';

// change audit log status
export const CHANGE_AUDITLOG_STATUS_SUCCESS = 'CHANGE_AUDITLOG_STATUS_SUCCESS';
export const CHANGE_AUDITLOG_STATUS_FAILED = 'CHANGE_AUDITLOG_STATUS_FAILED';
export const CHANGE_AUDITLOG_STATUS_REQUEST = 'CHANGE_AUDITLOG_STATUS_REQUEST';
export const CHANGE_AUDITLOG_STATUS_RESET = 'CHANGE_AUDITLOG_STATUS_RESET';
