// Fetch All Audit Log List
export const FETCH_AUDITLOGS_REQUEST = 'FETCH_AUDITLOGS_REQUEST';
export const FETCH_AUDITLOGS_SUCCESS = 'FETCH_AUDITLOGS_SUCCESS';
export const FETCH_AUDITLOGS_FAILURE = 'FETCH_AUDITLOGS_FAILURE';

// Search Audit Logs
export const SEARCH_AUDITLOGS_REQUEST = 'SEARCH_AUDITLOGS_REQUEST';
export const SEARCH_AUDITLOGS_SUCCESS = 'SEARCH_AUDITLOGS_SUCCESS';
export const SEARCH_AUDITLOGS_FAILURE = 'SEARCH_AUDITLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_AUDITLOGS_REQUEST = 'DELETE_ALL_AUDITLOGS_REQUEST';
export const DELETE_ALL_AUDITLOGS_SUCCESS = 'DELETE_ALL_AUDITLOGS_SUCCESS';
export const DELETE_ALL_AUDITLOGS_FAILURE = 'DELETE_ALL_AUDITLOGS_FAILURE';
