// Fetch All Call Log List
export const FETCH_CALLLOGS_REQUEST = 'FETCH_CALLLOGS_REQUEST';
export const FETCH_CALLLOGS_SUCCESS = 'FETCH_CALLLOGS_SUCCESS';
export const FETCH_CALLLOGS_FAILURE = 'FETCH_CALLLOGS_FAILURE';

// Search Call Logs
export const SEARCH_CALLLOGS_REQUEST = 'SEARCH_CALLLOGS_REQUEST';
export const SEARCH_CALLLOGS_SUCCESS = 'SEARCH_CALLLOGS_SUCCESS';
export const SEARCH_CALLLOGS_FAILURE = 'SEARCH_CALLLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_CALLLOGS_REQUEST = 'DELETE_ALL_CALLLOGS_REQUEST';
export const DELETE_ALL_CALLLOGS_SUCCESS = 'DELETE_ALL_CALLLOGS_SUCCESS';
export const DELETE_ALL_CALLLOGS_FAILURE = 'DELETE_ALL_CALLLOGS_FAILURE';

// Fetch call log status
export const FETCH_CALLLOG_STATUS_SUCCESS = 'FETCH_CALLLOG_STATUS_SUCCESS';
export const FETCH_CALLLOG_STATUS_FAILED = 'FETCH_CALLLOG_STATUS_FAILED';
export const FETCH_CALLLOG_STATUS_REQUEST = 'FETCH_CALLLOG_STATUS_REQUEST';
export const FETCH_CALLLOG_STATUS_RESET = 'FETCH_CALLLOG_STATUS_RESET';

// change call log status
export const CHANGE_CALLLOG_STATUS_SUCCESS = 'CHANGE_CALLLOG_STATUS_SUCCESS';
export const CHANGE_CALLLOG_STATUS_FAILED = 'CHANGE_CALLLOG_STATUS_FAILED';
export const CHANGE_CALLLOG_STATUS_REQUEST = 'CHANGE_CALLLOG_STATUS_REQUEST';
export const CHANGE_CALLLOG_STATUS_RESET = 'CHANGE_CALLLOG_STATUS_RESET';
