export const DASHBOARD_LOAD_SUCCESS = 'dashboard/DASHBOARD_LOAD_SUCCESS';
export const DASHBOARD_LOAD_REQUEST = 'dashboard/DASHBOARD_LOAD_REQUEST';
export const DASHBOARD_LOAD_RESET = 'dashboard/DASHBOARD_LOAD_RESET';
export const DASHBOARD_LOAD_FAILED = 'dashboard/DASHBOARD_LOAD_FAILED';
