// Fetch All Email Log List
export const FETCH_EMAILLOGS_REQUEST = 'FETCH_EMAILLOGS_REQUEST';
export const FETCH_EMAILLOGS_SUCCESS = 'FETCH_EMAILLOGS_SUCCESS';
export const FETCH_EMAILLOGS_FAILURE = 'FETCH_EMAILLOGS_FAILURE';

// Search Email Logs
export const SEARCH_EMAILLOGS_REQUEST = 'SEARCH_EMAILLOGS_REQUEST';
export const SEARCH_EMAILLOGS_SUCCESS = 'SEARCH_EMAILLOGS_SUCCESS';
export const SEARCH_EMAILLOGS_FAILURE = 'SEARCH_EMAILLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_EMAILLOGS_REQUEST = 'DELETE_ALL_EMAILLOGS_REQUEST';
export const DELETE_ALL_EMAILLOGS_SUCCESS = 'DELETE_ALL_EMAILLOGS_SUCCESS';
export const DELETE_ALL_EMAILLOGS_FAILURE = 'DELETE_ALL_EMAILLOGS_FAILURE';

// Fetch Email log status
export const FETCH_EMAILLOG_STATUS_SUCCESS = 'FETCH_EMAILLOG_STATUS_SUCCESS';
export const FETCH_EMAILLOG_STATUS_FAILED = 'FETCH_EMAILLOG_STATUS_FAILED';
export const FETCH_EMAILLOG_STATUS_REQUEST = 'FETCH_EMAILLOG_STATUS_REQUEST';
export const FETCH_EMAILLOG_STATUS_RESET = 'FETCH_EMAILLOG_STATUS_RESET';

// change Email log status
export const CHANGE_EMAILLOG_STATUS_SUCCESS = 'CHANGE_EMAILLOG_STATUS_SUCCESS';
export const CHANGE_EMAILLOG_STATUS_FAILED = 'CHANGE_EMAILLOG_STATUS_FAILED';
export const CHANGE_EMAILLOG_STATUS_REQUEST = 'CHANGE_EMAILLOG_STATUS_REQUEST';
export const CHANGE_EMAILLOG_STATUS_RESET = 'CHANGE_EMAILLOG_STATUS_RESET';
