export const OPEN_FEEDBACK_MODAL = 'OPEN_FEEDBACK_MODAL';
export const CLOSE_FEEDBACK_MODAL = 'CLOSE_FEEDBACK_MODAL';
// Create new project

export const CREATE_FEEDBACK_SUCCESS = 'feedback/CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_FAILED = 'feedback/CREATE_FEEDBACK_FAILED';
export const CREATE_FEEDBACK_REQUEST = 'feedback/CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_RESET = 'feedback/CREATE_FEEDBACK_RESET';