export const FETCH_LICENSE_SUCCESS = 'FETCH_LICENSE_SUCCESS';
export const FETCH_LICENSE_FAILED = 'FETCH_LICENSE_FAILED';
export const FETCH_LICENSE_REQUEST = 'FETCH_LICENSE_REQUEST';
export const FETCH_LICENSE_RESET = 'FETCH_LICENSE_RESET';

export const CONFIRM_LICENSE_SUCCESS = 'CONFIRM_LICENSE_SUCCESS';
export const CONFIRM_LICENSE_FAILED = 'CONFIRM_LICENSE_FAILED';
export const CONFIRM_LICENSE_REQUEST = 'CONFIRM_LICENSE_REQUEST';
export const CONFIRM_LICENSE_RESET = 'CONFIRM_LICENSE_RESET';
