export const OPEN_NOTIFICATION_MENU = 'OPEN_NOTIFICATION_MENU';
export const CLOSE_NOTIFICATION_MENU = 'CLOSE_NOTIFICATION_MENU';

// Create a new project

export const FETCH_NOTIFICATIONS_SUCCESS =
    'feedback/FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILED = 'feedback/FETCH_NOTIFICATIONS_FAILED';
export const FETCH_NOTIFICATIONS_REQUEST =
    'feedback/FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_RESET = 'feedback/FETCH_NOTIFICATIONS_RESET';
export const NOTIFICATION_READ_SUCCESS = 'feedback/NOTIFICATION_READ_SUCCESS';
