
//Update profile setting
export const UPDATE_PROFILE_SETTING_REQUEST = 'UPDATE_PROFILE_SETTING_REQUEST';
export const UPDATE_PROFILE_SETTING_SUCCESS = 'UPDATE_PROFILE_SETTING_SUCCESS';
export const UPDATE_PROFILE_SETTING_FAILURE = 'UPDATE_PROFILE_SETTING_FAILURE';
export const UPDATE_PROFILE_SETTING_RESET = 'UPDATE_PROFILE_SETTING_RESET';

//Update on cal alert setting.
export const UPDATE_ON_CALL_ALERT_SETTING_REQUEST = 'UPDATE_ON_CALL_ALERT_SETTING_REQUEST';
export const UPDATE_ON_CALL_ALERT_SETTING_SUCCESS = 'UPDATE_ON_CALL_ALERT_SETTING_SUCCESS';
export const UPDATE_ON_CALL_ALERT_SETTING_FAILURE = 'UPDATE_ON_CALL_ALERT_SETTING_FAILURE';
export const UPDATE_ON_CALL_ALERT_SETTING_RESET = 'UPDATE_ON_CALL_ALERT_SETTING_RESET';


//Update change password setting.
export const UPDATE_CHANGE_PASSWORD_SETTING_REQUEST = 'UPDATE_CHANGE_PASSWORD_SETTING_REQUEST';
export const UPDATE_CHANGE_PASSWORD_SETTING_SUCCESS = 'UPDATE_CHANGE_PASSWORD_SETTING_SUCCESS';
export const UPDATE_CHANGE_PASSWORD_SETTING_FAILURE = 'UPDATE_CHANGE_PASSWORD_SETTING_FAILURE';
export const UPDATE_CHANGE_PASSWORD_SETTING_RESET = 'UPDATE_CHANGE_PASSWORD_SETTING_RESET';

export const SHOW_PROFILE_MENU = 'SHOW_PROFILE_MENU';
export const HIDE_PROFILE_MENU = 'HIDE_PROFILE_MENU';

// Get Previous User Settings.
export const USER_SETTINGS_REQUEST = 'USER_SETTINGS_REQUEST';
export const USER_SETTINGS_SUCCESS = 'USER_SETTINGS_SUCCESS';
export const USER_SETTINGS_FAILURE = 'USER_SETTINGS_FAILURE';
export const USER_SETTINGS_RESET = 'USER_SETTINGS_RESET';