// Fetch All Projects List
export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
export const FETCH_PROJECTS_RESET = 'FETCH_PROJECTS_RESET';

// Fetch A Project
export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';
export const FETCH_PROJECT_RESET = 'FETCH_PROJECT_RESET';

// Fetch User Projects
export const FETCH_USER_PROJECTS_REQUEST = 'FETCH_USER_PROJECTS_REQUEST';
export const FETCH_USER_PROJECTS_SUCCESS = 'FETCH_USER_PROJECTS_SUCCESS';
export const FETCH_USER_PROJECTS_FAILURE = 'FETCH_USER_PROJECTS_FAILURE';
export const FETCH_USER_PROJECTS_RESET = 'FETCH_USER_PROJECTS_RESET';

// Delete Project
export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_RESET = 'DELETE_PROJECT_RESET';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

// Block Project
export const BLOCK_PROJECT_REQUEST = 'BLOCK_PROJECT_REQUEST';
export const BLOCK_PROJECT_RESET = 'BLOCK_PROJECT_RESET';
export const BLOCK_PROJECT_SUCCESS = 'BLOCK_PROJECT_SUCCESS';
export const BLOCK_PROJECT_FAILED = 'BLOCK_PROJECT_FAILED';

// Restore Alert Limit
export const ALERT_LIMIT_REQUEST = 'ALERT_LIMIT_REQUEST';
export const ALERT_LIMIT_RESET = 'ALERT_LIMIT_RESET';
export const ALERT_LIMIT_SUCCESS = 'ALERT_LIMIT_SUCCESS';
export const ALERT_LIMIT_FAILED = 'ALERT_LIMIT_FAILED';

// Restore Project
export const RESTORE_PROJECT_REQUEST = 'RESTORE_PROJECT_REQUEST';
export const RESTORE_PROJECT_RESET = 'RESTORE_PROJECT_RESET';
export const RESTORE_PROJECT_SUCCESS = 'RESTORE_PROJECT_SUCCESS';
export const RESTORE_PROJECT_FAILED = 'RESTORE_PROJECT_FAILED';

// Unblock Project
export const UNBLOCK_PROJECT_REQUEST = 'UNBLOCK_PROJECT_REQUEST';
export const UNBLOCK_PROJECT_RESET = 'UNBLOCK_PROJECT_RESET';
export const UNBLOCK_PROJECT_SUCCESS = 'UNBLOCK_PROJECT_SUCCESS';
export const UNBLOCK_PROJECT_FAILED = 'UNBLOCK_PROJECT_FAILED';

// Admin Project Note
export const ADD_PROJECT_NOTE_REQUEST = 'ADD_PROJECT_NOTE_REQUEST';
export const ADD_PROJECT_NOTE_RESET = 'ADD_PROJECT_NOTE_RESET';
export const ADD_PROJECT_NOTE_SUCCESS = 'ADD_PROJECT_NOTE_SUCCESS';
export const ADD_PROJECT_NOTE_FAILURE = 'ADD_PROJECT_NOTE_FAILURE';

// Search Users
export const SEARCH_PROJECTS_REQUEST = 'SEARCH_PROJECTS_REQUEST';
export const SEARCH_PROJECTS_RESET = 'SEARCH_PROJECTS_RESET';
export const SEARCH_PROJECTS_SUCCESS = 'SEARCH_PROJECTS_SUCCESS';
export const SEARCH_PROJECTS_FAILURE = 'SEARCH_PROJECTS_FAILURE';

// Upgrade Project
export const CHANGE_PLAN_REQUEST = 'CHANGE_PLAN_REQUEST';
export const CHANGE_PLAN_SUCCESS = 'CHANGE_PLAN_SUCCESS';
export const CHANGE_PLAN_FAILURE = 'CHANGE_PLAN_FAILURE';

// fetch project team
export const FETCH_PROJECT_TEAM_REQUEST = 'FETCH_PROJECT_TEAM_REQUEST';
export const FETCH_PROJECT_TEAM_SUCCESS = 'FETCH_PROJECT_TEAM_SUCCESS';
export const FETCH_PROJECT_TEAM_ERROR = 'FETCH_PROJECT_TEAM_ERROR';

// add user to project
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';

//update user role
export const USER_UPDATE_ROLE_REQUEST = 'USER_UPDATE_ROLE_REQUEST';
export const USER_UPDATE_ROLE_SUCCESS = 'USER_UPDATE_ROLE_SUCCESS';
export const USER_UPDATE_ROLE_FAILURE = 'USER_UPDATE_ROLE_FAILURE';
export const CHANGE_USER_PROJECT_ROLES = 'CHANGE_USER_PROJECT_ROLES';

//delete user from project
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS';
export const TEAM_DELETE_FAILURE = 'TEAM_DELETE_FAILURE';
export const TEAM_DELETE_RESET = 'TEAM_DELETE_RESET';
export const TEAM_DELETE_REQUEST = 'TEAM_DELETE_REQUEST';

//project balance
export const PROJECT_BALANCE_UPDATE_REQUEST = 'PROJECT_BALANCE_UPDATE_REQUEST';
export const PROJECT_BALANCE_UPDATE_SUCCESS = 'PROJECT_BALANCE_UPDATE_SUCCESS';
export const PROJECT_BALANCE_UPDATE_FAILURE = 'PROJECT_BALANCE_UPDATE_FAILURE';

//users pagination
export const PAGINATE_USERS_NEXT = 'PAGINATE_USERS_NEXT';
export const PAGINATE_USERS_PREV = 'PAGINATE_USERS_PREV';

//project domain settings
export const PROJECT_DOMAIN_REQUEST = 'PROJECT_DOMAIN_REQUEST';
export const PROJECT_DOMAIN_SUCCESS = 'PROJECT_DOMAIN_SUCCESS';
export const PROJECT_DOMAIN_FAILURE = 'PROJECT_DOMAIN_FAILURE';

//delete project domain
export const DELETE_PROJECT_DOMAIN_REQUEST = 'DELETE_PROJECT_DOMAIN_REQUEST';
export const DELETE_PROJECT_DOMAIN_SUCCESS = 'DELETE_PROJECT_DOMAIN_SUCCESS';
export const DELETE_PROJECT_DOMAIN_FAILURE = 'DELETE_PROJECT_DOMAIN_FAILURE';
export const RESET_DELETE_PROJECT_DOMAIN = 'RESET_DELETE_PROJECT_DOMAIN';

//verify project domain
export const VERIFY_PROJECT_DOMAIN_REQUEST = 'VERIFY_PROJECT_DOMAIN_REQUEST';
export const VERIFY_PROJECT_DOMAIN_SUCCESS = 'VERIFY_PROJECT_DOMAIN_SUCCESS';
export const VERIFY_PROJECT_DOMAIN_FAILURE = 'VERIFY_PROJECT_DOMAIN_FAILURE';
export const RESET_VERIFY_PROJECT_DOMAIN = 'RESET_VERIFY_PROJECT_DOMAIN';

//unverify project domain
export const UNVERIFY_PROJECT_DOMAIN_REQUEST =
    'UNVERIFY_PROJECT_DOMAIN_REQUEST';
export const UNVERIFY_PROJECT_DOMAIN_SUCCESS =
    'UNVERIFY_PROJECT_DOMAIN_SUCCESS';
export const UNVERIFY_PROJECT_DOMAIN_FAILURE =
    'UNVERIFY_PROJECT_DOMAIN_FAILURE';
export const RESET_UNVERIFY_PROJECT_DOMAIN = 'RESET_UNVERIFY_PROJECT_DOMAIN';

//reset project domain
export const RESET_PROJECT_DOMAIN_REQUEST = 'RESET_PROJECT_DOMAIN_REQUEST';
export const RESET_PROJECT_DOMAIN_SUCCESS = 'RESET_PROJECT_DOMAIN_SUCCESS';
export const RESET_PROJECT_DOMAIN_FAILURE = 'RESET_PROJECT_DOMAIN_FAILURE';
export const RESET_PROJECT_DOMAIN_ON_MOUNT = 'RESET_PROJECT_DOMAIN_ON_MOUNT';
