// Fetch All Projects List
export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
export const FETCH_PROJECTS_RESET = 'FETCH_PROJECTS_RESET';

// Fetch User Projects
export const FETCH_USER_PROJECTS_REQUEST = 'FETCH_USER_PROJECTS_REQUEST';
export const FETCH_USER_PROJECTS_SUCCESS = 'FETCH_USER_PROJECTS_SUCCESS';
export const FETCH_USER_PROJECTS_FAILURE = 'FETCH_USER_PROJECTS_FAILURE';
export const FETCH_USER_PROJECTS_RESET = 'FETCH_USER_PROJECTS_RESET';

// Delete Project
export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_RESET = 'DELETE_PROJECT_RESET';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

// Block Project
export const BLOCK_PROJECT_REQUEST = 'BLOCK_PROJECT_REQUEST';
export const BLOCK_PROJECT_RESET = 'BLOCK_PROJECT_RESET';
export const BLOCK_PROJECT_SUCCESS = 'BLOCK_PROJECT_SUCCESS';
export const BLOCK_PROJECT_FAILED = 'BLOCK_PROJECT_FAILED';

// Restore Project
export const RESTORE_PROJECT_REQUEST = 'RESTORE_PROJECT_REQUEST';
export const RESTORE_PROJECT_RESET = 'RESTORE_PROJECT_RESET';
export const RESTORE_PROJECT_SUCCESS = 'RESTORE_PROJECT_SUCCESS';
export const RESTORE_PROJECT_FAILED = 'RESTORE_PROJECT_FAILED';

// Unblock Project
export const UNBLOCK_PROJECT_REQUEST = 'UNBLOCK_PROJECT_REQUEST';
export const UNBLOCK_PROJECT_RESET = 'UNBLOCK_PROJECT_RESET';
export const UNBLOCK_PROJECT_SUCCESS = 'UNBLOCK_PROJECT_SUCCESS';
export const UNBLOCK_PROJECT_FAILED = 'UNBLOCK_PROJECT_FAILED';