// Fetch All Projects List
export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
export const FETCH_PROJECTS_RESET = 'FETCH_PROJECTS_RESET';

// Fetch A Project
export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';
export const FETCH_PROJECT_RESET = 'FETCH_PROJECT_RESET';

// Fetch User Projects
export const FETCH_USER_PROJECTS_REQUEST = 'FETCH_USER_PROJECTS_REQUEST';
export const FETCH_USER_PROJECTS_SUCCESS = 'FETCH_USER_PROJECTS_SUCCESS';
export const FETCH_USER_PROJECTS_FAILURE = 'FETCH_USER_PROJECTS_FAILURE';
export const FETCH_USER_PROJECTS_RESET = 'FETCH_USER_PROJECTS_RESET';

// Delete Project
export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_RESET = 'DELETE_PROJECT_RESET';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

// Block Project
export const BLOCK_PROJECT_REQUEST = 'BLOCK_PROJECT_REQUEST';
export const BLOCK_PROJECT_RESET = 'BLOCK_PROJECT_RESET';
export const BLOCK_PROJECT_SUCCESS = 'BLOCK_PROJECT_SUCCESS';
export const BLOCK_PROJECT_FAILED = 'BLOCK_PROJECT_FAILED';

// Restore Alert Limit
export const ALERT_LIMIT_REQUEST = 'ALERT_LIMIT_REQUEST';
export const ALERT_LIMIT_RESET = 'ALERT_LIMIT_RESET';
export const ALERT_LIMIT_SUCCESS = 'ALERT_LIMIT_SUCCESS';
export const ALERT_LIMIT_FAILED = 'ALERT_LIMIT_FAILED';

// Restore Project
export const RESTORE_PROJECT_REQUEST = 'RESTORE_PROJECT_REQUEST';
export const RESTORE_PROJECT_RESET = 'RESTORE_PROJECT_RESET';
export const RESTORE_PROJECT_SUCCESS = 'RESTORE_PROJECT_SUCCESS';
export const RESTORE_PROJECT_FAILED = 'RESTORE_PROJECT_FAILED';

// Unblock Project
export const UNBLOCK_PROJECT_REQUEST = 'UNBLOCK_PROJECT_REQUEST';
export const UNBLOCK_PROJECT_RESET = 'UNBLOCK_PROJECT_RESET';
export const UNBLOCK_PROJECT_SUCCESS = 'UNBLOCK_PROJECT_SUCCESS';
export const UNBLOCK_PROJECT_FAILED = 'UNBLOCK_PROJECT_FAILED';

// Admin Project Note
export const ADD_PROJECT_NOTE_REQUEST = 'ADD_PROJECT_NOTE_REQUEST';
export const ADD_PROJECT_NOTE_RESET = 'ADD_PROJECT_NOTE_RESET';
export const ADD_PROJECT_NOTE_SUCCESS = 'ADD_PROJECT_NOTE_SUCCESS';
export const ADD_PROJECT_NOTE_FAILURE = 'ADD_PROJECT_NOTE_FAILURE';

// Search Users
export const SEARCH_PROJECTS_REQUEST = 'SEARCH_PROJECTS_REQUEST';
export const SEARCH_PROJECTS_RESET = 'SEARCH_PROJECTS_RESET';
export const SEARCH_PROJECTS_SUCCESS = 'SEARCH_PROJECTS_SUCCESS';
export const SEARCH_PROJECTS_FAILURE = 'SEARCH_PROJECTS_FAILURE';
