export const REQUESTING_SETTINGS = 'REQUESTING_SETTINGS';
export const REQUESTING_SETTINGS_SUCCEEDED = 'REQUESTING_SETTINGS_SUCCEEDED';
export const REQUESTING_SETTINGS_FAILED = 'REQUESTING_SETTINGS_FAILED';
