export const REQUESTING_SETTINGS = 'REQUESTING_SETTINGS';
export const REQUESTING_SETTINGS_SUCCEEDED = 'REQUESTING_SETTINGS_SUCCEEDED';
export const REQUESTING_SETTINGS_FAILED = 'REQUESTING_SETTINGS_FAILED';
export const TEST_SMTP_REQUEST = 'TEST_SMTP_REQUEST';
export const TEST_SMTP_SUCCESS = 'TEST_SMTP_SUCCESS';
export const TEST_SMTP_FAILURE = 'TEST_SMTP_FAILURE';