// Fetch All SMS Log List
export const FETCH_SMSLOGS_REQUEST = 'FETCH_SMSLOGS_REQUEST';
export const FETCH_SMSLOGS_SUCCESS = 'FETCH_SMSLOGS_SUCCESS';
export const FETCH_SMSLOGS_FAILURE = 'FETCH_SMSLOGS_FAILURE';

// Search SMS Logs
export const SEARCH_SMSLOGS_REQUEST = 'SEARCH_SMSLOGS_REQUEST';
export const SEARCH_SMSLOGS_SUCCESS = 'SEARCH_SMSLOGS_SUCCESS';
export const SEARCH_SMSLOGS_FAILURE = 'SEARCH_SMSLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_SMSLOGS_REQUEST = 'DELETE_ALL_SMSLOGS_REQUEST';
export const DELETE_ALL_SMSLOGS_SUCCESS = 'DELETE_ALL_SMSLOGS_SUCCESS';
export const DELETE_ALL_SMSLOGS_FAILURE = 'DELETE_ALL_SMSLOGS_FAILURE';

// Fetch sms log status
export const FETCH_SMSLOG_STATUS_SUCCESS = 'FETCH_SMSLOG_STATUS_SUCCESS';
export const FETCH_SMSLOG_STATUS_FAILED = 'FETCH_SMSLOG_STATUS_FAILED';
export const FETCH_SMSLOG_STATUS_REQUEST = 'FETCH_SMSLOG_STATUS_REQUEST';
export const FETCH_SMSLOG_STATUS_RESET = 'FETCH_SMSLOG_STATUS_RESET';

// change sms log status
export const CHANGE_SMSLOG_STATUS_SUCCESS = 'CHANGE_SMSLOG_STATUS_SUCCESS';
export const CHANGE_SMSLOG_STATUS_FAILED = 'CHANGE_SMSLOG_STATUS_FAILED';
export const CHANGE_SMSLOG_STATUS_REQUEST = 'CHANGE_SMSLOG_STATUS_REQUEST';
export const CHANGE_SMSLOG_STATUS_RESET = 'CHANGE_SMSLOG_STATUS_RESET';
