//Fetch All Ssos list 
export const FETCH_SSOS_REQUEST = 'FETCH_SSOS_REQUEST';
export const FETCH_SSOS_SUCCESS = 'FETCH_SSOS_SUCCESS';
export const FETCH_SSOS_FAILURE = 'FETCH_SSOS_FAILURE';

//Delete Sso
export const DELETE_SSO_REQUEST = 'DELETE_SSO_REQUEST';
export const DELETE_SSO_SUCCESS = 'DELETE_SSO_SUCCESS';
export const DELETE_SSO_FAILED = 'DELETE_SSO_FAILED';

//Add Sso
export const ADD_SSO_REQUEST = 'ADD_SSO_REQUEST';
export const ADD_SSO_SUCCESS = 'ADD_SSO_SUCCESS';
export const ADD_SSO_FAILED = 'ADD_SSO_FAILED';
