//Fetch All Sso default roles list
export const FETCH_SSO_DEFAULT_ROLES_REQUEST =
    'FETCH_SSO_DEFAULT_ROLES_REQUEST';
export const FETCH_SSO_DEFAULT_ROLES_SUCCESS =
    'FETCH_SSO_DEFAULT_ROLES_SUCCESS';
export const FETCH_SSO_DEFAULT_ROLES_FAILURE =
    'FETCH_SSO_DEFAULT_ROLES_FAILURE';

//Delete Sso default role
export const DELETE_SSO_DEFAULT_ROLE_REQUEST =
    'DELETE_SSO_DEFAULT_ROLE_REQUEST';
export const DELETE_SSO_DEFAULT_ROLE_SUCCESS =
    'DELETE_SSO_DEFAULT_ROLE_SUCCESS';
export const DELETE_SSO_DEFAULT_ROLE_FAILED = 'DELETE_SSO_DEFAULT_ROLE_FAILED';

//Add Sso default role
export const ADD_SSO_DEFAULT_ROLE_REQUEST = 'ADD_SSO_DEFAULT_ROLE_REQUEST';
export const ADD_SSO_DEFAULT_ROLE_SUCCESS = 'ADD_SSO_DEFAULT_ROLE_SUCCESS';
export const ADD_SSO_DEFAULT_ROLE_FAILED = 'ADD_SSO_DEFAULT_ROLE_FAILED';

//Fetch Sso default role
export const FETCH_SSO_DEFAULT_ROLE_REQUEST = 'FETCH_SSO_DEFAULT_ROLE_REQUEST';
export const FETCH_SSO_DEFAULT_ROLE_SUCCESS = 'FETCH_SSO_DEFAULT_ROLE_SUCCESS';
export const FETCH_SSO_DEFAULT_ROLE_FAILURE = 'FETCH_SSO_DEFAULT_ROLE_FAILURE';

//Update Sso
export const UPDATE_SSO_DEFAULT_ROLE_REQUEST =
    'UPDATE_SSO_DEFAULT_ROLE_REQUEST';
export const UPDATE_SSO_DEFAULT_ROLE_SUCCESS =
    'UPDATE_SSO_DEFAULT_ROLE_SUCCESS';
export const UPDATE_SSO_DEFAULT_ROLE_FAILURE =
    'UPDATE_SSO_DEFAULT_ROLE_FAILURE';

export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';
