// Fetch All Users List
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_RESET = 'FETCH_USERS_RESET';

// Update User Setting
export const UPDATE_USER_SETTING_REQUEST = 'UPDATE_USER_SETTING_REQUEST';
export const UPDATE_USER_SETTING_SUCCESS = 'UPDATE_USER_SETTING_SUCCESS';
export const UPDATE_USER_SETTING_FAILURE = 'UPDATE_USER_SETTING_FAILURE';
export const UPDATE_USER_SETTING_RESET = 'UPDATE_USER_SETTING_RESET';

// file operations
export const LOG_FILE = 'LOG_FILE';
export const RESET_FILE = 'RESET_FILE';

// Delete User
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_RESET = 'DELETE_USER_RESET';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

// Restore User
export const RESTORE_USER_REQUEST = 'RESTORE_USER_REQUEST';
export const RESTORE_USER_RESET = 'RESTORE_USER_RESET';
export const RESTORE_USER_SUCCESS = 'RESTORE_USER_SUCCESS';
export const RESTORE_USER_FAILED = 'RESTORE_USER_FAILED';

// Block User
export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_RESET = 'BLOCK_USER_RESET';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAILED = 'BLOCK_USER_FAILED';

// Unblock User
export const UNBLOCK_USER_REQUEST = 'UNBLOCK_USER_REQUEST';
export const UNBLOCK_USER_RESET = 'UNBLOCK_USER_RESET';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAILED = 'UNBLOCK_USER_FAILED';

// Admin User Note
export const ADD_USER_NOTE_REQUEST = 'ADD_USER_NOTE_REQUEST';
export const ADD_USER_NOTE_RESET = 'ADD_USER_NOTE_RESET';
export const ADD_USER_NOTE_SUCCESS = 'ADD_USER_NOTE_SUCCESS';
export const ADD_USER_NOTE_FAILURE = 'ADD_USER_NOTE_FAILURE';

// Search Users
export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_RESET = 'SEARCH_USERS_RESET';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';