// Fetch All Users List
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_RESET = 'FETCH_USERS_RESET';

// Fetch User Projects
export const FETCH_USER_PROJECTS_REQUEST = 'FETCH_USER_PROJECTS_REQUEST';
export const FETCH_USER_PROJECTS_SUCCESS = 'FETCH_USER_PROJECTS_SUCCESS';
export const FETCH_USER_PROJECTS_FAILURE = 'FETCH_USER_PROJECTS_FAILURE';
export const FETCH_USER_PROJECTS_RESET = 'FETCH_USER_PROJECTS_RESET';

// Update User Setting
export const UPDATE_USER_SETTING_REQUEST = 'UPDATE_USER_SETTING_REQUEST';
export const UPDATE_USER_SETTING_SUCCESS = 'UPDATE_USER_SETTING_SUCCESS';
export const UPDATE_USER_SETTING_FAILURE = 'UPDATE_USER_SETTING_FAILURE';
export const UPDATE_USER_SETTING_RESET = 'UPDATE_USER_SETTING_RESET';

// file operations
export const LOG_FILE = 'LOG_FILE';
export const RESET_FILE = 'RESET_FILE';