production_rollback_status-page:
  stage: RollbackIfSmokeTestFail
  script:
    - chmod +x ./ci/scripts/deployment-setup.sh
    - ./ci/scripts/deployment-setup.sh
    - chmod +x ./ci/scripts/deployment-production-setup.sh
    - ./ci/scripts/deployment-production-setup.sh
    # Rollback status-page
    - chmod +x ./ci/scripts/job-status.sh
    - export smoke_test_production_status=`./ci/scripts/job-status.sh smoke_test_production`
    - if [[ $smoke_test_production_status == \"success\" ]]; then exit 0; fi
    - sudo $HOME/google-cloud-sdk/bin/kubectl rollout undo deployment/fi-status
  only:
    refs:
      - release