enum PageMap {
  INIT = "INIT",
  HOME = "HOME",
  HEALTH = "HEALTH",
  HEALTH_POSTGRES = "HEALTH_POSTGRES",
  HEALTH_CLICKHOUSE = "HEALTH_CLICKHOUSE",
  HEALTH_QUERY = "HEALTH_QUERY",
  HEALTH_LOGS = "HEALTH_LOGS",
  HEALTH_PROBES = "HEALTH_PROBES",
  HEALTH_MIGRATIONS = "HEALTH_MIGRATIONS",
  HEALTH_SUPPORT_BUNDLE = "HEALTH_SUPPORT_BUNDLE",
  LOGOUT = "LOGOUT",
  SETTINGS = "SETTINGS",

  USERS = "USERS",
  USER_VIEW = "USER_VIEW",
  USER_SETTINGS = "USER_SETTINGS",
  USER_DELETE = "USER_DELETE",

  PROJECTS = "PROJECTS",
  PROJECT_VIEW = "PROJECT_VIEW",
  PROJECT_DELETE = "PROJECT_DELETE",
  PROJECT_USERS = "PROJECT_USERS",
  PROJECT_USER_VIEW = "PROJECT_USER_VIEW",
  PROJECT_TEAMS = "PROJECT_TEAMS",
  PROJECT_TEAM_VIEW = "PROJECT_TEAM_VIEW",

  SETTINGS_HOST = "SETTINGS_HOST",
  SETTINGS_SMTP = "SETTINGS_SMTP",
  SETTINGS_CALL_AND_SMS = "SETTINGS_CALL_AND_SMS",
  SETTINGS_WHATSAPP = "SETTINGS_WHATSAPP",
  SETTINGS_TELEGRAM = "SETTINGS_TELEGRAM",
  SETTINGS_PROBES = "SETTINGS_PROBES",
  SETTINGS_AI_AGENTS = "SETTINGS_AI_AGENTS",
  SETTINGS_LLM_PROVIDERS = "SETTINGS_LLM_PROVIDERS",
  SETTINGS_AUTHENTICATION = "SETTINGS_AUTHENTICATION",
  SETTINGS_GLOBAL_SSO = "SETTINGS_GLOBAL_SSO",
  SETTINGS_GLOBAL_SSO_VIEW = "SETTINGS_GLOBAL_SSO_VIEW",
  SETTINGS_GLOBAL_OIDC = "SETTINGS_GLOBAL_OIDC",
  SETTINGS_GLOBAL_OIDC_VIEW = "SETTINGS_GLOBAL_OIDC_VIEW",
  SETTINGS_API_KEY = "SETTINGS_API_KEY",
  SETTINGS_DATA_RETENTION = "SETTINGS_DATA_RETENTION",

  SEND_EMAIL = "SEND_EMAIL",

  MORE_EMAIL = "MORE_EMAIL",
}

export default PageMap;
