#
# realtime Dockerfile
#

# Pull base image nodejs image.
FROM node:17-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

# Install common-server
RUN mkdir /usr/src
RUN mkdir /usr/src/common-server
WORKDIR /usr/src/common-server
COPY ./common-server/package*.json /usr/src/common-server/
RUN npm ci --only=production
COPY ./common-server /usr/src/common-server

WORKDIR /usr/src/app

# Install kubectl for kubernetes monitor scanning
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/$(OS_ARCHITECTURE)/kubectl"
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl && \
  chown root: /usr/local/bin/kubectl



# Install app dependencies
RUN cd /usr/src/app

# Copy package.json files
COPY ./realtime/package.json /usr/src/app/package.json
COPY ./realtime/package-lock.json /usr/src/app/package-lock.json


RUN npm ci

# Expose ports.
EXPOSE 3300

# Expose Debugging port.
EXPOSE 9229

#Run the app
CMD [ "npm", "run", "dev"]

