export const ALERT_FETCH_SUCCESS = 'alert/ALERT_FETCH_SUCCESS';
export const ALERT_FETCH_FAILED = 'alert/ALERT_FETCH_FAILED';
export const ALERT_FETCH_REQUEST = 'alert/ALERT_FETCH_REQUEST';
export const ALERT_FETCH_RESET = 'alert/ALERT_FETCH_RESET';

export const PROJECT_ALERT_FETCH_SUCCESS = 'alert/PROJECT_ALERT_FETCH_SUCCESS';
export const PROJECT_ALERT_FETCH_FAILED = 'alert/PROJECT_ALERT_FETCH_FAILED';
export const PROJECT_ALERT_FETCH_REQUEST = 'alert/PROJECT_ALERT_FETCH_REQUEST';
export const PROJECT_ALERT_FETCH_RESET = 'alert/PROJECT_ALERT_FETCH_RESET';

export const INCIDENTS_ALERT_FETCH_SUCCESS = 'alert/INCIDENTS_ALERT_FETCH_SUCCESS';
export const INCIDENTS_ALERT_FETCH_FAILED = 'alert/INCIDENTS_ALERT_FETCH_FAILED';
export const INCIDENTS_ALERT_FETCH_REQUEST = 'alert/INCIDENTS_ALERT_FETCH_REQUEST';
export const INCIDENTS_ALERT_FETCH_RESET = 'alert/INCIDENTS_ALERT_FETCH_RESET';

export const SUBSCRIBERS_ALERT_FETCH_SUCCESS = 'alert/SUBSCRIBERS_ALERT_FETCH_SUCCESS';
export const SUBSCRIBERS_ALERT_FETCH_FAILED = 'alert/SUBSCRIBERS_ALERT_FETCH_FAILED';
export const SUBSCRIBERS_ALERT_FETCH_REQUEST = 'alert/SUBSCRIBERS_ALERT_FETCH_REQUEST';
export const SUBSCRIBERS_ALERT_FETCH_RESET = 'alert/SUBSCRIBERS_ALERT_FETCH_RESET';

