export const  ALERT_FETCH_SUCCESS: string = 'alert/ALERT_FETCH_SUCCESS';
export const  ALERT_FETCH_FAILED: string = 'alert/ALERT_FETCH_FAILED';
export const  ALERT_FETCH_REQUEST: string = 'alert/ALERT_FETCH_REQUEST';
export const  ALERT_FETCH_RESET: string = 'alert/ALERT_FETCH_RESET';

export const  PROJECT_ALERT_FETCH_SUCCESS: string = 'alert/PROJECT_ALERT_FETCH_SUCCESS';
export const  PROJECT_ALERT_FETCH_FAILED: string = 'alert/PROJECT_ALERT_FETCH_FAILED';
export const  PROJECT_ALERT_FETCH_REQUEST: string = 'alert/PROJECT_ALERT_FETCH_REQUEST';
export const  PROJECT_ALERT_FETCH_RESET: string = 'alert/PROJECT_ALERT_FETCH_RESET';

export const INCIDENTS_ALERT_FETCH_SUCCESS =
    'alert/INCIDENTS_ALERT_FETCH_SUCCESS';
export const INCIDENTS_ALERT_FETCH_FAILED =
    'alert/INCIDENTS_ALERT_FETCH_FAILED';
export const INCIDENTS_ALERT_FETCH_REQUEST =
    'alert/INCIDENTS_ALERT_FETCH_REQUEST';
export const  INCIDENTS_ALERT_FETCH_RESET: string = 'alert/INCIDENTS_ALERT_FETCH_RESET';

export const SUBSCRIBERS_ALERT_FETCH_SUCCESS =
    'alert/SUBSCRIBERS_ALERT_FETCH_SUCCESS';
export const SUBSCRIBERS_ALERT_FETCH_FAILED =
    'alert/SUBSCRIBERS_ALERT_FETCH_FAILED';
export const SUBSCRIBERS_ALERT_FETCH_REQUEST =
    'alert/SUBSCRIBERS_ALERT_FETCH_REQUEST';
export const SUBSCRIBERS_ALERT_FETCH_RESET =
    'alert/SUBSCRIBERS_ALERT_FETCH_RESET';

export const  FETCH_ALERT_CHARGES_SUCCESS: string = 'FETCH_ALERT_CHARGES_SUCCESS';
export const  FETCH_ALERT_CHARGES_FAILED: string = 'FETCH_ALERT_CHARGES_FAILED';
export const  FETCH_ALERT_CHARGES_REQUEST: string = 'FETCH_ALERT_CHARGES_REQUEST';

export const  DOWNLOAD_ALERT_CHARGES_SUCCESS: string = 'DOWNLOAD_ALERT_CHARGES_SUCCESS';
export const  DOWNLOAD_ALERT_CHARGES_FAILED: string = 'DOWNLOAD_ALERT_CHARGES_FAILED';
export const  DOWNLOAD_ALERT_CHARGES_REQUEST: string = 'DOWNLOAD_ALERT_CHARGES_REQUEST';
