//Create new application log
export const CREATE_APPLICATION_LOG_SUCCESS = 'CREATE_APPLICATION_LOG_SUCCESS';
export const CREATE_APPLICATION_LOG_FAILURE = 'CREATE_APPLICATION_LOG_FAILURE';
export const CREATE_APPLICATION_LOG_RESET = 'CREATE_APPLICATION_LOG_RESET';
export const CREATE_APPLICATION_LOG_REQUEST = 'CREATE_APPLICATION_LOG_REQUEST';