//Create new Application log
export const CREATE_APPLICATION_LOG_SUCCESS = 'CREATE_APPLICATION_LOG_SUCCESS';
export const CREATE_APPLICATION_LOG_FAILURE = 'CREATE_APPLICATION_LOG_FAILURE';
export const CREATE_APPLICATION_LOG_RESET = 'CREATE_APPLICATION_LOG_RESET';
export const CREATE_APPLICATION_LOG_REQUEST = 'CREATE_APPLICATION_LOG_REQUEST';

//Application log list
export const FETCH_APPLICATION_LOGS_REQUEST = 'FETCH_APPLICATION_LOGS_REQUEST';
export const FETCH_APPLICATION_LOGS_SUCCESS = 'FETCH_APPLICATION_LOGS_SUCCESS';
export const FETCH_APPLICATION_LOGS_FAILURE = 'FETCH_APPLICATION_LOGS_FAILURE';
export const FETCH_APPLICATION_LOGS_RESET = 'FETCH_APPLICATION_LOGS_RESET';
