//Create new Log container
export const CREATE_APPLICATION_LOG_SUCCESS: string =
    'CREATE_APPLICATION_LOG_SUCCESS';
export const CREATE_APPLICATION_LOG_FAILURE: string =
    'CREATE_APPLICATION_LOG_FAILURE';
export const CREATE_APPLICATION_LOG_RESET: string =
    'CREATE_APPLICATION_LOG_RESET';
export const CREATE_APPLICATION_LOG_REQUEST: string =
    'CREATE_APPLICATION_LOG_REQUEST';

//Log container list
export const FETCH_APPLICATION_LOGS_REQUEST: string =
    'FETCH_APPLICATION_LOGS_REQUEST';
export const FETCH_APPLICATION_LOGS_SUCCESS: string =
    'FETCH_APPLICATION_LOGS_SUCCESS';
export const FETCH_APPLICATION_LOGS_FAILURE: string =
    'FETCH_APPLICATION_LOGS_FAILURE';
export const FETCH_APPLICATION_LOGS_RESET: string =
    'FETCH_APPLICATION_LOGS_RESET';

//Delete a log container
export const DELETE_APPLICATION_LOG_SUCCESS: string =
    'DELETE_APPLICATION_LOG_SUCCESS';
export const DELETE_APPLICATION_LOG_FAILURE: string =
    'DELETE_APPLICATION_LOG_FAILURE';
export const DELETE_APPLICATION_LOG_REQUEST: string =
    'DELETE_APPLICATION_LOG_REQUEST';
export const DELETE_COMPONENT_APPLICATION_LOGS =
    'DELETE_COMPONENT_APPLICATION_LOGS';

//Fetch logs of an log container
export const FETCH_LOGS_REQUEST: string = 'FETCH_LOGS_REQUEST';
export const FETCH_LOGS_SUCCESS: string = 'FETCH_LOGS_SUCCESS';
export const FETCH_LOGS_FAILURE: string = 'FETCH_LOGS_FAILURE';
export const FETCH_LOGS_RESET: string = 'FETCH_LOGS_RESET';

//Reset Log Container Key
export const RESET_APPLICATION_LOG_KEY_REQUEST =
    'RESET_APPLICATION_LOG_KEY_REQUEST';
export const RESET_APPLICATION_LOG_KEY_SUCCESS =
    'RESET_APPLICATION_LOG_KEY_SUCCESS';
export const RESET_APPLICATION_LOG_KEY_FAILURE =
    'RESET_APPLICATION_LOG_KEY_FAILURE';
export const RESET_APPLICATION_LOG_KEY_RESET =
    'RESET_APPLICATION_LOG_KEY_RESET';

//Edit new Log Container
export const EDIT_APPLICATION_LOG_SUCCESS: string =
    'EDIT_APPLICATION_LOG_SUCCESS';
export const EDIT_APPLICATION_LOG_FAILURE: string =
    'EDIT_APPLICATION_LOG_FAILURE';
export const EDIT_APPLICATION_LOG_RESET: string = 'EDIT_APPLICATION_LOG_RESET';
export const EDIT_APPLICATION_LOG_REQUEST: string =
    'EDIT_APPLICATION_LOG_REQUEST';
export const EDIT_APPLICATION_LOG_SWITCH: string =
    'EDIT_APPLICATION_LOG_SWITCH';

// Fetch Stat
export const FETCH_LOG_STAT_SUCCESS: string = 'FETCH_LOG_STAT_SUCCESS';
export const FETCH_LOG_STAT_FAILURE: string = 'FETCH_LOG_STAT_FAILURE';
export const FETCH_LOG_STAT_RESET: string = 'FETCH_LOG_STAT_RESET';
export const FETCH_LOG_STAT_REQUEST: string = 'FETCH_LOG_STAT_REQUEST';

// New Log added to an log container
export const GET_LOG_SUCCESS: string = 'GET_LOG_SUCCESS';
