//Create new Application log
export const CREATE_APPLICATION_LOG_SUCCESS = 'CREATE_APPLICATION_LOG_SUCCESS';
export const CREATE_APPLICATION_LOG_FAILURE = 'CREATE_APPLICATION_LOG_FAILURE';
export const CREATE_APPLICATION_LOG_RESET = 'CREATE_APPLICATION_LOG_RESET';
export const CREATE_APPLICATION_LOG_REQUEST = 'CREATE_APPLICATION_LOG_REQUEST';

//Application log list
export const FETCH_APPLICATION_LOGS_REQUEST = 'FETCH_APPLICATION_LOGS_REQUEST';
export const FETCH_APPLICATION_LOGS_SUCCESS = 'FETCH_APPLICATION_LOGS_SUCCESS';
export const FETCH_APPLICATION_LOGS_FAILURE = 'FETCH_APPLICATION_LOGS_FAILURE';
export const FETCH_APPLICATION_LOGS_RESET = 'FETCH_APPLICATION_LOGS_RESET';

//Delete a application log
export const DELETE_APPLICATION_LOG_SUCCESS = 'DELETE_APPLICATION_LOG_SUCCESS';
export const DELETE_APPLICATION_LOG_FAILURE = 'DELETE_APPLICATION_LOG_FAILURE';
export const DELETE_APPLICATION_LOG_REQUEST = 'DELETE_APPLICATION_LOG_REQUEST';
export const DELETE_COMPONENT_APPLICATION_LOGS = 'DELETE_COMPONENT_APPLICATION_LOGS';


//Fetch logs of an application log
export const FETCH_LOGS_REQUEST = 'FETCH_LOGS_REQUEST';
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';
export const FETCH_LOGS_FAILURE = 'FETCH_LOGS_FAILURE';
export const FETCH_LOGS_RESET = 'FETCH_LOGS_RESET';
