//Script list
export const FETCH_AUTOMATED_SCRIPT_REQUEST = 'FETCH_AUTOMATED_SCRIPT_REQUEST';
export const FETCH_AUTOMATED_SCRIPT_SUCCESS = 'FETCH_AUTOMATED_SCRIPT_SUCCESS';
export const FETCH_AUTOMATED_SCRIPT_FAILURE = 'FETCH_AUTOMATED_SCRIPT_FAILURE';
export const FETCH_AUTOMATED_SCRIPT_RESET = 'FETCH_AUTOMATED_SCRIPT_RESET';

//Create new component
export const CREATE_AUTOMATED_SCRIPT_SUCCESS =
    'CREATE_AUTOMATED_SCRIPT_SUCCESS';
export const CREATE_AUTOMATED_SCRIPT_FAILURE =
    'CREATE_AUTOMATED_SCRIPT_FAILURE';
export const CREATE_AUTOMATED_SCRIPT_RESET = 'CREATE_AUTOMATED_SCRIPT_RESET';
export const CREATE_AUTOMATED_SCRIPT_REQUEST =
    'CREATE_AUTOMATED_SCRIPT_REQUEST';

//Edit new AUTOMATED_SCRIPT
export const EDIT_AUTOMATED_SCRIPT_SUCCESS = 'EDIT_AUTOMATED_SCRIPT_SUCCESS';
export const EDIT_AUTOMATED_SCRIPT_FAILURE = 'EDIT_AUTOMATED_SCRIPT_FAILURE';
export const EDIT_AUTOMATED_SCRIPT_RESET = 'EDIT_AUTOMATED_SCRIPT_RESET';
export const EDIT_AUTOMATED_SCRIPT_REQUEST = 'EDIT_AUTOMATED_SCRIPT_REQUEST';
export const EDIT_AUTOMATED_SCRIPT_SWITCH = 'EDIT_AUTOMATED_SCRIPT_SWITCH';

//Delete a component
export const DELETE_AUTOMATED_SCRIPT_SUCCESS =
    'DELETE_AUTOMATED_SCRIPT_SUCCESS';
export const DELETE_AUTOMATED_SCRIPT_FAILURE =
    'DELETE_AUTOMATED_SCRIPT_FAILURE';
export const DELETE_AUTOMATED_SCRIPT_REQUEST =
    'DELETE_AUTOMATED_SCRIPT_REQUEST';
// export const DELETE_PROJECT_COMPONENTS = 'DELETE_PROJECT_COMPONENTS';

export const GET_AUTOMATED_SCRIPT_LOGS_REQUEST =
    'GET_AUTOMATED_SCRIPT_LOGS_REQUEST';
export const GET_AUTOMATED_SCRIPT_LOGS_SUCCESS =
    'GET_AUTOMATED_SCRIPT_LOGS_SUCCESS';
export const GET_AUTOMATED_SCRIPT_LOGS_FAILURE =
    'GET_AUTOMATED_SCRIPT_LOGS_FAILURE';
export const GET_AUTOMATED_SCRIPT_LOGS_RESET =
    'GET_AUTOMATED_SCRIPT_LOGS_RESET';
