//Fetch Script list
export const FETCH_AUTOMATED_SCRIPT_SUCCESS = 'FETCH_AUTOMATED_SCRIPT_SUCCESS';
export const FETCH_AUTOMATED_SCRIPT_FAILURE = 'FETCH_AUTOMATED_SCRIPT_FAILURE';

//Create new component
export const CREATE_AUTOMATED_SCRIPT_SUCCESS =
    'CREATE_AUTOMATED_SCRIPT_SUCCESS';
export const CREATE_AUTOMATED_SCRIPT_FAILURE =
    'CREATE_AUTOMATED_SCRIPT_FAILURE';
export const CREATE_AUTOMATED_SCRIPT_RESET = 'CREATE_AUTOMATED_SCRIPT_RESET';
export const CREATE_AUTOMATED_SCRIPT_REQUEST =
    'CREATE_AUTOMATED_SCRIPT_REQUEST';
export const RESET_AUTOMATED_SCRIPT = 'RESET_AUTOMATED_SCRIPT';

//fetch Individual script
export const FETCH_SINGLE_SCRIPT_SUCCESS = 'FETCH_SINGLE_SCRIPT_SUCCESS';
export const FETCH_SINGLE_SCRIPT_REQUEST = 'FETCH_SINGLE_SCRIPT_REQUEST';
export const FETCH_SINGLE_SCRIPT_FAILURE = 'FETCH_SINGLE_SCRIPT_FAILURE';

//Delete a component
export const DELETE_AUTOMATED_SCRIPT_SUCCESS =
    'DELETE_AUTOMATED_SCRIPT_SUCCESS';
export const DELETE_AUTOMATED_SCRIPT_FAILURE =
    'DELETE_AUTOMATED_SCRIPT_FAILURE';
export const DELETE_AUTOMATED_SCRIPT_REQUEST =
    'DELETE_AUTOMATED_SCRIPT_REQUEST';

//Run a script
export const RUN_AUTOMATED_SCRIPT_REQUEST = 'RUN_AUTOMATED_SCRIPT_REQUEST';
export const RUN_AUTOMATED_SCRIPT_FAILURE = 'RUN_AUTOMATED_SCRIPT_FAILURE';
export const RUN_AUTOMATED_SCRIPT_SUCCESS = 'RUN_AUTOMATED_SCRIPT_SUCCESS';
