//Get all routing numbers
export const GET_CALL_ROUTING_NUMBERS_SUCCESS =
    'GET_CALL_ROUTING_NUMBERS_SUCCESS';
export const GET_CALL_ROUTING_NUMBERS_FAILURE =
    'GET_CALL_ROUTING_NUMBERS_FAILURE';
export const GET_CALL_ROUTING_NUMBERS_REQUEST =
    'GET_CALL_ROUTING_NUMBERS_REQUEST';

//Get all team members and schedules
export const GET_TEAM_MEMBERS_AND_SCHEDULES_SUCCESS =
    'GET_TEAM_MEMBERS_AND_SCHEDULES_SUCCESS';
export const GET_TEAM_MEMBERS_AND_SCHEDULES_FAILURE =
    'GET_TEAM_MEMBERS_AND_SCHEDULES_FAILURE';
export const GET_TEAM_MEMBERS_AND_SCHEDULES_REQUEST =
    'GET_CALL_ROUTING_NUMBERS_REQUEST';
export const GET_TEAM_MEMBERS_AND_SCHEDULES_RESET =
    'GET_TEAM_MEMBERS_AND_SCHEDULES_RESET';

//Add new routing number
export const ADD_CALL_ROUTING_NUMBER_SUCCESS =
    'ADD_CALL_ROUTING_NUMBER_SUCCESS';
export const ADD_CALL_ROUTING_NUMBER_FAILURE =
    'ADD_CALL_ROUTING_NUMBER_FAILURE';
export const ADD_CALL_ROUTING_NUMBER_RESET = 'ADD_CALL_ROUTING_NUMBER_RESET';
export const ADD_CALL_ROUTING_NUMBER_REQUEST =
    'ADD_CALL_ROUTING_NUMBER_REQUEST';

//Add call routing audio
export const UPLOAD_CALL_ROUTING_AUDIO_SUCCESS =
    'UPLOAD_CALL_ROUTING_AUDIO_SUCCESS';
export const UPLOAD_CALL_ROUTING_AUDIO_FAILURE =
    'UPLOAD_CALL_ROUTING_AUDIO_FAILURE';
export const UPLOAD_CALL_ROUTING_AUDIO_RESET =
    'UPLOAD_CALL_ROUTING_AUDIO_RESET';
export const UPLOAD_CALL_ROUTING_AUDIO_REQUEST =
    'UPLOAD_CALL_ROUTING_AUDIO_REQUEST';

//Add new routing schedule
export const ADD_CALL_ROUTING_SCHEDULE_SUCCESS =
    'ADD_CALL_ROUTING_SCHEDULE_SUCCESS';
export const ADD_CALL_ROUTING_SCHEDULE_FAILURE =
    'ADD_CALL_ROUTING_SCHEDULE_FAILURE';
export const ADD_CALL_ROUTING_SCHEDULE_RESET =
    'ADD_CALL_ROUTING_SCHEDULE_RESET';
export const ADD_CALL_ROUTING_SCHEDULE_REQUEST =
    'ADD_CALL_ROUTING_SCHEDULE_REQUEST';

//Fetch routing numbers
export const FETCH_NUMBERS_SUCCESS = 'FETCH_NUMBERS_SUCCESS';
export const FETCH_NUMBERS_FAILURE = 'FETCH_NUMBERS_FAILURE';
export const FETCH_NUMBERS_RESET = 'FETCH_NUMBERS_RESET';
export const FETCH_NUMBERS_REQUEST = 'FETCH_NUMBERS_REQUEST';

//Remove routing numbers
export const REMOVE_NUMBERS_SUCCESS = 'REMOVE_NUMBERS_SUCCESS';
export const REMOVE_NUMBERS_FAILURE = 'REMOVE_NUMBERS_FAILURE';
export const REMOVE_NUMBERS_REQUEST = 'REMOVE_NUMBERS_REQUEST';

//Get call routing logs
export const GET_CALL_ROUTING_LOGS_SUCCESS = 'GET_CALL_ROUTING_LOGS_SUCCESS';
export const GET_CALL_ROUTING_LOGS_FAILURE = 'GET_CALL_ROUTING_LOGS_FAILURE';
export const GET_CALL_ROUTING_LOGS_REQUEST = 'GET_CALL_ROUTING_LOGS_REQUEST';
export const GET_CALL_ROUTING_LOGS_RESET = 'GET_CALL_ROUTING_LOGS_RESET';

//Remove Intro Audio
export const REMOVE_INTRO_AUDIO_SUCCESS = 'REMOVE_INTRO_AUDIO_SUCCESS';
export const REMOVE_INTRO_AUDIO_FAILURE = 'REMOVE_INTRO_AUDIO_FAILURE';
export const REMOVE_INTRO_AUDIO_REQUEST = 'REMOVE_INTRO_AUDIO_REQUEST';

//Remove Backup Intro Audio
export const REMOVE_BACKUP_INTRO_AUDIO_SUCCESS =
    'REMOVE_BACKUP_INTRO_AUDIO_SUCCESS';
export const REMOVE_BACKUP_INTRO_AUDIO_FAILURE =
    'REMOVE_BACKUP_INTRO_AUDIO_FAILURE';
export const REMOVE_BACKUP_INTRO_AUDIO_REQUEST =
    'REMOVE_BACKUP_INTRO_AUDIO_REQUEST';
