//Get all routing numbers
export const GET_CALL_ROUTING_NUMBERS_SUCCESS: $TSFixMe =
    'GET_CALL_ROUTING_NUMBERS_SUCCESS';
export const GET_CALL_ROUTING_NUMBERS_FAILURE: $TSFixMe =
    'GET_CALL_ROUTING_NUMBERS_FAILURE';
export const GET_CALL_ROUTING_NUMBERS_REQUEST: $TSFixMe =
    'GET_CALL_ROUTING_NUMBERS_REQUEST';

//Get all team members and schedules
export const GET_TEAM_MEMBERS_AND_SCHEDULES_SUCCESS: $TSFixMe =
    'GET_TEAM_MEMBERS_AND_SCHEDULES_SUCCESS';
export const GET_TEAM_MEMBERS_AND_SCHEDULES_FAILURE: $TSFixMe =
    'GET_TEAM_MEMBERS_AND_SCHEDULES_FAILURE';
export const GET_TEAM_MEMBERS_AND_SCHEDULES_REQUEST: $TSFixMe =
    'GET_CALL_ROUTING_NUMBERS_REQUEST';
export const GET_TEAM_MEMBERS_AND_SCHEDULES_RESET: $TSFixMe =
    'GET_TEAM_MEMBERS_AND_SCHEDULES_RESET';

//Add new routing number
export const ADD_CALL_ROUTING_NUMBER_SUCCESS: $TSFixMe =
    'ADD_CALL_ROUTING_NUMBER_SUCCESS';
export const ADD_CALL_ROUTING_NUMBER_FAILURE: $TSFixMe =
    'ADD_CALL_ROUTING_NUMBER_FAILURE';
export const ADD_CALL_ROUTING_NUMBER_RESET: string =
    'ADD_CALL_ROUTING_NUMBER_RESET';
export const ADD_CALL_ROUTING_NUMBER_REQUEST: $TSFixMe =
    'ADD_CALL_ROUTING_NUMBER_REQUEST';

//Add call routing audio
export const UPLOAD_CALL_ROUTING_AUDIO_SUCCESS: $TSFixMe =
    'UPLOAD_CALL_ROUTING_AUDIO_SUCCESS';
export const UPLOAD_CALL_ROUTING_AUDIO_FAILURE: $TSFixMe =
    'UPLOAD_CALL_ROUTING_AUDIO_FAILURE';
export const UPLOAD_CALL_ROUTING_AUDIO_RESET: $TSFixMe =
    'UPLOAD_CALL_ROUTING_AUDIO_RESET';
export const UPLOAD_CALL_ROUTING_AUDIO_REQUEST: $TSFixMe =
    'UPLOAD_CALL_ROUTING_AUDIO_REQUEST';

//Add new routing schedule
export const ADD_CALL_ROUTING_SCHEDULE_SUCCESS: $TSFixMe =
    'ADD_CALL_ROUTING_SCHEDULE_SUCCESS';
export const ADD_CALL_ROUTING_SCHEDULE_FAILURE: $TSFixMe =
    'ADD_CALL_ROUTING_SCHEDULE_FAILURE';
export const ADD_CALL_ROUTING_SCHEDULE_RESET: $TSFixMe =
    'ADD_CALL_ROUTING_SCHEDULE_RESET';
export const ADD_CALL_ROUTING_SCHEDULE_REQUEST: $TSFixMe =
    'ADD_CALL_ROUTING_SCHEDULE_REQUEST';

//Fetch routing numbers
export const FETCH_NUMBERS_SUCCESS: string = 'FETCH_NUMBERS_SUCCESS';
export const FETCH_NUMBERS_FAILURE: string = 'FETCH_NUMBERS_FAILURE';
export const FETCH_NUMBERS_RESET: string = 'FETCH_NUMBERS_RESET';
export const FETCH_NUMBERS_REQUEST: string = 'FETCH_NUMBERS_REQUEST';

//Remove routing numbers
export const REMOVE_NUMBERS_SUCCESS: string = 'REMOVE_NUMBERS_SUCCESS';
export const REMOVE_NUMBERS_FAILURE: string = 'REMOVE_NUMBERS_FAILURE';
export const REMOVE_NUMBERS_REQUEST: string = 'REMOVE_NUMBERS_REQUEST';

//Get call routing logs
export const GET_CALL_ROUTING_LOGS_SUCCESS: string =
    'GET_CALL_ROUTING_LOGS_SUCCESS';
export const GET_CALL_ROUTING_LOGS_FAILURE: string =
    'GET_CALL_ROUTING_LOGS_FAILURE';
export const GET_CALL_ROUTING_LOGS_REQUEST: string =
    'GET_CALL_ROUTING_LOGS_REQUEST';
export const GET_CALL_ROUTING_LOGS_RESET: string =
    'GET_CALL_ROUTING_LOGS_RESET';

//Remove Intro Audio
export const REMOVE_INTRO_AUDIO_SUCCESS: string = 'REMOVE_INTRO_AUDIO_SUCCESS';
export const REMOVE_INTRO_AUDIO_FAILURE: string = 'REMOVE_INTRO_AUDIO_FAILURE';
export const REMOVE_INTRO_AUDIO_REQUEST: string = 'REMOVE_INTRO_AUDIO_REQUEST';

//Remove Backup Intro Audio
export const REMOVE_BACKUP_INTRO_AUDIO_SUCCESS: $TSFixMe =
    'REMOVE_BACKUP_INTRO_AUDIO_SUCCESS';
export const REMOVE_BACKUP_INTRO_AUDIO_FAILURE: $TSFixMe =
    'REMOVE_BACKUP_INTRO_AUDIO_FAILURE';
export const REMOVE_BACKUP_INTRO_AUDIO_REQUEST: $TSFixMe =
    'REMOVE_BACKUP_INTRO_AUDIO_REQUEST';
