export const ADD_CARD_SUCCESS: string = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILED: string = 'ADD_CARD_FAILED';
export const ADD_CARD_REQUEST: string = 'ADD_CARD_REQUEST';

export const FETCH_CARDS_SUCCESS: string = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILED: string = 'FETCH_CARDS_FAILED';
export const FETCH_CARDS_REQUEST: string = 'FETCH_CARDS_REQUEST';

export const DELETE_CARD_SUCCESS: string = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILED: string = 'DELETE_CARD_FAILED';
export const DELETE_CARD_REQUEST: string = 'DELETE_CARD_REQUEST';

export const SET_DEFAULT_CARD_SUCCESS: string = 'SET_DEFAULT_CARD_SUCCESS';
export const SET_DEFAULT_CARD_FAILED: string = 'SET_DEFAULT_CARD_FAILED';
export const SET_DEFAULT_CARD_REQUEST: string = 'SET_DEFAULT_CARD_REQUEST';
