export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILED = 'ADD_CARD_FAILED';
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';

export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';
export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';

export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILED = 'DELETE_CARD_FAILED';
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';

export const SET_DEFAULT_CARD_SUCCESS = 'SET_DEFAULT_CARD_SUCCESS';
export const SET_DEFAULT_CARD_FAILED = 'SET_DEFAULT_CARD_FAILED';
export const SET_DEFAULT_CARD_REQUEST = 'SET_DEFAULT_CARD_REQUEST';