//Monitor list
export const FETCH_COMPONENTS_REQUEST = 'FETCH_COMPONENTS_REQUEST';
export const FETCH_COMPONENTS_SUCCESS = 'FETCH_COMPONENTS_SUCCESS';
export const FETCH_COMPONENTS_FAILURE = 'FETCH_COMPONENTS_FAILURE';
export const FETCH_COMPONENTS_RESET = 'FETCH_COMPONENTS_RESET';

//Create new component
export const CREATE_COMPONENT_SUCCESS = 'CREATE_COMPONENT_SUCCESS';
export const CREATE_COMPONENT_FAILURE = 'CREATE_COMPONENT_FAILURE';
export const CREATE_COMPONENT_RESET = 'CREATE_COMPONENT_RESET';
export const CREATE_COMPONENT_REQUEST = 'CREATE_COMPONENT_REQUEST';

//Edit new component
export const EDIT_COMPONENT_SUCCESS = 'EDIT_COMPONENT_SUCCESS';
export const EDIT_COMPONENT_FAILURE = 'EDIT_COMPONENT_FAILURE';
export const EDIT_COMPONENT_RESET = 'EDIT_COMPONENT_RESET';
export const EDIT_COMPONENT_REQUEST = 'EDIT_COMPONENT_REQUEST';
export const EDIT_COMPONENT_SWITCH = 'EDIT_COMPONENT_SWITCH';

//Delete a component
export const DELETE_COMPONENT_SUCCESS = 'DELETE_COMPONENT_SUCCESS';
export const DELETE_COMPONENT_FAILURE = 'DELETE_COMPONENT_FAILURE';
export const DELETE_COMPONENT_REQUEST = 'DELETE_COMPONENT_REQUEST';
export const DELETE_PROJECT_COMPONENTS = 'DELETE_PROJECT_COMPONENTS';

//Fetch Incidents of components
export const FETCH_COMPONENTS_INCIDENT_REQUEST =
    'FETCH_COMPONENTS_INCIDENT_REQUEST';
export const FETCH_COMPONENTS_INCIDENT_SUCCESS =
    'FETCH_COMPONENTS_INCIDENT_SUCCESS';
export const FETCH_COMPONENTS_INCIDENT_FAILURE =
    'FETCH_COMPONENTS_INCIDENT_FAILURE';

//Fetch Subscribers of components
export const FETCH_COMPONENTS_SUBSCRIBER_REQUEST =
    'FETCH_COMPONENTS_SUBSCRIBER_REQUEST';
export const FETCH_COMPONENTS_SUBSCRIBER_SUCCESS =
    'FETCH_COMPONENTS_SUBSCRIBER_SUCCESS';
export const FETCH_COMPONENTS_SUBSCRIBER_FAILURE =
    'FETCH_COMPONENTS_SUBSCRIBER_FAILURE';

export const REMOVE_COMPONENTS_SUBSCRIBERS = 'REMOVE_COMPONENTS_SUBSCRIBERS';

export const ADD_COMPONENTS_SUBSCRIBERS = 'ADD_COMPONENTS_SUBSCRIBERS';

// Fetch Monitor Logs
export const FETCH_COMPONENT_LOGS_REQUEST = 'FETCH_COMPONENT_LOGS_REQUEST';
export const FETCH_COMPONENT_LOGS_SUCCESS = 'FETCH_COMPONENT_LOGS_SUCCESS';
export const FETCH_COMPONENT_LOGS_FAILURE = 'FETCH_COMPONENT_LOGS_FAILURE';

// Fetch Monitor Statuses
export const FETCH_COMPONENT_STATUSES_REQUEST =
    'FETCH_COMPONENT_STATUSES_REQUEST';
export const FETCH_COMPONENT_STATUSES_SUCCESS =
    'FETCH_COMPONENT_STATUSES_SUCCESS';
export const FETCH_COMPONENT_STATUSES_FAILURE =
    'FETCH_COMPONENT_STATUSES_FAILURE';

// Fetch Monitor Logs list
export const GET_COMPONENT_LOGS_REQUEST = 'GET_COMPONENT_LOGS_REQUEST';
export const GET_COMPONENT_LOGS_SUCCESS = 'GET_COMPONENT_LOGS_SUCCESS';
export const GET_COMPONENT_LOGS_FAILURE = 'GET_COMPONENT_LOGS_FAILURE';
export const GET_COMPONENT_LOGS_RESET = 'GET_COMPONENT_LOGS_RESET';

// Fetch Monitor Criteria
export const FETCH_COMPONENT_CRITERIA_REQUEST =
    'FETCH_COMPONENT_CRITERIA_REQUEST';
export const FETCH_COMPONENT_CRITERIA_SUCCESS =
    'FETCH_COMPONENT_CRITERIA_SUCCESS';
export const FETCH_COMPONENT_CRITERIA_FAILURE =
    'FETCH_COMPONENT_CRITERIA_FAILURE';
export const SET_COMPONENT_CRITERIA = 'SET_COMPONENT_CRITERIA';

//Add seat
export const ADD_SEAT_SUCCESS = 'ADD_SEAT_SUCCESS';
export const ADD_SEAT_FAILURE = 'ADD_SEAT_FAILURE';
export const ADD_SEAT_REQUEST = 'ADD_SEAT_REQUEST';
export const ADD_SEAT_RESET = 'ADD_SEAT_RESET';

export const SELECT_PROBE = 'component/SELECT_PROBE';
