//Monitor list
export const FETCH_COMPONENTS_REQUEST: string = 'FETCH_COMPONENTS_REQUEST';
export const FETCH_COMPONENTS_SUCCESS: string = 'FETCH_COMPONENTS_SUCCESS';
export const FETCH_COMPONENTS_FAILURE: string = 'FETCH_COMPONENTS_FAILURE';
export const FETCH_COMPONENTS_RESET: string = 'FETCH_COMPONENTS_RESET';

// Monitor list: paginate
export const FETCH_PAGINATED_COMPONENTS_REQUEST =
    'FETCH_PAGINATED_COMPONENTS_REQUEST';
export const FETCH_PAGINATED_COMPONENTS_SUCCESS =
    'FETCH_PAGINATED_COMPONENTS_SUCCESS';
export const FETCH_PAGINATED_COMPONENTS_FAILURE =
    'FETCH_PAGINATED_COMPONENTS_FAILURE';

//Create new component
export const CREATE_COMPONENT_SUCCESS: string = 'CREATE_COMPONENT_SUCCESS';
export const CREATE_COMPONENT_FAILURE: string = 'CREATE_COMPONENT_FAILURE';
export const CREATE_COMPONENT_RESET: string = 'CREATE_COMPONENT_RESET';
export const CREATE_COMPONENT_REQUEST: string = 'CREATE_COMPONENT_REQUEST';

//Edit new component
export const EDIT_COMPONENT_SUCCESS: string = 'EDIT_COMPONENT_SUCCESS';
export const EDIT_COMPONENT_FAILURE: string = 'EDIT_COMPONENT_FAILURE';
export const EDIT_COMPONENT_RESET: string = 'EDIT_COMPONENT_RESET';
export const EDIT_COMPONENT_REQUEST: string = 'EDIT_COMPONENT_REQUEST';
export const EDIT_COMPONENT_SWITCH: string = 'EDIT_COMPONENT_SWITCH';

//Delete a component
export const DELETE_COMPONENT_SUCCESS: string = 'DELETE_COMPONENT_SUCCESS';
export const DELETE_COMPONENT_FAILURE: string = 'DELETE_COMPONENT_FAILURE';
export const DELETE_COMPONENT_REQUEST: string = 'DELETE_COMPONENT_REQUEST';
export const DELETE_PROJECT_COMPONENTS: string = 'DELETE_PROJECT_COMPONENTS';

//Fetch Incidents of components
export const FETCH_COMPONENTS_INCIDENT_REQUEST =
    'FETCH_COMPONENTS_INCIDENT_REQUEST';
export const FETCH_COMPONENTS_INCIDENT_SUCCESS =
    'FETCH_COMPONENTS_INCIDENT_SUCCESS';
export const FETCH_COMPONENTS_INCIDENT_FAILURE =
    'FETCH_COMPONENTS_INCIDENT_FAILURE';

//Fetch Subscribers of components
export const FETCH_COMPONENTS_SUBSCRIBER_REQUEST =
    'FETCH_COMPONENTS_SUBSCRIBER_REQUEST';
export const FETCH_COMPONENTS_SUBSCRIBER_SUCCESS =
    'FETCH_COMPONENTS_SUBSCRIBER_SUCCESS';
export const FETCH_COMPONENTS_SUBSCRIBER_FAILURE =
    'FETCH_COMPONENTS_SUBSCRIBER_FAILURE';

export const REMOVE_COMPONENTS_SUBSCRIBERS: string =
    'REMOVE_COMPONENTS_SUBSCRIBERS';

export const ADD_COMPONENTS_SUBSCRIBERS: string = 'ADD_COMPONENTS_SUBSCRIBERS';

// Fetch Monitor Logs
export const FETCH_COMPONENT_LOGS_REQUEST: string =
    'FETCH_COMPONENT_LOGS_REQUEST';
export const FETCH_COMPONENT_LOGS_SUCCESS: string =
    'FETCH_COMPONENT_LOGS_SUCCESS';
export const FETCH_COMPONENT_LOGS_FAILURE: string =
    'FETCH_COMPONENT_LOGS_FAILURE';

// Fetch Monitor Statuses
export const FETCH_COMPONENT_STATUSES_REQUEST =
    'FETCH_COMPONENT_STATUSES_REQUEST';
export const FETCH_COMPONENT_STATUSES_SUCCESS =
    'FETCH_COMPONENT_STATUSES_SUCCESS';
export const FETCH_COMPONENT_STATUSES_FAILURE =
    'FETCH_COMPONENT_STATUSES_FAILURE';

// Fetch Monitor Logs list
export const GET_COMPONENT_LOGS_REQUEST: string = 'GET_COMPONENT_LOGS_REQUEST';
export const GET_COMPONENT_LOGS_SUCCESS: string = 'GET_COMPONENT_LOGS_SUCCESS';
export const GET_COMPONENT_LOGS_FAILURE: string = 'GET_COMPONENT_LOGS_FAILURE';
export const GET_COMPONENT_LOGS_RESET: string = 'GET_COMPONENT_LOGS_RESET';

// Fetch Monitor Criteria
export const FETCH_COMPONENT_CRITERIA_REQUEST =
    'FETCH_COMPONENT_CRITERIA_REQUEST';
export const FETCH_COMPONENT_CRITERIA_SUCCESS =
    'FETCH_COMPONENT_CRITERIA_SUCCESS';
export const FETCH_COMPONENT_CRITERIA_FAILURE =
    'FETCH_COMPONENT_CRITERIA_FAILURE';
export const SET_COMPONENT_CRITERIA: string = 'SET_COMPONENT_CRITERIA';

//Add seat
export const ADD_SEAT_SUCCESS: string = 'ADD_SEAT_SUCCESS';
export const ADD_SEAT_FAILURE: string = 'ADD_SEAT_FAILURE';
export const ADD_SEAT_REQUEST: string = 'ADD_SEAT_REQUEST';
export const ADD_SEAT_RESET: string = 'ADD_SEAT_RESET';

export const SELECT_PROBE: string = 'component/SELECT_PROBE';

//All Resources list
export const FETCH_COMPONENT_RESOURCES_REQUEST =
    'FETCH_COMPONENT_RESOURCES_REQUEST';
export const FETCH_COMPONENT_RESOURCES_SUCCESS =
    'FETCH_COMPONENT_RESOURCES_SUCCESS';
export const FETCH_COMPONENT_RESOURCES_FAILURE =
    'FETCH_COMPONENT_RESOURCES_FAILURE';
export const FETCH_COMPONENT_RESOURCES_RESET =
    'FETCH_COMPONENT_RESOURCES_RESET';

//Summary
export const FETCH_COMPONENT_SUMMARY_REQUEST =
    'FETCH_COMPONENT_SUMMARY_REQUEST';
export const FETCH_COMPONENT_SUMMARY_SUCCESS =
    'FETCH_COMPONENT_SUMMARY_SUCCESS';
export const FETCH_COMPONENT_SUMMARY_FAILURE =
    'FETCH_COMPONENT_SUMMARY_FAILURE';
export const FETCH_COMPONENT_SUMMARY_RESET: string =
    'FETCH_COMPONENT_SUMMARY_RESET';

// Modal
export const SHOW_DELETE_MODAL: string = 'SHOW_DELETE_MODAL';
export const HIDE_DELETE_MODAL: string = 'HIDE_DELETE_MODAL';

//currentComponent
export const ADD_CURRENT_COMPONENT: string = 'ADD_CURRENT_COMPONENT';

// fetch component by slug
export const FETCH_COMPONENT_REQUEST: string = 'FETCH_COMPONENT_REQUEST';
export const FETCH_COMPONENT_SUCCESS: string = 'FETCH_COMPONENT_SUCCESS';
export const FETCH_COMPONENT_FAILURE: string = 'FETCH_COMPONENT_FAILURE';
