export const ADD_GIT_CREDENTIAL_REQUEST = 'ADD_GIT_CREDENTIAL_REQUEST';
export const ADD_GIT_CREDENTIAL_SUCCESS = 'ADD_GIT_CREDENTIAL_SUCCESS';
export const ADD_GIT_CREDENTIAL_FAILURE = 'ADD_GIT_CREDENTIAL_FAILURE';
export const GET_GIT_CREDENTIALS_REQUEST = 'GET_GIT_CREDENTIALS_REQUEST';
export const GET_GIT_CREDENTIALS_SUCCESS = 'GET_GIT_CREDENTIALS_SUCCESS';
export const GET_GIT_CREDENTIALS_FAILURE = 'GET_GIT_CREDENTIALS_FAILURE';

export const ADD_DOCKER_CREDENTIAL_REQUEST = 'ADD_DOCKER_CREDENTIAL_REQUEST';
export const ADD_DOCKER_CREDENTIAL_SUCCESS = 'ADD_DOCKER_CREDENTIAL_SUCCESS';
export const ADD_DOCKER_CREDENTIAL_FAILURE = 'ADD_DOCKER_CREDENTIAL_FAILURE';
export const GET_DOCKER_CREDENTIALS_REQUEST = 'GET_DOCKER_CREDENTIALS_REQUEST';
export const GET_DOCKER_CREDENTIALS_SUCCESS = 'GET_DOCKER_CREDENTIALS_SUCCESS';
export const GET_DOCKER_CREDENTIALS_FAILURE = 'GET_DOCKER_CREDENTIALS_FAILURE';
