// Git Credential
export const ADD_GIT_CREDENTIAL_REQUEST: string = 'ADD_GIT_CREDENTIAL_REQUEST';
export const ADD_GIT_CREDENTIAL_SUCCESS: string = 'ADD_GIT_CREDENTIAL_SUCCESS';
export const ADD_GIT_CREDENTIAL_FAILURE: string = 'ADD_GIT_CREDENTIAL_FAILURE';
export const GET_GIT_CREDENTIALS_REQUEST: string =
    'GET_GIT_CREDENTIALS_REQUEST';
export const GET_GIT_CREDENTIALS_SUCCESS: string =
    'GET_GIT_CREDENTIALS_SUCCESS';
export const GET_GIT_CREDENTIALS_FAILURE: string =
    'GET_GIT_CREDENTIALS_FAILURE';
export const DELETE_GIT_CREDENTIAL_REQUEST: string =
    'DELETE_GIT_CREDENTIAL_REQUEST';
export const DELETE_GIT_CREDENTIAL_SUCCESS: string =
    'DELETE_GIT_CREDENTIAL_SUCCESS';
export const DELETE_GIT_CREDENTIAL_FAILURE: string =
    'DELETE_GIT_CREDENTIAL_FAILURE';
export const UPDATE_GIT_CREDENTIAL_REQUEST: string =
    'UPDATE_GIT_CREDENTIAL_REQUEST';
export const UPDATE_GIT_CREDENTIAL_SUCCESS: string =
    'UPDATE_GIT_CREDENTIAL_SUCCESS';
export const UPDATE_GIT_CREDENTIAL_FAILURE: string =
    'UPDATE_GIT_CREDENTIAL_FAILURE';

// Docker Credential
export const ADD_DOCKER_CREDENTIAL_REQUEST: string =
    'ADD_DOCKER_CREDENTIAL_REQUEST';
export const ADD_DOCKER_CREDENTIAL_SUCCESS: string =
    'ADD_DOCKER_CREDENTIAL_SUCCESS';
export const ADD_DOCKER_CREDENTIAL_FAILURE: string =
    'ADD_DOCKER_CREDENTIAL_FAILURE';
export const GET_DOCKER_CREDENTIALS_REQUEST: string =
    'GET_DOCKER_CREDENTIALS_REQUEST';
export const GET_DOCKER_CREDENTIALS_SUCCESS: string =
    'GET_DOCKER_CREDENTIALS_SUCCESS';
export const GET_DOCKER_CREDENTIALS_FAILURE: string =
    'GET_DOCKER_CREDENTIALS_FAILURE';
export const DELETE_DOCKER_CREDENTIAL_REQUEST: $TSFixMe =
    'DELETE_DOCKER_CREDENTIAL_REQUEST';
export const DELETE_DOCKER_CREDENTIAL_SUCCESS: $TSFixMe =
    'DELETE_DOCKER_CREDENTIAL_SUCCESS';
export const DELETE_DOCKER_CREDENTIAL_FAILURE: $TSFixMe =
    'DELETE_DOCKER_CREDENTIAL_FAILURE';
export const UPDATE_DOCKER_CREDENTIAL_REQUEST: $TSFixMe =
    'UPDATE_DOCKER_CREDENTIAL_REQUEST';
export const UPDATE_DOCKER_CREDENTIAL_SUCCESS: $TSFixMe =
    'UPDATE_DOCKER_CREDENTIAL_SUCCESS';
export const UPDATE_DOCKER_CREDENTIAL_FAILURE: $TSFixMe =
    'UPDATE_DOCKER_CREDENTIAL_FAILURE';

//get security based on credential
export const GET_GIT_SECURITIES_REQUEST: string = 'GET_GIT_SECURITIES_REQUEST';
export const GET_GIT_SECURITIES_SUCCESS: string = 'GET_GIT_SECURITIES_SUCCESS';
export const GET_GIT_SECURITIES_FAILURE: string = 'GET_GIT_SECURITIES_FAILURE';
export const GET_DOCKER_SECURITIES_REQUEST: string =
    'GET_DOCKER_SECURITIES_REQUEST';
export const GET_DOCKER_SECURITIES_SUCCESS: string =
    'GET_DOCKER_SECURITIES_SUCCESS';
export const GET_DOCKER_SECURITIES_FAILURE: string =
    'GET_DOCKER_SECURITIES_FAILURE';
