export const CREATE_CUSTOM_FIELD_REQUEST: string =
    'CREATE_CUSTOM_FIELD_REQUEST';
export const CREATE_CUSTOM_FIELD_SUCCESS: string =
    'CREATE_CUSTOM_FIELD_SUCCESS';
export const CREATE_CUSTOM_FIELD_FAILURE: string =
    'CREATE_CUSTOM_FIELD_FAILURE';

export const UPDATE_CUSTOM_FIELD_REQUEST: string =
    'UPDATE_CUSTOM_FIELD_REQUEST';
export const UPDATE_CUSTOM_FIELD_SUCCESS: string =
    'UPDATE_CUSTOM_FIELD_SUCCESS';
export const UPDATE_CUSTOM_FIELD_FAILURE: string =
    'UPDATE_CUSTOM_FIELD_FAILURE';

export const FETCH_CUSTOM_FIELDS_REQUEST: string =
    'FETCH_CUSTOM_FIELDS_REQUEST';
export const FETCH_CUSTOM_FIELDS_SUCCESS: string =
    'FETCH_CUSTOM_FIELDS_SUCCESS';
export const FETCH_CUSTOM_FIELDS_FAILURE: string =
    'FETCH_CUSTOM_FIELDS_FAILURE';

export const DELETE_CUSTOM_FIELD_REQUEST: string =
    'DELETE_CUSTOM_FIELD_REQUEST';
export const DELETE_CUSTOM_FIELD_SUCCESS: string =
    'DELETE_CUSTOM_FIELD_SUCCESS';
export const DELETE_CUSTOM_FIELD_FAILURE: string =
    'DELETE_CUSTOM_FIELD_FAILURE';

export const NEXT_PAGE: string = 'NEXT_PAGE';
export const PREV_PAGE: string = 'PREV_PAGE';
