export const CREATE_DOMAIN_REQUEST = 'CREATE_DOMAIN_REQUEST';
export const CREATE_DOMAIN_SUCCESS = 'CREATE_DOMAIN_SUCCESS';
export const CREATE_DOMAIN_FAILURE = 'CREATE_DOMAIN_FAILURE';

export const VERIFY_DOMAIN_REQUEST = 'VERIFY_DOMAIN_REQUEST';
export const VERIFY_DOMAIN_SUCCESS = 'VERIFY_DOMAIN_SUCCESS';
export const VERIFY_DOMAIN_FAILURE = 'VERIFY_DOMAIN_FAILURE';

export const DELETE_DOMAIN_REQUEST = 'DELETE_DOMAIN_REQUEST';
export const DELETE_DOMAIN_SUCCESS = 'DELETE_DOMAIN_SUCCESS';
export const DELETE_DOMAIN_FAILURE = 'DELETE_DOMAIN_FAILURE';