export const CREATE_DOMAIN_REQUEST: string = 'CREATE_DOMAIN_REQUEST';
export const CREATE_DOMAIN_SUCCESS: string = 'CREATE_DOMAIN_SUCCESS';
export const CREATE_DOMAIN_FAILURE: string = 'CREATE_DOMAIN_FAILURE';

export const VERIFY_DOMAIN_REQUEST: string = 'VERIFY_DOMAIN_REQUEST';
export const VERIFY_DOMAIN_SUCCESS: string = 'VERIFY_DOMAIN_SUCCESS';
export const VERIFY_DOMAIN_FAILURE: string = 'VERIFY_DOMAIN_FAILURE';
export const RESET_VERIFY_DOMAIN: string = 'RESET_VERIFY_DOMAIN';

export const DELETE_DOMAIN_REQUEST: string = 'DELETE_DOMAIN_REQUEST';
export const DELETE_DOMAIN_SUCCESS: string = 'DELETE_DOMAIN_SUCCESS';
export const DELETE_DOMAIN_FAILURE: string = 'DELETE_DOMAIN_FAILURE';

export const UPDATE_DOMAIN_REQUEST: string = 'UPDATE_DOMAIN_REQUEST';
export const UPDATE_DOMAIN_SUCCESS: string = 'UPDATE_DOMAIN_SUCCESS';
export const UPDATE_DOMAIN_FAILURE: string = 'UPDATE_DOMAIN_FAILURE';
