//Create new Error Tracker
export const CREATE_ERROR_TRACKER_SUCCESS = 'CREATE_ERROR_TRACKER_SUCCESS';
export const CREATE_ERROR_TRACKER_FAILURE = 'CREATE_ERROR_TRACKER_FAILURE';
export const CREATE_ERROR_TRACKER_RESET = 'CREATE_ERROR_TRACKER_RESET';
export const CREATE_ERROR_TRACKER_REQUEST = 'CREATE_ERROR_TRACKER_REQUEST';

// Error Tracker list
export const FETCH_ERROR_TRACKERS_REQUEST = 'FETCH_ERROR_TRACKERS_REQUEST';
export const FETCH_ERROR_TRACKERS_SUCCESS = 'FETCH_ERROR_TRACKERS_SUCCESS';
export const FETCH_ERROR_TRACKERS_FAILURE = 'FETCH_ERROR_TRACKERS_FAILURE';
export const FETCH_ERROR_TRACKERS_RESET = 'FETCH_ERROR_TRACKERS_RESET';

//Delete an Error Tracker
export const DELETE_ERROR_TRACKER_SUCCESS = 'DELETE_ERROR_TRACKER_SUCCESS';
export const DELETE_ERROR_TRACKER_FAILURE = 'DELETE_ERROR_TRACKER_FAILURE';
export const DELETE_ERROR_TRACKER_REQUEST = 'DELETE_ERROR_TRACKER_REQUEST';

// Fetch issues of an error tracker
export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';
export const FETCH_ISSUES_RESET = 'FETCH_ISSUES_RESET';

// Fetch details of an error event
export const FETCH_ERROR_EVENT_REQUEST = 'FETCH_ERROR_EVENT_REQUEST';
export const FETCH_ERROR_EVENT_SUCCESS = 'FETCH_ERROR_EVENT_SUCCESS';
export const FETCH_ERROR_EVENT_FAILURE = 'FETCH_ERROR_EVENT_FAILURE';
export const FETCH_ERROR_EVENT_RESET = 'FETCH_ERROR_EVENT_RESET';

export const SET_CURRENT_ERROR_EVENT = 'SET_CURRENT_ERROR_EVENT';

// edit an error tracker
export const EDIT_ERROR_TRACKER_SUCCESS = 'EDIT_ERROR_TRACKER_SUCCESS';
export const EDIT_ERROR_TRACKER_FAILURE = 'EDIT_ERROR_TRACKER_FAILURE';
export const EDIT_ERROR_TRACKER_RESET = 'EDIT_ERROR_TRACKER_RESET';
export const EDIT_ERROR_TRACKER_REQUEST = 'EDIT_ERROR_TRACKER_REQUEST';
export const EDIT_ERROR_TRACKER_SWITCH = 'EDIT_ERROR_TRACKER_SWITCH';

//Reset Log Container Key
export const RESET_ERROR_TRACKER_KEY_REQUEST =
    'RESET_ERROR_TRACKER_KEY_REQUEST';
export const RESET_ERROR_TRACKER_KEY_SUCCESS =
    'RESET_ERROR_TRACKER_KEY_SUCCESS';
export const RESET_ERROR_TRACKER_KEY_FAILURE =
    'RESET_ERROR_TRACKER_KEY_FAILURE';
export const RESET_ERROR_TRACKER_KEY_RESET = 'RESET_ERROR_TRACKER_KEY_RESET';

// ignore an issue
export const IGNORE_ERROR_EVENT_REQUEST = 'IGNORE_ERROR_EVENT_REQUEST';
export const IGNORE_ERROR_EVENT_SUCCESS = 'IGNORE_ERROR_EVENT_SUCCESS';
export const IGNORE_ERROR_EVENT_FAILURE = 'IGNORE_ERROR_EVENT_FAILURE';
export const IGNORE_ERROR_EVENT_RESET = 'IGNORE_ERROR_EVENT_RESET';

// unresolve an issue
export const UNRESOLVE_ERROR_EVENT_REQUEST = 'UNRESOLVE_ERROR_EVENT_REQUEST';
export const UNRESOLVE_ERROR_EVENT_SUCCESS = 'UNRESOLVE_ERROR_EVENT_SUCCESS';
export const UNRESOLVE_ERROR_EVENT_FAILURE = 'UNRESOLVE_ERROR_EVENT_FAILURE';
export const UNRESOLVE_ERROR_EVENT_RESET = 'UNRESOLVE_ERROR_EVENT_RESET';

// resolve an issue
export const RESOLVE_ERROR_EVENT_REQUEST = 'RESOLVE_ERROR_EVENT_REQUEST';
export const RESOLVE_ERROR_EVENT_SUCCESS = 'RESOLVE_ERROR_EVENT_SUCCESS';
export const RESOLVE_ERROR_EVENT_FAILURE = 'RESOLVE_ERROR_EVENT_FAILURE';
export const RESOLVE_ERROR_EVENT_RESET = 'RESOLVE_ERROR_EVENT_RESET';

// update the members related to an issue
export const UPDATE_ERROR_EVENT_MEMBER_REQUEST =
    'UPDATE_ERROR_EVENT_MEMBER_REQUEST';
export const UPDATE_ERROR_EVENT_MEMBER_SUCCESS =
    'UPDATE_ERROR_EVENT_MEMBER_SUCCESS';
export const UPDATE_ERROR_EVENT_MEMBER_FAILURE =
    'UPDATE_ERROR_EVENT_MEMBER_FAILURE';
export const UPDATE_ERROR_EVENT_MEMBER_RESET =
    'UPDATE_ERROR_EVENT_MEMBER_RESET';

// real time listener for new error event
export const NEW_ERROR_EVENT_SUCCESS = 'NEW_ERROR_EVENT_SUCCESS';
