//Create new Log container
export const CREATE_ERROR_TRACKER_SUCCESS = 'CREATE_ERROR_TRACKER_SUCCESS';
export const CREATE_ERROR_TRACKER_FAILURE = 'CREATE_ERROR_TRACKER_FAILURE';
export const CREATE_ERROR_TRACKER_RESET = 'CREATE_ERROR_TRACKER_RESET';
export const CREATE_ERROR_TRACKER_REQUEST = 'CREATE_ERROR_TRACKER_REQUEST';

// Error Tracker list
export const FETCH_ERROR_TRACKERS_REQUEST = 'FETCH_ERROR_TRACKERS_REQUEST';
export const FETCH_ERROR_TRACKERS_SUCCESS = 'FETCH_ERROR_TRACKERS_SUCCESS';
export const FETCH_ERROR_TRACKERS_FAILURE = 'FETCH_ERROR_TRACKERS_FAILURE';
export const FETCH_ERROR_TRACKERS_RESET = 'FETCH_ERROR_TRACKERS_RESET';

// Fetch issuees of an error tracker
export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';
export const FETCH_ISSUES_RESET = 'FETCH_ISSUES_RESET';
