//Create new Log container
export const CREATE_ERROR_TRACKER_SUCCESS = 'CREATE_ERROR_TRACKER_SUCCESS';
export const CREATE_ERROR_TRACKER_FAILURE = 'CREATE_ERROR_TRACKER_FAILURE';
export const CREATE_ERROR_TRACKER_RESET = 'CREATE_ERROR_TRACKER_RESET';
export const CREATE_ERROR_TRACKER_REQUEST = 'CREATE_ERROR_TRACKER_REQUEST';
