//Create new Error Tracker
export const CREATE_ERROR_TRACKER_SUCCESS: string =
    'CREATE_ERROR_TRACKER_SUCCESS';
export const CREATE_ERROR_TRACKER_FAILURE: string =
    'CREATE_ERROR_TRACKER_FAILURE';
export const CREATE_ERROR_TRACKER_RESET: string = 'CREATE_ERROR_TRACKER_RESET';
export const CREATE_ERROR_TRACKER_REQUEST: string =
    'CREATE_ERROR_TRACKER_REQUEST';

// Error Tracker list
export const FETCH_ERROR_TRACKERS_REQUEST: string =
    'FETCH_ERROR_TRACKERS_REQUEST';
export const FETCH_ERROR_TRACKERS_SUCCESS: string =
    'FETCH_ERROR_TRACKERS_SUCCESS';
export const FETCH_ERROR_TRACKERS_FAILURE: string =
    'FETCH_ERROR_TRACKERS_FAILURE';
export const FETCH_ERROR_TRACKERS_RESET: string = 'FETCH_ERROR_TRACKERS_RESET';

//Delete an Error Tracker
export const DELETE_ERROR_TRACKER_SUCCESS: string =
    'DELETE_ERROR_TRACKER_SUCCESS';
export const DELETE_ERROR_TRACKER_FAILURE: string =
    'DELETE_ERROR_TRACKER_FAILURE';
export const DELETE_ERROR_TRACKER_REQUEST: string =
    'DELETE_ERROR_TRACKER_REQUEST';

// Fetch issues of an error tracker
export const FETCH_ISSUES_REQUEST: string = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS: string = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE: string = 'FETCH_ISSUES_FAILURE';
export const FETCH_ISSUES_RESET: string = 'FETCH_ISSUES_RESET';

// Fetch details of an error event
export const FETCH_ERROR_EVENT_REQUEST: string = 'FETCH_ERROR_EVENT_REQUEST';
export const FETCH_ERROR_EVENT_SUCCESS: string = 'FETCH_ERROR_EVENT_SUCCESS';
export const FETCH_ERROR_EVENT_FAILURE: string = 'FETCH_ERROR_EVENT_FAILURE';
export const FETCH_ERROR_EVENT_RESET: string = 'FETCH_ERROR_EVENT_RESET';

export const SET_CURRENT_ERROR_EVENT: string = 'SET_CURRENT_ERROR_EVENT';

// Edit an error tracker
export const EDIT_ERROR_TRACKER_SUCCESS: string = 'EDIT_ERROR_TRACKER_SUCCESS';
export const EDIT_ERROR_TRACKER_FAILURE: string = 'EDIT_ERROR_TRACKER_FAILURE';
export const EDIT_ERROR_TRACKER_RESET: string = 'EDIT_ERROR_TRACKER_RESET';
export const EDIT_ERROR_TRACKER_REQUEST: string = 'EDIT_ERROR_TRACKER_REQUEST';
export const EDIT_ERROR_TRACKER_SWITCH: string = 'EDIT_ERROR_TRACKER_SWITCH';

//Reset Log Container Key
export const RESET_ERROR_TRACKER_KEY_REQUEST: $TSFixMe =
    'RESET_ERROR_TRACKER_KEY_REQUEST';
export const RESET_ERROR_TRACKER_KEY_SUCCESS: $TSFixMe =
    'RESET_ERROR_TRACKER_KEY_SUCCESS';
export const RESET_ERROR_TRACKER_KEY_FAILURE: $TSFixMe =
    'RESET_ERROR_TRACKER_KEY_FAILURE';
export const RESET_ERROR_TRACKER_KEY_RESET: string =
    'RESET_ERROR_TRACKER_KEY_RESET';

// Ignore an issue
export const IGNORE_ERROR_EVENT_REQUEST: string = 'IGNORE_ERROR_EVENT_REQUEST';
export const IGNORE_ERROR_EVENT_SUCCESS: string = 'IGNORE_ERROR_EVENT_SUCCESS';
export const IGNORE_ERROR_EVENT_FAILURE: string = 'IGNORE_ERROR_EVENT_FAILURE';
export const IGNORE_ERROR_EVENT_RESET: string = 'IGNORE_ERROR_EVENT_RESET';

// Unresolve an issue
export const UNRESOLVE_ERROR_EVENT_REQUEST: string =
    'UNRESOLVE_ERROR_EVENT_REQUEST';
export const UNRESOLVE_ERROR_EVENT_SUCCESS: string =
    'UNRESOLVE_ERROR_EVENT_SUCCESS';
export const UNRESOLVE_ERROR_EVENT_FAILURE: string =
    'UNRESOLVE_ERROR_EVENT_FAILURE';
export const UNRESOLVE_ERROR_EVENT_RESET: string =
    'UNRESOLVE_ERROR_EVENT_RESET';

// Resolve an issue
export const RESOLVE_ERROR_EVENT_REQUEST: string =
    'RESOLVE_ERROR_EVENT_REQUEST';
export const RESOLVE_ERROR_EVENT_SUCCESS: string =
    'RESOLVE_ERROR_EVENT_SUCCESS';
export const RESOLVE_ERROR_EVENT_FAILURE: string =
    'RESOLVE_ERROR_EVENT_FAILURE';
export const RESOLVE_ERROR_EVENT_RESET: string = 'RESOLVE_ERROR_EVENT_RESET';

// Update the members related to an issue
export const UPDATE_ERROR_EVENT_MEMBER_REQUEST: $TSFixMe =
    'UPDATE_ERROR_EVENT_MEMBER_REQUEST';
export const UPDATE_ERROR_EVENT_MEMBER_SUCCESS: $TSFixMe =
    'UPDATE_ERROR_EVENT_MEMBER_SUCCESS';
export const UPDATE_ERROR_EVENT_MEMBER_FAILURE: $TSFixMe =
    'UPDATE_ERROR_EVENT_MEMBER_FAILURE';
export const UPDATE_ERROR_EVENT_MEMBER_RESET: $TSFixMe =
    'UPDATE_ERROR_EVENT_MEMBER_RESET';

// Real time listener for new error event
export const NEW_ERROR_EVENT_SUCCESS: string = 'NEW_ERROR_EVENT_SUCCESS';

//Delete an Error Tracker Issue
export const DELETE_ERROR_TRACKER_ISSUE_SUCCESS: $TSFixMe =
    'DELETE_ERROR_TRACKER_ISSUE_SUCCESS';
export const DELETE_ERROR_TRACKER_ISSUE_FAILURE: $TSFixMe =
    'DELETE_ERROR_TRACKER_ISSUE_FAILURE';
export const DELETE_ERROR_TRACKER_ISSUE_REQUEST: $TSFixMe =
    'DELETE_ERROR_TRACKER_ISSUE_REQUEST';
