export const FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_REQUEST =
    'FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_REQUEST';
export const FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_SUCCESS =
    'FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_SUCCESS';
export const FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_FAILURE =
    'FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_FAILURE';

export const SET_REVEAL_VARIABLES_INCIDENT_BASIC_SETTINGS =
    'SET_REVEAL_VARIABLES_INCIDENT_BASIC_SETTINGS';

// FETCH ALL TEMPLATES IN A PROJECT
export const FETCH_INCIDENT_TEMPLATES_REQUEST =
    'FETCH_INCIDENT_TEMPLATES_REQUEST';
export const FETCH_INCIDENT_TEMPLATES_SUCCESS =
    'FETCH_INCIDENT_TEMPLATES_SUCCESS';
export const FETCH_INCIDENT_TEMPLATE_FAILURE =
    'FETCH_INCIDENT_TEMPLATES_FAILURE';

// CREATE TEMPLATE IN A PROJECT
export const CREATE_INCIDENT_TEMPLATE_REQUEST =
    'CREATE_INCIDENT_TEMPLATE_REQUEST';
export const CREATE_INCIDENT_TEMPLATE_SUCCESS =
    'CREATE_INCIDENT_TEMPLATE_SUCCESS';
export const CREATE_INCIDENT_TEMPLATE_FAILURE =
    'CREATE_INCIDENT_TEMPLATE_FAILURE';

// UPDATE A TEMPLATE IN A PROJECT
export const UPDATE_INCIDENT_TEMPLATE_REQUEST =
    'UPDATE_INCIDENT_TEMPLATE_REQUEST';
export const UPDATE_INCIDENT_TEMPALTE_SUCCESS =
    'UPDATE_INCIDENT_TEMPLATE_SUCCESS';
export const UPDATE_INCIDENT_TEMPLATE_FAILURE =
    'UPDATE_INCIDENT_TEMPLATE_FAILURE';

// DELETE A TEMPLATE IN A PROJECT
export const DELETE_INCIDENT_TEMPLATE_REQUEST =
    'DELETE_INCIDENT_TEMPLATE_REQUEST';
export const DELETE_INCIDENT_TEMPLATE_SUCCESS =
    'DELETE_INCIDENT_TEMPLATE_SUCCESS';
export const DELETE_INCIDENT_TEMPLATE_FAILURE =
    'DELETE_INCIDENT_TEMPLATE_FAILURE';

// SET DEFAULT INCIDENT TEMPLATE
export const SET_DEFAULT_INCIDENT_TEMPLATE_REQUEST =
    'SET_DEFAULT_INCIDENT_TEMPLATE_REQUEST';
export const SET_DEFAULT_INCIDENT_TEMPLATE_SUCCESS =
    'SET_DEFAULT_INCIDENT_TEMPLATE_SUCCESS';
export const SET_DEFAULT_INCIDENT_TEMPLATE_FAILURE =
    'SET_DEFAULT_INCIDENT_TEMPLATE_FAILURE';

// SET ACTIVE TEMPLATE
export const SET_ACTIVE_TEMPLATE = 'SET_ACTIVE_TEMPLATE';

// FETCH DEFAULT INCIDENT TEMPLATE
export const FETCH_DEFAULT_TEMPLATE_REQUEST = 'FETCH_DEFAULT_TEMPLATE_REQUEST';
export const FETCH_DEFAULT_TEMPLATE_SUCCESS = 'FETCH_DEFAULT_TEMPLATE_SUCCESS';
export const FETCH_DEFAULT_TEMPLATE_FAILURE = 'FETCH_DEFAULT_TEMPLATE_FAILURE';
