export const CREATE_INCIDENT_PRIORITY_REQUEST =
    'CREATE_INCIDENT_PRIORITY_REQUEST';
export const CREATE_INCIDENT_PRIORITY_SUCCESS =
    'CREATE_INCIDENT_PRIORITY_SUCCESS';
export const CREATE_INCIDENT_PRIORITY_FAILURE =
    'CREATE_INCIDENT_PRIORITY_FAILURE';
export const CREATE_INCIDENT_PRIORITY_RESET: string =
    'CREATE_INCIDENT_PRIORITY_RESET';

export const UPDATE_INCIDENT_PRIORITY_REQUEST =
    'UPDATE_INCIDENT_PRIORITY_REQUEST';
export const UPDATE_INCIDENT_PRIORITY_SUCCESS =
    'UPDATE_INCIDENT_PRIORITY_SUCCESS';
export const UPDATE_INCIDENT_PRIORITY_FAILURE =
    'UPDATE_INCIDENT_PRIORITY_FAILURE';
export const UPDATE_INCIDENT_PRIORITY_RESET: string =
    'UPDATE_INCIDENT_PRIORITY_RESET';

export const FETCH_INCIDENT_PRIORITIES_REQUEST =
    'FETCH_INCIDENT_PRIORITIES_REQUEST';
export const FETCH_INCIDENT_PRIORITIES_SUCCESS =
    'FETCH_INCIDENT_PRIORITIES_SUCCESS';
export const FETCH_INCIDENT_PRIORITIES_FAILURE =
    'FETCH_INCIDENT_PRIORITIES_FAILURE';
export const FETCH_INCIDENT_PRIORITIES_RESET =
    'FETCH_INCIDENT_PRIORITIES_RESET';

export const DELETE_INCIDENT_PRIORITY_REQUEST =
    'DELETE_INCIDENT_PRIORITY_REQUEST';
export const DELETE_INCIDENT_PRIORITY_SUCCESS =
    'DELETE_INCIDENT_PRIORITY_SUCCESS';
export const DELETE_INCIDENT_PRIORITY_FAILURE =
    'DELETE_INCIDENT_PRIORITY_FAILURE';
export const DELETE_INCIDENT_PRIORITY_RESET: string =
    'DELETE_INCIDENT_PRIORITY_RESET';
