export const CREATE_INCIDENT_PRIORITY_REQUEST: $TSFixMe =
    'CREATE_INCIDENT_PRIORITY_REQUEST';
export const CREATE_INCIDENT_PRIORITY_SUCCESS: $TSFixMe =
    'CREATE_INCIDENT_PRIORITY_SUCCESS';
export const CREATE_INCIDENT_PRIORITY_FAILURE: $TSFixMe =
    'CREATE_INCIDENT_PRIORITY_FAILURE';
export const CREATE_INCIDENT_PRIORITY_RESET: string =
    'CREATE_INCIDENT_PRIORITY_RESET';

export const UPDATE_INCIDENT_PRIORITY_REQUEST: $TSFixMe =
    'UPDATE_INCIDENT_PRIORITY_REQUEST';
export const UPDATE_INCIDENT_PRIORITY_SUCCESS: $TSFixMe =
    'UPDATE_INCIDENT_PRIORITY_SUCCESS';
export const UPDATE_INCIDENT_PRIORITY_FAILURE: $TSFixMe =
    'UPDATE_INCIDENT_PRIORITY_FAILURE';
export const UPDATE_INCIDENT_PRIORITY_RESET: string =
    'UPDATE_INCIDENT_PRIORITY_RESET';

export const FETCH_INCIDENT_PRIORITIES_REQUEST: $TSFixMe =
    'FETCH_INCIDENT_PRIORITIES_REQUEST';
export const FETCH_INCIDENT_PRIORITIES_SUCCESS: $TSFixMe =
    'FETCH_INCIDENT_PRIORITIES_SUCCESS';
export const FETCH_INCIDENT_PRIORITIES_FAILURE: $TSFixMe =
    'FETCH_INCIDENT_PRIORITIES_FAILURE';
export const FETCH_INCIDENT_PRIORITIES_RESET: $TSFixMe =
    'FETCH_INCIDENT_PRIORITIES_RESET';

export const DELETE_INCIDENT_PRIORITY_REQUEST: $TSFixMe =
    'DELETE_INCIDENT_PRIORITY_REQUEST';
export const DELETE_INCIDENT_PRIORITY_SUCCESS: $TSFixMe =
    'DELETE_INCIDENT_PRIORITY_SUCCESS';
export const DELETE_INCIDENT_PRIORITY_FAILURE: $TSFixMe =
    'DELETE_INCIDENT_PRIORITY_FAILURE';
export const DELETE_INCIDENT_PRIORITY_RESET: string =
    'DELETE_INCIDENT_PRIORITY_RESET';
