export const CREATE_INCIDENT_PRIORITY_REQUEST = 'CREATE_INCIDENT_PRIORITY_REQUEST';
export const CREATE_INCIDENT_PRIORITY_SUCCESS = 'CREATE_INCIDENT_PRIORITY_SUCCESS';
export const CREATE_INCIDENT_PRIORITY_FAILURE = 'CREATE_INCIDENT_PRIORITY_FAILURE';
export const CREATE_INCIDENT_PRIORITY_RESET = 'CREATE_INCIDENT_PRIORITY_RESET';

export const FETCH_INCIDENT_PRIORITIES_REQUEST = 'FETCH_INCIDENT_PRIORITIES_REQUEST';
export const FETCH_INCIDENT_PRIORITIES_SUCCESS = 'FETCH_INCIDENT_PRIORITIES_SUCCESS';
export const FETCH_INCIDENT_PRIORITIES_FAILURE = 'FETCH_INCIDENT_PRIORITIES_FAILURE';
export const FETCH_INCIDENT_PRIORITIES_RESET = 'FETCH_INCIDENT_PRIORITIES_RESET';
