// CREATE INCIDENT NOTE TEMPLATE
export const CREATE_INCIDENT_NOTE_TEMPLATE_REQUEST: $TSFixMe =
    'CREATE_INCIDENT_NOTE_TEMPLATE_REQUEST';
export const CREATE_INCIDENT_NOTE_TEMPLATE_SUCCESS: $TSFixMe =
    'CREATE_INCIDENT_NOTE_TEMPLATE_SUCCESS';
export const CREATE_INCIDENT_NOTE_TEMPLATE_FAILURE: $TSFixMe =
    'CREATE_INCIDENT_NOTE_TEMPLATE_FAILURE';

// FETCH INCIDENT NOTE TEMPLATES
export const FETCH_INCIDENT_NOTE_TEMPLATES_REQUEST: $TSFixMe =
    'FETCH_INCIDENT_NOTE_TEMPLATES_REQUEST';
export const FETCH_INCIDENT_NOTE_TEMPLATES_SUCCESS: $TSFixMe =
    'FETCH_INCIDENT_NOTE_TEMPLATES_SUCCESS';
export const FETCH_INCIDENT_NOTE_TEMPLATES_FAILURE: $TSFixMe =
    'FETCH_INCIDENT_NOTE_TEMPLATES_FAILURE';

// UPDATE INCIDENT NOTE TEMPLATE
export const UPDATE_INCIDENT_NOTE_TEMPLATE_REQUEST: $TSFixMe =
    'UPDATE_INCIDENT_NOTE_TEMPLATE_REQUEST';
export const UPDATE_INCIDENT_NOTE_TEMPLATE_SUCCESS: $TSFixMe =
    'UPDATE_INCIDENT_NOTE_TEMPLATE_SUCCESS';
export const UPDATE_INCIDENT_NOTE_TEMPLATE_FAILURE: $TSFixMe =
    'UPDATE_INCIDENT_NOTE_TEMPLATE_FAILURE';

// DELETE INCIDENT NOTE TEMPLATE
export const DELETE_INCIDENT_NOTE_TEMPLATE_REQUEST: $TSFixMe =
    'DELETE_INCIDENT_NOTE_TEMPLATE_REQUEST';
export const DELETE_INCIDENT_NOTE_TEMPLATE_SUCCESS: $TSFixMe =
    'DELETE_INCIDENT_NOTE_TEMPLATE_SUCCESS';
export const DELETE_INCIDENT_NOTE_TEMPLATE_FAILURE: $TSFixMe =
    'DELETE_INCIDENT_NOTE_TEMPLATE_FAILURE';
