// CREATE INCIDENT NOTE TEMPLATE
export const CREATE_INCIDENT_NOTE_TEMPLATE_REQUEST =
    'CREATE_INCIDENT_NOTE_TEMPLATE_REQUEST';
export const CREATE_INCIDENT_NOTE_TEMPLATE_SUCCESS =
    'CREATE_INCIDENT_NOTE_TEMPLATE_SUCCESS';
export const CREATE_INCIDENT_NOTE_TEMPLATE_FAILURE =
    'CREATE_INCIDENT_NOTE_TEMPLATE_FAILURE';

// FETCH INCIDENT NOTE TEMPLATES
export const FETCH_INCIDENT_NOTE_TEMPLATES_REQUEST =
    'FETCH_INCIDENT_NOTE_TEMPLATES_REQUEST';
export const FETCH_INCIDENT_NOTE_TEMPLATES_SUCCESS =
    'FETCH_INCIDENT_NOTE_TEMPLATES_SUCCESS';
export const FETCH_INCIDENT_NOTE_TEMPLATES_FAILURE =
    'FETCH_INCIDENT_NOTE_TEMPLATES_FAILURE';

// UPDATE INCIDENT NOTE TEMPLATE
export const UPDATE_INCIDENT_NOTE_TEMPLATE_REQUEST =
    'UPDATE_INCIDENT_NOTE_TEMPLATE_REQUEST';
export const UPDATE_INCIDENT_NOTE_TEMPLATE_SUCCESS =
    'UPDATE_INCIDENT_NOTE_TEMPLATE_SUCCESS';
export const UPDATE_INCIDENT_NOTE_TEMPLATE_FAILURE =
    'UPDATE_INCIDENT_NOTE_TEMPLATE_FAILURE';

// DELETE INCIDENT NOTE TEMPLATE
export const DELETE_INCIDENT_NOTE_TEMPLATE_REQUEST =
    'DELETE_INCIDENT_NOTE_TEMPLATE_REQUEST';
export const DELETE_INCIDENT_NOTE_TEMPLATE_SUCCESS =
    'DELETE_INCIDENT_NOTE_TEMPLATE_SUCCESS';
export const DELETE_INCIDENT_NOTE_TEMPLATE_FAILURE =
    'DELETE_INCIDENT_NOTE_TEMPLATE_FAILURE';
