export const CREATE_COMMUNICATION_SLA_REQUEST: $TSFixMe =
    'CREATE_COMMUNICATION_SLA_REQUEST';
export const CREATE_COMMUNICATION_SLA_SUCCESS: $TSFixMe =
    'CREATE_COMMUNICATION_SLA_SUCCESS';
export const CREATE_COMMUNICATION_SLA_FAILURE: $TSFixMe =
    'CREATE_COMMUNICATION_SLA_FAILURE';

export const UPDATE_COMMUNICATION_SLA_REQUEST: $TSFixMe =
    'UPDATE_COMMUNICATION_SLA_REQUEST';
export const UPDATE_COMMUNICATION_SLA_SUCCESS: $TSFixMe =
    'UPDATE_COMMUNICATION_SLA_SUCCESS';
export const UPDATE_COMMUNICATION_SLA_FAILURE: $TSFixMe =
    'UPDATE_COMMUNICATION_SLA_FAILURE';

export const FETCH_COMMUNICATION_SLAS_REQUEST: $TSFixMe =
    'FETCH_COMMUNICATION_SLAS_REQUEST';
export const FETCH_COMMUNICATION_SLAS_SUCCESS: $TSFixMe =
    'FETCH_COMMUNICATION_SLAS_SUCCESS';
export const FETCH_COMMUNICATION_SLAS_FAILURE: $TSFixMe =
    'FETCH_COMMUNICATION_SLAS_FAILURE';

export const DELETE_COMMUNICATION_SLA_REQUEST: $TSFixMe =
    'DELETE_COMMUNICATION_SLA_REQUEST';
export const DELETE_COMMUNICATION_SLA_SUCCESS: $TSFixMe =
    'DELETE_COMMUNICATION_SLA_SUCCESS';
export const DELETE_COMMUNICATION_SLA_FAILURE: $TSFixMe =
    'DELETE_COMMUNICATION_SLA_FAILURE';

export const SET_ACTIVE_SLA: string = 'SET_ACTIVE_SLA';

export const FETCH_DEFAULT_COMMUNICATION_SLA_REQUEST: $TSFixMe =
    'FETCH_DEFAULT_COMMUNICATION_SLA_REQUEST';
export const FETCH_DEFAULT_COMMUNICATION_SLA_SUCCESS: $TSFixMe =
    'FETCH_DEFAULT_COMMUNICATION_SLA_SUCCESS';
export const FETCH_DEFAULT_COMMUNICATION_SLA_FAILURE: $TSFixMe =
    'FETCH_DEFAULT_COMMUNICATION_SLA_FAILURE';
