//SubProjects Incidents

export const INCIDENTS_SUCCESS = 'incidents/INCIDENTS_SUCCESS';
export const INCIDENTS_FAILED = 'incidents/INCIDENTS_FAILED';
export const INCIDENTS_REQUEST = 'incidents/INCIDENTS_REQUEST';
export const INCIDENTS_RESET = 'incidents/INCIDENTS_RESET';


//Array of Incidents

export const PROJECT_INCIDENTS_SUCCESS = 'incidents/PROJECT_INCIDENTS_SUCCESS';
export const PROJECT_INCIDENTS_FAILED = 'incidents/PROJECT_INCIDENTS_FAILED';
export const PROJECT_INCIDENTS_REQUEST = 'incidents/PROJECT_INCIDENTS_REQUEST';
export const PROJECT_INCIDENTS_RESET = 'incidents/PROJECT_INCIDENTS_RESET';

// Create a new incident

export const CREATE_INCIDENT_SUCCESS = 'incidents/CREATE_INCIDENT_SUCCESS';
export const CREATE_INCIDENT_FAILED = 'incidents/CREATE_INCIDENT_FAILED';
export const CREATE_INCIDENT_REQUEST = 'incidents/CREATE_INCIDENT_REQUEST';
export const CREATE_INCIDENT_RESET = 'incidents/CREATE_INCIDENT_RESET';

// Incident portion

export const INCIDENT_SUCCESS = 'incident/INCIDENT_SUCCESS';
export const INCIDENT_FAILED = 'incident/INCIDENT_FAILED';
export const INCIDENT_REQUEST = 'incident/INCIDENT_REQUEST';
export const INCIDENT_RESET = 'incident/INCIDENT_RESET';
export const ACKNOWLEDGE_INCIDENT_SUCCESS = 'incident/ACKNOWLEDGE_INCIDENT_SUCCESS';
export const RESOLVE_INCIDENT_SUCCESS = 'incident/RESOLVE_INCIDENT_SUCCESS';
export const ACKNOWLEDGE_INCIDENT_REQUEST = 'incident/ACKNOWLEDGE_INCIDENT_REQUEST';
export const RESOLVE_INCIDENT_REQUEST = 'incident/RESOLVE_INCIDENT_REQUEST';

// Incident Timeline

export const INCIDENT_TIMELINE_REQUEST = 'incident/INCIDENT_TIMELINE_REQUEST';
export const INCIDENT_TIMELINE_SUCCESS = 'incident/INCIDENT_TIMELINE_SUCCESS';
export const INCIDENT_TIMELINE_FAILED = 'incident/INCIDENT_TIMELINE_FAILED';

// Unresolved Incidents Section

export const UNRESOLVED_INCIDENTS_SUCCESS = 'incidents/UNRESOLVED_INCIDENTS_SUCCESS';
export const UNRESOLVED_INCIDENTS_FAILED = 'incidents/UNRESOLVED_INCIDENTS_FAILED';
export const UNRESOLVED_INCIDENTS_REQUEST = 'incidents/UNRESOLVED_INCIDENTS_REQUEST';
export const UNRESOLVED_INCIDENTS_RESET = 'incidents/UNRESOLVED_INCIDENTS_RESET';

export const DELETE_PROJECT_INCIDENTS = 'incident/DELETE_PROJECT_INCIDENTS';

// Internal notes and investigation notes Section

export const INVESTIGATION_NOTE_SUCCESS = 'incidents/INVESTIGATION_NOTE_SUCCESS';
export const INVESTIGATION_NOTE_FAILED = 'incidents/INVESTIGATION_NOTE_FAILED';
export const INVESTIGATION_NOTE_REQUEST = 'incidents/INVESTIGATION_NOTE_REQUEST';

export const INTERNAL_NOTE_SUCCESS = 'incidents/INTERNAL_NOTE_SUCCESS';
export const INTERNAL_NOTE_FAILED = 'incidents/INTERNAL_NOTE_FAILED';
export const INTERNAL_NOTE_REQUEST = 'incidents/INTERNAL_NOTE_REQUEST';

export const CLOSE_INCIDENT_SUCCESS = 'incidents/CLOSE_INCIDENT_SUCCESS';
export const CLOSE_INCIDENT_FAILED = 'incidents/CLOSE_INCIDENT_FAILED';
export const CLOSE_INCIDENT_REQUEST = 'incidents/CLOSE_INCIDENT_REQUEST';

// Delete Incident
export const DELETE_INCIDENT_SUCCESS = 'incidents/DELETE_INCIDENT_SUCCESS';
export const DELETE_INCIDENT_REQUEST = 'incidents/DELETE_INCIDENT_REQUEST';
export const DELETE_INCIDENT_FAILURE = 'incidents/DELETE_INCIDENT_FAILURE';
export const DELETE_INCIDENT_RESET = 'incidents/DELETE_INCIDENT_RESET';