export const FETCH_INCIDENT_BASIC_SETTINGS_REQUEST =
    'FETCH_INCIDENT_BASIC_SETTINGS_REQUEST';
export const FETCH_INCIDENT_BASIC_SETTINGS_SUCCESS =
    'FETCH_INCIDENT_BASIC_SETTINGS_SUCCESS';
export const FETCH_INCIDENT_BASIC_SETTINGS_FAILURE =
    'FETCH_INCIDENT_BASIC_SETTINGS_FAILURE';

export const UPDATE_INCIDENT_BASIC_SETTINGS_REQUEST =
    'UPDATE_INCIDENT_BASIC_SETTINGS_REQUEST';
export const UPDATE_INCIDENT_BASIC_SETTINGS_SUCCESS =
    'UPDATE_INCIDENT_BASIC_SETTINGS_SUCCESS';
export const UPDATE_INCIDENT_BASIC_SETTINGS_FAILURE =
    'UPDATE_INCIDENT_BASIC_SETTINGS_FAILURE';
