export const CREATE_COMMUNICATION_SLA_REQUEST =
    'CREATE_COMMUNICATION_SLA_REQUEST';
export const CREATE_COMMUNICATION_SLA_SUCCESS =
    'CREATE_COMMUNICATION_SLA_SUCCESS';
export const CREATE_COMMUNICATION_SLA_FAILURE =
    'CREATE_COMMUNICATION_SLA_FAILURE';

export const UPDATE_COMMUNICATION_SLA_REQUEST =
    'UPDATE_COMMUNICATION_SLA_REQUEST';
export const UPDATE_COMMUNICATION_SLA_SUCCESS =
    'UPDATE_COMMUNICATION_SLA_SUCCESS';
export const UPDATE_COMMUNICATION_SLA_FAILURE =
    'UPDATE_COMMUNICATION_SLA_FAILURE';

export const FETCH_COMMUNICATION_SLAS_REQUEST =
    'FETCH_COMMUNICATION_SLAS_REQUEST';
export const FETCH_COMMUNICATION_SLAS_SUCCESS =
    'FETCH_COMMUNICATION_SLAS_SUCCESS';
export const FETCH_COMMUNICATION_SLAS_FAILURE =
    'FETCH_COMMUNICATION_SLAS_FAILURE';

export const DELETE_COMMUNICATION_SLA_REQUEST =
    'DELETE_COMMUNICATION_SLA_REQUEST';
export const DELETE_COMMUNICATION_SLA_SUCCESS =
    'DELETE_COMMUNICATION_SLA_SUCCESS';
export const DELETE_COMMUNICATION_SLA_FAILURE =
    'DELETE_COMMUNICATION_SLA_FAILURE';

export const  SET_ACTIVE_SLA: string = 'SET_ACTIVE_SLA';

export const FETCH_DEFAULT_COMMUNICATION_SLA_REQUEST =
    'FETCH_DEFAULT_COMMUNICATION_SLA_REQUEST';
export const FETCH_DEFAULT_COMMUNICATION_SLA_SUCCESS =
    'FETCH_DEFAULT_COMMUNICATION_SLA_SUCCESS';
export const FETCH_DEFAULT_COMMUNICATION_SLA_FAILURE =
    'FETCH_DEFAULT_COMMUNICATION_SLA_FAILURE';
