export const FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_REQUEST: $TSFixMe =
    'FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_REQUEST';
export const FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_SUCCESS: $TSFixMe =
    'FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_SUCCESS';
export const FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_FAILURE: $TSFixMe =
    'FETCH_INCIDENT_BASIC_SETTINGS_VARIABLES_FAILURE';

export const SET_REVEAL_VARIABLES_INCIDENT_BASIC_SETTINGS: $TSFixMe =
    'SET_REVEAL_VARIABLES_INCIDENT_BASIC_SETTINGS';

// FETCH ALL TEMPLATES IN A PROJECT
export const FETCH_INCIDENT_TEMPLATES_REQUEST: $TSFixMe =
    'FETCH_INCIDENT_TEMPLATES_REQUEST';
export const FETCH_INCIDENT_TEMPLATES_SUCCESS: $TSFixMe =
    'FETCH_INCIDENT_TEMPLATES_SUCCESS';
export const FETCH_INCIDENT_TEMPLATE_FAILURE: $TSFixMe =
    'FETCH_INCIDENT_TEMPLATES_FAILURE';

// CREATE TEMPLATE IN A PROJECT
export const CREATE_INCIDENT_TEMPLATE_REQUEST: $TSFixMe =
    'CREATE_INCIDENT_TEMPLATE_REQUEST';
export const CREATE_INCIDENT_TEMPLATE_SUCCESS: $TSFixMe =
    'CREATE_INCIDENT_TEMPLATE_SUCCESS';
export const CREATE_INCIDENT_TEMPLATE_FAILURE: $TSFixMe =
    'CREATE_INCIDENT_TEMPLATE_FAILURE';

// UPDATE A TEMPLATE IN A PROJECT
export const UPDATE_INCIDENT_TEMPLATE_REQUEST: $TSFixMe =
    'UPDATE_INCIDENT_TEMPLATE_REQUEST';
export const UPDATE_INCIDENT_TEMPALTE_SUCCESS: $TSFixMe =
    'UPDATE_INCIDENT_TEMPLATE_SUCCESS';
export const UPDATE_INCIDENT_TEMPLATE_FAILURE: $TSFixMe =
    'UPDATE_INCIDENT_TEMPLATE_FAILURE';

// DELETE A TEMPLATE IN A PROJECT
export const DELETE_INCIDENT_TEMPLATE_REQUEST: $TSFixMe =
    'DELETE_INCIDENT_TEMPLATE_REQUEST';
export const DELETE_INCIDENT_TEMPLATE_SUCCESS: $TSFixMe =
    'DELETE_INCIDENT_TEMPLATE_SUCCESS';
export const DELETE_INCIDENT_TEMPLATE_FAILURE: $TSFixMe =
    'DELETE_INCIDENT_TEMPLATE_FAILURE';

// SET DEFAULT INCIDENT TEMPLATE
export const SET_DEFAULT_INCIDENT_TEMPLATE_REQUEST: $TSFixMe =
    'SET_DEFAULT_INCIDENT_TEMPLATE_REQUEST';
export const SET_DEFAULT_INCIDENT_TEMPLATE_SUCCESS: $TSFixMe =
    'SET_DEFAULT_INCIDENT_TEMPLATE_SUCCESS';
export const SET_DEFAULT_INCIDENT_TEMPLATE_FAILURE: $TSFixMe =
    'SET_DEFAULT_INCIDENT_TEMPLATE_FAILURE';

// SET ACTIVE TEMPLATE
export const SET_ACTIVE_TEMPLATE: string = 'SET_ACTIVE_TEMPLATE';

// FETCH DEFAULT INCIDENT TEMPLATE
export const FETCH_DEFAULT_TEMPLATE_REQUEST: string =
    'FETCH_DEFAULT_TEMPLATE_REQUEST';
export const FETCH_DEFAULT_TEMPLATE_SUCCESS: string =
    'FETCH_DEFAULT_TEMPLATE_SUCCESS';
export const FETCH_DEFAULT_TEMPLATE_FAILURE: string =
    'FETCH_DEFAULT_TEMPLATE_FAILURE';
