export const CREATE_INCOMING_REQUEST_REQUEST: $TSFixMe =
    'CREATE_INCOMING_REQUEST_REQUEST';
export const CREATE_INCOMING_REQUEST_SUCCESS: $TSFixMe =
    'CREATE_INCOMING_REQUEST_SUCCESS';
export const CREATE_INCOMING_REQUEST_FAILURE: $TSFixMe =
    'CREATE_INCOMING_REQUEST_FAILURE';

export const EDIT_INCOMING_REQUEST_REQUEST: string =
    'EDIT_INCOMING_REQUEST_REQUEST';
export const EDIT_INCOMING_REQUEST_SUCCESS: string =
    'EDIT_INCOMING_REQUEST_SUCCESS';
export const EDIT_INCOMING_REQUEST_FAILURE: string =
    'EDIT_INCOMING_REQUEST_FAILURE';

export const DELETE_INCOMING_REQUEST_REQUEST: $TSFixMe =
    'DELETE_INCOMING_REQUEST_REQUEST';
export const DELETE_INCOMING_REQUEST_SUCCESS: $TSFixMe =
    'DELETE_INCOMING_REQUEST_SUCCESS';
export const DELETE_INCOMING_REQUEST_FAILURE: $TSFixMe =
    'DELETE_INCOMING_REQUEST_FAILURE';

export const FETCH_ALL_INCOMING_REQUEST_REQUEST: $TSFixMe =
    'FETCH_ALL_INCOMING_REQUEST_REQUEST';
export const FETCH_ALL_INCOMING_REQUEST_SUCCESS: $TSFixMe =
    'FETCH_ALL_INCOMING_REQUEST_SUCCESS';
export const FETCH_ALL_INCOMING_REQUEST_FAILURE: $TSFixMe =
    'FETCH_ALL_INCOMING_REQUEST_FAILURE';

export const SET_ACTIVE_INCOMING_REQUEST: string =
    'SET_ACTIVE_INCOMING_REQUEST';
