export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAILED = 'GET_INVOICE_FAILED';
export const GET_INVOICE_REQUEST = 'GET_INVOICE_REQUEST';
export const GET_INVOICE_RESET = 'GET_INVOICE_RESET';
export const INCREMENT_NEXT_COUNT = 'INCREMENT_NEXT_COUNT';
export const DECREMENT_NEXT_COUNT = 'DECREMENT_NEXT_COUNT';
