export const CREATE_CUSTOM_FIELD_REQUEST: $TSFixMe =
    'CREATE_MONITOR_CUSTOM_FIELD_REQUEST';
export const CREATE_CUSTOM_FIELD_SUCCESS: $TSFixMe =
    'CREATE_MONITOR_CUSTOM_FIELD_SUCCESS';
export const CREATE_CUSTOM_FIELD_FAILURE: $TSFixMe =
    'CREATE_MONITOR_CUSTOM_FIELD_FAILURE';

export const UPDATE_CUSTOM_FIELD_REQUEST: $TSFixMe =
    'UPDATE_MONITOR_CUSTOM_FIELD_REQUEST';
export const UPDATE_CUSTOM_FIELD_SUCCESS: $TSFixMe =
    'UPDATE_MONITOR_CUSTOM_FIELD_SUCCESS';
export const UPDATE_CUSTOM_FIELD_FAILURE: $TSFixMe =
    'UPDATE_MONITOR_CUSTOM_FIELD_FAILURE';

export const FETCH_CUSTOM_FIELDS_REQUEST: $TSFixMe =
    'FETCH_MONITOR_CUSTOM_FIELDS_REQUEST';
export const FETCH_CUSTOM_FIELDS_SUCCESS: $TSFixMe =
    'FETCH_MONITOR_CUSTOM_FIELDS_SUCCESS';
export const FETCH_CUSTOM_FIELDS_FAILURE: $TSFixMe =
    'FETCH_MONITOR_CUSTOM_FIELDS_FAILURE';

export const DELETE_CUSTOM_FIELD_REQUEST: $TSFixMe =
    'DELETE_MONITOR_CUSTOM_FIELD_REQUEST';
export const DELETE_CUSTOM_FIELD_SUCCESS: $TSFixMe =
    'DELETE_MONITOR_CUSTOM_FIELD_SUCCESS';
export const DELETE_CUSTOM_FIELD_FAILURE: $TSFixMe =
    'DELETE_MONITOR_CUSTOM_FIELD_FAILURE';
