export const CREATE_MONITOR_SLA_REQUEST = 'CREATE_MONITOR_SLA_REQUEST';
export const CREATE_MONITOR_SLA_SUCCESS = 'CREATE_MONITOR_SLA_SUCCESS';
export const CREATE_MONITOR_SLA_FAILURE = 'CREATE_MONITOR_SLA_FAILURE';

export const UPDATE_MONITOR_SLA_REQUEST = 'UPDATE_MONITOR_SLA_REQUEST';
export const UPDATE_MONITOR_SLA_SUCCESS = 'UPDATE_MONITOR_SLA_SUCCESS';
export const UPDATE_MONITOR_SLA_FAILURE = 'UPDATE_MONITOR_SLA_FAILURE';

export const FETCH_MONITOR_SLAS_REQUEST = 'FETCH_MONITOR_SLAS_REQUEST';
export const FETCH_MONITOR_SLAS_SUCCESS = 'FETCH_MONITOR_SLAS_SUCCESS';
export const FETCH_MONITOR_SLAS_FAILURE = 'FETCH_MONITOR_SLAS_FAILURE';

export const DELETE_MONITOR_SLA_REQUEST = 'DELETE_MONITOR_SLA_REQUEST';
export const DELETE_MONITOR_SLA_SUCCESS = 'DELETE_MONITOR_SLA_SUCCESS';
export const DELETE_MONITOR_SLA_FAILURE = 'DELETE_MONITOR_SLA_FAILURE';

export const SET_ACTIVE_MONITOR_SLA = 'SET_ACTIVE_MONITOR_SLA';

export const FETCH_DEFAULT_MONITOR_SLA_REQUEST =
    'FETCH_DEFAULT_MONITOR_SLA_REQUEST';
export const FETCH_DEFAULT_MONITOR_SLA_SUCCESS =
    'FETCH_DEFAULT_MONITOR_SLA_SUCCESS';
export const FETCH_DEFAULT_MONITOR_SLA_FAILURE =
    'FETCH_DEFAULT_MONITOR_SLA_FAILURE';
export const NEXT_MONITOR_SLA_PAGE = 'NEXT_MONITOR_SLA_PAGE';
export const PREV_MONITOR_SLA_PAGE = 'PREV_MONITOR_SLA_PAGE';
