export const CREATE_CUSTOM_FIELD_REQUEST =
    'CREATE_MONITOR_CUSTOM_FIELD_REQUEST';
export const CREATE_CUSTOM_FIELD_SUCCESS =
    'CREATE_MONITOR_CUSTOM_FIELD_SUCCESS';
export const CREATE_CUSTOM_FIELD_FAILURE =
    'CREATE_MONITOR_CUSTOM_FIELD_FAILURE';

export const UPDATE_CUSTOM_FIELD_REQUEST =
    'UPDATE_MONITOR_CUSTOM_FIELD_REQUEST';
export const UPDATE_CUSTOM_FIELD_SUCCESS =
    'UPDATE_MONITOR_CUSTOM_FIELD_SUCCESS';
export const UPDATE_CUSTOM_FIELD_FAILURE =
    'UPDATE_MONITOR_CUSTOM_FIELD_FAILURE';

export const FETCH_CUSTOM_FIELDS_REQUEST =
    'FETCH_MONITOR_CUSTOM_FIELDS_REQUEST';
export const FETCH_CUSTOM_FIELDS_SUCCESS =
    'FETCH_MONITOR_CUSTOM_FIELDS_SUCCESS';
export const FETCH_CUSTOM_FIELDS_FAILURE =
    'FETCH_MONITOR_CUSTOM_FIELDS_FAILURE';

export const DELETE_CUSTOM_FIELD_REQUEST =
    'DELETE_MONITOR_CUSTOM_FIELD_REQUEST';
export const DELETE_CUSTOM_FIELD_SUCCESS =
    'DELETE_MONITOR_CUSTOM_FIELD_SUCCESS';
export const DELETE_CUSTOM_FIELD_FAILURE =
    'DELETE_MONITOR_CUSTOM_FIELD_FAILURE';
