export const CREATE_MONITOR_SLA_REQUEST: string = 'CREATE_MONITOR_SLA_REQUEST';
export const CREATE_MONITOR_SLA_SUCCESS: string = 'CREATE_MONITOR_SLA_SUCCESS';
export const CREATE_MONITOR_SLA_FAILURE: string = 'CREATE_MONITOR_SLA_FAILURE';

export const UPDATE_MONITOR_SLA_REQUEST: string = 'UPDATE_MONITOR_SLA_REQUEST';
export const UPDATE_MONITOR_SLA_SUCCESS: string = 'UPDATE_MONITOR_SLA_SUCCESS';
export const UPDATE_MONITOR_SLA_FAILURE: string = 'UPDATE_MONITOR_SLA_FAILURE';

export const FETCH_MONITOR_SLAS_REQUEST: string = 'FETCH_MONITOR_SLAS_REQUEST';
export const FETCH_MONITOR_SLAS_SUCCESS: string = 'FETCH_MONITOR_SLAS_SUCCESS';
export const FETCH_MONITOR_SLAS_FAILURE: string = 'FETCH_MONITOR_SLAS_FAILURE';

export const DELETE_MONITOR_SLA_REQUEST: string = 'DELETE_MONITOR_SLA_REQUEST';
export const DELETE_MONITOR_SLA_SUCCESS: string = 'DELETE_MONITOR_SLA_SUCCESS';
export const DELETE_MONITOR_SLA_FAILURE: string = 'DELETE_MONITOR_SLA_FAILURE';

export const SET_ACTIVE_MONITOR_SLA: string = 'SET_ACTIVE_MONITOR_SLA';

export const FETCH_DEFAULT_MONITOR_SLA_REQUEST: $TSFixMe =
    'FETCH_DEFAULT_MONITOR_SLA_REQUEST';
export const FETCH_DEFAULT_MONITOR_SLA_SUCCESS: $TSFixMe =
    'FETCH_DEFAULT_MONITOR_SLA_SUCCESS';
export const FETCH_DEFAULT_MONITOR_SLA_FAILURE: $TSFixMe =
    'FETCH_DEFAULT_MONITOR_SLA_FAILURE';
export const NEXT_MONITOR_SLA_PAGE: string = 'NEXT_MONITOR_SLA_PAGE';
export const PREV_MONITOR_SLA_PAGE: string = 'PREV_MONITOR_SLA_PAGE';
