//Monitor Category list
export const FETCH_MONITOR_CATEGORIES_REQUEST = 'FETCH_MONITOR_CATEGORIES_REQUEST';
export const FETCH_MONITOR_CATEGORIES_SUCCESS = 'FETCH_MONITOR_CATEGORIES_SUCCESS';
export const FETCH_MONITOR_CATEGORIES_FAILURE = 'FETCH_MONITOR_CATEGORIES_FAILURE';

//Create new monitor Category
export const CREATE_MONITOR_CATEGORY_SUCCESS = 'CREATE_MONITOR_CATEGORY_SUCCESS';
export const CREATE_MONITOR_CATEGORY_FAILURE = 'CREATE_MONITOR_CATEGORY_FAILURE';
export const CREATE_MONITOR_CATEGORY_REQUEST = 'CREATE_MONITOR_CATEGORY_REQUEST';

//Delete a monitor Category
export const DELETE_MONITOR_CATEGORY_SUCCESS = 'DELETE_MONITOR_CATEGORY_SUCCESS';
export const DELETE_MONITOR_CATEGORY_FAILURE = 'DELETE_MONITOR_CATEGORY_FAILURE';
export const DELETE_MONITOR_CATEGORY_REQUEST = 'DELETE_MONITOR_CATEGORY_REQUEST';

// Full Monitor Category list for project settings
export const FETCH_MONITOR_CATEGORIES_FOR_NEW_MONITOR_REQUEST = 'FETCH_MONITOR_CATEGORIES_FOR_NEW_MONITOR_REQUEST';
export const FETCH_MONITOR_CATEGORIES_FOR_NEW_MONITOR_SUCCESS = 'FETCH_MONITOR_CATEGORIES_FOR_NEW_MONITOR_SUCCESS';
export const FETCH_MONITOR_CATEGORIES_FOR_NEW_MONITOR_FAILURE = 'FETCH_MONITOR_CATEGORIES_FOR_NEW_MONITOR_FAILURE';
