//Monitor list
export const FETCH_MONITORS_REQUEST = 'FETCH_MONITORS_REQUEST';
export const FETCH_MONITORS_SUCCESS = 'FETCH_MONITORS_SUCCESS';
export const FETCH_MONITORS_FAILURE = 'FETCH_MONITORS_FAILURE';
export const FETCH_MONITORS_RESET = 'FETCH_MONITORS_RESET';

//Create new monitor
export const CREATE_MONITOR_SUCCESS = 'CREATE_MONITOR_SUCCESS';
export const CREATE_MONITOR_FAILURE = 'CREATE_MONITOR_FAILURE';
export const CREATE_MONITOR_RESET = 'CREATE_MONITOR_RESET';
export const CREATE_MONITOR_REQUEST = 'CREATE_MONITOR_REQUEST';

//Edit new monitor
export const EDIT_MONITOR_SUCCESS = 'EDIT_MONITOR_SUCCESS';
export const EDIT_MONITOR_FAILURE = 'EDIT_MONITOR_FAILURE';
export const EDIT_MONITOR_RESET = 'EDIT_MONITOR_RESET';
export const EDIT_MONITOR_REQUEST = 'EDIT_MONITOR_REQUEST';
export const EDIT_MONITOR_SWITCH = 'EDIT_MONITOR_SWITCH';

//Delete a monitor
export const DELETE_MONITOR_SUCCESS = 'DELETE_MONITOR_SUCCESS';
export const DELETE_MONITOR_FAILURE = 'DELETE_MONITOR_FAILURE';
export const DELETE_MONITOR_REQUEST = 'DELETE_MONITOR_REQUEST';
export const DELETE_PROJECT_MONITORS = 'DELETE_PROJECT_MONITORS';

//Fetch Incidents of monitors
export const FETCH_MONITORS_INCIDENT_REQUEST =
    'FETCH_MONITORS_INCIDENT_REQUEST';
export const FETCH_MONITORS_INCIDENT_SUCCESS =
    'FETCH_MONITORS_INCIDENT_SUCCESS';
export const FETCH_MONITORS_INCIDENT_FAILURE =
    'FETCH_MONITORS_INCIDENT_FAILURE';

//Fetch Subscribers of monitors
export const FETCH_MONITORS_SUBSCRIBER_REQUEST =
    'FETCH_MONITORS_SUBSCRIBER_REQUEST';
export const FETCH_MONITORS_SUBSCRIBER_SUCCESS =
    'FETCH_MONITORS_SUBSCRIBER_SUCCESS';
export const FETCH_MONITORS_SUBSCRIBER_FAILURE =
    'FETCH_MONITORS_SUBSCRIBER_FAILURE';

export const REMOVE_MONITORS_SUBSCRIBERS = 'REMOVE_MONITORS_SUBSCRIBERS';

export const ADD_MONITORS_SUBSCRIBERS = 'ADD_MONITORS_SUBSCRIBERS';

// Fetch Monitor Logs
export const FETCH_MONITOR_LOGS_REQUEST = 'FETCH_MONITOR_LOGS_REQUEST';
export const FETCH_MONITOR_LOGS_SUCCESS = 'FETCH_MONITOR_LOGS_SUCCESS';
export const FETCH_MONITOR_LOGS_FAILURE = 'FETCH_MONITOR_LOGS_FAILURE';

// Fetch Monitor Statuses
export const FETCH_MONITOR_STATUSES_REQUEST = 'FETCH_MONITOR_STATUSES_REQUEST';
export const FETCH_MONITOR_STATUSES_SUCCESS = 'FETCH_MONITOR_STATUSES_SUCCESS';
export const FETCH_MONITOR_STATUSES_FAILURE = 'FETCH_MONITOR_STATUSES_FAILURE';

// Fetch Monitor Logs list
export const GET_MONITOR_LOGS_REQUEST = 'GET_MONITOR_LOGS_REQUEST';
export const GET_MONITOR_LOGS_SUCCESS = 'GET_MONITOR_LOGS_SUCCESS';
export const GET_MONITOR_LOGS_FAILURE = 'GET_MONITOR_LOGS_FAILURE';
export const GET_MONITOR_LOGS_RESET = 'GET_MONITOR_LOGS_RESET';

// Fetch Monitor Criteria
export const FETCH_MONITOR_CRITERIA_REQUEST = 'FETCH_MONITOR_CRITERIA_REQUEST';
export const FETCH_MONITOR_CRITERIA_SUCCESS = 'FETCH_MONITOR_CRITERIA_SUCCESS';
export const FETCH_MONITOR_CRITERIA_FAILURE = 'FETCH_MONITOR_CRITERIA_FAILURE';
export const SET_MONITOR_CRITERIA = 'SET_MONITOR_CRITERIA';

//Add seat
export const ADD_SEAT_SUCCESS = 'ADD_SEAT_SUCCESS';
export const ADD_SEAT_FAILURE = 'ADD_SEAT_FAILURE';
export const ADD_SEAT_REQUEST = 'ADD_SEAT_REQUEST';
export const ADD_SEAT_RESET = 'ADD_SEAT_RESET';

export const SELECT_PROBE = 'monitor/SELECT_PROBE';
