//Monitor list
export const  FETCH_MONITORS_REQUEST: string = 'FETCH_MONITORS_REQUEST';
export const  FETCH_MONITORS_SUCCESS: string = 'FETCH_MONITORS_SUCCESS';
export const  FETCH_MONITORS_FAILURE: string = 'FETCH_MONITORS_FAILURE';
export const  FETCH_MONITORS_RESET: string = 'FETCH_MONITORS_RESET';

export const FETCH_PAGINATED_MONITORS_REQUEST =
    'FETCH_PAGINATED_MONITORS_REQUEST';
export const FETCH_PAGINATED_MONITORS_SUCCESS =
    'FETCH_PAGINATED_MONITORS_SUCCESS';
export const FETCH_PAGINATED_MONITORS_FAILURE =
    'FETCH_PAGINATED_MONITORS_FAILURE';

//Create new monitor
export const  CREATE_MONITOR_SUCCESS: string = 'CREATE_MONITOR_SUCCESS';
export const  CREATE_MONITOR_FAILURE: string = 'CREATE_MONITOR_FAILURE';
export const  CREATE_MONITOR_RESET: string = 'CREATE_MONITOR_RESET';
export const  CREATE_MONITOR_REQUEST: string = 'CREATE_MONITOR_REQUEST';

//Edit new monitor
export const  EDIT_MONITOR_SUCCESS: string = 'EDIT_MONITOR_SUCCESS';
export const  EDIT_MONITOR_FAILURE: string = 'EDIT_MONITOR_FAILURE';
export const  EDIT_MONITOR_RESET: string = 'EDIT_MONITOR_RESET';
export const  EDIT_MONITOR_REQUEST: string = 'EDIT_MONITOR_REQUEST';
export const  EDIT_MONITOR_SWITCH: string = 'EDIT_MONITOR_SWITCH';
//Delete a monitor
export const  DELETE_MONITOR_SUCCESS: string = 'DELETE_MONITOR_SUCCESS';
export const  DELETE_MONITOR_FAILURE: string = 'DELETE_MONITOR_FAILURE';
export const  DELETE_MONITOR_REQUEST: string = 'DELETE_MONITOR_REQUEST';
export const  DELETE_PROJECT_MONITORS: string = 'DELETE_PROJECT_MONITORS';

//Disable a monitor
export const  DISABLE_MONITOR_SUCCESS: string = 'DISABLE_MONITOR_SUCCESS';
export const  DISABLE_MONITOR_FAILURE: string = 'DISABLE_MONITOR_FAILURE';
export const  DISABLE_MONITOR_REQUEST: string = 'DISABLE_MONITOR_REQUEST';

//Move monitor to new component
export const CHANGE_MONITOR_COMPONENT_SUCCESS =
    'CHANGE_MONITOR_COMPONENT_SUCCESS';
export const CHANGE_MONITOR_COMPONENT_FAILURE =
    'CHANGE_MONITOR_COMPONENT_FAILURE';
export const CHANGE_MONITOR_COMPONENT_REQUEST =
    'CHANGE_MONITOR_COMPONENT_REQUEST';

//Fetch Incidents of monitors
export const FETCH_MONITORS_INCIDENT_REQUEST =
    'FETCH_MONITORS_INCIDENT_REQUEST';
export const FETCH_MONITORS_INCIDENT_SUCCESS =
    'FETCH_MONITORS_INCIDENT_SUCCESS';
export const FETCH_MONITORS_INCIDENT_FAILURE =
    'FETCH_MONITORS_INCIDENT_FAILURE';

//Fetch Subscribers of monitors
export const FETCH_MONITORS_SUBSCRIBER_REQUEST =
    'FETCH_MONITORS_SUBSCRIBER_REQUEST';
export const FETCH_MONITORS_SUBSCRIBER_SUCCESS =
    'FETCH_MONITORS_SUBSCRIBER_SUCCESS';
export const FETCH_MONITORS_SUBSCRIBER_FAILURE =
    'FETCH_MONITORS_SUBSCRIBER_FAILURE';

export const  REMOVE_MONITORS_SUBSCRIBERS: string = 'REMOVE_MONITORS_SUBSCRIBERS';

export const  ADD_MONITORS_SUBSCRIBERS: string = 'ADD_MONITORS_SUBSCRIBERS';

// Fetch Monitor Logs
export const  FETCH_MONITOR_LOGS_REQUEST: string = 'FETCH_MONITOR_LOGS_REQUEST';
export const  FETCH_MONITOR_LOGS_SUCCESS: string = 'FETCH_MONITOR_LOGS_SUCCESS';
export const  FETCH_MONITOR_LOGS_FAILURE: string = 'FETCH_MONITOR_LOGS_FAILURE';

// Fetch Monitor Statuses
export const  FETCH_MONITOR_STATUSES_REQUEST: string = 'FETCH_MONITOR_STATUSES_REQUEST';
export const  FETCH_MONITOR_STATUSES_SUCCESS: string = 'FETCH_MONITOR_STATUSES_SUCCESS';
export const  FETCH_MONITOR_STATUSES_FAILURE: string = 'FETCH_MONITOR_STATUSES_FAILURE';

// Fetch Monitor Logs list
export const  GET_MONITOR_LOGS_REQUEST: string = 'GET_MONITOR_LOGS_REQUEST';
export const  GET_MONITOR_LOGS_SUCCESS: string = 'GET_MONITOR_LOGS_SUCCESS';
export const  GET_MONITOR_LOGS_FAILURE: string = 'GET_MONITOR_LOGS_FAILURE';
export const  GET_MONITOR_LOGS_RESET: string = 'GET_MONITOR_LOGS_RESET';

// Fetch Lighthouse Logs
export const  FETCH_LIGHTHOUSE_LOGS_REQUEST: string = 'FETCH_LIGHTHOUSE_LOGS_REQUEST';
export const  FETCH_LIGHTHOUSE_LOGS_SUCCESS: string = 'FETCH_LIGHTHOUSE_LOGS_SUCCESS';
export const  FETCH_LIGHTHOUSE_LOGS_FAILURE: string = 'FETCH_LIGHTHOUSE_LOGS_FAILURE';

// Fetch Monitor Issue
export const  FETCH_MONITOR_ISSUE_REQUEST: string = 'FETCH_MONITOR_ISSUE_REQUEST';
export const  FETCH_MONITOR_ISSUE_SUCCESS: string = 'FETCH_MONITOR_ISSUE_SUCCESS';
export const  FETCH_MONITOR_ISSUE_FAILURE: string = 'FETCH_MONITOR_ISSUE_FAILURE';

// Fetch Monitor Criteria
export const  FETCH_MONITOR_CRITERIA_REQUEST: string = 'FETCH_MONITOR_CRITERIA_REQUEST';
export const  FETCH_MONITOR_CRITERIA_SUCCESS: string = 'FETCH_MONITOR_CRITERIA_SUCCESS';
export const  FETCH_MONITOR_CRITERIA_FAILURE: string = 'FETCH_MONITOR_CRITERIA_FAILURE';
export const  SET_MONITOR_CRITERIA: string = 'SET_MONITOR_CRITERIA';

//Add seat
export const  ADD_SEAT_SUCCESS: string = 'ADD_SEAT_SUCCESS';
export const  ADD_SEAT_FAILURE: string = 'ADD_SEAT_FAILURE';
export const  ADD_SEAT_REQUEST: string = 'ADD_SEAT_REQUEST';
export const  ADD_SEAT_RESET: string = 'ADD_SEAT_RESET';

export const  SELECT_PROBE: string = 'monitor/SELECT_PROBE';

// toggle
export const  TOGGLE_EDIT: string = 'TOGGLE_EDIT';

// close breached monitor sla
export const CLOSE_BREACHED_MONITOR_SLA_REQUEST =
    'CLOSE_BREACHED_MONITOR_SLA_REQUEST';
export const CLOSE_BREACHED_MONITOR_SLA_SUCCESS =
    'CLOSE_BREACHED_MONITOR_SLA_SUCCESS';
export const CLOSE_BREACHED_MONITOR_SLA_FAILURE =
    'CLOSE_BREACHED_MONITOR_SLA_FAILURE';

// get breached monitor sla
export const FETCH_BREACHED_MONITOR_SLA_REQUEST =
    'FETCH_BREACHED_MONITOR_SLA_REQUEST';
export const FETCH_BREACHED_MONITOR_SLA_SUCCESS =
    'FETCH_BREACHED_MONITOR_SLA_SUCCESS';
export const FETCH_BREACHED_MONITOR_SLA_FAILURE =
    'FETCH_BREACHED_MONITOR_SLA_FAILURE';

// identity file
export const  UPLOAD_IDENTITY_FILE_REQUEST: string = 'UPLOAD_IDENTITY_FILE_REQUEST';
export const  UPLOAD_IDENTITY_FILE_SUCCESS: string = 'UPLOAD_IDENTITY_FILE_SUCCESS';
export const  RESET_UPLOAD_IDENTITY_FILE: string = 'RESET_UPLOAD_IDENTITY_FILE';

// configuration file
export const UPLOAD_CONFIGURATION_FILE_REQUEST =
    'UPLOAD_CONFIGURATION_FILE_REQUEST';
export const UPLOAD_CONFIGURATION_FILE_SUCCESS =
    'UPLOAD_CONFIGURATION_FILE_SUCCESS';
export const RESET_UPLOAD_CONFIGURATION_FILE =
    'RESET_UPLOAD_CONFIGURATION_FILE';
export const SET_CONFIGURATION_FILE_INPUT_KEY =
    'SET_CONFIGURATION_FILE_INPUT_KEY';
