export const CREATE_MS_TEAMS_SUCCESS = 'CREATE_MS_TEAMS_SUCCESS';
export const CREATE_MS_TEAMS_FAILED = 'CREATE_MS_TEAMS_FAILED';
export const CREATE_MS_TEAMS_REQUEST = 'CREATE_MS_TEAMS_REQUEST';
export const CREATE_MS_TEAMS_RESET = 'CREATE_MS_TEAMS_RESET';

export const UPDATE_MS_TEAMS_SUCCESS = 'UPDATE_MS_TEAMS_SUCCESS';
export const UPDATE_MS_TEAMS_FAILED = 'UPDATE_MS_TEAMS_FAILED';
export const UPDATE_MS_TEAMS_REQUEST = 'UPDATE_MS_TEAMS_REQUEST';
export const UPDATE_MS_TEAMS_RESET = 'UPDATE_MS_TEAMS_RESET';

export const GET_MS_TEAMS_SUCCESS = 'GET_MS_TEAMS_SUCCESS';
export const GET_MS_TEAMS_FAILED = 'GET_MS_TEAMS_FAILED';
export const GET_MS_TEAMS_REQUEST = 'GET_MS_TEAMS_REQUEST';
export const GET_MS_TEAMS_RESET = 'GET_MS_TEAMS_RESET';

export const DELETE_MS_TEAMS_SUCCESS = 'DELETE_MS_TEAMS_SUCCESS';
export const DELETE_MS_TEAMS_FAILED = 'DELETE_MS_TEAMS_FAILED';
export const DELETE_MS_TEAMS_REQUEST = 'DELETE_MS_TEAMS_REQUEST';
export const DELETE_MS_TEAMS_RESET = 'DELETE_MS_TEAMS_RESET';

export const PAGINATE_NEXT = 'msteams/PAGINATE_NEXT';
export const PAGINATE_PREV = 'msteams/PAGINATE_PREV';
export const PAGINATE_RESET = 'msteams/PAGINATE_RESET';
