export const CREATE_MS_TEAMS_SUCCESS: string = 'CREATE_MS_TEAMS_SUCCESS';
export const CREATE_MS_TEAMS_FAILED: string = 'CREATE_MS_TEAMS_FAILED';
export const CREATE_MS_TEAMS_REQUEST: string = 'CREATE_MS_TEAMS_REQUEST';
export const CREATE_MS_TEAMS_RESET: string = 'CREATE_MS_TEAMS_RESET';

export const UPDATE_MS_TEAMS_SUCCESS: string = 'UPDATE_MS_TEAMS_SUCCESS';
export const UPDATE_MS_TEAMS_FAILED: string = 'UPDATE_MS_TEAMS_FAILED';
export const UPDATE_MS_TEAMS_REQUEST: string = 'UPDATE_MS_TEAMS_REQUEST';
export const UPDATE_MS_TEAMS_RESET: string = 'UPDATE_MS_TEAMS_RESET';

export const GET_MS_TEAMS_SUCCESS: string = 'GET_MS_TEAMS_SUCCESS';
export const GET_MS_TEAMS_FAILED: string = 'GET_MS_TEAMS_FAILED';
export const GET_MS_TEAMS_REQUEST: string = 'GET_MS_TEAMS_REQUEST';
export const GET_MS_TEAMS_RESET: string = 'GET_MS_TEAMS_RESET';

export const DELETE_MS_TEAMS_SUCCESS: string = 'DELETE_MS_TEAMS_SUCCESS';
export const DELETE_MS_TEAMS_FAILED: string = 'DELETE_MS_TEAMS_FAILED';
export const DELETE_MS_TEAMS_REQUEST: string = 'DELETE_MS_TEAMS_REQUEST';
export const DELETE_MS_TEAMS_RESET: string = 'DELETE_MS_TEAMS_RESET';

export const PAGINATE_NEXT: string = 'msteams/PAGINATE_NEXT';
export const PAGINATE_PREV: string = 'msteams/PAGINATE_PREV';
export const PAGINATE_RESET: string = 'msteams/PAGINATE_RESET';
