export const OPEN_NOTIFICATION_MENU: string = 'OPEN_NOTIFICATION_MENU';
export const CLOSE_NOTIFICATION_MENU: string = 'CLOSE_NOTIFICATION_MENU';

// Create a new project

export const FETCH_NOTIFICATIONS_SUCCESS =
    'feedback/FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILED: string =
    'feedback/FETCH_NOTIFICATIONS_FAILED';
export const FETCH_NOTIFICATIONS_REQUEST =
    'feedback/FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_RESET: string =
    'feedback/FETCH_NOTIFICATIONS_RESET';
export const NOTIFICATION_READ_SUCCESS: string =
    'feedback/NOTIFICATION_READ_SUCCESS';
export const NOTIFICATION_CLOSED_SUCCESS =
    'feedback/NOTIFICATION_CLOSED_SUCCESS';
export const ALL_NOTIFICATION_READ_SUCCESS =
    'feedback/ALL_NOTIFICATION_READ_SUCCESS';

export const RESET_PROJECT_NOTIFICATIONS: string =
    'RESET_PROJECT_NOTIFICATIONS';
