export const PAGE_LOAD_SUCCESS = 'page/PAGE_LOAD_SUCCESS';
export const PAGE_LOAD_REQUEST = 'page/PAGE_LOAD_REQUEST';
export const PAGE_LOAD_RESET = 'page/PAGE_LOAD_RESET';
export const TOGGLE_PROJECT_SETTINGS_MORE = "TOGGLE_PROJECT_SETTINGS_MORE"
