// Create performance monitor
export const CREATE_PERFORMANCE_TRACKER_REQUEST: $TSFixMe =
    'CREATE_PERFORMANCE_TRACKER_REQUEST';
export const CREATE_PERFORMANCE_TRACKER_SUCCESS: $TSFixMe =
    'CREATE_PERFORMANCE_TRACKER_SUCCESS';
export const CREATE_PERFORMANCE_TRACKER_FAILURE: $TSFixMe =
    'CREATE_PERFORMANCE_TRACKER_FAILURE';
export const CREATE_PERFORMANCE_TRACKER_RESET: $TSFixMe =
    'CREATE_PERFORMANCE_TRACKER_RESET';

// Fetch a single performance monitor
export const FETCH_PERFORMANCE_TRACKER_REQUEST: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKER_REQUEST';
export const FETCH_PERFORMANCE_TRACKER_SUCCESS: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKER_SUCCESS';
export const FETCH_PERFORMANCE_TRACKER_FAILURE: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKER_FAILURE';
export const FETCH_PERFORMANCE_TRACKER_RESET: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKER_RESET';

// Performance monitor list
export const FETCH_PERFORMANCE_TRACKERS_REQUEST: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKERS_REQUEST';
export const FETCH_PERFORMANCE_TRACKERS_SUCCESS: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKERS_SUCCESS';
export const FETCH_PERFORMANCE_TRACKERS_FAILURE: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKERS_FAILURE';
export const FETCH_PERFORMANCE_TRACKERS_RESET: $TSFixMe =
    'FETCH_PERFORMANCE_TRACKERS_RESET';

// Update performance monitor
export const UPDATE_PERFORMANCE_TRACKER_REQUEST: $TSFixMe =
    'UPDATE_PERFORMANCE_TRACKER_REQUEST';
export const UPDATE_PERFORMANCE_TRACKER_SUCCESS: $TSFixMe =
    'UPDATE_PERFORMANCE_TRACKER_SUCCESS';
export const UPDATE_PERFORMANCE_TRACKER_FAILURE: $TSFixMe =
    'UPDATE_PERFORMANCE_TRACKER_FAILURE';
export const UPDATE_PERFORMANCE_TRACKER_RESET: $TSFixMe =
    'UPDATE_PERFORMANCE_TRACKER_RESET';

// Delete performance monitor
export const DELETE_PERFORMANCE_TRACKER_REQUEST: $TSFixMe =
    'DELETE_PERFORMANCE_TRACKER_REQUEST';
export const DELETE_PERFORMANCE_TRACKER_SUCCESS: $TSFixMe =
    'DELETE_PERFORMANCE_TRACKER_SUCCESS';
export const DELETE_PERFORMANCE_TRACKER_FAILURE: $TSFixMe =
    'DELETE_PERFORMANCE_TRACKER_FAILURE';
export const DELETE_PERFORMANCE_TRACKER_RESET: $TSFixMe =
    'DELETE_PERFORMANCE_TRACKER_RESET';

// Reset performance monitor api key
export const RESET_PERFORMANCE_TRACKER_KEY_REQUEST: $TSFixMe =
    'RESET_PERFORMANCE_TRACKER_KEY_REQUEST';
export const RESET_PERFORMANCE_TRACKER_KEY_SUCCESS: $TSFixMe =
    'RESET_PERFORMANCE_TRACKER_KEY_SUCCESS';
export const RESET_PERFORMANCE_TRACKER_KEY_FAILURE: $TSFixMe =
    'RESET_PERFORMANCE_TRACKER_KEY_FAILURE';
export const RESET_PERFORMANCE_TRACKER_KEY_RESET: $TSFixMe =
    'RESET_PERFORMANCE_TRACKER_KEY_RESET';

export const REMOVE_QUICK_START_REQUEST: string = 'REMOVE_QUICK_START_REQUEST';
export const REMOVE_QUICK_START_SUCCESS: string = 'REMOVE_QUICK_START_SUCCESS';
export const REMOVE_QUICK_START_FAILURE: string = 'REMOVE_QUICK_START_FAILURE';

// Fetch last metrics
export const FETCH_LAST_METRICS_REQUEST: string = 'FETCH_LAST_METRICS_REQUEST';
export const FETCH_LAST_METRICS_SUCCESS: string = 'FETCH_LAST_METRICS_SUCCESS';
export const FETCH_LAST_METRICS_FAILURE: string = 'FETCH_LAST_METRICS_FAILURE';

//Add peformance tracker
export const ADD_PERFORMANCE_TRACKER: string = 'ADD_PERFORMANCE_TRACKER';
