// create performance monitor
export const CREATE_PERFORMANCE_TRACKER_REQUEST =
    'CREATE_PERFORMANCE_TRACKER_REQUEST';
export const CREATE_PERFORMANCE_TRACKER_SUCCESS =
    'CREATE_PERFORMANCE_TRACKER_SUCCESS';
export const CREATE_PERFORMANCE_TRACKER_FAILURE =
    'CREATE_PERFORMANCE_TRACKER_FAILURE';
export const CREATE_PERFORMANCE_TRACKER_RESET =
    'CREATE_PERFORMANCE_TRACKER_RESET';

// fetch a single performance monitor
export const FETCH_PERFORMANCE_TRACKER_REQUEST =
    'FETCH_PERFORMANCE_TRACKER_REQUEST';
export const FETCH_PERFORMANCE_TRACKER_SUCCESS =
    'FETCH_PERFORMANCE_TRACKER_SUCCESS';
export const FETCH_PERFORMANCE_TRACKER_FAILURE =
    'FETCH_PERFORMANCE_TRACKER_FAILURE';
export const FETCH_PERFORMANCE_TRACKER_RESET =
    'FETCH_PERFORMANCE_TRACKER_RESET';

// performance monitor list
export const FETCH_PERFORMANCE_TRACKERS_REQUEST =
    'FETCH_PERFORMANCE_TRACKERS_REQUEST';
export const FETCH_PERFORMANCE_TRACKERS_SUCCESS =
    'FETCH_PERFORMANCE_TRACKERS_SUCCESS';
export const FETCH_PERFORMANCE_TRACKERS_FAILURE =
    'FETCH_PERFORMANCE_TRACKERS_FAILURE';
export const FETCH_PERFORMANCE_TRACKERS_RESET =
    'FETCH_PERFORMANCE_TRACKERS_RESET';

// update performance monitor
export const UPDATE_PERFORMANCE_TRACKER_REQUEST =
    'UPDATE_PERFORMANCE_TRACKER_REQUEST';
export const UPDATE_PERFORMANCE_TRACKER_SUCCESS =
    'UPDATE_PERFORMANCE_TRACKER_SUCCESS';
export const UPDATE_PERFORMANCE_TRACKER_FAILURE =
    'UPDATE_PERFORMANCE_TRACKER_FAILURE';
export const UPDATE_PERFORMANCE_TRACKER_RESET =
    'UPDATE_PERFORMANCE_TRACKER_RESET';

// delete performance monitor
export const DELETE_PERFORMANCE_TRACKER_REQUEST =
    'DELETE_PERFORMANCE_TRACKER_REQUEST';
export const DELETE_PERFORMANCE_TRACKER_SUCCESS =
    'DELETE_PERFORMANCE_TRACKER_SUCCESS';
export const DELETE_PERFORMANCE_TRACKER_FAILURE =
    'DELETE_PERFORMANCE_TRACKER_FAILURE';
export const DELETE_PERFORMANCE_TRACKER_RESET =
    'DELETE_PERFORMANCE_TRACKER_RESET';

// reset performance monitor api key
export const RESET_PERFORMANCE_TRACKER_KEY_REQUEST =
    'RESET_PERFORMANCE_TRACKER_KEY_REQUEST';
export const RESET_PERFORMANCE_TRACKER_KEY_SUCCESS =
    'RESET_PERFORMANCE_TRACKER_KEY_SUCCESS';
export const RESET_PERFORMANCE_TRACKER_KEY_FAILURE =
    'RESET_PERFORMANCE_TRACKER_KEY_FAILURE';
export const RESET_PERFORMANCE_TRACKER_KEY_RESET =
    'RESET_PERFORMANCE_TRACKER_KEY_RESET';
