// create performance monitor
export const CREATE_PERFORMANCE_MONITOR_REQUEST =
    'CREATE_PERFORMANCE_MONITOR_REQUEST';
export const CREATE_PERFORMANCE_MONITOR_SUCCESS =
    'CREATE_PERFORMANCE_MONITOR_SUCCESS';
export const CREATE_PERFORMANCE_MONITOR_FAILURE =
    'CREATE_PERFORMANCE_MONITOR_FAILURE';
export const CREATE_PERFORMANCE_MONITOR_RESET =
    'CREATE_PERFORMANCE_MONITOR_RESET';

// fetch a single performance monitor
export const FETCH_PERFORMANCE_MONITOR_REQUEST =
    'FETCH_PERFORMANCE_MONITOR_REQUEST';
export const FETCH_PERFORMANCE_MONITOR_SUCCESS =
    'FETCH_PERFORMANCE_MONITOR_SUCCESS';
export const FETCH_PERFORMANCE_MONITOR_FAILURE =
    'FETCH_PERFORMANCE_MONITOR_FAILURE';
export const FETCH_PERFORMANCE_MONITOR_RESET =
    'FETCH_PERFORMANCE_MONITOR_RESET';

// performance monitor list
export const FETCH_PERFORMANCE_MONITORS_REQUEST =
    'FETCH_PERFORMANCE_MONITORS_REQUEST';
export const FETCH_PERFORMANCE_MONITORS_SUCCESS =
    'FETCH_PERFORMANCE_MONITORS_SUCCESS';
export const FETCH_PERFORMANCE_MONITORS_FAILURE =
    'FETCH_PERFORMANCE_MONITORS_FAILURE';
export const FETCH_PERFORMANCE_MONITORS_RESET =
    'FETCH_PERFORMANCE_MONITORS_RESET';

// update performance monitor
export const UPDATE_PERFORMANCE_MONITOR_REQUEST =
    'UPDATE_PERFORMANCE_MONITOR_REQUEST';
export const UPDATE_PERFORMANCE_MONITOR_SUCCESS =
    'UPDATE_PERFORMANCE_MONITOR_SUCCESS';
export const UPDATE_PERFORMANCE_MONITOR_FAILURE =
    'UPDATE_PERFORMANCE_MONITOR_FAILURE';
export const UPDATE_PERFORMANCE_MONITOR_RESET =
    'UPDATE_PERFORMANCE_MONITOR_RESET';

// delete performance monitor
export const DELETE_PERFORMANCE_MONITOR_REQUEST =
    'DELETE_PERFORMANCE_MONITOR_REQUEST';
export const DELETE_PERFORMANCE_MONITOR_SUCCESS =
    'DELETE_PERFORMANCE_MONITOR_SUCCESS';
export const DELETE_PERFORMANCE_MONITOR_FAILURE =
    'DELETE_PERFORMANCE_MONITOR_FAILURE';
export const DELETE_PERFORMANCE_MONITOR_RESET =
    'DELETE_PERFORMANCE_MONITOR_RESET';

// reset performance monitor api key
export const RESET_PERFORMANCE_MONITOR_KEY_REQUEST =
    'RESET_PERFORMANCE_MONITOR_KEY_REQUEST';
export const RESET_PERFORMANCE_MONITOR_KEY_SUCCESS =
    'RESET_PERFORMANCE_MONITOR_KEY_SUCCESS';
export const RESET_PERFORMANCE_MONITOR_KEY_FAILURE =
    'RESET_PERFORMANCE_MONITOR_KEY_FAILURE';
export const RESET_PERFORMANCE_MONITOR_KEY_RESET =
    'RESET_PERFORMANCE_MONITOR_KEY_RESET';
