// fetch performane tracker metrics - TIME
export const FETCH_TIME_METRICS_REQUEST = 'FETCH_TIME_METRICS_REQUEST';
export const FETCH_TIME_METRICS_SUCCESS = 'FETCH_TIME_METRICS_SUCCESS';
export const FETCH_TIME_METRICS_FAILURE = 'FETCH_TIME_METRICS_FAILURE';

// fetch performance tracker metrics - THROUGHPUT
export const FETCH_THROUGHPUT_METRICS_REQUEST =
    'FETCH_THROUGHPUT_METRICS_REQUEST';
export const FETCH_THROUGHPUT_METRICS_SUCCESS =
    'FETCH_THROUGHPUT_METRICS_SUCCESS';
export const FETCH_THROUGHPUT_METRICS_FAILURE =
    'FETCH_THROUGHPUT_METRICS_FAILURE';

// handle setting startDate/endDate - (TIME || THROUGHPUT)
export const SET_TIME_STARTDATE = 'SET_TIME_STARTDATE';
export const SET_TIME_ENDDATE = 'SET_TIME_ENDDATE';
export const SET_THROUGHPUT_STARTDATE = 'SET_THROUGHPUT_STARTDATE';
export const SET_THROUGHPUT_ENDDATE = 'SET_THROUGHPUT_ENDDATE';

// update metrics from realtime update
export const UPDATE_TIME_METRICS = 'UPDATE_TIME_METRICS';
export const UPDATE_THROUGHPUT_METRICS = 'UPDATE_THROUGHPUT_METRICS';
