
//Update profile setting
export const UPDATE_PROFILE_SETTING_REQUEST = 'ProfileSetting/UPDATE_PROFILE_SETTING_REQUEST';
export const UPDATE_PROFILE_SETTING_SUCCESS = 'ProfileSetting/UPDATE_PROFILE_SETTING_SUCCESS';
export const UPDATE_PROFILE_SETTING_FAILURE = 'ProfileSetting/UPDATE_PROFILE_SETTING_FAILURE';
export const UPDATE_PROFILE_SETTING_RESET = 'ProfileSetting/UPDATE_PROFILE_SETTING_RESET';

//Update on cal alert setting.
export const UPDATE_ON_CALL_ALERT_SETTING_REQUEST = 'UPDATE_ON_CALL_ALERT_SETTING_REQUEST';
export const UPDATE_ON_CALL_ALERT_SETTING_SUCCESS = 'UPDATE_ON_CALL_ALERT_SETTING_SUCCESS';
export const UPDATE_ON_CALL_ALERT_SETTING_FAILURE = 'UPDATE_ON_CALL_ALERT_SETTING_FAILURE';
export const UPDATE_ON_CALL_ALERT_SETTING_RESET = 'UPDATE_ON_CALL_ALERT_SETTING_RESET';


//Update change password setting.
export const UPDATE_CHANGE_PASSWORD_SETTING_REQUEST = 'ProfileSetting/UPDATE_CHANGE_PASSWORD_SETTING_REQUEST';
export const UPDATE_CHANGE_PASSWORD_SETTING_SUCCESS = 'ProfileSetting/UPDATE_CHANGE_PASSWORD_SETTING_SUCCESS';
export const UPDATE_CHANGE_PASSWORD_SETTING_FAILURE = 'ProfileSetting/UPDATE_CHANGE_PASSWORD_SETTING_FAILURE';
export const UPDATE_CHANGE_PASSWORD_SETTING_RESET = 'ProfileSetting/UPDATE_CHANGE_PASSWORD_SETTING_RESET';

export const SHOW_PROFILE_MENU = 'ProfileSetting/SHOW_PROFILE_MENU';
export const HIDE_PROFILE_MENU = 'ProfileSetting/HIDE_PROFILE_MENU';

// Get Previous User Settings.
export const USER_SETTINGS_REQUEST = 'ProfileSetting/USER_SETTINGS_REQUEST';
export const USER_SETTINGS_SUCCESS = 'ProfileSetting/USER_SETTINGS_SUCCESS';
export const USER_SETTINGS_FAILURE = 'ProfileSetting/USER_SETTINGS_FAILURE';
export const USER_SETTINGS_RESET = 'ProfileSetting/USER_SETTINGS_RESET';

export const SEND_VERIFICATION_SMS_REQUEST = 'ProfileSetting/SEND_VERIFICATION_SMS_REQUEST';
export const SEND_VERIFICATION_SMS_SUCCESS = 'ProfileSetting/SEND_VERIFICATION_SMS_SUCCESS';
export const SEND_VERIFICATION_SMS_FAILURE = 'ProfileSetting/SEND_VERIFICATION_SMS_FAILURE';

// Send email verification.
export const SEND_EMAIL_VERIFICATION_REQUEST = 'ProfileSetting/SEND_EMAIL_VERIFICATION_REQUEST';
export const SEND_EMAIL_VERIFICATION_SUCCESS = 'ProfileSetting/SEND_EMAIL_VERIFICATION_SUCCESS';
export const SEND_EMAIL_VERIFICATION_FAILURE = 'ProfileSetting/SEND_EMAIL_VERIFICATION_FAILURE';

export const VERIFY_SMS_CODE_REQUEST = 'ProfileSetting/VERIFY_SMS_CODE_REQUEST';
export const VERIFY_SMS_CODE_SUCCESS = 'ProfileSetting/VERIFY_SMS_CODE_SUCCESS';
export const VERIFY_SMS_CODE_FAILURE = 'ProfileSetting/VERIFY_SMS_CODE_FAILURE';

export const SET_INIT_PHONE_VERIFICATION_NUMBER = 'ProfileSetting/SET_INIT_PHONE_VERIFICATION_NUMBER';
export const SET_ALERT_PHONE_NUMBER = 'ProfileSetting/SET_ALERT_PHONE_NUMBER';
export const SET_INITIAL_ALERT_PHONE_NUMBER = 'ProfileSetting/SET_INITIAL_ALERT_PHONE_NUMBER';
export const SET_INIT_PHONE_VERIFICATION = 'ProfileSetting/SET_INIT_PHONE_VERIFICATION';
export const SET_FILE_INPUT_KEY = 'ProfileSetting/SET_FILE_INPUT_KEY';
export const SET_IS_VERIFIED = 'ProfileSetting/SET_IS_VERIFIED';
export const SET_PROFILE_PIC = 'ProfileSetting/SET_PROFILE_PIC';
export const SET_REMOVED_PIC = 'ProfileSetting/SET_REMOVED_PIC';
export const SET_USER_EMAIL = 'ProfileSetting/SET_USER_EMAIL';
export const SET_VERIFIED = 'ProfileSetting/SET_VERIFIED';
export const SET_RESEND_TIMER = 'ProfileSetting/SET_RESEND_TIMER';
export const SET_INIT_ALERT_EMAIL = 'ProfileSetting/SET_INIT_ALERT_EMAIL';
