export const CHANGE_DELETE_MODAL: string = 'projects/CHANGE_DELETE_MODAL';
export const SHOW_DELETE_MODAL: string = 'projects/SHOW_DELETE_MODAL';
export const HIDE_DELETE_MODAL: string = 'projects/HIDE_DELETE_MODAL';
export const HIDE_DELETE_MODAL_SAAS_MODE =
    'projects/HIDE_DELETE_MODAL_SAAS_MODE';

export const SHOW_PROJECT_FORM: string = 'projects/SHOW_PROJECT_FORM';
export const HIDE_PROJECT_FORM: string = 'projects/HIDE_PROJECT_FORM';

export const SHOW_UPGRADE_FORM: string = 'projects/SHOW_UPGRADE_FORM';
export const HIDE_UPGRADE_FORM: string = 'projects/HIDE_UPGRADE_FORM';

export const PROJECTS_SUCCESS: string = 'projects/PROJECTS_SUCCESS';
export const PROJECTS_FAILED: string = 'projects/PROJECTS_FAILED';
export const PROJECTS_REQUEST: string = 'projects/PROJECTS_REQUEST';
export const PROJECTS_RESET: string = 'projects/PROJECTS_RESET';

export const CREATE_PROJECT_SUCCESS: string = 'projects/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILED: string = 'projects/CREATE_PROJECT_FAILED';
export const CREATE_PROJECT_REQUEST: string = 'projects/CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_RESET: string = 'projects/CREATE_PROJECT_RESET';

export const SWITCH_PROJECT: string = 'projects/SWITCH_PROJECT';
export const SWITCH_PROJECT_RESET: string = 'projects/SWITCH_PROJECT_RESET';

export const SHOW_PROJECT_SWITCHER: string = 'projects/SHOW_PROJECT_SWITCHER';
export const HIDE_PROJECT_SWITCHER: string = 'projects/HIDE_PROJECT_SWITCHER';

export const RESET_PROJECT_TOKEN_REQUEST =
    'projects/RESET_PROJECT_TOKEN_REQUEST';
export const RESET_PROJECT_TOKEN_SUCCESS =
    'projects/RESET_PROJECT_TOKEN_SUCCESS';
export const RESET_PROJECT_TOKEN_FAILED: string =
    'projects/RESET_PROJECT_TOKEN_FAILED';
export const RESET_PROJECT_TOKEN_RESET: string =
    'projects/RESET_PROJECT_TOKEN_RESET';

export const RENAME_PROJECT_REQUEST: string = 'projects/RENAME_PROJECT_REQUEST';
export const RENAME_PROJECT_SUCCESS: string = 'projects/RENAME_PROJECT_SUCCESS';
export const RENAME_PROJECT_FAILED: string = 'projects/RENAME_PROJECT_FAILED';
export const RENAME_PROJECT_RESET: string = 'projects/RENAME_PROJECT_RESET';

export const DELETE_PROJECT_REQUEST: string = 'projects/DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS: string = 'projects/DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED: string = 'projects/DELETE_PROJECT_FAILED';
export const DELETE_PROJECT_RESET: string = 'projects/DELETE_PROJECT_RESET';

export const CHANGE_PLAN_REQUEST: string = 'projects/CHANGE_PLAN_REQUEST';
export const CHANGE_PLAN_SUCCESS: string = 'projects/CHANGE_PLAN_SUCCESS';
export const CHANGE_PLAN_FAILED: string = 'projects/CHANGE_PLAN_FAILED';
export const CHANGE_PLAN_RESET: string = 'projects/CHANGE_PLAN_RESET';

export const UPGRADE_PLAN_EMPTY: string = 'projects/UPGRADE_PLAN_EMPTY';

export const EXIT_PROJECT_REQUEST: string = 'EXIT_PROJECT_REQUEST';
export const EXIT_PROJECT_SUCCESS: string = 'EXIT_PROJECT_SUCCESS';
export const EXIT_PROJECT_FAILED: string = 'EXIT_PROJECT_FAILED';

export const CHANGE_PROJECT_ROLES: string = 'projects/CHANGE_PROJECT_ROLES';

export const MARK_PROJECT_DELETE_REQUEST =
    'projects/MARK_PROJECT_DELETE_REQUEST';
export const MARK_PROJECT_DELETE_SUCCESS =
    'projects/MARK_PROJECT_DELETE_SUCCESS';
export const MARK_PROJECT_DELETE_FAILED: string =
    'projects/MARK_PROJECT_DELETE_FAILED';
export const MARK_PROJECT_DELETE_RESET: string =
    'projects/MARK_PROJECT_DELETE_RESET';

export const ALERT_OPTIONS_UPDATE_REQUEST: string =
    'ALERT_OPTIONS_UPDATE_REQUEST';
export const ALERT_OPTIONS_UPDATE_SUCCESS: string =
    'ALERT_OPTIONS_UPDATE_SUCCESS';
export const ALERT_OPTIONS_UPDATE_FAILED: string =
    'ALERT_OPTIONS_UPDATE_FAILED';

export const ADD_BALANCE_REQUEST: string = 'ADD_BALANCE_REQUEST';
export const ADD_BALANCE_SUCCESS: string = 'ADD_BALANCE_SUCCESS';
export const ADD_BALANCE_FAILED: string = 'ADD_BALANCE_FAILED';

export const CHECK_CARD_SUCCESS: string = 'CHECK_CARD_SUCCESS';
export const CHECK_CARD_FAILED: string = 'CHECK_CARD_FAILED';
export const CHECK_CARD_REQUEST: string = 'CHECK_CARD_REQUEST';

export const SET_EMAIL_INCIDENT_NOTIFICATION_REQUEST =
    'SET_EMAIL_INCIDENT_NOTIFICATION_REQUEST';
export const SET_EMAIL_INCIDENT_NOTIFICATION_SUCCESS =
    'SET_EMAIL_INCIDENT_NOTIFICATION_SUCCESS';
export const SET_EMAIL_INCIDENT_NOTIFICATION_FAILURE =
    'SET_EMAIL_INCIDENT_NOTIFICATION_FAILURE';

export const SET_SMS_INCIDENT_NOTIFICATION_REQUEST =
    'SET_SMS_INCIDENT_NOTIFICATION_REQUEST';
export const SET_SMS_INCIDENT_NOTIFICATION_SUCCESS =
    'SET_SMS_INCIDENT_NOTIFICATION_SUCCESS';
export const SET_SMS_INCIDENT_NOTIFICATION_FAILURE =
    'SET_SMS_INCIDENT_NOTIFICATION_FAILURE';

export const SET_WEBHOOK_NOTIFICATION_SETTINGS_REQUEST =
    'SET_WEBHOOK_NOTIFICATION_SETTINGS_REQUEST';
export const SET_WEBHOOK_NOTIFICATION_SETTINGS_SUCCESS =
    'SET_WEBHOOK_NOTIFICATION_SETTINGS_SUCCESS';
export const SET_WEBHOOK_NOTIFICATION_SETTINGS_FAILURE =
    'SET_WEBHOOK_NOTIFICATION_SETTINGS_FAILURE';

export const UPDATE_PROJECT_BALANCE_REQUEST: string =
    'UPDATE_PROJECT_BALANCE_REQUEST';
export const UPDATE_PROJECT_BALANCE_SUCCESS: string =
    'UPDATE_PROJECT_BALANCE_SUCCESS';
export const UPDATE_PROJECT_BALANCE_FAILURE: string =
    'UPDATE_PROJECT_BALANCE_FAILURE';

export const GET_PROJECT_BALANCE_REQUEST: string =
    'GET_PROJECT_BALANCE_REQUEST';
export const GET_PROJECT_BALANCE_SUCCESS: string =
    'GET_PROJECT_BALANCE_SUCCESS';
export const GET_PROJECT_BALANCE_FAILED: string = 'GET_PROJECT_BALANCE_FAILED';

export const SHOW_VIEWER_MENU: string = 'SHOW_VIEWER_MENU';

export const FETCH_PROJECT_DOMAINS_REQUEST: string =
    'FETCH_PROJECT_DOMAINS_REQUEST';
export const FETCH_PROJECT_DOMAINS_SUCCESS: string =
    'FETCH_PROJECT_DOMAINS_SUCCESS';
export const FETCH_PROJECT_DOMAINS_FAILURE: string =
    'FETCH_PROJECT_DOMAINS_FAILURE';

export const CREATE_PROJECT_DOMAIN_REQUEST: string =
    'CREATE_PROJECT_DOMAIN_REQUEST';
export const CREATE_PROJECT_DOMAIN_SUCCESS: string =
    'CREATE_PROJECT_DOMAIN_SUCCESS';
export const CREATE_PROJECT_DOMAIN_FAILURE: string =
    'CREATE_PROJECT_DOMAIN_FAILURE';
export const RESET_CREATE_PROJECT_DOMAIN: string =
    'RESET_CREATE_PROJECT_DOMAIN';

export const UPDATE_PROJECT_DOMAIN_REQUEST: string =
    'UPDATE_PROJECT_DOMAIN_REQUEST';
export const UPDATE_PROJECT_DOMAIN_SUCCESS: string =
    'UPDATE_PROJECT_DOMAIN_SUCCESS';
export const UPDATE_PROJECT_DOMAIN_FAILURE: string =
    'UPDATE_PROJECT_DOMAIN_FAILURE';
export const RESET_UPDATE_PROJECT_DOMAIN: string =
    'RESET_UPDATE_PROJECT_DOMAIN';

export const DELETE_PROJECT_DOMAIN_REQUEST: string =
    'DELETE_PROJECT_DOMAIN_REQUEST';
export const DELETE_PROJECT_DOMAIN_SUCCESS: string =
    'DELETE_PROJECT_DOMAIN_SUCCESS';
export const DELETE_PROJECT_DOMAIN_FAILURE: string =
    'DELETE_PROJECT_DOMAIN_FAILURE';
export const RESET_DELETE_PROJECT_DOMAIN: string =
    'RESET_DELETE_PROJECT_DOMAIN';

export const VERIFY_PROJECT_DOMAIN_REQUEST: string =
    'VERIFY_PROJECT_DOMAIN_REQUEST';
export const VERIFY_PROJECT_DOMAIN_SUCCESS: string =
    'VERIFY_PROJECT_DOMAIN_SUCCESS';
export const VERIFY_PROJECT_DOMAIN_FAILURE: string =
    'VERIFY_PROJECT_DOMAIN_FAILURE';
export const RESET_VERIFY_PROJECT_DOMAIN: string =
    'RESET_VERIFY_PROJECT_DOMAIN';

export const FETCH_TRIAL_REQUEST: string = 'FETCH_TRIAL_REQUEST';
export const FETCH_TRIAL_SUCCESS: string = 'FETCH_TRIAL_SUCCESS';
export const FETCH_TRIAL_FAILURE: string = 'FETCH_TRIAL_FAILURE';
export const RESET_FETCH_TRIAL: string = 'RESET_FETCH_TRIAL';

export const FETCH_PROJECT_SLUG_REQUEST: string = 'FETCH_PROJECT_SLUG_REQUEST';
export const FETCH_PROJECT_SLUG_SUCCESS: string = 'FETCH_PROJECT_SLUG_SUCCESS';
export const FETCH_PROJECT_SLUG_FAILURE: string = 'FETCH_PROJECT_SLUG_FAILURE';
