export const CHANGE_DELETE_MODAL = 'projects/CHANGE_DELETE_MODAL';
export const SHOW_DELETE_MODAL = 'projects/SHOW_DELETE_MODAL';
export const HIDE_DELETE_MODAL = 'projects/HIDE_DELETE_MODAL';
export const HIDE_DELETE_MODAL_SAAS_MODE =
    'projects/HIDE_DELETE_MODAL_SAAS_MODE';

export const SHOW_PROJECT_FORM = 'projects/SHOW_PROJECT_FORM';
export const HIDE_PROJECT_FORM = 'projects/HIDE_PROJECT_FORM';

export const SHOW_UPGRADE_FORM = 'projects/SHOW_UPGRADE_FORM';
export const HIDE_UPGRADE_FORM = 'projects/HIDE_UPGRADE_FORM';

export const PROJECTS_SUCCESS = 'projects/PROJECTS_SUCCESS';
export const PROJECTS_FAILED = 'projects/PROJECTS_FAILED';
export const PROJECTS_REQUEST = 'projects/PROJECTS_REQUEST';
export const PROJECTS_RESET = 'projects/PROJECTS_RESET';

export const CREATE_PROJECT_SUCCESS = 'projects/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILED = 'projects/CREATE_PROJECT_FAILED';
export const CREATE_PROJECT_REQUEST = 'projects/CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_RESET = 'projects/CREATE_PROJECT_RESET';

export const SWITCH_PROJECT = 'projects/SWITCH_PROJECT';
export const SWITCH_PROJECT_RESET = 'projects/SWITCH_PROJECT_RESET';

export const SHOW_PROJECT_SWITCHER = 'projects/SHOW_PROJECT_SWITCHER';
export const HIDE_PROJECT_SWITCHER = 'projects/HIDE_PROJECT_SWITCHER';

export const RESET_PROJECT_TOKEN_REQUEST =
    'projects/RESET_PROJECT_TOKEN_REQUEST';
export const RESET_PROJECT_TOKEN_SUCCESS =
    'projects/RESET_PROJECT_TOKEN_SUCCESS';
export const RESET_PROJECT_TOKEN_FAILED = 'projects/RESET_PROJECT_TOKEN_FAILED';
export const RESET_PROJECT_TOKEN_RESET = 'projects/RESET_PROJECT_TOKEN_RESET';

export const RENAME_PROJECT_REQUEST = 'projects/RENAME_PROJECT_REQUEST';
export const RENAME_PROJECT_SUCCESS = 'projects/RENAME_PROJECT_SUCCESS';
export const RENAME_PROJECT_FAILED = 'projects/RENAME_PROJECT_FAILED';
export const RENAME_PROJECT_RESET = 'projects/RENAME_PROJECT_RESET';

export const DELETE_PROJECT_REQUEST = 'projects/DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'projects/DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'projects/DELETE_PROJECT_FAILED';
export const DELETE_PROJECT_RESET = 'projects/DELETE_PROJECT_RESET';

export const CHANGE_PLAN_REQUEST = 'projects/CHANGE_PLAN_REQUEST';
export const CHANGE_PLAN_SUCCESS = 'projects/CHANGE_PLAN_SUCCESS';
export const CHANGE_PLAN_FAILED = 'projects/CHANGE_PLAN_FAILED';
export const CHANGE_PLAN_RESET = 'projects/CHANGE_PLAN_RESET';

export const UPGRADE_PLAN_EMPTY = 'projects/UPGRADE_PLAN_EMPTY';

export const EXIT_PROJECT_REQUEST = 'EXIT_PROJECT_REQUEST';
export const EXIT_PROJECT_SUCCESS = 'EXIT_PROJECT_SUCCESS';
export const EXIT_PROJECT_FAILED = 'EXIT_PROJECT_FAILED';

export const CHANGE_PROJECT_ROLES = 'projects/CHANGE_PROJECT_ROLES';

export const MARK_PROJECT_DELETE_REQUEST =
    'projects/MARK_PROJECT_DELETE_REQUEST';
export const MARK_PROJECT_DELETE_SUCCESS =
    'projects/MARK_PROJECT_DELETE_SUCCESS';
export const MARK_PROJECT_DELETE_FAILED = 'projects/MARK_PROJECT_DELETE_FAILED';
export const MARK_PROJECT_DELETE_RESET = 'projects/MARK_PROJECT_DELETE_RESET';

export const ALERT_OPTIONS_UPDATE_REQUEST = 'ALERT_OPTIONS_UPDATE_REQUEST';
export const ALERT_OPTIONS_UPDATE_SUCCESS = 'ALERT_OPTIONS_UPDATE_SUCCESS';
export const ALERT_OPTIONS_UPDATE_FAILED = 'ALERT_OPTIONS_UPDATE_FAILED';

export const ADD_BALANCE_REQUEST = 'ADD_BALANCE_REQUEST';
export const ADD_BALANCE_SUCCESS = 'ADD_BALANCE_SUCCESS';
export const ADD_BALANCE_FAILED = 'ADD_BALANCE_FAILED';

export const CHECK_CARD_SUCCESS = 'CHECK_CARD_SUCCESS';
export const CHECK_CARD_FAILED = 'CHECK_CARD_FAILED';
export const CHECK_CARD_REQUEST = 'CHECK_CARD_REQUEST';

export const SET_EMAIL_INCIDENT_NOTIFICATION_REQUEST =
    'SET_EMAIL_INCIDENT_NOTIFICATION_REQUEST';
export const SET_EMAIL_INCIDENT_NOTIFICATION_SUCCESS =
    'SET_EMAIL_INCIDENT_NOTIFICATION_SUCCESS';
export const SET_EMAIL_INCIDENT_NOTIFICATION_FAILURE =
    'SET_EMAIL_INCIDENT_NOTIFICATION_FAILURE';

export const SET_SMS_INCIDENT_NOTIFICATION_REQUEST =
    'SET_SMS_INCIDENT_NOTIFICATION_REQUEST';
export const SET_SMS_INCIDENT_NOTIFICATION_SUCCESS =
    'SET_SMS_INCIDENT_NOTIFICATION_SUCCESS';
export const SET_SMS_INCIDENT_NOTIFICATION_FAILURE =
    'SET_SMS_INCIDENT_NOTIFICATION_FAILURE';

export const SET_WEBHOOK_NOTIFICATION_SETTINGS_REQUEST =
    'SET_WEBHOOK_NOTIFICATION_SETTINGS_REQUEST';
export const SET_WEBHOOK_NOTIFICATION_SETTINGS_SUCCESS =
    'SET_WEBHOOK_NOTIFICATION_SETTINGS_SUCCESS';
export const SET_WEBHOOK_NOTIFICATION_SETTINGS_FAILURE =
    'SET_WEBHOOK_NOTIFICATION_SETTINGS_FAILURE';

export const UPDATE_PROJECT_BALANCE_REQUEST = 'UPDATE_PROJECT_BALANCE_REQUEST';
export const UPDATE_PROJECT_BALANCE_SUCCESS = 'UPDATE_PROJECT_BALANCE_SUCCESS';
export const UPDATE_PROJECT_BALANCE_FAILURE = 'UPDATE_PROJECT_BALANCE_FAILURE';

export const GET_PROJECT_BALANCE_REQUEST = 'GET_PROJECT_BALANCE_REQUEST';
export const GET_PROJECT_BALANCE_SUCCESS = 'GET_PROJECT_BALANCE_SUCCESS';
export const GET_PROJECT_BALANCE_FAILED = 'GET_PROJECT_BALANCE_FAILED';

export const SHOW_VIEWER_MENU = 'SHOW_VIEWER_MENU';

export const FETCH_PROJECT_DOMAINS_REQUEST = 'FETCH_PROJECT_DOMAINS_REQUEST';
export const FETCH_PROJECT_DOMAINS_SUCCESS = 'FETCH_PROJECT_DOMAINS_SUCCESS';
export const FETCH_PROJECT_DOMAINS_FAILURE = 'FETCH_PROJECT_DOMAINS_FAILURE';

export const CREATE_PROJECT_DOMAIN_REQUEST = 'CREATE_PROJECT_DOMAIN_REQUEST';
export const CREATE_PROJECT_DOMAIN_SUCCESS = 'CREATE_PROJECT_DOMAIN_SUCCESS';
export const CREATE_PROJECT_DOMAIN_FAILURE = 'CREATE_PROJECT_DOMAIN_FAILURE';
export const RESET_CREATE_PROJECT_DOMAIN = 'RESET_CREATE_PROJECT_DOMAIN';

export const UPDATE_PROJECT_DOMAIN_REQUEST = 'UPDATE_PROJECT_DOMAIN_REQUEST';
export const UPDATE_PROJECT_DOMAIN_SUCCESS = 'UPDATE_PROJECT_DOMAIN_SUCCESS';
export const UPDATE_PROJECT_DOMAIN_FAILURE = 'UPDATE_PROJECT_DOMAIN_FAILURE';
export const RESET_UPDATE_PROJECT_DOMAIN = 'RESET_UPDATE_PROJECT_DOMAIN';

export const DELETE_PROJECT_DOMAIN_REQUEST = 'DELETE_PROJECT_DOMAIN_REQUEST';
export const DELETE_PROJECT_DOMAIN_SUCCESS = 'DELETE_PROJECT_DOMAIN_SUCCESS';
export const DELETE_PROJECT_DOMAIN_FAILURE = 'DELETE_PROJECT_DOMAIN_FAILURE';
export const RESET_DELETE_PROJECT_DOMAIN = 'RESET_DELETE_PROJECT_DOMAIN';

export const VERIFY_PROJECT_DOMAIN_REQUEST = 'VERIFY_PROJECT_DOMAIN_REQUEST';
export const VERIFY_PROJECT_DOMAIN_SUCCESS = 'VERIFY_PROJECT_DOMAIN_SUCCESS';
export const VERIFY_PROJECT_DOMAIN_FAILURE = 'VERIFY_PROJECT_DOMAIN_FAILURE';
export const RESET_VERIFY_PROJECT_DOMAIN = 'RESET_VERIFY_PROJECT_DOMAIN';

export const FETCH_TRIAL_REQUEST = 'FETCH_TRIAL_REQUEST';
export const FETCH_TRIAL_SUCCESS = 'FETCH_TRIAL_SUCCESS';
export const FETCH_TRIAL_FAILURE = 'FETCH_TRIAL_FAILURE';
export const RESET_FETCH_TRIAL = 'RESET_FETCH_TRIAL';
