
// Incidents Reports Section
export const WEEKLY_INCIDENTS_SUCCESS = 'reports/WEEKLY_INCIDENTS_SUCCESS';
export const WEEKLY_INCIDENTS_FAILED = 'reports/WEEEKLY_INCIDENTS_FAILED';
export const WEEKLY_INCIDENTS_REQUEST = 'reports/WEEKLY_INCIDENTS_REQUEST';

export const GET_ACTIVE_MEMBERS_SUCCESS = 'reports/GET_ACTIVE_MEMBERS_SUCCESS';
export const GET_ACTIVE_MEMBERS_FAILED = 'reports/GET_ACTIVE_MEMBERS_FAILED';
export const GET_ACTIVE_MEMBERS_REQUEST = 'reports/GET_ACTIVE_MEMBERS_REQUEST';

export const GET_ACTIVE_MONITORS_SUCCESS = 'reports/GET_ACTIVE_MONITORS_SUCCESS';
export const GET_ACTIVE_MONITORS_FAILED = 'reports/GET_ACTIVE_MONITORS_FAILED';
export const GET_ACTIVE_MONITORS_REQUEST = 'reports/GET_ACTIVE_MONITORS_REQUEST';

export const GET_INCIDENTS_SUCCESS = 'reports/GET_INCIDENTS_SUCCESS';
export const GET_INCIDENTS_FAILED = 'reports/GET_INCIDENTS_FAILED';
export const GET_INCIDENTS_REQUEST = 'reports/GET_INCIDENTS_REQUEST';

export const GET_MONTHLY_INCIDENTS_SUCCESS = 'reports/GET_MONTHLY_INCIDENTS_SUCCESS';
export const GET_MONTHLY_INCIDENTS_FAILED = 'reports/GET_MONTHLY_INCIDENTS_FAILED';
export const GET_MONTHLY_INCIDENTS_REQUEST = 'reports/GET_MONTHLY_INCIDENTS_REQUEST';

export const GET_MONTHLY_RESOLVE_TIME_SUCCESS = 'reports/GET_MONTHLY_RESOLVE_TIME_SUCCESS';
export const GET_MONTHLY_RESOLVE_TIME_FAILED = 'reports/GET_MONTHLY_RESOLVE_TIME_FAILED';
export const GET_MONTHLY_RESOLVE_TIME_REQUEST = 'reports/GET_MONTHLY_RESOLVE_TIME_REQUEST';

export const GET_WEEKLY_RESOLVE_TIME_SUCCESS = 'reports/GET_WEEKLY_RESOLVE_TIME_SUCCESS';
export const GET_WEEKLY_RESOLVE_TIME_FAILED = 'reports/GET_WEEKLY_RESOLVE_TIME_FAILED';
export const GET_WEEKLY_RESOLVE_TIME_REQUEST = 'reports/GET_WEEKLY_RESOLVE_TIME_REQUEST';
