//Resource Category list
export const FETCH_RESOURCE_CATEGORIES_REQUEST: $TSFixMe =
    'FETCH_RESOURCE_CATEGORIES_REQUEST';
export const FETCH_RESOURCE_CATEGORIES_SUCCESS: $TSFixMe =
    'FETCH_RESOURCE_CATEGORIES_SUCCESS';
export const FETCH_RESOURCE_CATEGORIES_FAILURE: $TSFixMe =
    'FETCH_RESOURCE_CATEGORIES_FAILURE';

//Create new resource Category
export const CREATE_RESOURCE_CATEGORY_SUCCESS: $TSFixMe =
    'CREATE_RESOURCE_CATEGORY_SUCCESS';
export const CREATE_RESOURCE_CATEGORY_FAILURE: $TSFixMe =
    'CREATE_RESOURCE_CATEGORY_FAILURE';
export const CREATE_RESOURCE_CATEGORY_REQUEST: $TSFixMe =
    'CREATE_RESOURCE_CATEGORY_REQUEST';

// Update resource Category
export const UPDATE_RESOURCE_CATEGORY_SUCCESS: $TSFixMe =
    'UPDATE_RESOURCE_CATEGORY_SUCCESS';
export const UPDATE_RESOURCE_CATEGORY_FAILURE: $TSFixMe =
    'UPDATE_RESOURCE_CATEGORY_FAILURE';
export const UPDATE_RESOURCE_CATEGORY_REQUEST: $TSFixMe =
    'UPDATE_RESOURCE_CATEGORY_REQUEST';

//Delete a resource Category
export const DELETE_RESOURCE_CATEGORY_SUCCESS: $TSFixMe =
    'DELETE_RESOURCE_CATEGORY_SUCCESS';
export const DELETE_RESOURCE_CATEGORY_FAILURE: $TSFixMe =
    'DELETE_RESOURCE_CATEGORY_FAILURE';
export const DELETE_RESOURCE_CATEGORY_REQUEST: $TSFixMe =
    'DELETE_RESOURCE_CATEGORY_REQUEST';

// Full Resource Category list for project settings
export const FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_REQUEST: $TSFixMe =
    'FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_REQUEST';
export const FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_SUCCESS: $TSFixMe =
    'FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_SUCCESS';
export const FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_FAILURE: $TSFixMe =
    'FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_FAILURE';
