//Resource Category list
export const FETCH_RESOURCE_CATEGORIES_REQUEST =
    'FETCH_RESOURCE_CATEGORIES_REQUEST';
export const FETCH_RESOURCE_CATEGORIES_SUCCESS =
    'FETCH_RESOURCE_CATEGORIES_SUCCESS';
export const FETCH_RESOURCE_CATEGORIES_FAILURE =
    'FETCH_RESOURCE_CATEGORIES_FAILURE';

//Create new resource Category
export const CREATE_RESOURCE_CATEGORY_SUCCESS =
    'CREATE_RESOURCE_CATEGORY_SUCCESS';
export const CREATE_RESOURCE_CATEGORY_FAILURE =
    'CREATE_RESOURCE_CATEGORY_FAILURE';
export const CREATE_RESOURCE_CATEGORY_REQUEST =
    'CREATE_RESOURCE_CATEGORY_REQUEST';

// Update resource Category
export const UPDATE_RESOURCE_CATEGORY_SUCCESS =
    'UPDATE_RESOURCE_CATEGORY_SUCCESS';
export const UPDATE_RESOURCE_CATEGORY_FAILURE =
    'UPDATE_RESOURCE_CATEGORY_FAILURE';
export const UPDATE_RESOURCE_CATEGORY_REQUEST =
    'UPDATE_RESOURCE_CATEGORY_REQUEST';

//Delete a resource Category
export const DELETE_RESOURCE_CATEGORY_SUCCESS =
    'DELETE_RESOURCE_CATEGORY_SUCCESS';
export const DELETE_RESOURCE_CATEGORY_FAILURE =
    'DELETE_RESOURCE_CATEGORY_FAILURE';
export const DELETE_RESOURCE_CATEGORY_REQUEST =
    'DELETE_RESOURCE_CATEGORY_REQUEST';

// Full Resource Category list for project settings
export const FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_REQUEST =
    'FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_REQUEST';
export const FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_SUCCESS =
    'FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_SUCCESS';
export const FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_FAILURE =
    'FETCH_RESOURCE_CATEGORIES_FOR_NEW_RESOURCE_FAILURE';
