export const FETCH_SCHEDULED_EVENTS_REQUEST: string =
    'FETCH_SCHEDULED_EVENTS_REQUEST';
export const FETCH_SCHEDULED_EVENTS_SUCCESS: string =
    'FETCH_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_SCHEDULED_EVENTS_FAILURE: string =
    'FETCH_SCHEDULED_EVENTS_FAILURE';

export const FETCH_SCHEDULED_EVENT_REQUEST: string =
    'FETCH_SCHEDULED_EVENT_REQUEST';
export const FETCH_SCHEDULED_EVENT_SUCCESS: string =
    'FETCH_SCHEDULED_EVENT_SUCCESS';
export const FETCH_SCHEDULED_EVENT_FAILURE: string =
    'FETCH_SCHEDULED_EVENT_FAILURE';

export const FETCH_ONGOING_SCHEDULED_EVENTS_REQUEST: $TSFixMe =
    'FETCH_ONGOING_SCHEDULED_EVENTS_REQUEST';
export const FETCH_ONGOING_SCHEDULED_EVENTS_SUCCESS: $TSFixMe =
    'FETCH_ONGOING_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_ONGOING_SCHEDULED_EVENTS_FAILURE: $TSFixMe =
    'FETCH_ONGOING_SCHEDULED_EVENTS_FAILURE';

export const FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_REQUEST: $TSFixMe =
    'FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_REQUEST';
export const FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_SUCCESS: $TSFixMe =
    'FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_FAILURE: $TSFixMe =
    'FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_FAILURE';

export const CREATE_SCHEDULED_EVENT_SUCCESS: string =
    'CREATE_SCHEDULED_EVENT_SUCCESS';
export const CREATE_SCHEDULED_EVENT_FAILURE: string =
    'CREATE_SCHEDULED_EVENT_FAILURE';
export const CREATE_SCHEDULED_EVENT_REQUEST: string =
    'CREATE_SCHEDULED_EVENT_REQUEST';

export const DELETE_SCHEDULED_EVENT_SUCCESS: string =
    'DELETE_SCHEDULED_EVENT_SUCCESS';
export const DELETE_SCHEDULED_EVENT_FAILURE: string =
    'DELETE_SCHEDULED_EVENT_FAILURE';
export const DELETE_SCHEDULED_EVENT_REQUEST: string =
    'DELETE_SCHEDULED_EVENT_REQUEST';

export const CANCEL_SCHEDULED_EVENT_SUCCESS: string =
    'CANCEL_SCHEDULED_EVENT_SUCCESS';
export const CANCEL_SCHEDULED_EVENT_FAILURE: string =
    'CANCEL_SCHEDULED_EVENT_FAILURE';
export const CANCEL_SCHEDULED_EVENT_REQUEST: string =
    'CANCEL_SCHEDULED_EVENT_REQUEST';

export const UPDATE_SCHEDULED_EVENT_SUCCESS: string =
    'UPDATE_SCHEDULED_EVENT_SUCCESS';
export const UPDATE_SCHEDULED_EVENT_FAILURE: string =
    'UPDATE_SCHEDULED_EVENT_FAILURE';
export const UPDATE_SCHEDULED_EVENT_REQUEST: string =
    'UPDATE_SCHEDULED_EVENT_REQUEST';

export const FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_REQUEST: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_REQUEST';
export const FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_SUCCESS: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_SUCCESS';
export const FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_FAILURE: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_FAILURE';

export const FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_REQUEST: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_REQUEST';
export const FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_SUCCESS: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_SUCCESS';
export const FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_FAILURE: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_FAILURE';

export const CREATE_SCHEDULED_EVENT_NOTE_REQUEST: $TSFixMe =
    'CREATE_SCHEDULED_EVENT_NOTE_REQUEST';
export const CREATE_SCHEDULED_EVENT_NOTE_SUCCESS: $TSFixMe =
    'CREATE_SCHEDULED_EVENT_NOTE_SUCCESS';
export const CREATE_SCHEDULED_EVENT_NOTE_FAILURE: $TSFixMe =
    'CREATE_SCHEDULED_EVENT_NOTE_FAILURE';

export const UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_REQUEST: $TSFixMe =
    'UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_REQUEST';
export const UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_SUCCESS: $TSFixMe =
    'UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_SUCCESS';
export const UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_FAILURE: $TSFixMe =
    'UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_FAILURE';

export const UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_REQUEST: $TSFixMe =
    'UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_REQUEST';
export const UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_SUCCESS: $TSFixMe =
    'UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_SUCCESS';
export const UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_FAILURE: $TSFixMe =
    'UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_FAILURE';

export const DELETE_SCHEDULED_EVENT_NOTE_REQUEST: $TSFixMe =
    'DELETE_SCHEDULED_EVENT_NOTE_REQUEST';
export const DELETE_SCHEDULED_EVENT_NOTE_SUCCESS: $TSFixMe =
    'DELETE_SCHEDULED_EVENT_NOTE_SUCCESS';
export const DELETE_SCHEDULED_EVENT_NOTE_FAILURE: $TSFixMe =
    'DELETE_SCHEDULED_EVENT_NOTE_FAILURE';

export const FETCH_SUBPROJECT_SCHEDULED_EVENTS_REQUEST: $TSFixMe =
    'FETCH_SUBPROJECT_SCHEDULED_EVENTS_REQUEST';
export const FETCH_SUBPROJECT_SCHEDULED_EVENTS_SUCCESS: $TSFixMe =
    'FETCH_SUBPROJECT_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_SUBPROJECT_SCHEDULED_EVENTS_FAILURE: $TSFixMe =
    'FETCH_SUBPROJECT_SCHEDULED_EVENTS_FAILURE';

export const RESOLVE_SCHEDULED_EVENT_REQUEST: $TSFixMe =
    'RESOLVE_SCHEDULED_EVENT_REQUEST';
export const RESOLVE_SCHEDULED_EVENT_SUCCESS: $TSFixMe =
    'RESOLVE_SCHEDULED_EVENT_SUCCESS';
export const RESOLVE_SCHEDULED_EVENT_FAILURE: $TSFixMe =
    'RESOLVE_SCHEDULED_EVENT_FAILURE';

export const NEXT_PAGE: string = 'NEXT_PAGE';
export const PREV_PAGE: string = 'PREV_PAGE';

// fetch scheduled event by slug
export const FETCH_SCHEDULED_EVENT_REQUEST_SLUG: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_REQUEST_SLUG';
export const FETCH_SCHEDULED_EVENT_SUCCESS_SLUG: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_SUCCESS_SLUG';
export const FETCH_SCHEDULED_EVENT_FAILURE_SLUG: $TSFixMe =
    'FETCH_SCHEDULED_EVENT_FAILURE_SLUG';

//add schedule event
export const ADD_SCHEDULE_EVENT: string = 'ADD_SCHEDULE_EVENT';
