export const FETCH_SCHEDULED_EVENTS_REQUEST = 'FETCH_SCHEDULED_EVENTS_REQUEST';
export const FETCH_SCHEDULED_EVENTS_SUCCESS = 'FETCH_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_SCHEDULED_EVENTS_FAILURE = 'FETCH_SCHEDULED_EVENTS_FAILURE';

export const FETCH_SCHEDULED_EVENT_REQUEST = 'FETCH_SCHEDULED_EVENT_REQUEST';
export const FETCH_SCHEDULED_EVENT_SUCCESS = 'FETCH_SCHEDULED_EVENT_SUCCESS';
export const FETCH_SCHEDULED_EVENT_FAILURE = 'FETCH_SCHEDULED_EVENT_FAILURE';

export const FETCH_ONGOING_SCHEDULED_EVENTS_REQUEST =
    'FETCH_ONGOING_SCHEDULED_EVENTS_REQUEST';
export const FETCH_ONGOING_SCHEDULED_EVENTS_SUCCESS =
    'FETCH_ONGOING_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_ONGOING_SCHEDULED_EVENTS_FAILURE =
    'FETCH_ONGOING_SCHEDULED_EVENTS_FAILURE';

export const FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_REQUEST =
    'FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_REQUEST';
export const FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_SUCCESS =
    'FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_FAILURE =
    'FETCH_SUBPROJECT_ONGOING_SCHEDULED_EVENTS_FAILURE';

export const CREATE_SCHEDULED_EVENT_SUCCESS = 'CREATE_SCHEDULED_EVENT_SUCCESS';
export const CREATE_SCHEDULED_EVENT_FAILURE = 'CREATE_SCHEDULED_EVENT_FAILURE';
export const CREATE_SCHEDULED_EVENT_REQUEST = 'CREATE_SCHEDULED_EVENT_REQUEST';

export const DELETE_SCHEDULED_EVENT_SUCCESS = 'DELETE_SCHEDULED_EVENT_SUCCESS';
export const DELETE_SCHEDULED_EVENT_FAILURE = 'DELETE_SCHEDULED_EVENT_FAILURE';
export const DELETE_SCHEDULED_EVENT_REQUEST = 'DELETE_SCHEDULED_EVENT_REQUEST';

export const UPDATE_SCHEDULED_EVENT_SUCCESS = 'UPDATE_SCHEDULED_EVENT_SUCCESS';
export const UPDATE_SCHEDULED_EVENT_FAILURE = 'UPDATE_SCHEDULED_EVENT_FAILURE';
export const UPDATE_SCHEDULED_EVENT_REQUEST = 'UPDATE_SCHEDULED_EVENT_REQUEST';

export const FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_REQUEST =
    'FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_REQUEST';
export const FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_SUCCESS =
    'FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_SUCCESS';
export const FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_FAILURE =
    'FETCH_SCHEDULED_EVENT_NOTES_INVESTIGATION_FAILURE';

export const FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_REQUEST =
    'FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_REQUEST';
export const FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_SUCCESS =
    'FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_SUCCESS';
export const FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_FAILURE =
    'FETCH_SCHEDULED_EVENT_NOTES_INTERNAL_FAILURE';

export const CREATE_SCHEDULED_EVENT_NOTE_REQUEST =
    'CREATE_SCHEDULED_EVENT_NOTE_REQUEST';
export const CREATE_SCHEDULED_EVENT_NOTE_SUCCESS =
    'CREATE_SCHEDULED_EVENT_NOTE_SUCCESS';
export const CREATE_SCHEDULED_EVENT_NOTE_FAILURE =
    'CREATE_SCHEDULED_EVENT_NOTE_FAILURE';

export const UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_REQUEST =
    'UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_REQUEST';
export const UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_SUCCESS =
    'UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_SUCCESS';
export const UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_FAILURE =
    'UPDATE_SCHEDULED_EVENT_NOTE_INTERNAL_FAILURE';

export const UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_REQUEST =
    'UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_REQUEST';
export const UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_SUCCESS =
    'UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_SUCCESS';
export const UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_FAILURE =
    'UPDATE_SCHEDULED_EVENT_NOTE_INVESTIGATION_FAILURE';

export const DELETE_SCHEDULED_EVENT_NOTE_REQUEST =
    'DELETE_SCHEDULED_EVENT_NOTE_REQUEST';
export const DELETE_SCHEDULED_EVENT_NOTE_SUCCESS =
    'DELETE_SCHEDULED_EVENT_NOTE_SUCCESS';
export const DELETE_SCHEDULED_EVENT_NOTE_FAILURE =
    'DELETE_SCHEDULED_EVENT_NOTE_FAILURE';

export const FETCH_SUBPROJECT_SCHEDULED_EVENTS_REQUEST =
    'FETCH_SUBPROJECT_SCHEDULED_EVENTS_REQUEST';
export const FETCH_SUBPROJECT_SCHEDULED_EVENTS_SUCCESS =
    'FETCH_SUBPROJECT_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_SUBPROJECT_SCHEDULED_EVENTS_FAILURE =
    'FETCH_SUBPROJECT_SCHEDULED_EVENTS_FAILURE';

export const RESOLVE_SCHEDULED_EVENT_REQUEST =
    'RESOLVE_SCHEDULED_EVENT_REQUEST';
export const RESOLVE_SCHEDULED_EVENT_SUCCESS =
    'RESOLVE_SCHEDULED_EVENT_SUCCESS';
export const RESOLVE_SCHEDULED_EVENT_FAILURE =
    'RESOLVE_SCHEDULED_EVENT_FAILURE';

export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';
