export const FETCH_SCHEDULED_EVENTS_REQUEST = 'FETCH_SCHEDULED_EVENTS_REQUEST';
export const FETCH_SCHEDULED_EVENTS_SUCCESS = 'FETCH_SCHEDULED_EVENTS_SUCCESS';
export const FETCH_SCHEDULED_EVENTS_FAILURE = 'FETCH_SCHEDULED_EVENTS_FAILURE';

export const CREATE_SCHEDULED_EVENT_SUCCESS = 'CREATE_SCHEDULED_EVENT_SUCCESS';
export const CREATE_SCHEDULED_EVENT_FAILURE = 'CREATE_SCHEDULED_EVENT_FAILURE';
export const CREATE_SCHEDULED_EVENT_REQUEST = 'CREATE_SCHEDULED_EVENT_REQUEST';

export const DELETE_SCHEDULED_EVENT_SUCCESS = 'DELETE_SCHEDULED_EVENT_SUCCESS';
export const DELETE_SCHEDULED_EVENT_FAILURE = 'DELETE_SCHEDULED_EVENT_FAILURE';
export const DELETE_SCHEDULED_EVENT_REQUEST = 'DELETE_SCHEDULED_EVENT_REQUEST';

export const UPDATE_SCHEDULED_EVENT_SUCCESS = 'UPDATE_SCHEDULED_EVENT_SUCCESS';
export const UPDATE_SCHEDULED_EVENT_FAILURE = 'UPDATE_SCHEDULED_EVENT_FAILURE';
export const UPDATE_SCHEDULED_EVENT_REQUEST = 'UPDATE_SCHEDULED_EVENT_REQUEST';