export const POPULATE_SEARCH_REQUEST: string = 'POPULATE_SEARCH_REQUEST';
export const POPULATE_SEARCH_FAILURE: string = 'POPULATE_SEARCH_FAILURE';
export const POPULATE_SEARCH_SUCCESS: string = 'POPULATE_SEARCH_SUCCESS';

export const SHOW_SEARCH_BAR: string = 'SHOW_SEARCH_BAR';
export const CLOSE_SEARCH_BAR: string = 'CLOSE_SEARCH_BAR';

export const RESET_SEARCH_FIELDS: string = 'RESET_SEARCH_FIELDS';
