export const POPULATE_SEARCH_REQUEST = 'POPULATE_SEARCH_REQUEST';
export const POPULATE_SEARCH_FAILURE = 'POPULATE_SEARCH_FAILURE';
export const POPULATE_SEARCH_SUCCESS = 'POPULATE_SEARCH_SUCCESS';

export const SHOW_SEARCH_BAR = 'SHOW_SEARCH_BAR';
export const CLOSE_SEARCH_BAR = 'CLOSE_SEARCH_BAR';

export const RESET_SEARCH_FIELDS = 'RESET_SEARCH_FIELDS';
