export const POPULATE_SEARCH_REQUEST = 'POPULATE_SEARCH_REQUEST';
export const POPULATE_SEARCH_FAILURE = 'POPULATE_SEARCH_FAILURE';
export const POPULATE_SEARCH_SUCCESS = 'POPULATE_SEARCH_SUCCESS';

export const RESET_SEARCH_FIELDS = 'RESET_SEARCH_FIELDS';
