// Container Security
export const ADD_CONTAINER_SECURITY_REQUEST: string =
    'ADD_CONTAINER_SECURITY_REQUEST';
export const ADD_CONTAINER_SECURITY_SUCCESS: string =
    'ADD_CONTAINER_SECURITY_SUCCESS';
export const ADD_CONTAINER_SECURITY_FAILURE: string =
    'ADD_CONTAINER_SECURITY_FAILURE';
export const GET_CONTAINER_SECURITIES_REQUEST: $TSFixMe =
    'GET_CONTAINER_SECURITIES_REQUEST';
export const GET_CONTAINER_SECURITIES_SUCCESS: $TSFixMe =
    'GET_CONTAINER_SECURITIES_SUCCESS';
export const GET_CONTAINER_SECURITIES_FAILURE: $TSFixMe =
    'GET_CONTAINER_SECURITIES_FAILURE';
export const DELETE_CONTAINER_SECURITY_REQUEST: $TSFixMe =
    'DELETE_CONTAINER_SECURITY_REQUEST';
export const DELETE_CONTAINER_SECURITY_SUCCESS: $TSFixMe =
    'DELETE_CONTAINER_SECURITY_SUCCESS';
export const DELETE_CONTAINER_SECURITY_FAILURE: $TSFixMe =
    'DELETE_CONTAINER_SECURITY_FAILURE';
export const GET_CONTAINER_SECURITY_REQUEST: string =
    'GET_CONTAINER_SECURITY_REQUEST';
export const GET_CONTAINER_SECURITY_SUCCESS: string =
    'GET_CONTAINER_SECURITY_SUCCESS';
export const GET_CONTAINER_SECURITY_FAILURE: string =
    'GET_CONTAINER_SECURITY_FAILURE';
export const SCAN_CONTAINER_SECURITY_REQUEST: $TSFixMe =
    'SCAN_CONTAINER_SECURITY_REQUEST';
export const SCAN_CONTAINER_SECURITY_SUCCESS: $TSFixMe =
    'SCAN_CONTAINER_SECURITY_SUCCESS';
export const SCAN_CONTAINER_SECURITY_FAILURE: $TSFixMe =
    'SCAN_CONTAINER_SECURITY_FAILURE';
export const GET_CONTAINER_SECURITY_LOG_REQUEST: $TSFixMe =
    'GET_CONTAINER_SECURITY_LOG_REQUEST';
export const GET_CONTAINER_SECURITY_LOG_SUCCESS: $TSFixMe =
    'GET_CONTAINER_SECURITY_LOG_SUCCESS';
export const GET_CONTAINER_SECURITY_LOG_FAILURE: $TSFixMe =
    'GET_CONTAINER_SECURITY_LOG_FAILURE';
export const GET_CONTAINER_SECURITY_LOGS_REQUEST: $TSFixMe =
    'GET_CONTAINER_SECURITY_LOGS_REQUEST';
export const GET_CONTAINER_SECURITY_LOGS_SUCCESS: $TSFixMe =
    'GET_CONTAINER_SECURITY_LOGS_SUCCESS';
export const GET_CONTAINER_SECURITY_LOGS_FAILURE: $TSFixMe =
    'GET_CONTAINER_SECURITY_LOGS_FAILURE';
export const EDIT_CONTAINER_SECURITY_REQUEST: $TSFixMe =
    'EDIT_CONTAINER_SECURITY_REQUEST';
export const EDIT_CONTAINER_SECURITY_SUCCESS: $TSFixMe =
    'EDIT_CONTAINER_SECURITY_SUCCESS';
export const EDIT_CONTAINER_SECURITY_FAILURE: $TSFixMe =
    'EDIT_CONTAINER_SECURITY_FAILURE';
export const SET_ACTIVE_CONTAINER_SECURITY: string =
    'SET_ACTIVE_CONTAINER_SECURITY';

// Application Security
export const ADD_APPLICATION_SECURITY_REQUEST: $TSFixMe =
    'ADD_APPLICATION_SECURITY_REQUEST';
export const ADD_APPLICATION_SECURITY_SUCCESS: $TSFixMe =
    'ADD_APPLICATION_SECURITY_SUCCESS';
export const ADD_APPLICATION_SECURITY_FAILURE: $TSFixMe =
    'ADD_APPLICATION_SECURITY_FAILURE';
export const GET_APPLICATION_SECURITIES_REQUEST: $TSFixMe =
    'GET_APPLICATION_SECURITIES_REQUEST';
export const GET_APPLICATION_SECURITIES_SUCCESS: $TSFixMe =
    'GET_APPLICATION_SECURITIES_SUCCESS';
export const GET_APPLICATION_SECURITIES_FAILURE: $TSFixMe =
    'GET_APPLICATION_SECURITIES_FAILURE';
export const DELETE_APPLICATION_SECURITY_REQUEST: $TSFixMe =
    'DELETE_APPLICATION_SECURITY_REQUEST';
export const DELETE_APPLICATION_SECURITY_SUCCESS: $TSFixMe =
    'DELETE_APPLICATION_SECURITY_SUCCESS';
export const DELETE_APPLICATION_SECURITY_FAILURE: $TSFixMe =
    'DELETE_APPLICATION_SECURITY_FAILURE';
export const GET_APPLICATION_SECURITY_REQUEST: $TSFixMe =
    'GET_APPLICATION_SECURITY_REQUEST';
export const GET_APPLICATION_SECURITY_SUCCESS: $TSFixMe =
    'GET_APPLICATION_SECURITY_SUCCESS';
export const GET_APPLICATION_SECURITY_FAILURE: $TSFixMe =
    'GET_APPLICATION_SECURITY_FAILURE';
export const SCAN_APPLICATION_SECURITY_REQUEST: $TSFixMe =
    'SCAN_APPLICATION_SECURITY_REQUEST';
export const SCAN_APPLICATION_SECURITY_SUCCESS: $TSFixMe =
    'SCAN_APPLICATION_SECURITY_SUCCESS';
export const SCAN_APPLICATION_SECURITY_FAILURE: $TSFixMe =
    'SCAN_APPLICATION_SECURITY_FAILURE';
export const GET_APPLICATION_SECURITY_LOG_REQUEST: $TSFixMe =
    'GET_APPLICATION_SECURITY_LOG_REQUEST';
export const GET_APPLICATION_SECURITY_LOG_SUCCESS: $TSFixMe =
    'GET_APPLICATION_SECURITY_LOG_SUCCESS';
export const GET_APPLICATION_SECURITY_LOG_FAILURE: $TSFixMe =
    'GET_APPLICATION_SECURITY_LOG_FAILURE';
export const GET_APPLICATION_SECURITY_LOGS_REQUEST: $TSFixMe =
    'GET_APPLICATION_SECURITY_LOGS_REQUEST';
export const GET_APPLICATION_SECURITY_LOGS_SUCCESS: $TSFixMe =
    'GET_APPLICATION_SECURITY_LOGS_SUCCESS';
export const GET_APPLICATION_SECURITY_LOGS_FAILURE: $TSFixMe =
    'GET_APPLICATION_SECURITY_LOGS_FAILURE';
export const EDIT_APPLICATION_SECURITY_REQUEST: $TSFixMe =
    'EDIT_APPLICATION_SECURITY_REQUEST';
export const EDIT_APPLICATION_SECURITY_SUCCESS: $TSFixMe =
    'EDIT_APPLICATION_SECURITY_SUCCESS';
export const EDIT_APPLICATION_SECURITY_FAILURE: $TSFixMe =
    'EDIT_APPLICATION_SECURITY_FAILURE';
export const SET_ACTIVE_APPLICATION_SECURITY: $TSFixMe =
    'SET_ACTIVE_APPLICATION_SECURITY';
