// Container Security
export const ADD_CONTAINER_SECURITY_REQUEST = 'ADD_CONTAINER_SECURITY_REQUEST';
export const ADD_CONTAINER_SECURITY_SUCCESS = 'ADD_CONTAINER_SECURITY_SUCCESS';
export const ADD_CONTAINER_SECURITY_FAILURE = 'ADD_CONTAINER_SECURITY_FAILURE';
export const GET_CONTAINER_SECURITIES_REQUEST =
    'GET_CONTAINER_SECURITIES_REQUEST';
export const GET_CONTAINER_SECURITIES_SUCCESS =
    'GET_CONTAINER_SECURITIES_SUCCESS';
export const GET_CONTAINER_SECURITIES_FAILURE =
    'GET_CONTAINER_SECURITIES_FAILURE';
export const DELETE_CONTAINER_SECURITY_REQUEST =
    'DELETE_CONTAINER_SECURITY_REQUEST';
export const DELETE_CONTAINER_SECURITY_SUCCESS =
    'DELETE_CONTAINER_SECURITY_SUCCESS';
export const DELETE_CONTAINER_SECURITY_FAILURE =
    'DELETE_CONTAINER_SECURITY_FAILURE';
export const GET_CONTAINER_SECURITY_REQUEST = 'GET_CONTAINER_SECURITY_REQUEST';
export const GET_CONTAINER_SECURITY_SUCCESS = 'GET_CONTAINER_SECURITY_SUCCESS';
export const GET_CONTAINER_SECURITY_FAILURE = 'GET_CONTAINER_SECURITY_FAILURE';
export const SCAN_CONTAINER_SECURITY_REQUEST =
    'SCAN_CONTAINER_SECURITY_REQUEST';
export const SCAN_CONTAINER_SECURITY_SUCCESS =
    'SCAN_CONTAINER_SECURITY_SUCCESS';
export const SCAN_CONTAINER_SECURITY_FAILURE =
    'SCAN_CONTAINER_SECURITY_FAILURE';
export const GET_CONTAINER_SECURITY_LOG_REQUEST =
    'GET_CONTAINER_SECURITY_LOG_REQUEST';
export const GET_CONTAINER_SECURITY_LOG_SUCCESS =
    'GET_CONTAINER_SECURITY_LOG_SUCCESS';
export const GET_CONTAINER_SECURITY_LOG_FAILURE =
    'GET_CONTAINER_SECURITY_LOG_FAILURE';
export const GET_CONTAINER_SECURITY_LOGS_REQUEST =
    'GET_CONTAINER_SECURITY_LOGS_REQUEST';
export const GET_CONTAINER_SECURITY_LOGS_SUCCESS =
    'GET_CONTAINER_SECURITY_LOGS_SUCCESS';
export const GET_CONTAINER_SECURITY_LOGS_FAILURE =
    'GET_CONTAINER_SECURITY_LOGS_FAILURE';
export const EDIT_CONTAINER_SECURITY_REQUEST =
    'EDIT_CONTAINER_SECURITY_REQUEST';
export const EDIT_CONTAINER_SECURITY_SUCCESS =
    'EDIT_CONTAINER_SECURITY_SUCCESS';
export const EDIT_CONTAINER_SECURITY_FAILURE =
    'EDIT_CONTAINER_SECURITY_FAILURE';

// Application Security
export const ADD_APPLICATION_SECURITY_REQUEST =
    'ADD_APPLICATION_SECURITY_REQUEST';
export const ADD_APPLICATION_SECURITY_SUCCESS =
    'ADD_APPLICATION_SECURITY_SUCCESS';
export const ADD_APPLICATION_SECURITY_FAILURE =
    'ADD_APPLICATION_SECURITY_FAILURE';
export const GET_APPLICATION_SECURITIES_REQUEST =
    'GET_APPLICATION_SECURITIES_REQUEST';
export const GET_APPLICATION_SECURITIES_SUCCESS =
    'GET_APPLICATION_SECURITIES_SUCCESS';
export const GET_APPLICATION_SECURITIES_FAILURE =
    'GET_APPLICATION_SECURITIES_FAILURE';
export const DELETE_APPLICATION_SECURITY_REQUEST =
    'DELETE_APPLICATION_SECURITY_REQUEST';
export const DELETE_APPLICATION_SECURITY_SUCCESS =
    'DELETE_APPLICATION_SECURITY_SUCCESS';
export const DELETE_APPLICATION_SECURITY_FAILURE =
    'DELETE_APPLICATION_SECURITY_FAILURE';
export const GET_APPLICATION_SECURITY_REQUEST =
    'GET_APPLICATION_SECURITY_REQUEST';
export const GET_APPLICATION_SECURITY_SUCCESS =
    'GET_APPLICATION_SECURITY_SUCCESS';
export const GET_APPLICATION_SECURITY_FAILURE =
    'GET_APPLICATION_SECURITY_FAILURE';
export const SCAN_APPLICATION_SECURITY_REQUEST =
    'SCAN_APPLICATION_SECURITY_REQUEST';
export const SCAN_APPLICATION_SECURITY_SUCCESS =
    'SCAN_APPLICATION_SECURITY_SUCCESS';
export const SCAN_APPLICATION_SECURITY_FAILURE =
    'SCAN_APPLICATION_SECURITY_FAILURE';
export const GET_APPLICATION_SECURITY_LOG_REQUEST =
    'GET_APPLICATION_SECURITY_LOG_REQUEST';
export const GET_APPLICATION_SECURITY_LOG_SUCCESS =
    'GET_APPLICATION_SECURITY_LOG_SUCCESS';
export const GET_APPLICATION_SECURITY_LOG_FAILURE =
    'GET_APPLICATION_SECURITY_LOG_FAILURE';
export const GET_APPLICATION_SECURITY_LOGS_REQUEST =
    'GET_APPLICATION_SECURITY_LOGS_REQUEST';
export const GET_APPLICATION_SECURITY_LOGS_SUCCESS =
    'GET_APPLICATION_SECURITY_LOGS_SUCCESS';
export const GET_APPLICATION_SECURITY_LOGS_FAILURE =
    'GET_APPLICATION_SECURITY_LOGS_FAILURE';
