export const CREATE_SLACK_WEBHOOK_SUCCESS = 'CREATE_SLACK_WEBHOOK_SUCCESS';
export const CREATE_SLACK_WEBHOOK_FAILED = 'CREATE_SLACK_WEBHOOK_FAILED';
export const CREATE_SLACK_WEBHOOK_REQUEST = 'CREATE_SLACK_WEBHOOK_REQUEST';
export const CREATE_SLACK_WEBHOOK_RESET = 'CREATE_SLACK_WEBHOOK_RESET';

export const UPDATE_SLACK_WEBHOOK_SUCCESS = 'UPDATE_SLACK_WEBHOOK_SUCCESS';
export const UPDATE_SLACK_WEBHOOK_FAILED = 'UPDATE_SLACK_WEBHOOK_FAILED';
export const UPDATE_SLACK_WEBHOOK_REQUEST = 'UPDATE_SLACK_WEBHOOK_REQUEST';
export const UPDATE_SLACK_WEBHOOK_RESET = 'UPDATE_SLACK_WEBHOOK_RESET';

export const GET_SLACK_WEBHOOK_SUCCESS = 'GET_SLACK_WEBHOOK_SUCCESS';
export const GET_SLACK_WEBHOOK_FAILED = 'GET_SLACK_WEBHOOK_FAILED';
export const GET_SLACK_WEBHOOK_REQUEST = 'GET_SLACK_WEBHOOK_REQUEST';
export const GET_SLACK_WEBHOOK_RESET = 'GET_SLACK_WEBHOOK_RESET';

export const DELETE_SLACK_WEBHOOK_SUCCESS = 'DELETE_SLACK_WEBHOOK_SUCCESS';
export const DELETE_SLACK_WEBHOOK_FAILED = 'DELETE_SLACK_WEBHOOK_FAILED';
export const DELETE_SLACK_WEBHOOK_REQUEST = 'DELETE_SLACK_WEBHOOK_REQUEST';
export const DELETE_SLACK_WEBHOOK_RESET = 'DELETE_SLACK_WEBHOOK_RESET';

export const PAGINATE_NEXT = 'slackWebhook/PAGINATE_NEXT';
export const PAGINATE_PREV = 'slackWebhook/PAGINATE_PREV';
export const PAGINATE_RESET = 'slackWebhook/PAGINATE_RESET';
