export const CREATE_SLACK_LINK_SUCCESS = 'slack/CREATE_SLACK_LINK_SUCCESS';
export const CREATE_SLACK_LINK_FAILED = 'slack/CREATE_SLACK_LINK_FAILED';
export const CREATE_SLACK_LINK_REQUEST = 'slack/CREATE_SLACK_LINK_REQUEST';
export const CREATE_SLACK_LINK_RESET = 'slack/CREATE_SLACK_LINK_RESET';

export const GET_SLACK_TEAM_SUCCESS = 'slack/GET_SLACK_TEAM_SUCCESS';
export const GET_SLACK_TEAM_FAILED = 'slack/GET_SLACK_TEAM_FAILED';
export const GET_SLACK_TEAM_REQUEST = 'slack/GET_SLACK_TEAM_REQUEST';
export const GET_SLACK_TEAM_RESET = 'slack/GET_SLACK_TEAM_RESET';

export const DELETE_SLACK_LINK_SUCCESS = 'slack/DELETE_SLACK_LINK_SUCCESS';
export const DELETE_SLACK_LINK_FAILED = 'slack/DELETE_SLACK_LINK_FAILED';
export const DELETE_SLACK_LINK_REQUEST = 'slack/DELETE_SLACK_LINK_REQUEST';
export const DELETE_SLACK_LINK_RESET = 'slack/DELETE_SLACK_LINK_RESET';

export const PAGINATE_NEXT = 'slack/PAGINATE_NEXT';
export const PAGINATE_PREV = 'slack/PAGINATE_PREV';
export const PAGINATE_RESET = 'slack/PAGINATE_RESET';
