export const  CREATE_SLACK_WEBHOOK_SUCCESS: string = 'CREATE_SLACK_WEBHOOK_SUCCESS';
export const  CREATE_SLACK_WEBHOOK_FAILED: string = 'CREATE_SLACK_WEBHOOK_FAILED';
export const  CREATE_SLACK_WEBHOOK_REQUEST: string = 'CREATE_SLACK_WEBHOOK_REQUEST';
export const  CREATE_SLACK_WEBHOOK_RESET: string = 'CREATE_SLACK_WEBHOOK_RESET';

export const  UPDATE_SLACK_WEBHOOK_SUCCESS: string = 'UPDATE_SLACK_WEBHOOK_SUCCESS';
export const  UPDATE_SLACK_WEBHOOK_FAILED: string = 'UPDATE_SLACK_WEBHOOK_FAILED';
export const  UPDATE_SLACK_WEBHOOK_REQUEST: string = 'UPDATE_SLACK_WEBHOOK_REQUEST';
export const  UPDATE_SLACK_WEBHOOK_RESET: string = 'UPDATE_SLACK_WEBHOOK_RESET';

export const  GET_SLACK_WEBHOOK_SUCCESS: string = 'GET_SLACK_WEBHOOK_SUCCESS';
export const  GET_SLACK_WEBHOOK_FAILED: string = 'GET_SLACK_WEBHOOK_FAILED';
export const  GET_SLACK_WEBHOOK_REQUEST: string = 'GET_SLACK_WEBHOOK_REQUEST';
export const  GET_SLACK_WEBHOOK_RESET: string = 'GET_SLACK_WEBHOOK_RESET';

export const  DELETE_SLACK_WEBHOOK_SUCCESS: string = 'DELETE_SLACK_WEBHOOK_SUCCESS';
export const  DELETE_SLACK_WEBHOOK_FAILED: string = 'DELETE_SLACK_WEBHOOK_FAILED';
export const  DELETE_SLACK_WEBHOOK_REQUEST: string = 'DELETE_SLACK_WEBHOOK_REQUEST';
export const  DELETE_SLACK_WEBHOOK_RESET: string = 'DELETE_SLACK_WEBHOOK_RESET';

export const  PAGINATE_NEXT: string = 'slackWebhook/PAGINATE_NEXT';
export const  PAGINATE_PREV: string = 'slackWebhook/PAGINATE_PREV';
export const  PAGINATE_RESET: string = 'slackWebhook/PAGINATE_RESET';
