export const SMS_TEMPLATES_SUCCESS = 'smstemplates/SMS_TEMPLATES_SUCCESS';
export const SMS_TEMPLATES_FAILED = 'smstemplates/SMS_TEMPLATES_FAILED';
export const SMS_TEMPLATES_REQUEST = 'smstemplates/SMS_TEMPLATES_REQUEST';
export const SMS_TEMPLATES_RESET = 'smstemplates/SMS_TEMPLATES_RESET';

export const RESET_SMS_TEMPLATES_SUCCESS = 'smstemplates/RESET_SMS_TEMPLATES_SUCCESS';
export const RESET_SMS_TEMPLATES_FAILED = 'smstemplates/RESET_SMS_TEMPLATES_FAILED';
export const RESET_SMS_TEMPLATES_REQUEST = 'smstemplates/RESET_SMS_TEMPLATES_REQUEST';

export const EDIT_SMS_TEMPLATES_SUCCESS = 'smstemplates/EDIT_SMS_TEMPLATES_SUCCESS';
export const EDIT_SMS_TEMPLATES_FAILED = 'smstemplates/EDIT_SMS_TEMPLATES_FAILED';
export const EDIT_SMS_TEMPLATES_REQUEST = 'smstemplates/EDIT_SMS_TEMPLATES_REQUEST';
export const EDIT_SMS_TEMPLATES_RESET = 'smstemplates/EDIT_SMS_TEMPLATES_RESET';

export const CHANGE_SHOWING_TEMPLATE = 'smstemplates/CHANGE_SHOWING_TEMPLATE';

export const SET_REVEAL_VARIABLE = 'smstemplates/SET_REVEAL_VARIABLE';

export const SET_SMTP_CONFIG = 'smstemplates/SET_SMTP_CONFIG';

export const SMTP_CONFIG_SUCCESS = 'smstemplates/SMTP_CONFIG_SUCCESS';
export const SMTP_CONFIG_FAILED = 'smstemplates/SMTP_CONFIG_FAILED';
export const SMTP_CONFIG_REQUEST = 'smstemplates/SMTP_CONFIG_REQUEST';

export const DELETE_SMTP_CONFIG_SUCCESS = 'smstemplates/DELETE_SMTP_CONFIG_SUCCESS';
export const DELETE_SMTP_CONFIG_FAILED = 'smstemplates/DELETE_SMTP_CONFIG_FAILED';
export const DELETE_SMTP_CONFIG_REQUEST = 'smstemplates/DELETE_SMTP_CONFIG_REQUEST';