export const CREATE_SSO_REQUEST = 'CREATE_SSO_REQUEST';
export const CREATE_SSO_SUCCESS = 'CREATE_SSO_SUCCESS';
export const CREATE_SSO_FAILURE = 'CREATE_SSO_FAILURE';

export const FETCH_SSOS_REQUEST = 'FETCH_SSOS_REQUEST';
export const FETCH_SSOS_SUCCESS = 'FETCH_SSOS_SUCCESS';
export const FETCH_SSOS_FAILURE = 'FETCH_SSOS_FAILURE';

export const UPDATE_SSO_REQUEST = 'UPDATE_SSO_REQUEST';
export const UPDATE_SSO_SUCCESS = 'UPDATE_SSO_SUCCESS';
export const UPDATE_SSO_FAILURE = 'UPDATE_SSO_FAILURE';

export const FETCH_SSO_REQUEST = 'FETCH_SSO_REQUEST';
export const FETCH_SSO_SUCCESS = 'FETCH_SSO_SUCCESS';
export const FETCH_SSO_FAILURE = 'FETCH_SSO_FAILURE';

export const DELETE_SSO_REQUEST = 'DELETE_SSO_REQUEST';
export const DELETE_SSO_SUCCESS = 'DELETE_SSO_REQUEST';
export const DELETE_SSO_FAILURE = 'DELETE_SSO_FAILURE';
