//Create status page
export const CREATE_STATUSPAGE_REQUEST: string = 'CREATE_STATUSPAGE_REQUEST';
export const CREATE_STATUSPAGE_SUCCESS: string = 'CREATE_STATUSPAGE_SUCCESS';
export const CREATE_STATUSPAGE_FAILURE: string = 'CREATE_STATUSPAGE_FAILURE';
export const CREATE_STATUSPAGE_RESET: string = 'CREATE_STATUSPAGE_RESET';

//Update status page setting
export const UPDATE_STATUSPAGE_SETTING_REQUEST: $TSFixMe =
    'UPDATE_STATUSPAGE_SETTING_REQUEST';
export const UPDATE_STATUSPAGE_SETTING_SUCCESS: $TSFixMe =
    'UPDATE_STATUSPAGE_SETTING_SUCCESS';
export const UPDATE_STATUSPAGE_SETTING_FAILURE: $TSFixMe =
    'UPDATE_STATUSPAGE_SETTING_FAILURE';
export const UPDATE_STATUSPAGE_SETTING_RESET: $TSFixMe =
    'UPDATE_STATUSPAGE_SETTING_RESET';

//Update status page monitors
export const UPDATE_STATUSPAGE_MONITORS_REQUEST: $TSFixMe =
    'UPDATE_STATUSPAGE_MONITORS_REQUEST';
export const UPDATE_STATUSPAGE_MONITORS_SUCCESS: $TSFixMe =
    'UPDATE_STATUSPAGE_MONITORS_SUCCESS';
export const UPDATE_STATUSPAGE_MONITORS_FAILURE: $TSFixMe =
    'UPDATE_STATUSPAGE_MONITORS_FAILURE';
export const UPDATE_STATUSPAGE_MONITORS_RESET: $TSFixMe =
    'UPDATE_STATUSPAGE_MONITORS_RESET';

//Update private status pages
export const UPDATE_PRIVATE_STATUSPAGE_REQUEST: $TSFixMe =
    'UPDATE_PRIVATE_STATUSPAGE_REQUEST';
export const UPDATE_PRIVATE_STATUSPAGE_SUCCESS: $TSFixMe =
    'UPDATE_PRIVATE_STATUSPAGE_SUCCESS';
export const UPDATE_PRIVATE_STATUSPAGE_FAILURE: $TSFixMe =
    'UPDATE_PRIVATE_STATUSPAGE_FAILURE';
export const UPDATE_PRIVATE_STATUSPAGE_RESET: $TSFixMe =
    'UPDATE_PRIVATE_STATUSPAGE_RESET';

//Update status page subscriber options
export const UPDATE_SUBSCRIBER_OPTION_REQUEST: $TSFixMe =
    'UPDATE_SUBSCRIBER_OPTION_REQUEST';
export const UPDATE_SUBSCRIBER_OPTION_SUCCESS: $TSFixMe =
    'UPDATE_SUBSCRIBER_OPTION_SUCCESS';
export const UPDATE_SUBSCRIBER_OPTION_FAILURE: $TSFixMe =
    'UPDATE_SUBSCRIBER_OPTION_FAILURE';
export const UPDATE_SUBSCRIBER_OPTION_RESET: string =
    'UPDATE_SUBSCRIBER_OPTION_RESET';

//Update status page branding
export const UPDATE_STATUSPAGE_BRANDING_REQUEST: $TSFixMe =
    'UPDATE_STATUSPAGE_BRANDING_REQUEST';
export const UPDATE_STATUSPAGE_BRANDING_SUCCESS: $TSFixMe =
    'UPDATE_STATUSPAGE_BRANDING_SUCCESS';
export const UPDATE_STATUSPAGE_BRANDING_FAILURE: $TSFixMe =
    'UPDATE_STATUSPAGE_BRANDING_FAILURE';
export const UPDATE_STATUSPAGE_BRANDING_RESET: $TSFixMe =
    'UPDATE_STATUSPAGE_BRANDING_RESET';

// update status page theme
export const UPDATE_STATUSPAGE_THEME_REQUEST: $TSFixMe =
    'UPDATE_STATUSPAGE_THEME_REQUEST';
export const UPDATE_STATUSPAGE_THEME_SUCCESS: $TSFixMe =
    'UPDATE_STATUSPAGE_THEME_SUCCESS';
export const UPDATE_STATUSPAGE_THEME_FAILURE: $TSFixMe =
    'UPDATE_STATUSPAGE_THEME_FAILURE';

//Update status page name
export const UPDATE_STATUSPAGE_NAME_REQUEST: string =
    'UPDATE_STATUSPAGE_NAME_REQUEST';
export const UPDATE_STATUSPAGE_NAME_SUCCESS: string =
    'UPDATE_STATUSPAGE_NAME_SUCCESS';
export const UPDATE_STATUSPAGE_NAME_FAILURE: string =
    'UPDATE_STATUSPAGE_NAME_FAILURE';
export const UPDATE_STATUSPAGE_NAME_RESET: string =
    'UPDATE_STATUSPAGE_NAME_RESET';

//Update status page links
export const UPDATE_STATUSPAGE_LINKS_REQUEST: $TSFixMe =
    'UPDATE_STATUSPAGE_LINKS_REQUEST';
export const UPDATE_STATUSPAGE_LINKS_SUCCESS: $TSFixMe =
    'UPDATE_STATUSPAGE_LINKS_SUCCESS';
export const UPDATE_STATUSPAGE_LINKS_FAILURE: $TSFixMe =
    'UPDATE_STATUSPAGE_LINKS_FAILURE';
export const UPDATE_STATUSPAGE_LINKS_RESET: string =
    'UPDATE_STATUSPAGE_LINKS_RESET';

//Update status page links
export const UPDATE_STATUSPAGE_CUSTOM_HTML_REQUEST: $TSFixMe =
    'UPDATE_STATUSPAGE_CUSTOM_HTML_REQUEST';
export const UPDATE_STATUSPAGE_CUSTOM_HTML_SUCCESS: $TSFixMe =
    'UPDATE_STATUSPAGE_CUSTOM_HTML_SUCCESS';
export const UPDATE_STATUSPAGE_CUSTOM_HTML_FAILURE: $TSFixMe =
    'UPDATE_STATUSPAGE_CUSTOM_HTML_FAILURE';

//fetch status page
export const FETCH_STATUSPAGE_REQUEST: string = 'FETCH_STATUSPAGE_REQUEST';
export const FETCH_STATUSPAGE_SUCCESS: string = 'FETCH_STATUSPAGE_SUCCESS';
export const FETCH_STATUSPAGE_FAILURE: string = 'FETCH_STATUSPAGE_FAILURE';
export const FETCH_STATUSPAGE_RESET: string = 'FETCH_STATUSPAGE_RESET';

//fetch subproject status page
export const FETCH_SUBPROJECT_STATUSPAGE_REQUEST: $TSFixMe =
    'FETCH_SUBPROJECT_STATUSPAGE_REQUEST';
export const FETCH_SUBPROJECT_STATUSPAGE_SUCCESS: $TSFixMe =
    'FETCH_SUBPROJECT_STATUSPAGE_SUCCESS';
export const FETCH_SUBPROJECT_STATUSPAGE_FAILURE: $TSFixMe =
    'FETCH_SUBPROJECT_STATUSPAGE_FAILURE';
export const FETCH_SUBPROJECT_STATUSPAGE_RESET: $TSFixMe =
    'FETCH_SUBPROJECT_STATUSPAGE_RESET';

//fetch list of statuspages in a project
export const FETCH_PROJECT_STATUSPAGE_REQUEST: $TSFixMe =
    'FETCH_PROJECT_STATUSPAGE_REQUEST';
export const FETCH_PROJECT_STATUSPAGE_SUCCESS: $TSFixMe =
    'FETCH_PROJECT_STATUSPAGE_SUCCESS';
export const FETCH_PROJECT_STATUSPAGE_FAILURE: $TSFixMe =
    'FETCH_PROJECT_STATUSPAGE_FAILURE';
export const FETCH_PROJECT_STATUSPAGE_RESET: string =
    'FETCH_PROJECT_STATUSPAGE_RESET';

export const SWITCH_STATUSPAGE_SUCCESS: string = 'SWITCH_STATUSPAGE_SUCCESS';

export const DELETE_PROJECT_STATUSPAGES: string =
    'incident/DELETE_PROJECT_STATUSPAGES';
export const DELETE_STATUSPAGE_REQUEST: string = 'DELETE_STATUSPAGE_REQUEST';
export const DELETE_STATUSPAGE_SUCCESS: string = 'DELETE_STATUSPAGE_SUCCESS';
export const DELETE_STATUSPAGE_FAILED: string = 'DELETE_STATUSPAGE_FAILED';
export const DELETE_STATUSPAGE_RESET: string = 'DELETE_STATUSPAGE_RESET';

//Duplicate Status Page
export const DUPLICATE_STATUSPAGE_REQUEST: string =
    'DUPLICATE_STATUSPAGE_REQUEST';
export const DUPLICATE_STATUSPAGE_SUCCESS: string =
    'DUPLICATE_STATUSPAGE_SUCCESS';
export const DUPLICATE_STATUSPAGE_FAILURE: string =
    'DUPLICATE_STATUSPAGE_FAILURE';
export const DUPLICATE_STATUSPAGE_RESET: string = 'DUPLICATE_STATUSPAGE_RESET';

//fetch incident's status page
export const FETCH_INCIDENT_STATUSPAGE_REQUEST: $TSFixMe =
    'FETCH_INCIDENT_STATUSPAGE_REQUEST';
export const FETCH_INCIDENT_STATUSPAGE_SUCCESS: $TSFixMe =
    'FETCH_INCIDENT_STATUSPAGE_SUCCESS';
export const FETCH_INCIDENT_STATUSPAGE_FAILURE: $TSFixMe =
    'FETCH_INCIDENT_STATUSPAGE_FAILURE';
export const FETCH_INCIDENT_STATUSPAGE_RESET: $TSFixMe =
    'FETCH_INCIDENT_STATUSPAGE_RESET';

// Logo
export const FAVICON_CACHE_INSERT: string = 'incident/FAVICON_CACHE_INSERT';
export const LOGO_CACHE_INSERT: string = 'incident/LOGO_CACHE_INSERT';
export const FAVICON_CACHE_RESET: string = 'incident/FAVICON_CACHE_RESET';
export const LOGO_CACHE_RESET: string = 'incident/LOGO_CACHE_RESET';

// Banner
export const BANNER_CACHE_INSERT: string = 'BANNER_CACHE_INSERT';
export const BANNER_CACHE_RESET: string = 'BANNER_CACHE_RESET';

// Colors
export const SET_STATUS_PAGE_COLORS: string = 'UPDATE_STATUS_PAGE_COLORS';

// Implements pagination for Status pages table

export const PAGINATE_NEXT: string = 'PAGINATE_NEXT';
export const PAGINATE_PREV: string = 'PAGINATE_PREV';
export const PAGINATE_RESET: string = 'PAGINATE_RESET';

// whether to show input field to add more domain
export const ADD_MORE_DOMAIN: string = 'ADD_MORE_DOMAIN';
export const CANCEL_ADD_MORE_DOMAIN: string = 'CANCEL_ADD_MORE_DOMAIN';

//Reset status bubble id
export const RESET_STATUS_BUBBLE_ID_REQUEST: string =
    'RESET_STATUS_BUBBLE_ID_REQUEST';
export const RESET_STATUS_BUBBLE_ID_SUCCESS: string =
    'RESET_STATUS_BUBBLE_ID_SUCCESS';
export const RESET_STATUS_BUBBLE_ID_FAILURE: string =
    'RESET_STATUS_BUBBLE_ID_FAILURE';

//Update status page embedded css
export const UPDATE_STATUSPAGE_EMBEDDED_CSS_REQUEST: $TSFixMe =
    'UPDATE_STATUSPAGE_EMBEDDED_CSS_REQUEST';
export const UPDATE_STATUSPAGE_EMBEDDED_CSS_SUCCESS: $TSFixMe =
    'UPDATE_STATUSPAGE_EMBEDDED_CSS_SUCCESS';
export const UPDATE_STATUSPAGE_EMBEDDED_CSS_FAILURE: $TSFixMe =
    'UPDATE_STATUSPAGE_SETTING_FAILURE';

//Reset status page embedded css
export const RESET_STATUSPAGE_EMBEDDED_CSS_REQUEST: $TSFixMe =
    'RESET_STATUSPAGE_EMBEDDED_CSS_REQUEST';
export const RESET_STATUSPAGE_EMBEDDED_CSS_SUCCESS: $TSFixMe =
    'RESET_STATUSPAGE_EMBEDDED_CSS_SUCCESS';
export const RESET_STATUSPAGE_EMBEDDED_CSS_FAILURE: $TSFixMe =
    'RESET_STATUSPAGE_SETTING_FAILURE';

//Duplicate Status Page

export const SHOW_DUPLICATE_STATUSPAGE: string = 'SHOW_DUPLICATE_STATUSPAGE';

//reseting brand colors
export const RESET_BRANDING_COLORS_REQUEST: string =
    'RESET_BRANDING_COLORS_REQUEST';
export const RESET_BRANDING_COLORS_FAILURE: string =
    'RESET_BRANDING_COLORS_FAILURE';
export const RESET_BRANDING_COLORS_SUCCESS: string =
    'RESET_BRANDING_COLORS_SUCCESS';

//subscribers tab
export const FETCH_SUBSCRIBER_SUCCESS: string = 'FETCH_SUBSCRIBER_SUCCESS';
export const FETCH_SUBSCRIBER_REQUEST: string = 'FETCH_SUBSCRIBER_REQUEST';
export const FETCH_SUBSCRIBER_FAILURE: string = 'FETCH_SUBSCRIBER_FAILURE';

//Create External Status Page
export const CREATE_EXTERNAL_STATUSPAGE_REQUEST: $TSFixMe =
    'CREATE_EXTERNAL_STATUSPAGE_REQUEST';
export const CREATE_EXTERNAL_STATUSPAGE_SUCCESS: $TSFixMe =
    'CREATE_EXTERNAL_STATUSPAGE_SUCCESS';
export const CREATE_EXTERNAL_STATUSPAGE_FAILURE: $TSFixMe =
    'CREATE_EXTERNAL_STATUSPAGE_FAILURE';

//Update External Status Page
export const UPDATE_EXTERNAL_STATUSPAGE_REQUEST: $TSFixMe =
    'UPDATE_EXTERNAL_STATUSPAGE_REQUEST';
export const UPDATE_EXTERNAL_STATUSPAGE_SUCCESS: $TSFixMe =
    'UPDATE_EXTERNAL_STATUSPAGE_SUCCESS';
export const UPDATE_EXTERNAL_STATUSPAGE_FAILURE: $TSFixMe =
    'UPDATE_EXTERNAL_STATUSPAGE_FAILURE';

//Fetch External Status Pages
export const FETCH_EXTERNAL_STATUSPAGES_REQUEST: $TSFixMe =
    'FETCH_EXTERNAL_STATUSPAGES_REQUEST';
export const FETCH_EXTERNAL_STATUSPAGES_SUCCESS: $TSFixMe =
    'FETCH_EXTERNAL_STATUSPAGES_SUCCESS';
export const FETCH_EXTERNAL_STATUSPAGES_FAILURE: $TSFixMe =
    'FETCH_EXTERNAL_STATUSPAGES_FAILURE';

//Delete External Status Page
export const DELETE_EXTERNAL_STATUSPAGE_REQUEST: $TSFixMe =
    'DELETE_EXTERNAL_STATUSPAGE_REQUEST';
export const DELETE_EXTERNAL_STATUSPAGE_SUCCESS: $TSFixMe =
    'DELETE_EXTERNAL_STATUSPAGE_SUCCESS';
export const DELETE_EXTERNAL_STATUSPAGE_FAILURE: $TSFixMe =
    'DELETE_EXTERNAL_STATUSPAGE_FAILURE';

//Announcement tab
export const CREATE_ANNOUNCEMEMT_REQUEST: string =
    'CREATE_ANNOUNCEMEMT_REQUEST';
export const CREATE_ANNOUNCEMEMT_FAILURE: string =
    'CREATE_ANNOUNCEMEMT_FAILURE';
export const CREATE_ANNOUNCEMEMT_SUCCESS: string =
    'CREATE_ANNOUNCEMEMT_SUCCESS';
export const FETCH_ANNOUNCEMEMT_REQUEST: string = 'FETCH_ANNOUNCEMEMT_REQUEST';
export const FETCH_ANNOUNCEMEMT_FAILURE: string = 'FETCH_ANNOUNCEMEMT_FAILURE';
export const FETCH_ANNOUNCEMEMT_SUCCESS: string = 'FETCH_ANNOUNCEMEMT_SUCCESS';

export const FETCH_SINCLE_ANNOUNCEMENT_SUCCESS: $TSFixMe =
    'FETCH_SINCLE_ANNOUNCEMENT_SUCCESS';
export const FETCH_SINCLE_ANNOUNCEMENT_FAILURE: $TSFixMe =
    'FETCH_SINCLE_ANNOUNCEMENT_FAILURE';
export const HANDLE_ANNOUNCEMENT_SUCCESS: string =
    'HANDLE_ANNOUNCEMENT_SUCCESS';
export const HANDLE_ANNOUNCEMENT_FAILURE: string =
    'HANDLE_ANNOUNCEMENT_FAILURE';
export const RESET_HANDLE_ANNOUNCEMENT: string = 'RESET_HANDLE_ANNOUNCEMENT';

export const DELETE_ANNOUNCEMENT_REQUEST: string =
    'DELETE_ANNOUNCEMENT_REQUEST';
export const DELETE_ANNOUNCEMENT_SUCCESS: string =
    'DELETE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_FAILURE: string =
    'DELETE_ANNOUNCEMENT_FAILURE';
export const RESET_DELETE_ANNOUNCEMENT: string = 'RESET_DELETE_ANNOUNCEMENT';
export const FETCH_ANNOUNCEMEMTLOGS_REQUEST: string =
    'FETCH_ANNOUNCEMEMTLOGS_REQUEST';
export const FETCH_ANNOUNCEMEMTLOGS_SUCCESS: string =
    'FETCH_ANNOUNCEMEMTLOGS_SUCCESS';
export const FETCH_ANNOUNCEMEMTLOGS_FAILURE: string =
    'FETCH_ANNOUNCEMEMTLOGS_FAILURE';

//update status page layout
export const UPDATE_STATUS_PAGE_LAYOUT_REQUEST: $TSFixMe =
    'UPDATE_STATUS_PAGE_LAYOUT_REQUEST';
export const UPDATE_STATUS_PAGE_LAYOUT_SUCCESS: $TSFixMe =
    'UPDATE_STATUS_PAGE_LAYOUT_SUCCESS';
export const UPDATE_STATUS_PAGE_LAYOUT_FAILURE: $TSFixMe =
    'UPDATE_STATUS_PAGE_LAYOUT_FAILURE';

export const UPDATE_STATUSPAGE_SUCCESS: string = 'UPDATE_STATUSPAGE_SUCCESS';

//update status page language
export const UPDATE_MULTIPLE_LANGUAGE_REQUEST: $TSFixMe =
    'UPDATE_MULTIPLE_LANGUAGE_REQUEST';
export const UPDATE_MULTIPLE_LANGUAGE_SUCCESS: $TSFixMe =
    'UPDATE_MULTIPLE_LANGUAGE_SUCCESS';
export const UPDATE_MULTIPLE_LANGUAGE_FAILURE: $TSFixMe =
    'UPDATE_MULTIPLE_LANGUAGE_FAILURE';
