// create status page category
export const CREATE_STATUS_PAGE_CATEGORY_REQUEST =
    'CREATE_STATUS_PAGE_CATEGORY_REQUEST';
export const CREATE_STATUS_PAGE_CATEGORY_SUCCESS =
    'CREATE_STATUS_PAGE_CATEGORY_SUCCESS';
export const CREATE_STATUS_PAGE_CATEGORY_FAILURE =
    'CREATE_STATUS_PAGE_CATEGORY_FAILURE';

// update status page category
export const UPDATE_STATUS_PAGE_CATEGORY_REQUEST =
    'UPDATE_STATUS_PAGE_CATEGORY_REQUEST';
export const UPDATE_STATUS_PAGE_CATEGORY_SUCCESS =
    'UPDATE_STATUS_PAGE_CATEGORY_SUCCESS';
export const UPDATE_STATUS_PAGE_CATEGORY_FAILURE =
    'UPDATE_STATUS_PAGE_CATEGORY_FAILURE';

// fetch status page categories
export const FETCH_STATUS_PAGE_CATEGORIES_REQUEST =
    'FETCH_STATUS_PAGE_CATEGORIES_REQUEST';
export const FETCH_STATUS_PAGE_CATEGORIES_SUCCESS =
    'FETCH_STATUS_PAGE_CATEGORIES_SUCCESS';
export const FETCH_STATUS_PAGE_CATEGORIES_FAILURE =
    'FETCH_STATUS_PAGE_CATEGORIES_FAILURE';

// fetch all status page categories without limit
export const FETCH_ALL_STATUS_PAGE_CATEGORIES_REQUEST =
    'FETCH_ALL_STATUS_PAGE_CATEGORIES_REQUEST';
export const FETCH_ALL_STATUS_PAGE_CATEGORIES_SUCCESS =
    'FETCH_ALL_STATUS_PAGE_CATEGORIES_SUCCESS';
export const FETCH_ALL_STATUS_PAGE_CATEGORIES_FAILURE =
    'FETCH_ALL_STATUS_PAGE_CATEGORIES_FAILURE';

// delete status page category
export const DELETE_STATUS_PAGE_CATEGORY_REQUEST =
    'DELETE_STATUS_PAGE_CATEGORY_REQUEST';
export const DELETE_STATUS_PAGE_CATEGORY_SUCCESS =
    'DELETE_STATUS_PAGE_CATEGORY_SUCCESS';
export const DELETE_STATUS_PAGE_CATEGORY_FAILURE =
    'DELETE_STATUS_PAGE_CATEGORY_FAILURE';
