//Create status page
export const CREATE_STATUSPAGE_REQUEST = 'CREATE_STATUSPAGE_REQUEST';
export const CREATE_STATUSPAGE_SUCCESS = 'CREATE_STATUSPAGE_SUCCESS';
export const CREATE_STATUSPAGE_FAILURE = 'CREATE_STATUSPAGE_FAILURE';
export const CREATE_STATUSPAGE_RESET = 'CREATE_STATUSPAGE_RESET';

//Update status page setting
export const UPDATE_STATUSPAGE_SETTING_REQUEST = 'UPDATE_STATUSPAGE_SETTING_REQUEST';
export const UPDATE_STATUSPAGE_SETTING_SUCCESS = 'UPDATE_STATUSPAGE_SETTING_SUCCESS';
export const UPDATE_STATUSPAGE_SETTING_FAILURE = 'UPDATE_STATUSPAGE_SETTING_FAILURE';
export const UPDATE_STATUSPAGE_SETTING_RESET = 'UPDATE_STATUSPAGE_SETTING_RESET';

//Update status page monitors
export const UPDATE_STATUSPAGE_MONITORS_REQUEST = 'UPDATE_STATUSPAGE_MONITORS_REQUEST';
export const UPDATE_STATUSPAGE_MONITORS_SUCCESS = 'UPDATE_STATUSPAGE_MONITORS_SUCCESS';
export const UPDATE_STATUSPAGE_MONITORS_FAILURE = 'UPDATE_STATUSPAGE_MONITORS_FAILURE';
export const UPDATE_STATUSPAGE_MONITORS_RESET = 'UPDATE_STATUSPAGE_MONITORS_RESET'

//Update private status pages
export const UPDATE_PRIVATE_STATUSPAGE_REQUEST = 'UPDATE_PRIVATE_STATUSPAGE_REQUEST';
export const UPDATE_PRIVATE_STATUSPAGE_SUCCESS = 'UPDATE_PRIVATE_STATUSPAGE_SUCCESS';
export const UPDATE_PRIVATE_STATUSPAGE_FAILURE = 'UPDATE_PRIVATE_STATUSPAGE_FAILURE';
export const UPDATE_PRIVATE_STATUSPAGE_RESET = 'UPDATE_PRIVATE_STATUSPAGE_RESET'

//Update status page branding
export const UPDATE_STATUSPAGE_BRANDING_REQUEST = 'UPDATE_STATUSPAGE_BRANDING_REQUEST';
export const UPDATE_STATUSPAGE_BRANDING_SUCCESS = 'UPDATE_STATUSPAGE_BRANDING_SUCCESS';
export const UPDATE_STATUSPAGE_BRANDING_FAILURE = 'UPDATE_STATUSPAGE_BRANDING_FAILURE';
export const UPDATE_STATUSPAGE_BRANDING_RESET = 'UPDATE_STATUSPAGE_BRANDING_RESET';

//Update status page name
export const UPDATE_STATUSPAGE_NAME_REQUEST = 'UPDATE_STATUSPAGE_NAME_REQUEST';
export const UPDATE_STATUSPAGE_NAME_SUCCESS = 'UPDATE_STATUSPAGE_NAME_SUCCESS';
export const UPDATE_STATUSPAGE_NAME_FAILURE = 'UPDATE_STATUSPAGE_NAME_FAILURE';
export const UPDATE_STATUSPAGE_NAME_RESET = 'UPDATE_STATUSPAGE_NAME_RESET';

//Update status page links
export const UPDATE_STATUSPAGE_LINKS_REQUEST = 'UPDATE_STATUSPAGE_LINKS_REQUEST';
export const UPDATE_STATUSPAGE_LINKS_SUCCESS = 'UPDATE_STATUSPAGE_LINKS_SUCCESS';
export const UPDATE_STATUSPAGE_LINKS_FAILURE = 'UPDATE_STATUSPAGE_LINKS_FAILURE';
export const UPDATE_STATUSPAGE_LINKS_RESET = 'UPDATE_STATUSPAGE_LINKS_RESET';

//fetch status page
export const FETCH_STATUSPAGE_REQUEST = 'FETCH_STATUSPAGE_REQUEST';
export const FETCH_STATUSPAGE_SUCCESS = 'FETCH_STATUSPAGE_SUCCESS';
export const FETCH_STATUSPAGE_FAILURE = 'FETCH_STATUSPAGE_FAILURE';
export const FETCH_STATUSPAGE_RESET = 'FETCH_STATUSPAGE_RESET';

//fetch subproject status page
export const FETCH_SUBPROJECT_STATUSPAGE_REQUEST = 'FETCH_SUBPROJECT_STATUSPAGE_REQUEST';
export const FETCH_SUBPROJECT_STATUSPAGE_SUCCESS = 'FETCH_SUBPROJECT_STATUSPAGE_SUCCESS';
export const FETCH_SUBPROJECT_STATUSPAGE_FAILURE = 'FETCH_SUBPROJECT_STATUSPAGE_FAILURE';
export const FETCH_SUBPROJECT_STATUSPAGE_RESET = 'FETCH_SUBPROJECT_STATUSPAGE_RESET';

//fetch list of statuspages in a project
export const FETCH_PROJECT_STATUSPAGE_REQUEST = 'FETCH_PROJECT_STATUSPAGE_REQUEST';
export const FETCH_PROJECT_STATUSPAGE_SUCCESS = 'FETCH_PROJECT_STATUSPAGE_SUCCESS';
export const FETCH_PROJECT_STATUSPAGE_FAILURE = 'FETCH_PROJECT_STATUSPAGE_FAILURE';
export const FETCH_PROJECT_STATUSPAGE_RESET = 'FETCH_PROJECT_STATUSPAGE_RESET';

export const SWITCH_STATUSPAGE_SUCCESS = 'SWITCH_STATUSPAGE_SUCCESS';

export const DELETE_PROJECT_STATUSPAGES = 'incident/DELETE_PROJECT_STATUSPAGES';
export const DELETE_STATUSPAGE_REQUEST = 'DELETE_STATUSPAGE_REQUEST';
export const DELETE_STATUSPAGE_SUCCESS = 'DELETE_STATUSPAGE_SUCCESS';
export const DELETE_STATUSPAGE_FAILED = 'DELETE_STATUSPAGE_FAILED';
export const DELETE_STATUSPAGE_RESET = 'DELETE_STATUSPAGE_RESET';

// Logo
export const FAVICON_CACHE_INSERT = 'incident/FAVICON_CACHE_INSERT';
export const LOGO_CACHE_INSERT = 'incident/LOGO_CACHE_INSERT';
export const FAVICON_CACHE_RESET = 'incident/FAVICON_CACHE_RESET';
export const LOGO_CACHE_RESET = 'incident/LOGO_CACHE_RESET';

// Implements pagination for Status pages table

export const PAGINATE_NEXT = 'PAGINATE_NEXT';
export const PAGINATE_PREV = 'PAGINATE_PREV';
export const PAGINATE_RESET = 'PAGINATE_RESET';
