// create status page category
export const CREATE_STATUS_PAGE_CATEGORY_REQUEST: $TSFixMe =
    'CREATE_STATUS_PAGE_CATEGORY_REQUEST';
export const CREATE_STATUS_PAGE_CATEGORY_SUCCESS: $TSFixMe =
    'CREATE_STATUS_PAGE_CATEGORY_SUCCESS';
export const CREATE_STATUS_PAGE_CATEGORY_FAILURE: $TSFixMe =
    'CREATE_STATUS_PAGE_CATEGORY_FAILURE';

// update status page category
export const UPDATE_STATUS_PAGE_CATEGORY_REQUEST: $TSFixMe =
    'UPDATE_STATUS_PAGE_CATEGORY_REQUEST';
export const UPDATE_STATUS_PAGE_CATEGORY_SUCCESS: $TSFixMe =
    'UPDATE_STATUS_PAGE_CATEGORY_SUCCESS';
export const UPDATE_STATUS_PAGE_CATEGORY_FAILURE: $TSFixMe =
    'UPDATE_STATUS_PAGE_CATEGORY_FAILURE';

// fetch status page categories
export const FETCH_STATUS_PAGE_CATEGORIES_REQUEST: $TSFixMe =
    'FETCH_STATUS_PAGE_CATEGORIES_REQUEST';
export const FETCH_STATUS_PAGE_CATEGORIES_SUCCESS: $TSFixMe =
    'FETCH_STATUS_PAGE_CATEGORIES_SUCCESS';
export const FETCH_STATUS_PAGE_CATEGORIES_FAILURE: $TSFixMe =
    'FETCH_STATUS_PAGE_CATEGORIES_FAILURE';

// fetch all status page categories without limit
export const FETCH_ALL_STATUS_PAGE_CATEGORIES_REQUEST: $TSFixMe =
    'FETCH_ALL_STATUS_PAGE_CATEGORIES_REQUEST';
export const FETCH_ALL_STATUS_PAGE_CATEGORIES_SUCCESS: $TSFixMe =
    'FETCH_ALL_STATUS_PAGE_CATEGORIES_SUCCESS';
export const FETCH_ALL_STATUS_PAGE_CATEGORIES_FAILURE: $TSFixMe =
    'FETCH_ALL_STATUS_PAGE_CATEGORIES_FAILURE';

// delete status page category
export const DELETE_STATUS_PAGE_CATEGORY_REQUEST: $TSFixMe =
    'DELETE_STATUS_PAGE_CATEGORY_REQUEST';
export const DELETE_STATUS_PAGE_CATEGORY_SUCCESS: $TSFixMe =
    'DELETE_STATUS_PAGE_CATEGORY_SUCCESS';
export const DELETE_STATUS_PAGE_CATEGORY_FAILURE: $TSFixMe =
    'DELETE_STATUS_PAGE_CATEGORY_FAILURE';
