export const SUBPROJECTS_SUCCESS: string = 'subProjects/SUBPROJECTS_SUCCESS';
export const SUBPROJECTS_FAILED: string = 'subProjects/SUBPROJECTS_FAILED';
export const SUBPROJECTS_REQUEST: string = 'subProjects/SUBPROJECTS_REQUEST';
export const SUBPROJECTS_RESET: string = 'subProjects/SUBPROJECTS_RESET';

export const CREATE_SUBPROJECT_SUCCESS: $TSFixMe =
    'subProjects/CREATE_SUBPROJECT_SUCCESS';
export const CREATE_SUBPROJECT_FAILED: string =
    'subProjects/CREATE_SUBPROJECT_FAILED';
export const CREATE_SUBPROJECT_REQUEST: $TSFixMe =
    'subProjects/CREATE_SUBPROJECT_REQUEST';
export const CREATE_SUBPROJECT_RESET: string =
    'subProjects/CREATE_SUBPROJECT_RESET';
export const CREATE_NEW_SUBPROJECT_RESET: $TSFixMe =
    'subProjects/CREATE_NEW_SUBPROJECT_RESET';

export const SWITCH_SUBPROJECT: string = 'subProjects/SWITCH_SUBPROJECT';
export const SWITCH_SUBPROJECT_RESET: string =
    'subProjects/SWITCH_SUBPROJECT_RESET';

export const RESET_SUBPROJECT_TOKEN_REQUEST: $TSFixMe =
    'subProjects/RESET_SUBPROJECT_TOKEN_REQUEST';
export const RESET_SUBPROJECT_TOKEN_SUCCESS: $TSFixMe =
    'subProjects/RESET_SUBPROJECT_TOKEN_SUCCESS';
export const RESET_SUBPROJECT_TOKEN_FAILED: $TSFixMe =
    'subProjects/RESET_SUBPROJECT_TOKEN_FAILED';
export const RESET_SUBPROJECT_TOKEN_RESET: $TSFixMe =
    'subProjects/RESET_SUBPROJECT_TOKEN_RESET';

export const RENAME_SUBPROJECT_REQUEST: $TSFixMe =
    'subProjects/RENAME_SUBPROJECT_REQUEST';
export const RENAME_SUBPROJECT_SUCCESS: $TSFixMe =
    'subProjects/RENAME_SUBPROJECT_SUCCESS';
export const RENAME_SUBPROJECT_FAILED: string =
    'subProjects/RENAME_SUBPROJECT_FAILED';
export const RENAME_SUBPROJECT_RESET: string =
    'subProjects/RENAME_SUBPROJECT_RESET';

export const DELETE_SUBPROJECT_REQUEST: $TSFixMe =
    'subProjects/DELETE_SUBPROJECT_REQUEST';
export const DELETE_SUBPROJECT_SUCCESS: $TSFixMe =
    'subProjects/DELETE_SUBPROJECT_SUCCESS';
export const DELETE_SUBPROJECT_FAILED: string =
    'subProjects/DELETE_SUBPROJECT_FAILED';
export const DELETE_SUBPROJECT_RESET: string =
    'subProjects/DELETE_SUBPROJECT_RESET';

export const EXIT_SUBPROJECT_REQUEST: string = 'EXIT_SUBPROJECT_REQUEST';
export const EXIT_SUBPROJECT_SUCCESS: string = 'EXIT_SUBPROJECT_SUCCESS';
export const EXIT_SUBPROJECT_FAILED: string = 'EXIT_SUBPROJECT_FAILED';

export const CHANGE_SUBPROJECT_ROLES: string =
    'subProjects/CHANGE_SUBPROJECT_ROLES';

export const MARK_SUBPROJECT_DELETE_REQUEST: $TSFixMe =
    'subProjects/MARK_SUBPROJECT_DELETE_REQUEST';
export const MARK_SUBPROJECT_DELETE_SUCCESS: $TSFixMe =
    'subProjects/MARK_SUBPROJECT_DELETE_SUCCESS';
export const MARK_SUBPROJECT_DELETE_FAILED: $TSFixMe =
    'subProjects/MARK_SUBPROJECT_DELETE_FAILED';
export const MARK_SUBPROJECT_DELETE_RESET: $TSFixMe =
    'subProjects/MARK_SUBPROJECT_DELETE_RESET';

export const SET_ACTIVE_SUBPROJECT: string = 'SET_ACTIVE_SUBPROJECT';
