export const SUBPROJECTS_SUCCESS = 'subProjects/SUBPROJECTS_SUCCESS';
export const SUBPROJECTS_FAILED = 'subProjects/SUBPROJECTS_FAILED';
export const SUBPROJECTS_REQUEST = 'subProjects/SUBPROJECTS_REQUEST';
export const SUBPROJECTS_RESET = 'subProjects/SUBPROJECTS_RESET';

export const CREATE_SUBPROJECT_SUCCESS = 'subProjects/CREATE_SUBPROJECT_SUCCESS';
export const CREATE_SUBPROJECT_FAILED = 'subProjects/CREATE_SUBPROJECT_FAILED';
export const CREATE_SUBPROJECT_REQUEST = 'subProjects/CREATE_SUBPROJECT_REQUEST';
export const CREATE_SUBPROJECT_RESET = 'subProjects/CREATE_SUBPROJECT_RESET';

export const SWITCH_SUBPROJECT = 'subProjects/SWITCH_SUBPROJECT';
export const SWITCH_SUBPROJECT_RESET = 'subProjects/SWITCH_SUBPROJECT_RESET';

export const RESET_SUBPROJECT_TOKEN_REQUEST = 'subProjects/RESET_SUBPROJECT_TOKEN_REQUEST';
export const RESET_SUBPROJECT_TOKEN_SUCCESS = 'subProjects/RESET_SUBPROJECT_TOKEN_SUCCESS';
export const RESET_SUBPROJECT_TOKEN_FAILED = 'subProjects/RESET_SUBPROJECT_TOKEN_FAILED';
export const RESET_SUBPROJECT_TOKEN_RESET = 'subProjects/RESET_SUBPROJECT_TOKEN_RESET';

export const RENAME_SUBPROJECT_REQUEST = 'subProjects/RENAME_SUBPROJECT_REQUEST';
export const RENAME_SUBPROJECT_SUCCESS = 'subProjects/RENAME_SUBPROJECT_SUCCESS';
export const RENAME_SUBPROJECT_FAILED = 'subProjects/RENAME_SUBPROJECT_FAILED';
export const RENAME_SUBPROJECT_RESET = 'subProjects/RENAME_SUBPROJECT_RESET';

export const DELETE_SUBPROJECT_REQUEST = 'subProjects/DELETE_SUBPROJECT_REQUEST';
export const DELETE_SUBPROJECT_SUCCESS = 'subProjects/DELETE_SUBPROJECT_SUCCESS';
export const DELETE_SUBPROJECT_FAILED = 'subProjects/DELETE_SUBPROJECT_FAILED';
export const DELETE_SUBPROJECT_RESET = 'subProjects/DELETE_SUBPROJECT_RESET';

export const EXIT_SUBPROJECT_REQUEST = 'EXIT_SUBPROJECT_REQUEST';
export const EXIT_SUBPROJECT_SUCCESS = 'EXIT_SUBPROJECT_SUCCESS';
export const EXIT_SUBPROJECT_FAILED = 'EXIT_SUBPROJECT_FAILED';

export const CHANGE_SUBPROJECT_ROLES = 'subProjects/CHANGE_SUBPROJECT_ROLES';


export const MARK_SUBPROJECT_DELETE_REQUEST = 'subProjects/MARK_SUBPROJECT_DELETE_REQUEST';
export const MARK_SUBPROJECT_DELETE_SUCCESS = 'subProjects/MARK_SUBPROJECT_DELETE_SUCCESS';
export const MARK_SUBPROJECT_DELETE_FAILED = 'subProjects/MARK_SUBPROJECT_DELETE_FAILED';
export const MARK_SUBPROJECT_DELETE_RESET = 'subProjects/MARK_SUBPROJECT_DELETE_RESET';