export const TEAM_LOADING_REQUEST: string = 'TEAM_LOADING_REQUEST';
export const TEAM_LOADING_SUCCESS: string = 'TEAM_LOADING_SUCCESS';
export const TEAM_LOADING_FAILURE: string = 'TEAM_LOADING_FAILURE';
export const TEAM_MEMBER_REQUEST: string = 'TEAM_MEMBER_REQUEST';
export const TEAM_MEMBER_SUCCESS: string = 'TEAM_MEMBER_SUCCESS';
export const TEAM_MEMBER_FAILURE: string = 'TEAM_MEMBER_FAILURE';
export const TEAM_SUBPROJECT_LOADING_REQUEST =
    'TEAM_SUBPROJECT_LOADING_REQUEST';
export const TEAM_SUBPROJECT_LOADING_SUCCESS =
    'TEAM_SUBPROJECT_LOADING_SUCCESS';
export const TEAM_SUBPROJECT_LOADING_FAILURE =
    'TEAM_SUBPROJECT_LOADING_FAILURE';
export const TEAM_CREATE_REQUEST: string = 'TEAM_CREATE_REQUEST';
export const TEAM_CREATE_SUCCESS: string = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAILURE: string = 'TEAM_CREATE_FAILURE';
export const TEAM_DELETE_REQUEST: string = 'TEAM_DELETE_REQUEST';
export const TEAM_DELETE_SUCCESS: string = 'TEAM_DELETE_SUCCESS';
export const TEAM_DELETE_FAILURE: string = 'TEAM_DELETE_FAILURE';
export const TEAM_DELETE_RESET: string = 'TEAM_DELETE_RESET';
export const TEAM_UPDATE_ROLE_REQUEST: string = 'TEAM_UPDATE_ROLE_REQUEST';
export const TEAM_UPDATE_ROLE_SUCCESS: string = 'TEAM_UPDATE_ROLE_SUCCESS';
export const TEAM_UPDATE_ROLE_FAILURE: string = 'TEAM_UPDATE_ROLE_FAILURE';
export const PAGINATE_NEXT: string = 'PAGINATE_NEXT';
export const PAGINATE_PREV: string = 'PAGINATE_PREV';
export const PAGINATE_RESET: string = 'PAGINATE_RESET';
