// Tutorial status list
export const FETCH_TUTORIAL_REQUEST: string = 'FETCH_TUTORIAL_REQUEST';
export const FETCH_TUTORIAL_SUCCESS: string = 'FETCH_TUTORIAL_SUCCESS';
export const FETCH_TUTORIAL_FAILURE: string = 'FETCH_TUTORIAL_FAILURE';
export const FETCH_TUTORIAL_RESET: string = 'FETCH_TUTORIAL_RESET';

// Close tutorial status list
export const CLOSE_TUTORIAL_REQUEST: string = 'CLOSE_TUTORIAL_REQUEST';
export const CLOSE_TUTORIAL_SUCCESS: string = 'CLOSE_TUTORIAL_SUCCESS';
export const CLOSE_TUTORIAL_FAILURE: string = 'CLOSE_TUTORIAL_FAILURE';
export const CLOSE_TUTORIAL_RESET: string = 'CLOSE_TUTORIAL_RESET';
