// Tutorial status list
export const FETCH_TUTORIAL_REQUEST = 'FETCH_TUTORIAL_REQUEST';
export const FETCH_TUTORIAL_SUCCESS = 'FETCH_TUTORIAL_SUCCESS';
export const FETCH_TUTORIAL_FAILURE = 'FETCH_TUTORIAL_FAILURE';
export const FETCH_TUTORIAL_RESET = 'FETCH_TUTORIAL_RESET';

// Close tutorial status list
export const CLOSE_TUTORIAL_REQUEST = 'CLOSE_TUTORIAL_REQUEST';
export const CLOSE_TUTORIAL_SUCCESS = 'CLOSE_TUTORIAL_SUCCESS';
export const CLOSE_TUTORIAL_FAILURE = 'CLOSE_TUTORIAL_FAILURE';
export const CLOSE_TUTORIAL_RESET = 'CLOSE_TUTORIAL_RESET';