export const GET_VERSION_SUCCESS: string = 'GET_VERSION_SUCCESS';
export const GET_VERSION_FAILED: string = 'GET_VERSION_FAILED';
export const GET_VERSION_REQUEST: string = 'GET_VERSION_REQUEST';
export const GET_VERSION_RESET: string = 'GET_VERSION_RESET';
