export const GET_VERSION_SUCCESS = 'GET_VERSION_SUCCESS';
export const GET_VERSION_FAILED = 'GET_VERSION_FAILED';
export const GET_VERSION_REQUEST = 'GET_VERSION_REQUEST';
export const GET_VERSION_RESET = 'GET_VERSION_RESET';