// Fetch All Audit Log List
export const FETCH_AUDITLOGS_REQUEST: string = 'FETCH_AUDITLOGS_REQUEST';
export const FETCH_AUDITLOGS_SUCCESS: string = 'FETCH_AUDITLOGS_SUCCESS';
export const FETCH_AUDITLOGS_FAILURE: string = 'FETCH_AUDITLOGS_FAILURE';

// Search Audit Logs
export const SEARCH_AUDITLOGS_REQUEST: string = 'SEARCH_AUDITLOGS_REQUEST';
export const SEARCH_AUDITLOGS_SUCCESS: string = 'SEARCH_AUDITLOGS_SUCCESS';
export const SEARCH_AUDITLOGS_FAILURE: string = 'SEARCH_AUDITLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_AUDITLOGS_REQUEST: string =
    'DELETE_ALL_AUDITLOGS_REQUEST';
export const DELETE_ALL_AUDITLOGS_SUCCESS: string =
    'DELETE_ALL_AUDITLOGS_SUCCESS';
export const DELETE_ALL_AUDITLOGS_FAILURE: string =
    'DELETE_ALL_AUDITLOGS_FAILURE';

// Fetch audit log status
export const FETCH_AUDITLOG_STATUS_SUCCESS: string =
    'FETCH_AUDITLOG_STATUS_SUCCESS';
export const FETCH_AUDITLOG_STATUS_FAILED: string =
    'FETCH_AUDITLOG_STATUS_FAILED';
export const FETCH_AUDITLOG_STATUS_REQUEST: string =
    'FETCH_AUDITLOG_STATUS_REQUEST';
export const FETCH_AUDITLOG_STATUS_RESET: string =
    'FETCH_AUDITLOG_STATUS_RESET';

// Change audit log status
export const CHANGE_AUDITLOG_STATUS_SUCCESS: string =
    'CHANGE_AUDITLOG_STATUS_SUCCESS';
export const CHANGE_AUDITLOG_STATUS_FAILED: string =
    'CHANGE_AUDITLOG_STATUS_FAILED';
export const CHANGE_AUDITLOG_STATUS_REQUEST: string =
    'CHANGE_AUDITLOG_STATUS_REQUEST';
export const CHANGE_AUDITLOG_STATUS_RESET: string =
    'CHANGE_AUDITLOG_STATUS_RESET';
