// Fetch All Call Log List
export const FETCH_CALLLOGS_REQUEST: string = 'FETCH_CALLLOGS_REQUEST';
export const FETCH_CALLLOGS_SUCCESS: string = 'FETCH_CALLLOGS_SUCCESS';
export const FETCH_CALLLOGS_FAILURE: string = 'FETCH_CALLLOGS_FAILURE';

// Search Call Logs
export const SEARCH_CALLLOGS_REQUEST: string = 'SEARCH_CALLLOGS_REQUEST';
export const SEARCH_CALLLOGS_SUCCESS: string = 'SEARCH_CALLLOGS_SUCCESS';
export const SEARCH_CALLLOGS_FAILURE: string = 'SEARCH_CALLLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_CALLLOGS_REQUEST: string =
    'DELETE_ALL_CALLLOGS_REQUEST';
export const DELETE_ALL_CALLLOGS_SUCCESS: string =
    'DELETE_ALL_CALLLOGS_SUCCESS';
export const DELETE_ALL_CALLLOGS_FAILURE: string =
    'DELETE_ALL_CALLLOGS_FAILURE';

// Fetch call log status
export const FETCH_CALLLOG_STATUS_SUCCESS: string =
    'FETCH_CALLLOG_STATUS_SUCCESS';
export const FETCH_CALLLOG_STATUS_FAILED: string =
    'FETCH_CALLLOG_STATUS_FAILED';
export const FETCH_CALLLOG_STATUS_REQUEST: string =
    'FETCH_CALLLOG_STATUS_REQUEST';
export const FETCH_CALLLOG_STATUS_RESET: string = 'FETCH_CALLLOG_STATUS_RESET';

// change call log status
export const CHANGE_CALLLOG_STATUS_SUCCESS: string =
    'CHANGE_CALLLOG_STATUS_SUCCESS';
export const CHANGE_CALLLOG_STATUS_FAILED: string =
    'CHANGE_CALLLOG_STATUS_FAILED';
export const CHANGE_CALLLOG_STATUS_REQUEST: string =
    'CHANGE_CALLLOG_STATUS_REQUEST';
export const CHANGE_CALLLOG_STATUS_RESET: string =
    'CHANGE_CALLLOG_STATUS_RESET';
