// Fetch All Email Log List
export const FETCH_EMAILLOGS_REQUEST: string = 'FETCH_EMAILLOGS_REQUEST';
export const FETCH_EMAILLOGS_SUCCESS: string = 'FETCH_EMAILLOGS_SUCCESS';
export const FETCH_EMAILLOGS_FAILURE: string = 'FETCH_EMAILLOGS_FAILURE';

// Search Email Logs
export const SEARCH_EMAILLOGS_REQUEST: string = 'SEARCH_EMAILLOGS_REQUEST';
export const SEARCH_EMAILLOGS_SUCCESS: string = 'SEARCH_EMAILLOGS_SUCCESS';
export const SEARCH_EMAILLOGS_FAILURE: string = 'SEARCH_EMAILLOGS_FAILURE';

// Delete All Logs
export const DELETE_ALL_EMAILLOGS_REQUEST: string =
    'DELETE_ALL_EMAILLOGS_REQUEST';
export const DELETE_ALL_EMAILLOGS_SUCCESS: string =
    'DELETE_ALL_EMAILLOGS_SUCCESS';
export const DELETE_ALL_EMAILLOGS_FAILURE: string =
    'DELETE_ALL_EMAILLOGS_FAILURE';

// Fetch Email log status
export const FETCH_EMAILLOG_STATUS_SUCCESS: string =
    'FETCH_EMAILLOG_STATUS_SUCCESS';
export const FETCH_EMAILLOG_STATUS_FAILED: string =
    'FETCH_EMAILLOG_STATUS_FAILED';
export const FETCH_EMAILLOG_STATUS_REQUEST: string =
    'FETCH_EMAILLOG_STATUS_REQUEST';
export const FETCH_EMAILLOG_STATUS_RESET: string =
    'FETCH_EMAILLOG_STATUS_RESET';

// Change Email log status
export const CHANGE_EMAILLOG_STATUS_SUCCESS: string =
    'CHANGE_EMAILLOG_STATUS_SUCCESS';
export const CHANGE_EMAILLOG_STATUS_FAILED: string =
    'CHANGE_EMAILLOG_STATUS_FAILED';
export const CHANGE_EMAILLOG_STATUS_REQUEST: string =
    'CHANGE_EMAILLOG_STATUS_REQUEST';
export const CHANGE_EMAILLOG_STATUS_RESET: string =
    'CHANGE_EMAILLOG_STATUS_RESET';
