export const FETCH_LICENSE_SUCCESS: string = 'FETCH_LICENSE_SUCCESS';
export const FETCH_LICENSE_FAILED: string = 'FETCH_LICENSE_FAILED';
export const FETCH_LICENSE_REQUEST: string = 'FETCH_LICENSE_REQUEST';
export const FETCH_LICENSE_RESET: string = 'FETCH_LICENSE_RESET';

export const CONFIRM_LICENSE_SUCCESS: string = 'CONFIRM_LICENSE_SUCCESS';
export const CONFIRM_LICENSE_FAILED: string = 'CONFIRM_LICENSE_FAILED';
export const CONFIRM_LICENSE_REQUEST: string = 'CONFIRM_LICENSE_REQUEST';
export const CONFIRM_LICENSE_RESET: string = 'CONFIRM_LICENSE_RESET';
