export const REQUESTING_SETTINGS: string = 'REQUESTING_SETTINGS';
export const REQUESTING_SETTINGS_SUCCEEDED: string =
    'REQUESTING_SETTINGS_SUCCEEDED';
export const REQUESTING_SETTINGS_FAILED: string = 'REQUESTING_SETTINGS_FAILED';
export const TEST_SMTP_REQUEST: string = 'TEST_SMTP_REQUEST';
export const TEST_SMTP_SUCCESS: string = 'TEST_SMTP_SUCCESS';
export const TEST_SMTP_FAILURE: string = 'TEST_SMTP_FAILURE';
export const TEST_TWILIO_REQUEST: string = 'TEST_TWILIO_REQUEST';
export const TEST_TWILIO_SUCCESS: string = 'TEST_TWILIO_SUCCESS';
export const TEST_TWILIO_FAILURE: string = 'TEST_TWILIO_FAILURE';
