// Fetch All SMS Log List
export const  FETCH_SMSLOGS_REQUEST: string = 'FETCH_SMSLOGS_REQUEST';
export const  FETCH_SMSLOGS_SUCCESS: string = 'FETCH_SMSLOGS_SUCCESS';
export const  FETCH_SMSLOGS_FAILURE: string = 'FETCH_SMSLOGS_FAILURE';

// Search SMS Logs
export const  SEARCH_SMSLOGS_REQUEST: string = 'SEARCH_SMSLOGS_REQUEST';
export const  SEARCH_SMSLOGS_SUCCESS: string = 'SEARCH_SMSLOGS_SUCCESS';
export const  SEARCH_SMSLOGS_FAILURE: string = 'SEARCH_SMSLOGS_FAILURE';

// Delete All Logs
export const  DELETE_ALL_SMSLOGS_REQUEST: string = 'DELETE_ALL_SMSLOGS_REQUEST';
export const  DELETE_ALL_SMSLOGS_SUCCESS: string = 'DELETE_ALL_SMSLOGS_SUCCESS';
export const  DELETE_ALL_SMSLOGS_FAILURE: string = 'DELETE_ALL_SMSLOGS_FAILURE';

// Fetch sms log status
export const  FETCH_SMSLOG_STATUS_SUCCESS: string = 'FETCH_SMSLOG_STATUS_SUCCESS';
export const  FETCH_SMSLOG_STATUS_FAILED: string = 'FETCH_SMSLOG_STATUS_FAILED';
export const  FETCH_SMSLOG_STATUS_REQUEST: string = 'FETCH_SMSLOG_STATUS_REQUEST';
export const  FETCH_SMSLOG_STATUS_RESET: string = 'FETCH_SMSLOG_STATUS_RESET';

// change sms log status
export const  CHANGE_SMSLOG_STATUS_SUCCESS: string = 'CHANGE_SMSLOG_STATUS_SUCCESS';
export const  CHANGE_SMSLOG_STATUS_FAILED: string = 'CHANGE_SMSLOG_STATUS_FAILED';
export const  CHANGE_SMSLOG_STATUS_REQUEST: string = 'CHANGE_SMSLOG_STATUS_REQUEST';
export const  CHANGE_SMSLOG_STATUS_RESET: string = 'CHANGE_SMSLOG_STATUS_RESET';
