//Fetch All Sso default roles list
export const FETCH_SSO_DEFAULT_ROLES_REQUEST: $TSFixMe =
    'FETCH_SSO_DEFAULT_ROLES_REQUEST';
export const FETCH_SSO_DEFAULT_ROLES_SUCCESS: $TSFixMe =
    'FETCH_SSO_DEFAULT_ROLES_SUCCESS';
export const FETCH_SSO_DEFAULT_ROLES_FAILURE: $TSFixMe =
    'FETCH_SSO_DEFAULT_ROLES_FAILURE';

//Delete Sso default role
export const DELETE_SSO_DEFAULT_ROLE_REQUEST: $TSFixMe =
    'DELETE_SSO_DEFAULT_ROLE_REQUEST';
export const DELETE_SSO_DEFAULT_ROLE_SUCCESS: $TSFixMe =
    'DELETE_SSO_DEFAULT_ROLE_SUCCESS';
export const DELETE_SSO_DEFAULT_ROLE_FAILED: string =
    'DELETE_SSO_DEFAULT_ROLE_FAILED';

//Add Sso default role
export const ADD_SSO_DEFAULT_ROLE_REQUEST: string =
    'ADD_SSO_DEFAULT_ROLE_REQUEST';
export const ADD_SSO_DEFAULT_ROLE_SUCCESS: string =
    'ADD_SSO_DEFAULT_ROLE_SUCCESS';
export const ADD_SSO_DEFAULT_ROLE_FAILED: string =
    'ADD_SSO_DEFAULT_ROLE_FAILED';

//Fetch Sso default role
export const FETCH_SSO_DEFAULT_ROLE_REQUEST: string =
    'FETCH_SSO_DEFAULT_ROLE_REQUEST';
export const FETCH_SSO_DEFAULT_ROLE_SUCCESS: string =
    'FETCH_SSO_DEFAULT_ROLE_SUCCESS';
export const FETCH_SSO_DEFAULT_ROLE_FAILURE: string =
    'FETCH_SSO_DEFAULT_ROLE_FAILURE';

//Update Sso
export const UPDATE_SSO_DEFAULT_ROLE_REQUEST: $TSFixMe =
    'UPDATE_SSO_DEFAULT_ROLE_REQUEST';
export const UPDATE_SSO_DEFAULT_ROLE_SUCCESS: $TSFixMe =
    'UPDATE_SSO_DEFAULT_ROLE_SUCCESS';
export const UPDATE_SSO_DEFAULT_ROLE_FAILURE: $TSFixMe =
    'UPDATE_SSO_DEFAULT_ROLE_FAILURE';

export const NEXT_PAGE: string = 'NEXT_PAGE';
export const PREV_PAGE: string = 'PREV_PAGE';
