import { BASE_URL, IS_BILLING_ENABLED } from "../../Config";
import { APIResponse, Page, expect, test } from "@playwright/test";
import URL from "Common/Types/API/URL";

/*
 * The Home service serves a Markdown variant of its marketing pages: appending
 * `.md` to a known page path (e.g. /pricing.md, /compare/<x>.md, or any
 * PageSEOConfig page) returns the page's content as text/markdown for
 * LLMs/agents (Home/Routes.ts, generated by Home/Utils/AIDiscovery.ts). An
 * unknown page's `.md` variant is a deliberate 404 with a plain-text pointer to
 * /llms.txt.
 *
 * Unit tests already pin the generator output; this suite is the deployment
 * contract - it proves the `.md` route is actually mounted, returns the right
 * status and content type, carries the open CORS header crawlers need on the
 * 200 path, and does not silently serve an HTML error page. Like the other Home
 * specs it runs only where the marketing site is deployed (IS_BILLING_ENABLED).
 */

function endpointFor(path: string): string {
  return URL.fromString(BASE_URL.toString()).addRoute(path).toString();
}

test.describe("Home: Markdown page variants", () => {
  test("/pricing.md is served as markdown with an open CORS policy", async ({
    page,
  }: {
    page: Page;
  }) => {
    if (!IS_BILLING_ENABLED) {
      return; // Home marketing site is only deployed in the SaaS stack.
    }

    page.setDefaultNavigationTimeout(120000); // 2 minutes

    const response: APIResponse = await page.request.get(
      endpointFor("/pricing.md"),
    );

    expect(response.status()).toBe(200);

    const headers: { [key: string]: string } = response.headers();
    expect(headers["content-type"] || "").toContain("text/markdown");
    // Crawlers/agents fetch this cross-origin, so it must be world-readable.
    expect(headers["access-control-allow-origin"]).toBe("*");

    const body: string = await response.text();
    // The pricing markdown always leads with the Pricing heading and table.
    expect(body).toContain("## Pricing");
    expect(body).toContain(
      "| Plan | Price (monthly billing) | Price (yearly billing) |",
    );
    // It links back to the canonical HTML page.
    expect(body).toContain("/pricing");
    // Guard against the 404 fallback and any generation error leaking through.
    expect(body).not.toContain("No markdown variant");
    expect(body).not.toContain("Error generating");
  });

  test("an unknown page's .md variant is a 404 pointing at /llms.txt", async ({
    page,
  }: {
    page: Page;
  }) => {
    if (!IS_BILLING_ENABLED) {
      return;
    }

    page.setDefaultNavigationTimeout(120000);

    const response: APIResponse = await page.request.get(
      endpointFor("/this-page-does-not-exist-e2e.md"),
    );

    expect(response.status()).toBe(404);

    const headers: { [key: string]: string } = response.headers();
    expect(headers["content-type"] || "").toContain("text/plain");

    const body: string = await response.text();
    expect(body).toContain("No markdown variant for this page");
    expect(body).toContain("/llms.txt");
  });
});
