#
# OneUptime-fetch-resources Dockerfile
#

# Pull base image nodejs image.
FROM node:17-alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

WORKDIR /usr/src/app

# Install app dependencies
RUN cd /usr/src/app

# Copy package.json files
COPY ./package.json /usr/src/app/package.json
COPY ./package-lock.json /usr/src/app/package-lock.json


RUN npm ci

# Expose ports.
EXPOSE 3400

# Expose Debugging port.
EXPOSE 9229

#Run the app
CMD [ "npm", "run", "dev"]

