import CodeExampleGenerator, {
  ApiRequestParams,
  CodeExamples,
} from "../../../FeatureSet/APIReference/Utils/CodeExampleGenerator";
import { JSONObject } from "Common/Types/JSON";
import { describe, expect, test } from "@jest/globals";

/*
 * The snippets on every API reference page. A reader copies one and runs it,
 * so a snippet that is subtly wrong is worse than no snippet: it fails in
 * their terminal, against their key, and the mistake looks like theirs.
 *
 * Eleven languages plus the raw request preview are generated by eleven
 * near-identical methods, which is exactly the shape where one of them quietly
 * loses a piece. These tests therefore hold every language to the same four
 * things -- the URL, the method, the ApiKey header, and the body -- rather
 * than asserting one language's exact text, and then check the per-language
 * value conversions that are the only real logic here.
 */

const API_KEY_PLACEHOLDER: string = "YOUR_API_KEY";
const BASE_URL: string = "https://oneuptime.com";
const ENDPOINT: string = "/api/monitor/get-list";
const FULL_URL: string = `${BASE_URL}${ENDPOINT}`;

type LanguageKey = Exclude<keyof CodeExamples, "requestPreview">;

const LANGUAGES: Array<LanguageKey> = [
  "curl",
  "javascript",
  "typescript",
  "python",
  "go",
  "java",
  "csharp",
  "php",
  "ruby",
  "rust",
  "powershell",
];

const METHODS: Array<ApiRequestParams["method"]> = [
  "GET",
  "POST",
  "PUT",
  "DELETE",
];

function generate(params: Partial<ApiRequestParams> = {}): CodeExamples {
  return CodeExampleGenerator.generate({
    method: "POST",
    endpoint: ENDPOINT,
    ...params,
  });
}

function snippets(examples: CodeExamples): Array<[LanguageKey, string]> {
  return LANGUAGES.map((language: LanguageKey) => {
    return [language, examples[language]];
  });
}

describe("CodeExampleGenerator.generate", () => {
  test("returns a snippet for every language and the raw request preview", () => {
    const examples: CodeExamples = generate();

    for (const [language, code] of snippets(examples)) {
      expect(typeof code).toBe("string");
      expect(code.trim().length).toBeGreaterThan(0);
      // A generator that lost a language would return "" rather than throw.
      expect(code).not.toBe("undefined");
      expect(language).toBeTruthy();
    }

    expect(examples.requestPreview.headers).toContain(
      `ApiKey: ${API_KEY_PLACEHOLDER}`,
    );
    expect(examples.requestPreview.headers).toContain(
      "Content-Type: application/json",
    );
  });

  test("no two languages produce the same snippet", () => {
    const examples: CodeExamples = generate({ body: { limit: 10 } });
    const unique: Set<string> = new Set(
      snippets(examples).map(([, code]: [LanguageKey, string]) => {
        return code;
      }),
    );
    expect(unique.size).toBe(LANGUAGES.length);
  });
});

describe("every snippet carries the request it describes", () => {
  for (const method of METHODS) {
    test(`a ${method} snippet names the full URL and the ApiKey placeholder in every language`, () => {
      const examples: CodeExamples = generate({ method: method });

      for (const [language, code] of snippets(examples)) {
        expect(`${language}:${code}`).toContain(FULL_URL);
        expect(`${language}:${code}`).toContain(API_KEY_PLACEHOLDER);
        /*
         * The verb, in whichever case the language writes it: curl and Go
         * shout it, axios and reqwest lower-case it, and C# and Ruby title-case
         * it into a method or class name. Losing it is how a POST example
         * turns into a GET that reads nothing.
         */
        const namesTheMethod: boolean = code
          .toLowerCase()
          .includes(method.toLowerCase());
        expect(`${language} names ${method}: ${namesTheMethod}`).toBe(
          `${language} names ${method}: true`,
        );
      }
    });
  }

  test("the placeholder is the only credential in any snippet", () => {
    const examples: CodeExamples = generate({ body: { limit: 10 } });

    for (const [language, code] of snippets(examples)) {
      expect(`${language}:${code}`).toContain(API_KEY_PLACEHOLDER);
      // Nothing that looks like a real key was baked in.
      expect(code).not.toMatch(
        /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i,
      );
    }
  });

  test("the endpoint is used verbatim, however it is spelled", () => {
    for (const endpoint of [
      "/api/monitor",
      "/api/monitor/00000000-0000-4000-8000-000000000000/get-item",
      "/api/status-page-subscriber/get-list",
    ]) {
      const examples: CodeExamples = generate({ endpoint: endpoint });
      for (const [language, code] of snippets(examples)) {
        expect(`${language}:${code}`).toContain(`${BASE_URL}${endpoint}`);
      }
    }
  });
});

describe("a request body reaches every snippet", () => {
  const body: JSONObject = {
    query: { projectId: "abc" },
    limit: 10,
    isActive: true,
  };

  test("every language carries the body's keys", () => {
    const examples: CodeExamples = generate({ body: body });

    for (const [language, code] of snippets(examples)) {
      for (const key of ["query", "projectId", "limit", "isActive"]) {
        expect(`${language} carries ${key}:${code}`).toContain(key);
      }
    }
  });

  test("no language renders an object as [object Object]", () => {
    const examples: CodeExamples = generate({
      body: { nested: { deeper: { value: 1 } }, list: [{ a: 1 }, { b: 2 }] },
    });

    for (const [language, code] of snippets(examples)) {
      expect(`${language}:${code}`).not.toContain("[object Object]");
      expect(`${language}:${code}`).not.toContain("undefined");
    }
  });

  test("an empty body object is treated as no body at all", () => {
    const withEmpty: CodeExamples = generate({ body: {} });
    const withNone: CodeExamples = generate();

    for (const language of LANGUAGES) {
      expect(withEmpty[language]).toBe(withNone[language]);
    }
    expect(withEmpty.requestPreview.body).toBe("");
    expect(withNone.requestPreview.body).toBe("");
  });

  test("the request preview shows the body as pretty JSON", () => {
    const examples: CodeExamples = generate({ body: body });

    expect(examples.requestPreview.body).toBe(JSON.stringify(body, null, 2));
    // And it round-trips, so the preview is something a reader can paste.
    expect(JSON.parse(examples.requestPreview.body)).toEqual(body);
  });

  test("a bodyless request does not carry payload scaffolding", () => {
    const examples: CodeExamples = generate({ method: "GET" });

    expect(examples.python).toContain("requests.get(url, headers=headers)");
    expect(examples.python).not.toContain("payload");
    expect(examples.go).toContain("nil)");
    expect(examples.go).not.toContain("payload :=");
    expect(examples.javascript).not.toContain("data:");
    expect(examples.typescript).not.toContain("data:");
    expect(examples.php).not.toContain("CURLOPT_POSTFIELDS");
    expect(examples.ruby).not.toContain("request.body");
    expect(examples.rust).not.toContain("let body");
    expect(examples.powershell).not.toContain("-Body $body");
    expect(examples.java).toContain("BodyPublishers.noBody()");
  });
});

describe("per-language value conversion", () => {
  const body: JSONObject = {
    flag: true,
    off: false,
    missing: null,
    count: 7,
    text: "hello",
  };

  test("Python writes True, False and None", () => {
    const python: string = generate({ body: body }).python;
    expect(python).toContain('"flag": True');
    expect(python).toContain('"off": False');
    expect(python).toContain('"missing": None');
    expect(python).toContain('"count": 7');
    expect(python).toContain('"text": "hello"');
  });

  test("Go writes true, false and nil", () => {
    const go: string = generate({ body: body }).go;
    expect(go).toContain('"flag": true');
    expect(go).toContain('"off": false');
    expect(go).toContain('"missing": nil');
  });

  test("Ruby writes true, false and nil with hash rockets", () => {
    const ruby: string = generate({ body: body }).ruby;
    expect(ruby).toContain('"flag" => true');
    expect(ruby).toContain('"missing" => nil');
  });

  test("PowerShell writes $true, $false and $null", () => {
    const powershell: string = generate({ body: body }).powershell;
    expect(powershell).toContain("flag = $true");
    expect(powershell).toContain("off = $false");
    expect(powershell).toContain("missing = $null");
  });

  test("PHP writes true, false and null inside an associative array", () => {
    const php: string = generate({ body: body }).php;
    expect(php).toContain('"flag" => true');
    expect(php).toContain('"missing" => null');
  });

  test("Rust wraps the body in json! and writes null", () => {
    const rust: string = generate({ body: body }).rust;
    expect(rust).toContain("json!({");
    expect(rust).toContain('"missing": null');
  });

  test("an empty array keeps each language's own empty-collection spelling", () => {
    const examples: CodeExamples = generate({ body: { ids: [] } });
    expect(examples.python).toContain('"ids": []');
    expect(examples.go).toContain('"ids": []interface{}{}');
    expect(examples.ruby).toContain('"ids" => []');
    expect(examples.php).toContain('"ids" => []');
    expect(examples.powershell).toContain("ids = @()");
    expect(examples.rust).toContain('"ids": [');
  });

  test("a body string with a quote is escaped for Java and C#", () => {
    const examples: CodeExamples = generate({
      body: { name: 'the "primary" monitor' },
    });
    // Java builds a Java string literal, so every quote is backslashed.
    expect(examples.java).toContain('\\"name\\"');
    // C# uses a verbatim string, where a quote is doubled.
    expect(examples.csharp).toContain('""name""');
  });
});

describe("HTTP verbs are spelled the way each language expects", () => {
  test("Ruby names the Net::HTTP class for the verb", () => {
    for (const [method, rubyClass] of [
      ["GET", "Get"],
      ["POST", "Post"],
      ["PUT", "Put"],
      ["DELETE", "Delete"],
    ] as Array<[ApiRequestParams["method"], string]>) {
      expect(generate({ method: method }).ruby).toContain(
        `Net::HTTP::${rubyClass}.new`,
      );
    }
  });

  test("C# calls the HttpClient method for the verb", () => {
    for (const [method, csharpMethod] of [
      ["GET", "Get"],
      ["POST", "Post"],
      ["PUT", "Put"],
      ["DELETE", "Delete"],
    ] as Array<[ApiRequestParams["method"], string]>) {
      expect(generate({ method: method }).csharp).toContain(
        `client.${csharpMethod}Async(`,
      );
    }
  });

  test("C# only passes content on the verbs that carry a body", () => {
    const body: JSONObject = { limit: 10 };
    expect(generate({ method: "POST", body: body }).csharp).toContain(
      ", content)",
    );
    expect(generate({ method: "PUT", body: body }).csharp).toContain(
      ", content)",
    );
    // GET and DELETE take no content overload on HttpClient.
    expect(generate({ method: "GET", body: body }).csharp).not.toContain(
      ", content)",
    );
    expect(generate({ method: "DELETE", body: body }).csharp).not.toContain(
      ", content)",
    );
  });

  test("curl passes the verb to -X and the body to -d", () => {
    const curl: string = generate({
      method: "PUT",
      body: { limit: 10 },
    }).curl;
    expect(curl).toContain(`curl -X PUT "${FULL_URL}"`);
    expect(curl).toContain(`-H "ApiKey: ${API_KEY_PLACEHOLDER}"`);
    expect(curl).toContain("-d '");
    expect(generate({ method: "GET" }).curl).not.toContain("-d '");
  });
});
