enum ColorSwatch {
  Zinc = "zinc",
  Neutra = "neutra",
  Stone = "stone",
  Slate = "slate",
  Purple = "purple",
  Pink = "pink",
  Red = "red",
  Orange = "orange",
  Yellow = "yellow",
  Green = "green",
  Teal = "teal",
  Cyan = "cyan",
  Gray = "gray",
  Moroon = "moroon",
  Blue = "blue",
  Indigo = "indigo",
  Amber = "amber",
  Lime = "lime",
  Emerald = "emerald",
  Sky = "sky",
  Violet = "violet",
  Fuchsia = "fuchsia",
  Rose = "rose",
}

export default ColorSwatch;
