#
# OneUptime-ProbeAPI Dockerfile
#

# Pull base image nodejs image.
FROM node:alpine

# Install bash. 
RUN apk update && apk add bash && apk add curl

#Use bash shell by default
SHELL ["/bin/bash", "-c"]

RUN mkdir /usr/src

# Install common
RUN mkdir /usr/src/Common
WORKDIR /usr/src/Common
COPY ./Common/package*.json /usr/src/Common/
RUN npm install
COPY ./Common /usr/src/Common
RUN npm run compile

# Install CommonServer
RUN mkdir /usr/src/CommonServer
WORKDIR /usr/src/CommonServer
COPY ./CommonServer/package*.json /usr/src/CommonServer/
RUN npm install
COPY ./CommonServer /usr/src/CommonServer
RUN npm run compile

WORKDIR /usr/src/app

# Install app dependencies
RUN cd /usr/src/app

# Copy package.json files
COPY ./ProbeAPI/package.json /usr/src/app/package.json
COPY ./ProbeAPI/package-lock.json /usr/src/app/package-lock.json


RUN npm install

# Expose ports.
EXPOSE 3400

# Expose Debugging port.
EXPOSE 9229

#Run the app
RUN npm run compile
CMD [ "npm", "run", "dev"]

