#!/usr/bin/env node
/*
 * an analog of `cat` using read-input.
 *
 *     ./cat < file.txt
 *     echo "hello" | ./cat
 *     ./cat file.txt file2.txt
 */

var read = require('../index');
var args = process.argv.slice(2);

read(args).then(function (res) {
  if (res.error) throw error;
  process.stdout.write(res.data);
}).catch(function (err) {
  throw err;
});
