import { BASE_URL, IS_BILLING_ENABLED } from "../../Config";
import { APIResponse, Page, expect, test } from "@playwright/test";
import URL from "Common/Types/API/URL";

/*
 * The Home service exposes machine-readable "AI discovery" surfaces so that
 * LLMs / agents can find OneUptime: /llms.txt, /llms-full.txt and the MCP
 * well-known manifest (Home/Routes.ts, generated by Home/Utils/AIDiscovery.ts).
 *
 * Unit tests already pin the generator output; this suite is the deployment
 * contract - it proves the routes are actually mounted, return 200, carry the
 * right content types and CORS header (they are meant to be fetched
 * cross-origin by crawlers/agents), and are not accidentally serving an HTML
 * error page. These run only where the Home marketing site is deployed, which
 * the suite gates on IS_BILLING_ENABLED like the other Home specs.
 */

function endpointFor(path: string): string {
  return URL.fromString(BASE_URL.toString()).addRoute(path).toString();
}

test.describe("Home: AI discovery surfaces", () => {
  test("/llms.txt is served as plain text with an open CORS policy", async ({
    page,
  }: {
    page: Page;
  }) => {
    if (!IS_BILLING_ENABLED) {
      return; // Home marketing site is only deployed in the SaaS stack.
    }

    page.setDefaultNavigationTimeout(120000); // 2 minutes

    const response: APIResponse = await page.request.get(
      endpointFor("/llms.txt"),
    );

    expect(response.status()).toBe(200);

    const headers: { [key: string]: string } = response.headers();
    expect(headers["content-type"] || "").toContain("text/plain");
    // Crawlers/agents fetch this cross-origin, so it must be world-readable.
    expect(headers["access-control-allow-origin"]).toBe("*");

    const body: string = await response.text();
    // The document always leads with the OneUptime heading and summary blurb.
    expect(body).toContain("# OneUptime");
    expect(body).toContain("## Products");
    expect(body).toContain("## Pricing");
    // Guard against the 500 fallback ("Error generating llms.txt").
    expect(body).not.toContain("Error generating");
  });

  test("/llms-full.txt is served as plain text and is a superset of llms.txt", async ({
    page,
  }: {
    page: Page;
  }) => {
    if (!IS_BILLING_ENABLED) {
      return;
    }

    page.setDefaultNavigationTimeout(120000);

    const response: APIResponse = await page.request.get(
      endpointFor("/llms-full.txt"),
    );

    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"] || "").toContain("text/plain");

    const body: string = await response.text();
    expect(body).toContain("# OneUptime");
    expect(body).not.toContain("Error generating");

    // The full variant should carry at least as much content as the short one.
    const shortResponse: APIResponse = await page.request.get(
      endpointFor("/llms.txt"),
    );
    const shortBody: string = await shortResponse.text();
    expect(body.length).toBeGreaterThanOrEqual(shortBody.length);
  });

  test("/.well-known/mcp.json is a valid JSON manifest describing the MCP server", async ({
    page,
  }: {
    page: Page;
  }) => {
    if (!IS_BILLING_ENABLED) {
      return;
    }

    page.setDefaultNavigationTimeout(120000);

    const response: APIResponse = await page.request.get(
      endpointFor("/.well-known/mcp.json"),
    );

    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"] || "").toContain(
      "application/json",
    );
    expect(response.headers()["access-control-allow-origin"]).toBe("*");

    const manifest: {
      name?: string;
      endpoint?: string;
      transport?: Array<string>;
      capabilities?: { tools?: boolean };
    } = await response.json();

    expect(manifest.name).toBe("OneUptime MCP Server");
    // The endpoint must be an absolute URL ending in /mcp.
    expect(manifest.endpoint || "").toMatch(/^https?:\/\/.+\/mcp$/);
    expect(Array.isArray(manifest.transport)).toBe(true);
    expect(manifest.transport).toContain("streamable-http");
    expect(manifest.capabilities?.tools).toBe(true);
  });
});
