export const CREATE_INCOMING_REQUEST_REQUEST =
    'CREATE_INCOMING_REQUEST_REQUEST';
export const CREATE_INCOMING_REQUEST_SUCCESS =
    'CREATE_INCOMING_REQUEST_SUCCESS';
export const CREATE_INCOMING_REQUEST_FAILURE =
    'CREATE_INCOMING_REQUEST_FAILURE';

export const EDIT_INCOMING_REQUEST_REQUEST = 'EDIT_INCOMING_REQUEST_REQUEST';
export const EDIT_INCOMING_REQUEST_SUCCESS = 'EDIT_INCOMING_REQUEST_SUCCESS';
export const EDIT_INCOMING_REQUEST_FAILURE = 'EDIT_INCOMING_REQUEST_FAILURE';

export const DELETE_INCOMING_REQUEST_REQUEST =
    'DELETE_INCOMING_REQUEST_REQUEST';
export const DELETE_INCOMING_REQUEST_SUCCESS =
    'DELETE_INCOMING_REQUEST_SUCCESS';
export const DELETE_INCOMING_REQUEST_FAILURE =
    'DELETE_INCOMING_REQUEST_FAILURE';

export const FETCH_ALL_INCOMING_REQUEST_REQUEST =
    'FETCH_ALL_INCOMING_REQUEST_REQUEST';
export const FETCH_ALL_INCOMING_REQUEST_SUCCESS =
    'FETCH_ALL_INCOMING_REQUEST_SUCCESS';
export const FETCH_ALL_INCOMING_REQUEST_FAILURE =
    'FETCH_ALL_INCOMING_REQUEST_FAILURE';

export const SET_ACTIVE_INCOMING_REQUEST = 'SET_ACTIVE_INCOMING_REQUEST';
