import { MigrationInterface, QueryRunner } from "typeorm";

/*
 * Restores the expression index that serves the telemetry ingest path's
 * `service.name` lookup, and that an autogenerated migration deleted.
 *
 * WHAT BROKE
 *
 * `OTelIngestService.findOrCreateTelemetryService` resolves an OTLP resource's
 * `service.name` to a Service row through `QueryHelper.findWithSameText`, which
 * emits a case-insensitive predicate:
 *
 *   WHERE "projectId" = $1 AND LOWER("name") = $2 AND "deletedAt" IS NULL
 *   ORDER BY "createdAt" ASC LIMIT 1
 *
 * Every live index on Service is over the RAW `name` column. Postgres cannot
 * invert `lower()` (it is not order-preserving under any non-C collation) and
 * PG16 has no index-condition pushdown, so `LOWER("name") = $2` degrades to a
 * post-heap-fetch Filter. Only the `projectId` prefix acts as an index qual,
 * which makes each lookup cost O(services in that project) heap fetches plus
 * that many collation-aware lower() calls — not O(log n).
 *
 * That query runs once per OTLP *resource* (hundreds per batch for the shipped
 * host-metrics collector config), again per signal type, from every ingest pod.
 * Production sat at 100% CPU against a 100% buffer cache hit ratio and ~110 B/s
 * of reads: entirely in memory, entirely CPU.
 *
 * WHY IT BROKE
 *
 * The correct index existed. Migration 1774559064921 created:
 *
 *   CREATE UNIQUE INDEX "IDX_SERVICE_PROJECT_NAME_UNIQUE"
 *     ON "Service" ("projectId", LOWER("name")) WHERE "deletedAt" IS NULL
 *
 * Migration 1775735059360 — otherwise two unrelated column-default changes —
 * dropped it. TypeORM's schema builder matches database indexes to entity
 * metadata BY NAME and drops any it cannot find, and a hand-named expression
 * index created only in a migration is invisible to entity metadata. Its down()
 * "restores" the index as ("projectId") alone, silently losing the expression,
 * which is the signature of a machine-generated statement rather than a
 * deliberate one.
 *
 * The Service entity now declares this index with `synchronize: false`, which
 * makes the schema builder skip it in both directions. Without that decorator
 * this migration would be undone again by the next autogenerated one.
 *
 * WHY THIS IS HAND-WRITTEN
 *
 * AGENTS.md requires migrations to come from `npm run generate-postgres-migration`.
 * That cannot produce this one: `@Index()` has no way to express `LOWER(...)`,
 * so TypeORM can neither generate nor round-trip an expression index. The
 * generator is authoritative for column and table drift; expression indexes are
 * outside what it can model.
 *
 * NOT UNIQUE, DELIBERATELY
 *
 * The dropped original was UNIQUE. Recreating it that way would make this
 * migration fail on any project that already holds two services whose names
 * differ only by case — which the surviving raw-name unique index permits, so
 * such rows can legitimately exist today. Failing a deploy to enforce an
 * invariant nobody is currently relying on is the wrong trade: this index
 * exists to make the lookup fast. `ORDER BY "createdAt" ASC LIMIT 1` in the
 * query already resolves duplicates deterministically (oldest wins), and the
 * raw-name unique index still blocks exact-duplicate races. Restoring
 * case-insensitive uniqueness would need a dedupe pass first, as migration
 * 1778100000000 did, and belongs in its own change.
 *
 * `createdAt` is the third key column so the ORDER BY is satisfied by the index
 * itself and the plan carries no Sort node even when duplicates exist.
 *
 * NOT CONCURRENT, DELIBERATELY
 *
 * DataSourceOptions sets no `migrationsTransactionMode`, so TypeORM defaults to
 * "all" and runs every migration inside ONE transaction. `CREATE INDEX
 * CONCURRENTLY` cannot run inside a transaction block and would abort the whole
 * run. A plain CREATE INDEX takes a SHARE lock that blocks writes to Service
 * for the duration, which is milliseconds at this table's size (thousands of
 * live rows).
 *
 * IF NOT EXISTS makes this a no-op when an operator has already created the
 * index by hand — the recommended incident mitigation is to build it
 * CONCURRENTLY on the live database under this exact name, ahead of the deploy.
 */
export class RestoreServiceLowerNameIndex1786100000000
  implements MigrationInterface
{
  public name: string = "RestoreServiceLowerNameIndex1786100000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_SERVICE_PROJECT_LOWER_NAME" ON "Service" ("projectId", LOWER("name"), "createdAt") WHERE "deletedAt" IS NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."IDX_SERVICE_PROJECT_LOWER_NAME"`,
    );
  }
}
