import { MigrationInterface, QueryRunner } from "typeorm";

/*
 * Restores nine UNIQUE indexes that autogenerated migrations deleted, and that
 * no migration ever put back.
 *
 * HOW THEY WENT MISSING
 *
 * TypeORM's schema builder matches database indexes to entity metadata BY NAME
 * (RdbmsSchemaBuilder.dropOldIndices) and drops every index it cannot find a
 * match for. A hand-named index created only in a migration is invisible to
 * entity metadata, so the next `migration:generate` emits a DROP for it, mixed
 * in with whatever change was actually intended.
 *
 * Found by auditing every hand-named index ever created in a migration up()
 * against a database with all 504 registered migrations applied. 308 such
 * indexes exist; 302 are absent from the migrated schema. Almost all of those
 * are benign — TypeORM re-created an equivalent plain index under its own
 * canonical IDX_<hash> name. The ten that were NOT benign carried a UNIQUE,
 * partial, or expression definition that TypeORM cannot express and therefore
 * never re-created. One of the ten (the Service LOWER(name) index) was restored
 * separately in migration 1786100000000. This handles the other nine.
 *
 * Each one is a lost integrity guarantee, not just a lost index:
 *
 *   slug uniqueness  CephCluster, DockerHost, IoTFleet, KubernetesCluster,
 *                    NetworkDevice, ProxmoxCluster — the slug is the public URL
 *                    identifier for the resource. These six tables currently
 *                    have NO index on slug at all, so slug lookups are also
 *                    sequential scans.
 *   SSO/OIDC binding GlobalOIDCProject, GlobalSSOProject — one mapping row per
 *                    (provider, project). Duplicates make a project's identity
 *                    binding ambiguous.
 *   interface ids    NetworkInterface — a device cannot have two live
 *                    interfaces at the same SNMP ifIndex. App-level
 *                    @UniqueColumnBy does a find-then-insert, which races under
 *                    concurrency exactly as it did for Service before migration
 *                    1778100000000 added a DB constraint.
 *
 * PARTIAL, WHERE THE ORIGINALS MOSTLY WERE NOT
 *
 * Only IDX_network_interface_device_ifindex was originally partial. The other
 * eight were unqualified UNIQUE indexes, and they are restored here as partial
 * on `deletedAt IS NULL`. This is a deliberate change, for three reasons:
 *
 *   1. It matches how the data is actually read. Every query the app issues
 *      carries `deletedAt IS NULL` (DatabaseService adds it to every read that
 *      is not explicitly withDeleted), so nothing loses index coverage.
 *   2. An unqualified unique index lets a soft-deleted row hold a slug
 *      hostage forever — delete a cluster and you can never create another one
 *      that slugifies the same way. That is a bug, and restoring it verbatim
 *      would restore the bug with it.
 *   3. It makes the repair below non-destructive: a duplicate can be taken out
 *      of the index by soft-deleting it rather than by hard-deleting a row.
 *
 * REPAIR BEFORE CREATE
 *
 * A UNIQUE index cannot be created over existing duplicates, and a migration
 * that can fail on real data is a migration that blocks a deploy. Each index is
 * therefore preceded by a repair step that is deterministic (oldest row always
 * wins: createdAt, then _id) and non-destructive:
 *
 *   - slugs are RENAMED, not deleted. The losing row keeps all its data and
 *     gets a discriminator appended. Slugs already end in a random 10-digit
 *     suffix (see Common/Utils/Slug.ts), so collisions should not exist at all;
 *     this is a guard, not an expected path.
 *   - duplicate mapping / interface rows are SOFT-deleted, which removes them
 *     from a partial index without destroying anything. Nothing is hard-deleted
 *     and no foreign key is touched, so no cascade can fire.
 *
 * Every statement is idempotent: the repairs are no-ops when there are no
 * duplicates, and each CREATE uses IF NOT EXISTS so an index built by hand
 * ahead of the deploy does not fail the migration.
 *
 * NOT CONCURRENT
 *
 * DataSourceOptions sets no `migrationsTransactionMode`, so TypeORM defaults to
 * "all" and runs every migration inside one transaction. CREATE INDEX
 * CONCURRENTLY cannot run inside a transaction block and would abort the run.
 * These tables are small (infrastructure inventory, not telemetry), so the
 * brief SHARE lock is not a concern.
 *
 * HAND-WRITTEN
 *
 * AGENTS.md requires migrations to come from generate-postgres-migration. It
 * cannot produce this one: @Index() can express neither a partial index nor the
 * repair steps. The entities declare each index with `synchronize: false` so
 * the generator leaves them alone from here on.
 */

interface SlugTable {
  table: string;
  indexName: string;
}

const SLUG_TABLES: Array<SlugTable> = [
  { table: "CephCluster", indexName: "IDX_ceph_cluster_slug" },
  { table: "DockerHost", indexName: "IDX_docker_host_slug" },
  { table: "IoTFleet", indexName: "IDX_iot_fleet_slug" },
  { table: "KubernetesCluster", indexName: "IDX_kubernetes_cluster_slug" },
  { table: "NetworkDevice", indexName: "IDX_network_device_slug" },
  { table: "ProxmoxCluster", indexName: "IDX_proxmox_cluster_slug" },
];

interface PairIndex {
  table: string;
  indexName: string;
  columns: Array<string>;
}

const PAIR_INDEXES: Array<PairIndex> = [
  {
    table: "GlobalOIDCProject",
    indexName: "IDX_GlobalOIDCProject_globalOidcId_projectId",
    columns: ["globalOidcId", "projectId"],
  },
  {
    table: "GlobalSSOProject",
    indexName: "IDX_GlobalSSOProject_globalSsoId_projectId",
    columns: ["globalSsoId", "projectId"],
  },
  {
    table: "NetworkInterface",
    indexName: "IDX_network_interface_device_ifindex",
    columns: ["networkDeviceId", "interfaceIndex"],
  },
];

export class RestoreDroppedUniqueIndexes1786200000000
  implements MigrationInterface
{
  public name: string = "RestoreDroppedUniqueIndexes1786200000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    /*
     * Slug tables: rename the losers rather than removing them. Oldest row
     * keeps the slug; every other live row with the same slug gets the first
     * eight characters of its own _id appended, which is unique by
     * construction and keeps the slug URL-safe.
     */
    for (const { table, indexName } of SLUG_TABLES) {
      await queryRunner.query(`
        WITH ranked AS (
          SELECT _id,
                 ROW_NUMBER() OVER (
                   PARTITION BY "slug"
                   ORDER BY "createdAt" ASC, _id ASC
                 ) AS rn
          FROM "${table}"
          WHERE "deletedAt" IS NULL AND "slug" IS NOT NULL
        )
        UPDATE "${table}" t
        SET "slug" = t."slug" || '-' || LEFT(t._id::text, 8)
        FROM ranked r
        WHERE t._id = r._id AND r.rn > 1;
      `);

      await queryRunner.query(
        `CREATE UNIQUE INDEX IF NOT EXISTS "${indexName}" ON "${table}" ("slug") WHERE "deletedAt" IS NULL`,
      );
    }

    /*
     * Composite tables: soft-delete the losers. The index is partial on
     * `deletedAt IS NULL`, so stamping deletedAt removes the row from the
     * index while leaving every column intact and every foreign key valid.
     */
    for (const { table, indexName, columns } of PAIR_INDEXES) {
      const partitionBy: string = columns
        .map((column: string): string => {
          return `"${column}"`;
        })
        .join(", ");

      const notNull: string = columns
        .map((column: string): string => {
          return `"${column}" IS NOT NULL`;
        })
        .join(" AND ");

      await queryRunner.query(`
        WITH ranked AS (
          SELECT _id,
                 ROW_NUMBER() OVER (
                   PARTITION BY ${partitionBy}
                   ORDER BY "createdAt" ASC, _id ASC
                 ) AS rn
          FROM "${table}"
          WHERE "deletedAt" IS NULL AND ${notNull}
        )
        UPDATE "${table}" t
        SET "deletedAt" = CURRENT_TIMESTAMP
        FROM ranked r
        WHERE t._id = r._id AND r.rn > 1;
      `);

      await queryRunner.query(
        `CREATE UNIQUE INDEX IF NOT EXISTS "${indexName}" ON "${table}" (${partitionBy}) WHERE "deletedAt" IS NULL`,
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    /*
     * Only the indexes are reversible. The repair is not: a renamed slug and a
     * soft-deleted duplicate cannot be distinguished afterwards from one the
     * application produced, and guessing would corrupt live data. Dropping the
     * indexes is enough to restore the previous schema shape.
     */
    for (const { indexName } of [...SLUG_TABLES, ...PAIR_INDEXES]) {
      await queryRunner.query(`DROP INDEX IF EXISTS "public"."${indexName}"`);
    }
  }
}
