export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const RESET_LOGIN = 'RESET_LOGIN';
export const LOGIN_REQUIRED = 'LOGIN_REQUIRED';
