export const PROBE_SUCCESS = 'probe/PROBE_SUCCESS';
export const PROBE_FAILED = 'probe/PROBE_FAILED';
export const PROBE_REQUEST = 'probe/PROBE_REQUEST';
export const PROBE_RESET = 'probe/PROBE_RESET';

export const PROBE_SUCCESS_STATUSPAGE = 'probe/PROBE_SUCCESS_STATUSPAGE';
export const PROBE_FAILED_STATUSPAGE = 'probe/PROBE_FAILED_STATUSPAGE';
export const PROBE_REQUEST_STATUSPAGE = 'probe/PROBE_REQUEST_STATUSPAGE';
export const PROBE_RESET_STATUSPAGE = 'probe/PROBE_RESET_STATUSPAGE';
