export const STATUSPAGE_REQUEST = 'STATUSPAGE_REQUEST';
export const STATUSPAGE_SUCCESS = 'STATUSPAGE_SUCCESS';
export const STATUSPAGE_FAILURE = 'STATUSPAGE_FAILURE';

export const STATUSPAGE_NOTES_REQUEST = 'STATUSPAGE_NOTES_REQUEST';
export const STATUSPAGE_NOTES_SUCCESS = 'STATUSPAGE_NOTES_SUCCESS';
export const STATUSPAGE_NOTES_FAILURE = 'STATUSPAGE_NOTES_FAILURE';
export const STATUSPAGE_NOTES_RESET = 'STATUSPAGE_NOTES_RESET';
export const INDIVIDUAL_NOTES_ENABLE = 'INDIVIDUAL_NOTES_ENABLE';
export const INDIVIDUAL_NOTES_DISABLE = 'INDIVIDUAL_NOTES_DISABLE';

export const NEW_THEME_NOTES_SUCCESS = 'NEW_THEME_NOTES_SUCCESS';

export const MORE_NOTES_REQUEST = 'MORE_NOTES_REQUEST';
export const MORE_NOTES_SUCCESS = 'MORE_NOTES_SUCCESS';
export const MORE_NOTES_FAILURE = 'MORE_NOTES_FAILURE';

export const SCHEDULED_EVENTS_REQUEST = 'SCHEDULED_EVENTS_REQUEST';
export const SCHEDULED_EVENTS_SUCCESS = 'SCHEDULED_EVENTS_SUCCESS';
export const SCHEDULED_EVENTS_FAILURE = 'SCHEDULED_EVENTS_FAILURE';
export const SCHEDULED_EVENTS_RESET = 'SCHEDULED_EVENTS_RESET';

export const MORE_EVENTS_REQUEST = 'MORE_EVENTS_REQUEST';
export const MORE_EVENTS_SUCCESS = 'MORE_EVENTS_SUCCESS';
export const MORE_EVENTS_FAILURE = 'MORE_EVENTS_FAILURE';

export const FUTURE_EVENTS_REQUEST = 'FUTURE_EVENTS_REQUEST';
export const FUTURE_EVENTS_SUCCESS = 'FUTURE_EVENTS_SUCCESS';
export const FUTURE_EVENTS_FAILURE = 'FUTURE_EVENTS_FAILURE';

export const MORE_FUTURE_EVENTS_REQUEST = 'MORE_FUTURE_EVENTS_REQUEST';
export const MORE_FUTURE_EVENTS_SUCCESS = 'MORE_FUTURE_EVENTS_SUCCESS';
export const MORE_FUTURE_EVENTS_FAILURE = 'MORE_FUTURE_EVENTS_FAILURE';

export const INDIVIDUAL_EVENTS_REQUEST = 'INDIVIDUAL_EVENTS_REQUEST';
export const INDIVIDUAL_EVENTS_SUCCESS = 'INDIVIDUAL_EVENTS_SUCCESS';
export const INDIVIDUAL_EVENTS_FAILURE = 'INDIVIDUAL_EVENTS_FAILURE';

export const SELECT_PROBE = 'SELECT_PROBE';

export const FETCH_INCIDENT_NOTES_REQUEST = 'FETCH_INCIDENT_NOTES_REQUEST';
export const FETCH_INCIDENT_NOTES_SUCCESS = 'FETCH_INCIDENT_NOTES_SUCCESS';
export const FETCH_INCIDENT_NOTES_FAILURE = 'FETCH_INCIDENT_NOTES_FAILURE';

export const MORE_INCIDENT_NOTES_REQUEST = 'MORE_INCIDENT_NOTES_REQUEST';
export const MORE_INCIDENT_NOTES_SUCCESS = 'MORE_INCIDENT_NOTES_SUCCESS';
export const MORE_INCIDENT_NOTES_FAILURE = 'MORE_INCIDENT_NOTES_FAILURE';

export const FETCH_INCIDENT_REQUEST = 'FETCH_INCIDENT_REQUEST';
export const FETCH_INCIDENT_SUCCESS = 'FETCH_INCIDENT_SUCCESS';
export const FETCH_INCIDENT_FAILURE = 'FETCH_INCIDENT_FAILURE';

// Fetch Monitor Statuses
export const FETCH_MONITOR_STATUSES_REQUEST = 'FETCH_MONITOR_STATUSES_REQUEST';
export const FETCH_MONITOR_STATUSES_SUCCESS = 'FETCH_MONITOR_STATUSES_SUCCESS';
export const FETCH_MONITOR_STATUSES_FAILURE = 'FETCH_MONITOR_STATUSES_FAILURE';

export const FETCH_MONITOR_LOGS_REQUEST = 'FETCH_MONITOR_LOGS_REQUEST';
export const FETCH_MONITOR_LOGS_SUCCESS = 'FETCH_MONITOR_LOGS_SUCCESS';
export const FETCH_MONITOR_LOGS_FAILURE = 'FETCH_MONITOR_LOGS_FAILURE';

export const FETCH_EVENT_NOTES_REQUEST = 'FETCH_EVENT_NOTES_REQUEST';
export const FETCH_EVENT_NOTES_SUCCESS = 'FETCH_EVENT_NOTES_SUCCESS';
export const FETCH_EVENT_NOTES_FAILURE = 'FETCH_EVENT_NOTES_FAILURE';
export const MORE_EVENT_NOTE_REQUEST = 'MORE_EVENT_NOTE_REQUEST';
export const MORE_EVENT_NOTE_SUCCESS = 'MORE_EVENT_NOTE_SUCCESS';
export const MORE_EVENT_NOTE_FAILURE = 'MORE_EVENT_NOTE_FAILURE';
export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';

export const FETCH_LAST_INCIDENT_TIMELINE_REQUEST =
    'FETCH_LAST_INCIDENT_TIMELINE_REQUEST';
export const FETCH_LAST_INCIDENT_TIMELINE_SUCCESS =
    'FETCH_LAST_INCIDENT_TIMELINE_SUCCESS';
export const FETCH_LAST_INCIDENT_TIMELINE_FAILURE =
    'FETCH_LAST_INCIDENT_TIMELINE_FAILURE';

export const FETCH_LAST_INCIDENT_TIMELINES_REQUEST =
    'FETCH_LAST_INCIDENT_TIMELINES_REQUEST';
export const FETCH_LAST_INCIDENT_TIMELINES_SUCCESS =
    'FETCH_LAST_INCIDENT_TIMELINES_SUCCESS';
export const FETCH_LAST_INCIDENT_TIMELINES_FAILURE =
    'FETCH_LAST_INCIDENT_TIMELINES_FAILURE';

export const SHOW_EVENT_CARD = 'SHOW_EVENT_CARD';
export const SHOW_INCIDENT_CARD = 'SHOW_INCIDENT_CARD';
