export const STATUSPAGE_REQUEST = 'STATUSPAGE_REQUEST';
export const STATUSPAGE_SUCCESS = 'STATUSPAGE_SUCCESS';
export const STATUSPAGE_FAILURE = 'STATUSPAGE_FAILURE';

export const STATUSPAGE_NOTES_REQUEST = 'STATUSPAGE_NOTES_REQUEST';
export const STATUSPAGE_NOTES_SUCCESS = 'STATUSPAGE_NOTES_SUCCESS';
export const STATUSPAGE_NOTES_FAILURE = 'STATUSPAGE_NOTES_FAILURE';
export const STATUSPAGE_NOTES_RESET = 'STATUSPAGE_NOTES_RESET';
export const INDIVIDUAL_NOTES_ENABLE = 'INDIVIDUAL_NOTES_ENABLE';
export const INDIVIDUAL_NOTES_DISABLE = 'INDIVIDUAL_NOTES_DISABLE';

export const MORE_NOTES_REQUEST = 'MORE_NOTES_REQUEST';
export const MORE_NOTES_SUCCESS = 'MORE_NOTES_SUCCESS';
export const MORE_NOTES_FAILURE = 'MORE_NOTES_FAILURE';

export const SCHEDULED_EVENTS_REQUEST = 'SCHEDULED_EVENTS_REQUEST';
export const SCHEDULED_EVENTS_SUCCESS = 'SCHEDULED_EVENTS_SUCCESS';
export const SCHEDULED_EVENTS_FAILURE = 'SCHEDULED_EVENTS_FAILURE';
export const SCHEDULED_EVENTS_RESET = 'SCHEDULED_EVENTS_RESET';
export const INDIVIDUAL_EVENTS_ENABLE = 'INDIVIDUAL_EVENTS_ENABLE';
export const INDIVIDUAL_EVENTS_DISABLE = 'INDIVIDUAL_EVENTS_DISABLE';

export const MORE_EVENTS_REQUEST = 'MORE_EVENTS_REQUEST';
export const MORE_EVENTS_SUCCESS = 'MORE_EVENTS_SUCCESS';
export const MORE_EVENTS_FAILURE = 'MORE_EVENTS_FAILURE';

export const SELECT_PROBE = 'SELECT_PROBE';

// Fetch Monitor Statuses
export const FETCH_MONITOR_STATUSES_REQUEST = 'FETCH_MONITOR_STATUSES_REQUEST';
export const FETCH_MONITOR_STATUSES_SUCCESS = 'FETCH_MONITOR_STATUSES_SUCCESS';
export const FETCH_MONITOR_STATUSES_FAILURE = 'FETCH_MONITOR_STATUSES_FAILURE';
