export const VALIDATE_TOKEN_SUCCESS = 'auth/VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILED = 'auth/VALIDATE_TOKEN_FAILED';
export const VALIDATE_TOKEN_REQUEST = 'auth/VALIDATE_TOKEN_REQUEST';
export const RESET_VALIDATE_TOKEN = 'auth/RESET_LOGIN';